### ISSUE TITLE
[BUG] HELP

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#100]
anybody can help me for this

how i can do this clone ---> openable .exe ?

**Comment by Teals53** [comment]
when i start source from visual studio its says
![image](https://user-images.githubusercontent.com/13446881/56309633-99611600-6152-11e9-8b9a-ee06a03c5f5a.png)

**Comment by openbullet** [comment]
I don't think anyone understood a thing. Please explain.

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/56321826-29fa1f00-6170-11e9-9adb-0fb6b46bd8ce.png)
i want to use this version but i cant whyi click reconfigure it but its says tons of errrors xD

**Comment by Teals53** [comment]
i do this steps but i cant its say tons of errors dude pls help me @openbullet 


Make sure you have installed the .NET framework (dev) 4.6.1 (I will retarget to a more recent one soon).
Clone this repository and open the solution file with Visual Studio.
Switch to Release mode for a much cleaner output.
Build the solution (Visual Studio will fetch all the missing nuget packages).
You can find the executables inside the folders OpenBullet/bin/Release and OpenBulletCLI/bin/Release.

**Comment by openbullet** [comment]
Are you sure you cloned the entire repository? Make sure you're using VS 2017 or 2019. Also can you translate the error you're getting into English? (The red one)

**Comment by Teals53** [comment]
anyway maybe its my fault bcs if i scrape ur source from link i can create without problem :) so u can close this issues
