### ISSUE TITLE
[REQUEST] auto proxy scraping from proxyscrape

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#101]
like a forlax one

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/56310678-273e0080-6155-11e9-8bbf-8f23b527ac88.png)

**Comment by Teals53** [comment]
and this button
![image](https://user-images.githubusercontent.com/13446881/56310712-38870d00-6155-11e9-8ccb-772d9569a7d4.png)

**Comment by openbullet** [comment]
I won't add the automatic scraper because I don't want to favor one service over the others.

**Comment by openbullet** [comment]
Also stop comparing this to modded versions.

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/56321034-39786880-616e-11e9-9d9e-fe669cb22b87.png)

**Comment by Teals53** [comment]
but delete untested button is not bad :D

**Comment by openbullet** [comment]
And that's exactly why this issue is still open ^_^

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/56326146-8a438d80-617d-11e9-8bcd-6244fe92a781.png)

**Comment by ForlaxPy** [comment]
You could add that to you version on any proxy services not a big deal, just http request their api and scrape the proxies.

**Comment by openbullet** [comment]
@Teals53 by the way, if you go to Settings > RuriLib > Proxies you can define a reload from API. As far as I can see proxyscrape has an API so you can definitely use it without having to import them inside the manager!

**Comment by openbullet** [comment]
Also I changed my mind about the "Delete untested" button, as I don't think there is no use for it at all.

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/56964760-7d9f3c00-6b64-11e9-981b-33a7539fa52b.png)
this api just refresh one type proxy how i can do this for all proxy type ?

**Comment by openbullet** [comment]
Maybe one day I'll add multiple endpoints where OB can get proxies from instead of just one. But that would be a different issue.
