### ISSUE TITLE
[REQUEST] double click support for select something (config-wordlist etc)

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#102]
its really need for quickly

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/56321462-65481e00-616f-11e9-902f-1f9e6cd8ec19.png)
wtf xD

**Comment by openbullet** [comment]
Don't use the word **Combo**, use the word **Wordlist** it's more appropriate

**Comment by Teals53** [comment]
oh kk :3

**Comment by Teals53** [comment]
bump xd

**Comment by openbullet** [comment]
The only thing it makes sense to double click btw is a Config, so basically on double click you want it to be loaded?

**Comment by openbullet** [comment]
Because that behaviour is already working

**Comment by openbullet** [comment]
Oh wait you mean in the selector in the Runner. Okay I got you

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/ccfa0f862b4658ca5f7cb35a46d9d0426df9e936

**Comment by Teals53** [comment]
u r best
