### ISSUE TITLE
[REQUEST] write bots manually

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#103]
![image](https://user-images.githubusercontent.com/13446881/56313441-4b9cdb80-615b-11e9-81ec-ce5bb4f654d5.png)

**Comment by Teals53** [comment]
btw actually just do better ob then modded one bcs its offical one so why not ?

**Comment by Teals53** [comment]
just follow modded one for what he do this then make a more good base

**Comment by Teals53** [comment]
idk this offical ob have same bugs from modded one bcs every modded ob changelog have some bug fixes

**Comment by blurar** [comment]
Just open an issue commit if there is any bug or any requests. You don't need to _**advertise**_ . and most of bugs are fixed on OB.

**Comment by Teals53** [comment]
dont be mad dude xd

**Comment by blurar** [comment]
Am using OB why should i be ? xD

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/56318381-c10ea900-6167-11e9-8018-1e5586c5430e.png)

**Comment by NoB1rDs** [comment]
@blurar he an obv "modded OB" user mad that the ex-lax (forlax) build got compromised. Now he is spam posting trying to make this version just like that one. Can we silence this man please lol

**Comment by Teals53** [comment]
? i do this bcs its not bad suggestions lol

**Comment by Teals53** [comment]
btw modded one is not dead its still alive lol

**Comment by openbullet** [comment]
I'll be very brief as I'm trying not to lose my patience:
1. 90% of the fixes you see in the "changelog" of Forlax's version are just my commits that he copied over to his version, you can compare them here https://github.com/openbullet/openbullet/commits/master so stop saying I should follow his example
2. If you go to the Runner Manager and click on "bots" you can see that exact window to set the bots manually
3. "just follow modded one for what he do this then make a more good base" please **stop** comparing this version to modded versions. This is a warning, next time you will be banned from posting on this repository.

**Comment by Teals53** [comment]
kk
