### ISSUE TITLE
[REQUEST] "save runner" option in settings

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#104]
so when my ob close for any reason and i neede recovery my left check or just when I want to move on from where I left off another time

**Comment by openbullet** [comment]
You know that records are saved in the database? When you select a Wordlist / Config combination that was previously stopped it will recover your starting point ^_^ Is that what you meant?

**Comment by Teals53** [comment]
Oh, this is really great. and that's really a secret trait :D wow so no need save runner bcs looks like it's already been saved xD

i ask this bcs i lose my all runners just %40 completed and i want done this check. rn i know solution for this thx ruri <3
