### ISSUE TITLE
[BUG] bug for proxy

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#106]
i add proxy and close program then reopen ob and all proxy are mixed automatically but "shuffle" option is disabled in settings ?

**Comment by meinname** [comment]
Works for me - maybe you forgot to press the save button?

**Comment by openbullet** [comment]
The proxies are shuffled directly in the runner, they are never shuffled inside the manager! The order of import is the same order in which they are stored in the DB and it won't change.

**Comment by Teals53** [comment]
i dont understand so ?

**Comment by Teals53** [comment]
if this option is disabled and i start bruteforce proxy are not mixed bu if its open, proxy are mixed and if its disable and i re open OB its mixed automatically but until you restart the program proxy tab, proxies are not mixed, but if the option is active, it comes mixed in the runnerde. so maybe something going wrong

![image](https://user-images.githubusercontent.com/13446881/56443546-d4537d00-62fd-11e9-98d4-a30a2998262d.png)
