### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#107]
for example if my bots is 200 and i click "Bots" for edit its show this number so if its 200 say 200 if 50 say 50 not always 1 xD

![image](https://user-images.githubusercontent.com/13446881/56325149-c5dc5880-6179-11e9-9109-4453f4f3f424.png)

**Comment by Teals53** [comment]
actually its realy shit suggestion idk why i posted this lol

**Comment by Doffy06** [comment]
Bu nedir yahu, "Bekir Akdemir" doldu mail kaç gündür... Ota b.ka yorum, istek....

**Comment by Teals53** [comment]
knk bu olay bende takıntı valla asokdfadfjdfljafasjıfsaekldfasjk

**Comment by Teals53** [comment]
aa reis sen türkmüydün :D discorddan eklermisin rica etsem Teals53#1508

**Comment by Cheetah55** [comment]
ya bekir senin ben beynini sikeyim adam babasının hayrırna yapıyo bu iş zaten haberi ne yazıp durun malmısın a.q herif bıraakacak senin yüzünden uptade yi valla o zaman bende sana çok fena sövecem amcıklık yapma dandik heirf. OpenBB admin Thanks sana adamsın senin yarranı yesin bu bekir sen alınma ona  :D

**Comment by Teals53** [comment]
AMIAN KOYİM NERDEN GELİYORSUNUZ SİZ ASKLDFSADFASJFDASDFALFKAEFJKDADFLKAFDEAD

**Comment by Teals53** [comment]
hacı birşey demedik ya ruri reyizin taşşanı emeyim kölesi olayım benim allahım o

**Comment by Cheetah55** [comment]
:D:D:D:D biz fransafa yaşayan almacı türkleriz :D:D:D:D:D

**Comment by Teals53** [comment]
LOL dc gelin dc

**Comment by Teals53** [comment]
ister istemez bu arada sikiyoruz issuesi 😡

**Comment by Cheetah55** [comment]
la olum o nasıl kelime gaymısın lan :D taşşan emeyim hmuhahahahhahahaha :D:D:D:DD

**Comment by openbullet** [comment]
Please keep the discussion in English or I'll close it

**Comment by Teals53** [comment]
yeah true

**Comment by Cheetah55** [comment]
ahh okey my friend , so sory ,  but we were nervous for one person, and we wanted to express it. Thanks for you all work openbb , you are a star.

**Comment by Teals53** [comment]
+1

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/54f7dface3736abc460895f2dba6c6edd22b8747
