### ISSUE TITLE
[REQUEST] reset button for every settings

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#108]
<3

**Comment by openbullet** [comment]
Just delete the settings file in the Settings folder of OB. When OB launches it will create a default one for you again.

**Comment by Teals53** [comment]
thx for information :)

**Comment by openbullet** [comment]
The suggestion for this button is nice though, I'll consider it

**Comment by openbullet** [comment]
Done https://github.com/openbullet/openbullet/commit/4f875da1a71807f9da743653fcbdcf3f381371c0
