### ISSUE TITLE
[BUG] Data in debugger are ignored

### ISSUE THREAD

**Issue by theamericans47** [openbullet/openbullet#109]
Hello,

I compiled 1.0.2 OB on W10 64-bits. When I try a very simple config in debugger with "default" as credentials (email:pass), I get this log :

> <--- Executing Block LOGIN_POST --->
> Calling URL: [REDACTED]
> **Post Data: email=< USER >&password=< PASS >**
> Sent Headers:
> User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
> Pragma: no-cache
> Accept: */*
> Origin: [REDACTED]
> Upgrade-Insecure-Requests: 1
> DNT: 1
> Referer: [REDACTED]
> Content-Type: application/x-www-form-urlencoded
> Sent Cookies:
> [....]

I tried a valid (random) credential in debugger, I got an error page in HTML view like it's not a valid cred. But in log it's like the software did not change <USER> and <PASS> with appropriate value as shown in screenshot and above : 

[REDACTED]

When I put **manually** the same credential in Stacker, everything works fine.

[REDACTED]

**Comment by Cheetah55** [comment]
yes i have same problem.

**Comment by openbullet** [comment]
You guys have to edit your Environment.ini file. By default, it won't allow you to use USER and PASS as these are very often used by cracking forums for illegally performing credential stuffing on websites. I will not help with that.
