### ISSUE TITLE
error on build MVS

### ISSUE THREAD

**Issue by atiemar** [openbullet/openbullet#11]
Im traslating OB on MVS Latest version (Comunity) and when i try to debug or build im getting this error 

 
Error	CS0246	The type or namespace name 'Extreme' could not be found (are you missing a using directive or an assembly reference?)	RuriLib	C:\Users\Yolo\Documents\Visual Studio 2017\openbullet-master\openbullet-master\RuriLib\LoliScript\Parser\SetParser.cs	

 (23 times), and yes, im a noob... anyone can help me?

**Comment by MeowBullet** [comment]
1 - Clone the Extreme.Net rep
2 - Compile it
3 - Add a reference to the compiled dll for all 3 projects
4 - change mode to release and not debug using the dropdown
5 - compile all 3 projects (aka your selection)
6 - enjoy. 

It told you the error from the start - there's a difference between being a noob and not being able to read 1. instructions left by the dev & 2. the error it's giving you.

**Comment by openbullet** [comment]
Thanks @MeowBullet for the response, closing this.
