### ISSUE TITLE
Capmnoster Normal Captcha does not work

### ISSUE THREAD

**Issue by Cheetah55** [openbullet/openbullet#110]
hello dear openbullet, i have some poblem with by capmnoster normaly captcha. Re-captcha working fine.

if you possible please help me, thank you so much.

CAPMNOSTER NORMAL CAPTCHA RESULT (NOT WORK )

<--- Executing Block KEY CHECK --->
<--- Executing Block CAPTCHA --->
Checking balance...
[TwoCaptcha] Current Balance: $555
Downloading image...
ERROR
ERROR: ERROR

---------------------------------

imagetypers NORMAL CPTCHA RESULT  ( is Working )

<--- Executing Block KEY CHECK --->
<--- Executing Block CAPTCHA --->
Checking balance...
[ImageTypers] Current Balance: $2,2513
Downloading image...
Succesfully got the response: 4vv952
Response stored in variable: CAP
<--- Executing Block REQUEST --->

**Comment by kdog2018** [comment]
doesn't work with xevil neither works great with blackbullet though hopefully add more time as end of april coming up

**Comment by openbullet** [comment]
Can someone else test this please? I think it works fine on XEvil @kdog2018 which version are you on?

**Comment by percebal** [comment]
yes xevil all perfect,Capmonster ReCaptcha perfect but normal captchas Error not work.

**Comment by openbullet** [comment]
Okay guys I think I have an idea of why it's not working, I'll make sure to have someone (who owns CapMonster Pro) test the fixes before pushing them.

**Comment by Cheetah55** [comment]
we are grateful to you. Thank you so much for helping us.

**Comment by kdog2018** [comment]
using free version for normal captcha works great on black bullet just not open bullet

**Comment by kdog2018** [comment]
any fix yet ?

**Comment by openbullet** [comment]
Tried again today with no luck. Does CapMonster also implement Anti-Captcha or just 2Captcha?

**Comment by percebal** [comment]
have only implement 2Captcha,i try all siytes whit not luck
only site capmonster show credits is 2Captcha.

**Comment by dbz123** [comment]
I believe CapMonster doesn't accept Base64 form. They want it in Multipart form. I believe that was what BlackBullet was doing.

**Comment by openbullet** [comment]
> 
> 
> I believe CapMonster doesn't accept Base64 form. They want it in Multipart form. I believe that was what BlackBullet was doing.

Yep I know it, and that's what I was doing, but as soon as I send the multipart request it replies with a ZERO_CAPTCHA_FILESIZE error, even if the bytes are all there. The multipart works with many other services (DBC, DeCaptcher) so I don't know what's the issue with 2Captcha. If you manage to implement it WITHOUT using an external library (for consistency with the other implementations) feel free to make a pull request!

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/fe6277d6f474ea9e3b0e283db7de40cf7595d197 fixed, much thanks to #155
