### ISSUE TITLE
[BUG] The app crashed while bruting

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#114]
**Describe the bug**
Checking an old list of hits again site X, the app crashed 3 times
one time at 5k hits, i was using the config debugger that time (the debugger was slow also)
second time, only 1 runner, no debugger, at around 8k hits
third time, only 1 runner, no debugger, at around 10k hits
the capture is something long, like:
capture = name: fn ln, age: int, country: name, city/zip: name/int, phone: int, ...

Keep in mind:
while the crash, the app does not save the last stop in the list
so try to fix this also, please

**To Reproduce**
1. Not sure what to say here, maybe if you have a list with 90% valid hits

**Version**
 - Version [e.g. 1.0.2] Commit 99/115

**Comment by openbullet** [comment]
It's crash not crush btw. I'll try to have the beta testers reproduce this issue, but if it's that hard to reproduce there's little I can do.

**Comment by ReDDOOne** [comment]
@openbullet sorry about the lang mistake

**Comment by openbullet** [comment]
It should update the DB record every 2 minutes I think

**Comment by ReDDOOne** [comment]
weird, because i started at 65K, and after i lunched the app again, it was at 65K
and i was running the app for 30 mins

**Comment by ReDDOOne** [comment]
I guess i have found it, the problem behind the crash

the app is saving the last **HTML** source of every Success/Custom/ToCheck
<img width="345" alt="Screen Shot 2019-04-21 at 5 31 09 PM" src="https://user-images.githubusercontent.com/23710158/56472879-0ed32c00-645c-11e9-81ef-79082a6f3372.png">

if the content of last source is big + a high number of Success/Custom/ToCheck
the app is becoming very slow and close.

**Test**
i was testing this with 2 links: 
1. First is "https://httpbin.org/status/302" with Content-Length = 200
2. Second is "https://pastebin.com/raw/2gJa7mrD" with Content-Length = 89k

Case 1: The app does not crash, and not slow, i was able to work on another config while the runner is on
<img width="724" alt="Screen Shot 2019-04-21 at 5 49 46 PM" src="https://user-images.githubusercontent.com/23710158/56473073-198ec080-645e-11e9-9f37-eaf173edd2c2.png">


case 2: No way i can use the debugger because the app is running slow, the moment the runner reach 8k to 10k, it crash 
<img width="710" alt="Screen Shot 2019-04-21 at 5 50 18 PM" src="https://user-images.githubusercontent.com/23710158/56473108-607cb600-645e-11e9-9e80-6c14ea621408.png">

**Request**
can you disable the function "show last response in browser" for SUCCESS AND CUSTOM
and leave it for the unknown section

**Comment by openbullet** [comment]
You did a very good debugging work, I'm really impressed. I will add a setting to disable the source saving (it will be not saved by default since not many people use that rightclick option). Again, thank you so much and keep up the good work, you are helping this program become the best!

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/3e60801f7735b30f7e247b0f1ff7cbaff7545f52

**Comment by ReDDOOne** [comment]
thank you so much
