### ISSUE TITLE
[BUG] doesn't parse <USER> <PASS>

### ISSUE THREAD

**Issue by Ron-Swansonl** [openbullet/openbullet#117]
[Version 1.0.2]

I added <USER> and <PASS> to the post-data as usual. But for some reason in this build it doesn't convert the information. Looking at the HTML view tab confirms that, for whatever reason it's posting <USER> and not the correct information. However it works fine with parsed tokens, since I also checked that

![image](https://user-images.githubusercontent.com/49811113/56456825-b6bbfd00-6369-11e9-9f07-dcbc70c6f75f.png)

![image](https://user-images.githubusercontent.com/49811113/56456832-cd625400-6369-11e9-88a3-f938f8df9b35.png)

**Comment by ReDDOOne** [comment]
open this file: OB folder / Settings / Environment.ini
and edit it

**Comment by Ron-Swansonl** [comment]
and may I ask what to put in here?

**Comment by ReDDOOne** [comment]
check the lines with  **Slines=**
change USERNAME,PASSWORD to USER,PASS
reboot your app and you are good to go

**Comment by Ron-Swansonl** [comment]
same issue going on, after saving the .ini

**Comment by openbullet** [comment]
This is not an issue, you just need to fix your Environment.ini file. Closing.

**Comment by n4mc0d** [comment]
> same issue going on, after saving the .ini

Same here.
