### ISSUE TITLE
[REQUEST] Encode POST data

### ISSUE THREAD

**Issue by twister77** [openbullet/openbullet#118]
I know you could do this with the Function feature but it would be useful if there was a selectable checkmark in the requests stacker that encodes the POST data.

**Comment by openbullet** [comment]
How many people want this?

**Comment by beer14** [comment]
Good idea

**Comment by openbullet** [comment]
Just to be sure, you are referring to URLencoding right?

**Comment by twister77** [comment]
Yep.

**Comment by openbullet** [comment]
Done
