### ISSUE TITLE
Translation - Traduccion

### ISSUE THREAD

**Issue by pedroperez90** [openbullet/openbullet#120]
My question is whether translations can be added to the program.
If so, I would help in Latin Spanish

Mi pregunta es si se pueden agregar traducciones al programa.
si es asi, ayudaria en el español latino

**Comment by openbullet** [comment]
Yes of course you can, just fork the repo and translate everything, then release your own translated version! When I push updates you can just merge them in your repo and translate the updated stuff that I write in English.
