### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Pabsb** [openbullet/openbullet#122]
**Before you begin**
1. This is **NOT** Forlax's mod or any other mod. If you have issues related to those versions **DO NOT** post them here as they will be closed and disregarded immediately.
2. Do **NOT** post any form of illegal content (e.g. screenshots of you cracking a website with stolen credentials) and do **NOT** ask for Configs for websites. Doing that will result in a report to the GitHub security team and a permanent ban from posting to this repository.

**Describe the bug**

**To Reproduce**
1. Go to 'Proxies'
2. Click on 'Import'
3. Add working proxies
4. Run a config with its default for proxies true or setting proxies true.
5. Will always keep retrying with error messages

**Expected behavior**
Should be good or bad not only retires

**Screenshots**

**Version**
 - Version Newest as of this post

**Additional context**
Will constantly do errors in block request when using proxies. Without using proxies with any config works fine but with just breaks.

**Comment by openbullet** [comment]
Are you 100% sure your proxies are working fine on other programs? They might also be banned on the site you are trying to scrape. Please test further before blaming it on the program itself. Reopen when you have a more accurate description of the error.
