### ISSUE TITLE
[BUG] Content-Type Missing in GET Request

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#123]
**Describe the bug**
Lately, you have fixed the an issue with content-Type present in header for non POST requests
but the problem i am having now, is that i have a GET request, and i need to send the content-type in header
i try to add it as a HEADER "Content-Type: --", but it is not working, the app does not send it

**Expected behavior**
Enable Content-Type in **Custom Headers**, so the user can take control of that.
Or add a checkBox for the Content-Type, so the user can choose when to send it or not, better than the association with the existence of POST DATA (pData) request only.

Thanks

**Version**
 - Version [e.g. 1.0.2] Commit 124

**Comment by openbullet** [comment]
I just want to comment this: people who make webapps that require a Content-Type header even when no content is sent are just bad developers.

**Comment by openbullet** [comment]
Also I don't think I can do much as if I recall correctly Extreme.NET only accepts a Content-Type definition when the request actually has some content.

**Comment by ReDDOOne** [comment]
maybe if you can edit the fix you did last time

so the "Content-Type use" will be related to a checkbox, better than  'if pData == ''" '

after all the app is here for security check of the work of bad developers, so it have to be flexible in all way to find those left bugs ; )

**Comment by mastercho** [comment]
I was expecting this and was sure will broke some of mine configs but was too lazy to open issue lol.
Anyway, in BB works so you can do the same as in BB?

**Comment by openbullet** [comment]
Fixed https://github.com/openbullet/openbullet/commit/d95eb3443af78042efe7fffb9feb3c417c9a5c3a
If this doesn't work please reopen the issue because I didn't have any site to test this on.

**Comment by openbullet** [comment]
Sorry use this commit too ^_^ https://github.com/openbullet/openbullet/commit/3990ea76c931e63499118f6ec9270f069614366c
