### ISSUE TITLE
[BUG] from first issıe

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#124]
https://youtu.be/m3XwfLUeo3I

second one

**Comment by openbullet** [comment]
Is anyone else having that bug? I cannot reproduce it.

**Comment by Teals53** [comment]
wut ?

**Comment by Teals53** [comment]
damn its not a question xD

**Comment by ShadixAced** [comment]
Delete (http) for the proxy thing. OpenBullet might not recognize it as a normal "proxy" domain name.

The second one might be a bit trivial, but might also be due to Windows.

**Comment by Teals53** [comment]
DAMN İ SAY SECOND ONE SO İ DONT TELL PROXY BUG FAPPA

**Comment by Teals53** [comment]
first one is already solved im talking about second one Fappa

**Comment by ShadixAced** [comment]
Might be a Windows issue, that's what I said. Can't replicate issue on mine either.

**Comment by Teals53** [comment]
so u dont have this issue ?

**Comment by ShadixAced** [comment]
Nope, i don't have this issue.

**Comment by Teals53** [comment]
can you show me ? add me on discord i want test myself xd

Teals53#1508
