### ISSUE TITLE
in-config generator function

### ISSUE THREAD

**Issue by Ac3n34d-X** [openbullet/openbullet#125]
what im saying is , a function that can generate both random letters and numbers , inside the config
so basically a generator function in the config blocks
here is an example
having
! = letter, + = number
"!+!+"
Should generate a random letter then a random number another random letter and another random number !
Also a function to turn variables upper case or lower case would be great !

**Comment by meinname** [comment]
Small enhancement Maybe also not only letter and (decimal)number but also hex value

**Comment by beer14** [comment]
Good idea for generate letters and numbers, needed for alot configs +1

**Comment by openbullet** [comment]
Done https://github.com/openbullet/openbullet/commit/c6f9af145cc207376ff113025fc256ac152aec2d
