### ISSUE TITLE
Recursive capture

### ISSUE THREAD

**Issue by weres123** [openbullet/openbullet#126]
can u make capture like sentry 

like this

type1=xxxx expired1=xxxx, type2 =xxxx expired2=xxxxxx

OB capture 

type1=xxxx type2=xxx expired1=xxxx expired2=xxxx

hope u understand. tq

**Comment by openbullet** [comment]
When you make a recursive parse, it will make a LIST variable. You can zip or map LIST variables together like this to have a clean output:
```
UTILITY List "First" Zip "Second" -> VAR "NewList"
UTILITY List "First" Map "Second" -> VAR "NewDict"
```

**Comment by weres123** [comment]
@openbullet how to add more list?  3 4  var?

**Comment by weres123** [comment]
UTILITY List "Producto" Map "ActivationCode" -> CAP "1" 

UTILITY List "ActivationCode" Map "DaysReminder" -> CAP "2" 

want to combine cap1 and cap2
