### ISSUE TITLE
[Question] Crypted configs

### ISSUE THREAD

**Issue by shdf2** [openbullet/openbullet#127]
i just wanted to know when are you planing to add the crypted config feature ??
i can see that 2 forks have it actualy.

**Comment by openbullet** [comment]
I plan to make a branch of the projects that will support Encrypted configs but you will most likely need to host your own server. I will give indications on how to implement the API to make it work with the branched client.

**Comment by openbullet** [comment]
I might even give a very simple ASP.NET core 3.0 web API project you can spawn on any server to have an easy to access place to host your encrypted Configs.

**Comment by shdf2** [comment]
Thanks !
But maybe a php version would be more easier to use, it's easier to find a free hosting with PH than ASP...

**Comment by openbullet** [comment]
You can buy a linux VPS for 3$ a month and place it there. I don't know PHP, if you want you can write your own PHP webapp following the API specifications I will give.

**Comment by shdf2** [comment]
Ho yes for sure, i'll try to convert it in PHP then.

**Comment by shdf2** [comment]
But any idea about "when" you'll add this feature ?? all sellers and those who want to hide their work are waiting for it.... that's mainly the reason why people are going to the forked mods offering it.
