### ISSUE TITLE
Issue ERROR: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

### ISSUE THREAD

**Issue by Salman0ansari** [openbullet/openbullet#129]
idk what that mean i am trying to send capture to my discord with webhooks and this error comes

**Comment by openbullet** [comment]
You must provide a way to replicate the issue or I will close this.

**Comment by openbullet** [comment]
The issue templates are there for a reason.

**Comment by meinname** [comment]
At least a simple test works for me
![image](https://user-images.githubusercontent.com/16181408/56581134-84620800-65d4-11e9-9398-fc96478f80b3.png)
