### ISSUE TITLE
Proxies error

### ISSUE THREAD

**Issue by jeanpierre19** [openbullet/openbullet#13]
Hello,
All the proxies I'm imported are adding with the http type even though I've selected a Socks type. I cannot add socks proxies.

Thank you in advance and congratulations for the work done.

**Comment by openbullet** [comment]
If you add proxies by pasting them in the box, you will have to use advanced syntax. In order to use the dropdown you have to load from file. Although I can see why this is confusing and I will solve the issue soon.

**Comment by openbullet** [comment]
Solved with commit https://github.com/openbullet/openbullet/commit/5fac7d0fa1110e89971fb47e1dbc37ed6d6986b7
