### ISSUE TITLE
[BUG] config bug

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#130]
if i search in config then go runner and select config its just show me search result ?

![image](https://user-images.githubusercontent.com/13446881/56582511-19b6c980-65e0-11e9-9167-e412adf71a00.png)

![image](https://user-images.githubusercontent.com/13446881/56582519-1f141400-65e0-11e9-9148-8fe03d365934.png)

**Comment by openbullet** [comment]
The two are strictly bound together, they draw from the same collection, so yeah this happens. What I can do is reset the search when you click on the Select Config button. Is that fine?

**Comment by shdf2** [comment]
+1 for the reset.
And would it be possible please to sort the list alphabeticaly by default ? else we have to do that extra clic on the column name to sort it...

**Comment by Teals53** [comment]
yea maybe and +1 for @shdf2 request

**Comment by openbullet** [comment]
Many people prefer them to be in chronological order, me included.

**Comment by Teals53** [comment]
damn xD

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/b5c64af9ff141a8176d8d5027e975161c12d24b4

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/56652762-cf435480-6694-11e9-8649-0f25100a9bd0.png)
can u reset this to ?

**Comment by shdf2** [comment]
yea at least a way to filter would help people with 200+ configs in their folder, and who doesn't like  chronoligical order.

**Comment by Teals53** [comment]
+1 xD
