### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by weres123** [openbullet/openbullet#131]
1.i want use this 403 forbidden as success key.  but look like OB auto detect as failed key.
2. recursive , need output capture  Like this Product#1 Product#2

**Comment by openbullet** [comment]
1. OB does not detect any 4xx response as failure. Show me a screenshot please.
2. You can't. That was the old way, now we have list variables.

**Comment by weres123** [comment]
KEYCHECK BanOnToCheck=FALSE 
  KEYCHAIN Success OR 
    KEY "Login Failed - Streaming customer does not have


  KEYCHAIN Failure OR 
    KEY "Login Failed" 

![Screenshot_1](https://user-images.githubusercontent.com/49624042/56617638-0264f400-6653-11e9-9b27-26d2bdbd0cfd.png)

u can close . just put another failed key. :)
