### ISSUE TITLE
[BUG] String generator + Suggestion

### ISSUE THREAD

**Issue by beer14** [openbullet/openbullet#132]
**Describe the bug**
String Random generator, generate Uppercase generate Symbol or number
**To Reproduce**
1. Go to function
2. Click on Select generate string
3. chois U, Uppercase

https://i.gyazo.com/7706239f2b3231707bc3a940f1f3a714.png

**Expected behavior**
Fix

**Screenshots**
https://i.gyazo.com/7706239f2b3231707bc3a940f1f3a714.png

**Version**
 - Version [e.g. 1.0.2]

**suggestion**
Example, to generate an Uppercase, instead of simply making U put, #U, it is a better solution, if we have to keep a constant U

**Comment by openbullet** [comment]
You're right. I'll use hashcat syntax.

**Comment by openbullet** [comment]
Done ^_^

**Comment by beer14** [comment]
Nice thanks alot ruri :)

**Comment by badr2004** [comment]
> Done ^_^

when im generating random string in openbullet 1.4.4 it returns aaaaaaaaaaaaaa is there any solution for this ?

**Comment by openbullet** [comment]
> 
> 
> > Done ^_^
> 
> when im generating random string in openbullet 1.4.4 it returns aaaaaaaaaaaaaa is there any solution for this ?

Yes, use 1.2.2 which is the latest official version

**Comment by badr2004** [comment]
> > > Done ^_^
> > 
> > 
> > when im generating random string in openbullet 1.4.4 it returns aaaaaaaaaaaaaa is there any solution for this ?
> 
> Yes, use 1.2.2 which is the latest official version

Thanks problem solved but some configs i made in 1.4.4 don't want to work in 1.2.2 🙁

**Comment by openbullet** [comment]
Did you change the extension to .loli? Sometimes it's as simple as that. Otherwise I don't know what to tell you.

**Comment by badr2004** [comment]
> Did you change the extension to .loli? Sometimes it's as simple as that. Otherwise I don't know what to tell you. Ah also make sure the Environment.ini file is the same cause that's the main cause of incompatibility between versions.

Oh thanks now it's working ❤️
Also another question 😇 : is the JavaScript the only language i can use in OB scripts ?

**Comment by openbullet** [comment]
You can also use ironpython which is basically the .NET framework but with python syntax. I don't suggest using it because it adds a lot of overhead. Otherwise you can call an external program using the shell plugin which you can find here https://forum.openbullet.dev/topic/1045/run-and-parse-cmd-commands-possible

**Comment by badr2004** [comment]
> You can also use ironpython which is basically the .NET framework but with python syntax. I don't suggest using it because it adds a lot of overhead. Otherwise you can call an external program using the shell plugin which you can find here https://forum.openbullet.dev/topic/1045/run-and-parse-cmd-commands-possible

Okay thanks for your help. Do you have any social media acc so i can contact you ?

**Comment by openbullet** [comment]
You can contact me on the forum or write me a mail (address in the readme of the repo).

**Comment by badr2004** [comment]
> You can contact me on the forum or write me a mail (address in the readme of the repo).

Okay i will contact you here , and i wonder if i can add password for my config or add ip adress authorisation so if someone want to steal my configs he won't be able to modify or use it 🤔

**Comment by openbullet** [comment]
That's a feature that is coming with OB2. Also please stop commenting on this issue otherwise other people who commented will get a lot of useless notifications.

**Comment by badr2004** [comment]
> That's a feature that is coming with OB2. Also please stop commenting on this issue otherwise other people who commented will get a lot of useless notifications.

Oh sorry everyone , it's just i don't know how github works , and thanks for your time Ruri ❤️🙏

**Comment by Mister10999** [comment]
Alguien tiene link para descargar onlyfans hit?
