### ISSUE TITLE
[REQUEST] Manually delete proxies on the fly

### ISSUE THREAD

**Issue by M3T4LL1C4** [openbullet/openbullet#133]
**Is your feature request related to a problem? Please describe.**
When I bruteforce a site without having a success key, I get responces in the "to check" tab" sent by proxies that block the site or send errors for some reasons. After several minutes, the "to check" tab is filled by these responces. To avoid that, when I see in the log that a proxy sends such a responce, I stop the runner, switch to proxy page, find the proxy, delete it and restart the runner. It could be easier

**Describe the solution you'd like**
In the to check tab, when you right click on a responce, add a "delete proxy".

**Describe alternatives you've considered**
If it's not possible to delete the proxy without stopping the runner, it's not a big deal. Stopping and restarting the runner is not that hard. It's switching the proxy page that is time consuming.

**Comment by openbullet** [comment]
I suggest you put global ban keys for the proxies, it will solve your issue. Sorry but I don't think I'll implement this.

**Comment by M3T4LL1C4** [comment]
.

**Comment by ioio101** [comment]
Simply make it so you check the source for the page's name or something that the page has, and if it doesn't have it, ban the proxy.
