### ISSUE TITLE
[REQUEST] Add searching bar to configs list which in runner

### ISSUE THREAD

**Issue by noammiz007** [openbullet/openbullet#134]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would like you to add a search bar to the configs list which inside the runner interface.

**Describe alternatives you've considered**
hmm, idk. i would just like you to add it.

**Additional context**
no.

**Comment by shdf2** [comment]
+1
a search bar or anything that will help you to find quickly a config by its name...

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/3bcfb7cae9c3da45741325ebe15aea45975295b8
