### ISSUE TITLE
[BUG] Building Failed Then Success?

### ISSUE THREAD

**Issue by noammiz007** [openbullet/openbullet#136]
**Describe the bug**
Every time i download the latest version then i build in visual studio i get some errors :(,
BUT! after closing vs, then waiting some minutes, then retrying it successfully builds.

**To Reproduce**
1. Clone openbullet
2. Open OpenBullet.sln
3. Change to release version.
4. Build the solution.

**Expected behavior**
No errors, Just build.

**Error Screenshot**
![Error](https://i.imgur.com/xHsL9KO.png)

**Success Screenshot**
![Success](https://i.imgur.com/UWH60YA.png)

**Version**
Latest, After this commit: https://github.com/openbullet/openbullet/commit/abdc7e4e1024728f498133f02a7ca1acdf0ff17b

**Additional Information**
I do have .NET framework (dev) 4.6.1 installed!

**Comment by Teals53** [comment]
u scrape files from link or download file ?

**Comment by noammiz007** [comment]
> 
> 
> u scrape files from link or download file ?

I use `git clone https://github.com/openbullet/openbullet.git`

**Comment by Teals53** [comment]
maybe i can solve ur problem add me on discord Teals53#1508

**Comment by noammiz007** [comment]
> Teals53#1508

hmm, i actually prefer here. cuz i don't talk about this stuff on discord.

**Comment by openbullet** [comment]
The chmod error is solved after switching to the other build type (Release or Debug, the one you don't have selected). Also I **STRONGLY** suggest to not do git clone each time but rather simply do `git pull` when there is a new version (close VS before doing it). So solving the problem once will suffice for any further build.

**Comment by Teals53** [comment]
lol

**Comment by noammiz007** [comment]
> 
> 
> The chmod error is solved after switching to the other build type (Release or Debug, the one you don't have selected). Also I **STRONGLY** suggest to not do git clone each time but rather simply do `git pull` when there is a new version (close VS before doing it). So solving the problem once will suffice for any further build.

ofc i selected release mode.

**Comment by noammiz007** [comment]
here is a video
https://streamable.com/kqozq
