### ISSUE TITLE
[BUG] Proxy checker, Only Untested: does not work?

### ISSUE THREAD

**Issue by M3T4LL1C4** [openbullet/openbullet#137]
**Describe the bug**
Unchecking "Only Untested" doesn't seem to work

**To Reproduce**
- Let say I have 2000 working proxies. I import 10000 proxies. Total: 12000 proxies.
- I uncheck "Only Untested"
- I click check. In the statistics: Test and Working are not reset. And the progress bar is not reset.

**Expected behavior**
Check all proxies, even the previously tested ones.

**Version**
 - Version [e.g. 1.1.0]

**Comment by openbullet** [comment]
The proxies are indeed re-checked, their status is not reset to unchecked but they still get tested.

**Comment by openbullet** [comment]
This was fixed recently
