### ISSUE TITLE
[REQUEST] combo types in config selector

### ISSUE THREAD

**Issue by meinname** [openbullet/openbullet#139]
**Is your feature request related to a problem? Please describe.**
Some guy who is really BUGging me wanted me to do a request

**Describe the solution you'd like**
"we need allowed combo types
in config selector"

**Describe alternatives you've considered**
None - as this guy seems to know, what he wants.

**Additional context**
did i already tell about this guy? - nvm...

**Comment by openbullet** [comment]
Done
