### ISSUE TITLE
[REQUEST] Captcha activation key

### ISSUE THREAD

**Issue by twister77** [openbullet/openbullet#141]
Some sites activate captchas only after a few failed logins so it would be very useful
if captcha/recaptcha blocks had a field similar to Sentry's "Activation Key" feature
where we could enter a value from the page source which triggers the captcha solving.

https://i.imgur.com/XIB44ty.png

**Comment by openbullet** [comment]
There are IF - ELSE constructs. Use them.

**Comment by twister77** [comment]
Sorry, i didn't know that IF conditions exits.
Are there any examples of using them or any premade configs that could be inspected for learning?

**Comment by openbullet** [comment]
Click on "switch to loliscript" then click on the "documentation" button, go to "Flow Control" and finally click on IF ELSE, it will be explained there.
