### ISSUE TITLE
[BUG] Send to Recheck

### ISSUE THREAD

**Issue by sieunhando** [openbullet/openbullet#143]
In `HitDB`, If you select some results and choose `Send to Recheck`, It will create a new wordlist and auto add it to `Wordlists menu` but it don't change the `Type`. The type of new wordlist always `default`.

**Comment by openbullet** [comment]
Are you on the latest commit? Or which version are you on?

**Comment by openbullet** [comment]
I just tested and I confirm it's working on the latest build, please update
