### ISSUE TITLE
[BUG] select CFG clears search

### ISSUE THREAD

**Issue by Ron-Swansonl** [openbullet/openbullet#144]
**Describe the bug**
Under the Runner tab, if you click "Select CFG" after searching for the config under Configs tab, it clears the search leaving you with all your configs to manually go through.

**To Reproduce**
1. Go to the Configs tab, and search for any config
2. Then go to the Runner Tab and click Select CFG

**Version**
 - Version 1.1.0

**Additional context**
I think this may have been because of the enhancement request made by someone else to search for configs in that box. But I'm not sure if that was even implemented yet.

**Comment by openbullet** [comment]
It's not a bug, it was a feature request and I implemented it here https://github.com/openbullet/openbullet/commit/b5c64af9ff141a8176d8d5027e975161c12d24b4
Guys make up your mind please.

**Comment by openbullet** [comment]
For now it will stay like this, later I will put the search box in the config selector as well so that it will show the filter and you can clear it from there directly.
