### ISSUE TITLE
[REQUEST] Center Window

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#145]
**Intro lol**
Lately, i have seen that you are working on the visual of the app
so i thought i add this request that i had for a long time

**Problem**
As i have a big resolution (5k), the window app and all others, are opening in the top left corner with a small size.
So i have to move the main window and resize it, each time

**Describe**
Can you Center the main window of the app
and all other popup windows
(Select config/wordlist, import proxies, add wordlists)

**Optional Request**
If you can add setting for the initial window size (Width, Height) also

Thanks 
Regards

**Comment by openbullet** [comment]
All done

**Comment by ReDDOOne** [comment]
thank you
