### ISSUE TITLE
[REQUEST] Adding multiple wordlists

### ISSUE THREAD

**Issue by noammiz007** [openbullet/openbullet#146]
**Is your feature request related to a problem? Please describe.**
No, It's just a suggestion.

**Describe the solution you'd like**
I would like you to add an option to add multiple wordlists together instead of choosing one by one.

**Describe alternatives you've considered**
hmm i don't have. I was just choosing it one by one.

**Additional context**
No

**Comment by openbullet** [comment]
You can already do it, just drag and drop multiple files into the Wordlist Manager list. OB will automatically recognize their type (you must be on the latest version) and import them.

**Comment by noammiz007** [comment]
> 
> 
> You can already do it, just drag and drop multiple files into the Wordlist Manager list. OB will automatically recognize their type (you must be on the latest version) and import them.

Oh, Didn't know. Thank you 😁
