### ISSUE TITLE
[BUG] CF New Update

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#147]
**Describe the bug** / **To Reproduce** / **Screenshots**
<img width="1506" alt="Screen Shot 2019-04-29 at 8 22 20 PM" src="https://user-images.githubusercontent.com/23710158/56920987-918f6300-6abc-11e9-9ded-04ff12593751.png">

Am i missing something here

**Comment by openbullet** [comment]
Please either give the website or tell me how I can reproduce it. Or debug it yourself and tell me which line throws the exception. Thanks.

**Comment by ReDDOOne** [comment]
sorry, i was trying to respect what you said about not posting ...
Anyway, here are the sites:
1. 5euros.com/connexion
2. stormproxies.com/clients/login

**Comment by openbullet** [comment]
Is it absolutely necessary to make a request BEFORE the cf bypass? You're supposed to just use the CF Bypass as the first block.

**Comment by openbullet** [comment]
I think the cookies grabbed during the first visit are messing up the bypass itself.

**Comment by ReDDOOne** [comment]
i am closing this
it was my problem, not the app's
