### ISSUE TITLE
[REQUEST] More Notifications For Hits

### ISSUE THREAD

**Issue by noammiz007** [openbullet/openbullet#148]
**Is your feature request related to a problem? Please describe.**
hmm, it isn't related to any problem.

**Describe the solution you'd like**
Hmm, i would like to see in the program more options for notifications for hits. The wav sounds are ok but sometimes i (or someone else) can miss them or even being afk and then coming back and forgetting about the hits number . So i can suggest more notifications like: Making the program have a counter in the taskbar like discord: 
![image](https://user-images.githubusercontent.com/31467235/56922807-bc37e680-6ad1-11e9-93af-07d249aee091.png) but instead counting messages, it should count the hits number.
Or even pushing a notification on the windows 8/10 action center.

**Describe alternatives you've considered**
Hmm, i was just using the sounds option.

**Additional context**
I am not saying it's very important or something like this, i would just like to see this.
So, That's all.

**Comment by ForlaxPy** [comment]
What if the user is running more than a runner how would the system work.

**Comment by openbullet** [comment]
I'm already imagining the notification spam when someone gets a lot of hits ^^

**Comment by ForlaxPy** [comment]
@openbullet I think he is just talking about the notification counter and he is asking for something such as it for OB hits, we can prob make it by drawing an image to overlay the program ico like this:
![preview](https://i.stack.imgur.com/XFPKM.png)
 and bind it to the current runner hits counter

**Comment by openbullet** [comment]
I have no idea how to do that ^_^ do some research and let me know! It would be a really nice feature

**Comment by ForlaxPy** [comment]
Well the code is pretty simple but has a lot of lack and won't be efficient for OB. 
This is how it looks like:
![preview](https://i.imgur.com/wnos6it.png)
But we will have to code a system that will keep changing the size of the int each time the counter multi by 10, will get messy a little bit and it turn out to be very small if the user reached 1k+,  also there was no libraries out that that could stand as helpers for this. So actually came up to a solution, why not make an additional wpf tab that will stand as a widget and make it AlwaysOnTop, ofc this features would be optional and even for us it will be a peace of cake to implement as well. 
Maybe a small windows for the current runner
![preview2](https://i.imgur.com/47WoCt2.png)
OR make it get the list of all runners and do something like this:
![preview3](https://i.imgur.com/tvRT3iw.png)

Anyway these were just suggestions but yeah the actually overlay in the task icon is a bit complicated I think.

**Comment by openbullet** [comment]
@ForlaxPy do not post images like that one. Please...

**Comment by openbullet** [comment]
Making a new image to use as icon every time there's a new hit might interfere with the performances to be honest, and if it's not an optional feature it might turn out to be a bad one for some people. Notifications in the windows action center would be crazy on a lot of hits. Your idea of the widget is nice.
Anyways this is very low prio so I say we focus on actual bugs first okay? ^_^

**Comment by noammiz007** [comment]
well you can set a maximum for number, like 99+ or 9+
but it's okay, it's just a suggestion. i don't beg for adding this ^_^
so you can work on more important stuff.

**Comment by openbullet** [comment]
Closing as old and not happening
