### ISSUE TITLE
[BUG] Config Orders İs Not Working

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#149]
Just Working "Name" Order Other Ones Are Not Work

![image](https://user-images.githubusercontent.com/13446881/56929532-894a1e80-6ae2-11e9-827e-627ba1b07873.png)

**Comment by openbullet** [comment]
This was recently fixed by a PR

**Comment by Teals53** [comment]
ok

**Comment by openbullet** [comment]
It's on the dev branch, it will be merged to master when 1.2.0 is ready
