### ISSUE TITLE
Compilation error in RuriLib

### ISSUE THREAD

**Issue by kernelzeroday** [openbullet/openbullet#15]
Built in release mode, looks like a syntax error in CProxy.cs. VS Studio 2015 Enterprise output:

> 1>------ Build started: Project: RuriLib, Configuration: Debug Any CPU ------
> 1>C:\Users\cute_username_here\openbullet\RuriLib\Models\CProxy.cs(133,73,133,77): error CS1003: > Syntax error, ',' expected
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

The offenting line is:

> Enum.TryParse<ProxyType>(groups[1].Value, true, out var type);

Looks like the final bit there should be something other than 'var type', I'm not up to date on much C# Windows programming so I'll submit this as an issue rather than just shoot you a pull request.

Cheers.

**Comment by Choempie** [comment]
I have it like this and its working fine
![code](http://conk.sucks/Code_lrwO40wfxQ.png)

**Comment by openbullet** [comment]
Use VS 2017

**Comment by kernelzeroday** [comment]
Thanks, I suppose this is a VS 2015 issue, help is much appreciated!
