### ISSUE TITLE
[BUG] Content-Type - GET Request - II

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#150]
**Describe the bug**
Sadly, the bug is not fixed yet

Now, You can see the Content-Type in the sent headers
But when i watch the traffic, there is no Content-Type on the headers

**Screenshots**
<img width="1498" alt="Screen Shot 2019-04-30 at 9 09 23 PM" src="https://user-images.githubusercontent.com/23710158/56990240-84da4000-6b8c-11e9-9c06-8a2cac49411e.png">
<img width="805" alt="Screen Shot 2019-04-30 at 9 10 44 PM" src="https://user-images.githubusercontent.com/23710158/56990258-8efc3e80-6b8c-11e9-9949-955a4dfb2ffd.png">

another thing that httpbin allow, is that it is able to show you received headers by server as a returned source
<img width="829" alt="Screen Shot 2019-04-30 at 9 16 16 PM" src="https://user-images.githubusercontent.com/23710158/56990620-7d676680-6b8d-11e9-9fa1-7588f8b995f1.png">
as you can see no "Content Type"

**Version**
 - Version [e.g. 1.1.1]

**Comment by ReDDOOne** [comment]
@openbullet 
today, i was trying to change the code many times, build and try a config
but i am always getting Content-Type displayed in Sent Headers, but not in the request

i guess it is something related to Extreme.Net lib, right ?

**Comment by openbullet** [comment]
Sadly right now I don't have time to look into this, please wait a few days.

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/be1bbc76c87abc6a377e19d166887df6437e2362
