### ISSUE TITLE
[REQUEST] Use of cookies from jar while downloading captcha image

### ISSUE THREAD

**Issue by bfx002** [openbullet/openbullet#152]
many sites refreshes captcha image when same captcha url is visited twice or without cookies so in that configs captcha image is always different than original image that is bound to cookies. this can be bypassed if image is downloaded with same proxy and cookies as request.

**Comment by openbullet** [comment]
If you go look at the source code, in particular in the `BlockImageCaptcha.cs` file, `DownloadRemoteImageFile` method, you will see that the things you said are already implemented.

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/blob/master/RuriLib/Blocks/BlockImageCaptcha.cs
