### ISSUE TITLE
[REQUEST] CUSTOM COLUMN LABEL

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#156]
**Is your feature request related to a problem? Please describe.**
If have couple custom keys in env file, and hit any of them in checker. They will go under CUSTOM. 
**Describe the solution you'd like**
Add another column next to Captured Data, to show which CUSTOM key hit exactly. 
**Describe alternatives you've considered**
Can be done with setting Constant as capture but is pain in big configs.

**Comment by noammiz007** [comment]
I was actually thinking about it too xD

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/49663a0c6706be0c5f6d66bef8a2d2a32b8960ed
