### ISSUE TITLE
[BUG] Configs auto save even without button

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#160]
**Describe the bug**
If i made some mistakes, as CTRL+Z doesn't work i went to load another config to REDO changes
But turns out that it is auto saves config when loads another config

**To Reproduce**
1. Load config
2. Do changes
3. Without clicking, SAVE went to load another config

**Expected behavior**
Must redo the changes as long as you don't save it

**Version**
 - Version 1.1.1

**Comment by openbullet** [comment]
Only the object stored in memory gets changed, the config is never saved to file without pressing the button or pressing Ctrl+S. So just do ReScan before you load the config, and it will be back to its original state.
