### ISSUE TITLE
[BUG] ELEMENT ACTION Doesn't work on CAP

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#161]
**Describe the bug**
If on ELEMENT ACTION you specify element but leave output empty and Capture is ticked, its still goes to VAR instead CAP
**To Reproduce**
1. SET ELEMENT ACTION with some element
2. Tick "is Capture" and leave Output Variable empty
3. Would get it as VAR instead CAP

**Expected behavior**
If CAP is ticked must get as CAP instead VAR

**Version**
 - Version 1.1.1

**Comment by openbullet** [comment]
The LS writer will check if OutputVariable is empty. If it's empty, it will not output the part after the arrow. Please give a name to your output variable instead of leaving it blank, or it will not be written to LS and it will use the default settings of the block.

**Comment by mastercho** [comment]
There is long text which i have to capture and giving a name to output doesn't make sense to it
If that was the case i was not gonna submit this as an issue

**Comment by openbullet** [comment]
I made it behave the same way of the function block. If you don't want dirty LS code you don't need that. Is it that hard to just put a space as variable name? :D

**Comment by mastercho** [comment]
empty space worked. Thanks
