### ISSUE TITLE
[REQUEST] Luminati proxy support

### ISSUE THREAD

**Issue by sieunhando** [openbullet/openbullet#162]
**Is your feature request related to a problem? Please describe.**
Hi, can you make it support Luminati proxy? Now if we want to use Luminati services, we need to download their client but the connection is slow and heavy in performance.

**Describe the solution you'd like**
This is Luminati's provide code:
```
using System;
using System.Net;

class Example
{
    static void Main()
    {
        var client = new WebClient();
        client.Proxy = new WebProxy("zproxy.lum-superproxy.io:22225");
        client.Proxy.Credentials = new NetworkCredential("lum-customer-[username]-zone-static-country-us", "[password]");
        Console.WriteLine(client.DownloadString("http://lumtest.com/myip.json"));
    }
}
```

**Comment by openbullet** [comment]
You can already do this.
Import proxies from the textbox instead of the file and use this syntax
`(http)ip:port:username:password`

**Comment by Teals53** [comment]
just put proxy in here no need add "(http)"
![image](https://user-images.githubusercontent.com/13446881/57135833-702bc100-6db3-11e9-9ef7-c01dad5776ab.png)

**Comment by openbullet** [comment]
There is a text that says "hover on the box below to see the syntax". If you do that, you will see the syntax I just showed you. And you can clearly see the text that says for advanced mode (chain, auth) use the box below. Your proxies use Auth so you have to use the box below.

**Comment by sieunhando** [comment]
I saw and tested but not work for Luminati proxy. I can send you demo account via email to check.
This is what I tested:

```
(http)zproxy.lum-superproxy.io:22225:lum-customer-[user]-zone-static-country-us:[pass]
(http)107.170.54.77:22225:lum-customer-[user]-zone-static-country-us:[pass]
zproxy.lum-superproxy.io:22225:lum-customer-[user]-zone-static-country-us-session-1000000:[pass]
107.170.54.77:22225:lum-customer-[user]-zone-static-country-us-session-1000000:[pass]
```

**Comment by openbullet** [comment]
I tested with that service exactly and it worked.
Are you sure you are pasting them inside the box and not loading from file? If you load from file it won't allow you to use user:pass proxies.

**Comment by sieunhando** [comment]
I posted inside the box, not load from a file. I am using newest version.

**Comment by openbullet** [comment]
You're not using any modded version right?

**Comment by openbullet** [comment]
If you want you can leave your discord tag here and I will help you better on there via chat.

**Comment by sieunhando** [comment]
Yes. I build it by my self and it's newest version. 
This is my discord: blackturtle404#4263

**Comment by openbullet** [comment]
Just to inform anyone else reading this thread with the same problem:
- If you only have 1-2 rotating proxies, enable Concurrency and Never Ban in the settings
- If you have a lot of proxies, check that line endings are windows-like not unix-like or it will paste them inside the box as 1 long string. It happens with some proxy services.

**Comment by mhaney3931** [comment]
my vote to support Luminati proxy for Openbullet. i love openbullet.  live long very nice project.

**Comment by openbullet** [comment]
@mhaney3931 they are already supported, read above.

**Comment by YashvirTheCarder** [comment]
any idea how to make Luminati proxies works in Openbullet
cuz it ain't checking, no CPM at all, its not even processing,
getting lot of RETRIES

tested without LUMINATI proxy used socks4 mixed fresh, and your config is working I get HITS ! but its SLOW

I even did the (http) thing for the Luminaties proxies

Also tried the LPM thing with 127.0.0.1:24000 = same errors it does not check

**Comment by Tenx22** [comment]
YashvirGa

> any idea how to make Luminati proxies works in Openbullet
> cuz it ain't checking, no CPM at all, its not even processing,
> getting lot of RETRIES
> 
> tested without LUMINATI proxy used socks4 mixed fresh, and your config is working I get HITS ! but its SLOW
> 
> I even did the (http) thing for the Luminaties proxies
> 
> Also tried the LPM thing with 127.0.0.1:24000 = same errors it does not check

same problem

**Comment by YashvirGaming** [comment]
> YashvirGa
> 
> > any idea how to make Luminati proxies works in Openbullet
> > cuz it ain't checking, no CPM at all, its not even processing,
> > getting lot of RETRIES
> > tested without LUMINATI proxy used socks4 mixed fresh, and your config is working I get HITS ! but its SLOW
> > I even did the (http) thing for the Luminaties proxies
> > Also tried the LPM thing with 127.0.0.1:24000 = same errors it does not check
> 
> same problem

Hey there my start checking i had change password and redownload the proxies, then import on openbullet, also in ob settings, I had to tweak something Never ban proxies, allow low concurency 
And remote sources set to file manager.
only then it works for me.
