### ISSUE TITLE
[REQUEST] Retry Key

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#163]
Hello,
these first 2 lines are more of a question, i want to know what happen after RetryKey triggered
does the app change proxy or re-run from same proxy, if yes for how many time
can u link me please to the .cs file, please

**A Case**
lets say i am testing a website which lunch recaptcha / or any other security in 2 cases:
_ proxy is banned
_ good user

to bypass the the first case of banned proxy, i need to retry from different proxy
then i want to set the config to use recaptcha service if the amont of retries is greater than X
which mean that the combo is good, and recaptcha is on forever

but until here i don't have a variable or a way to save the number of retries of each bot with specific combo

**Describe the solution you'd like**
Maybe you can set an accessible counter for number of retries for Combo-X in Bot-Y

**Describe alternatives you've considered**
Do like old S.MBA was doing, there many kind of retries
a normal retry (with the same proxy )
another retry from different proxy ...
what is more important is the following settings:
the ability to send a combo to recheck, after x retry
(Sorry to compare)

i like the first solution more, it would give the user more control
and it is useful with IF function
thanks for reading until here
regards

**Comment by openbullet** [comment]
Retry = the proxy is set back to available in the proxy pool and the data is retried.
Ban = the proxy is set to banned (and it won't be used by any bot until unbanned) and the data is retried.

I will consider the first solution you proposed.

**Comment by ReDDOOne** [comment]
thank you
