### ISSUE TITLE
[REQUEST]Faster delete from DB

### ISSUE THREAD

**Issue by shdf2** [openbullet/openbullet#165]
Hello, i just made a mistake in a config, and now i have 50 000+ "To Check" in the DB...when i select all and click delete, it takes a century to delete and it never finish after 30 minutes waiting...
that should be just a simple : 
DELETE FROM DB WHERE configname="myconfigname"
it shouldn't take more than 5sec in all database...
Now i'm stuck and i don't want to purge my DB because i have some content from other configs that i want to keep...
I tried LiteDbExplorer but the problem is the same as i can't do my own query to delete the rows. i have to select all and push the delete button which take a very long time...

**Comment by openbullet** [comment]
First of all it's not an SQL database. I will add support for custom queries if you want, this was actually a thing I already had in mind, or you could use a 3rd party tool that lets you send queries to a LiteDB database.

**Comment by openbullet** [comment]
Or I could add a button that says "delete all for config". As you prefer.

**Comment by shdf2** [comment]
if possible a button which will delete all from the TYPE of the selected config.
usually we don't want to keep the "to check" in the database.

if not possible then "delete all for config" wil better than nothing....

Thank you very much if you can do that.

**Comment by openbullet** [comment]
I think the best way would be to implement a "Delete Displayed" or "Delete Filtered" button, which will act basing on the filters (the search box, the config name and the hit type). I will do this.

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/1aff26e3c850368e0d880ccc95f6d9041ec6bbee
