### ISSUE TITLE
[BUG] Save Config Button

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#166]
**Describe the bug**
Both Save Buttons are not working

**To Reproduce**
1. Open/reboot the app
2. Click New Config
3. Go on with the blocks
4. Click Save Config
(Until Here the config is not saved, the button is not working, to make sure of that)
5. 1. create a runner with the config you just created, when trying to run it. it will return **the config has zero blocks**
5. 2. or, Try to load another config, and load back the new config, you will see that there are no blocks

**Version**
 - Version [e.g. 1.1.1]

**Comment by openbullet** [comment]
Fixed, if you still have issues open another one thanks.
