### ISSUE TITLE
[REQUEST] Rework TCP Connect

### ISSUE THREAD

**Issue by meinname** [openbullet/openbullet#167]
**Is your feature request related to a problem? Please describe.**
the 200 ms I set sometimes are too long and sometimes not long enough, so the user i originally did the fix for wants a other solution

**Describe the solution you'd like**
A "do not wait for banner" switch  on TCP Connect to either wait forever for a connect message or not to wait

**Describe alternatives you've considered**
yep - to make the hardcoded wait time configurable - but the other one is prefered 

**Additional context**
adding as an issiue so it wont get forgotten ;)

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/22c4f50b37833e8b864b177e20b2e05fcf45b156
