### ISSUE TITLE
[REQUEST] FIFO buffer for Logs

### ISSUE THREAD

**Issue by meinname** [openbullet/openbullet#168]
**Is your feature request related to a problem? Please describe.**
For a fix you added 2 options to disable the HTML and Botlog - i suggested an enhancement/alternative

**Describe the solution you'd like**
copy and paste, cause i'm lazy:
maybe if you have too much time and nothing better to do a kind of FIFO Buffer for any kind of log.
one for Botlog, one for respnse source, one for general log. 
All with predefined sizes and if full then the entries at the end get deleted. 

**Describe alternatives you've considered**
nope - but very low prio.

**Additional context**
Just posting here so it won't get forgotten

**Comment by openbullet** [comment]
If and when I do it, it will be for the general log only.

**Comment by meinname** [comment]
🤷‍♂ :D

**Comment by meinname** [comment]
done on https://github.com/openbullet/openbullet/commit/e25751e50f8e1c4e99f5e81fd469d8d409b7cec7
