### ISSUE TITLE
[REQUEST] [BUG] double suggestion + bug

### ISSUE THREAD

**Issue by beer15** [openbullet/openbullet#169]
**BUG;.**
before when you looked for your config example "facebook" in configs, you could only see it "facebook" in the runner, now everything is reset

**Describe the solution you'd like**
Fix.

**suggestion**

Add file name config 
example; https://i.gyazo.com/8f29a50fd7259b8dd565d10ffed36e6c.png

**suggestion 2**
Add "Search" config in runner 
example; https://i.gyazo.com/96e4ee252c91652a43959a096c53a374.png

**Comment by openbullet** [comment]
Duplicate https://github.com/openbullet/openbullet/issues/134
