### ISSUE TITLE
[BUG] Length List after a recursive Parse

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#170]
**Describe the bug**
After a bad recursive parse, the app return an empty list
when you try to get the length of this empty list, it return 1

**Expected behavior**
should return 0

**Screenshots**
<img width="1521" alt="Screen Shot 2019-05-04 at 8 40 51 PM" src="https://user-images.githubusercontent.com/23710158/57184064-99c91300-6ead-11e9-8fbd-296fefb54204.png">

**Version**
 - Version [e.g. 1.1.1]

**Comment by openbullet** [comment]
Thanks for reporting, fixed. https://github.com/openbullet/openbullet/commit/233d01403555a9707345995b0091d793f6e4cad3
