### ISSUE TITLE
[REQUEST] sort by author

### ISSUE THREAD

**Issue by noammiz007** [openbullet/openbullet#171]
**Describe the solution you'd like**
Please add "Sort by author" to DialogSelectConfig in runner

**Comment by openbullet** [comment]
It's already pretty crowded isn't it?

**Comment by noammiz007** [comment]
@openbullet it isnt in the runner configs selector

**Comment by openbullet** [comment]
Yeah I'm aware but do we really need it?

**Comment by noammiz007** [comment]
@openbullet well i guess it can help for fast search. But you don't need. I only suggested.

**Comment by openbullet** [comment]
Done
