### ISSUE TITLE
[BUG] <USER> and <PASS> variables not working

### ISSUE THREAD

**Issue by n4mc0d** [openbullet/openbullet#172]
Describe the bug
When trying to parse <USER> or <PASS> they aren't parsed

To Reproduce

Go to stacker for stacker
Run some parse with <USER> or <PASS> variable

Expected behavior
Replace <USER> and <PASS> from data field.

Images
![parse_not_working_ob](https://user-images.githubusercontent.com/2848601/57185979-0d1e5500-6ead-11e9-9ef3-4d099ec37c8e.png)

Version
Version 1.1.1

**Comment by openbullet** [comment]
Duplicate https://github.com/openbullet/openbullet/issues/117
