### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by darta1964** [openbullet/openbullet#173]
I load a configuration created by others. I load the correct combos (in this case user: pass). I will leave on start and exit the error:

![image](https://user-images.githubusercontent.com/41988017/57196883-4d3f0f80-6f61-11e9-9aaf-c499409c7723.png)

Version 1.2.2.4 !

**Comment by zqdscxjfbq** [comment]
open the config and add userpass here https://gyazo.com/7bfc516f181a6e4f43c0faf9be6e9a99

**Comment by DrKralle** [comment]
(^o^) Just wanted to post an answer with the same content. Do not get worried when such minor problems occur - a lot of configs are a little bit older, but can be fixed with very few work. Cheers!
