### ISSUE TITLE
[BUG] issue with hits on OB 1.1.1

### ISSUE THREAD

**Issue by zqdscxjfbq** [openbullet/openbullet#174]
Number of hits not loading properly with the same dB as 1.1.0 

https://i.gyazo.com/ad86f1b846ef078e14a7c0ab7199114d.png

**Comment by openbullet** [comment]
It's just a visual thing because I added a button. I'll try to fit them in a grid at this point.

**Comment by zqdscxjfbq** [comment]
ahh ic at first I thought I lost my hits then I copied the dB to older ver and saw hits were still there 

thank you for the fast reply ruri you the best ^.^

**Comment by openbullet** [comment]
Fixed
