### ISSUE TITLE
[REQUEST] Pause for x amount of time if CPM falls below y value (to prevent crashing sites)

### ISSUE THREAD

**Issue by theycallmek** [openbullet/openbullet#176]
Some sites I have noticed can't handle even getting hit with 50 bots at a time. If we had a feature where we could specify "if CPM < 400 then wait 60 seconds, resume" for example this could help not crash the site and result in a higher CPM overall.

Thanks for your time!

EDIT: had my symbol backward =/

**Comment by openbullet** [comment]
Why wait 60 seconds? I could add a wait inside the master worker that assigns data lines to the bots. If the CPM is above the threshold, it will just wait until it's not. I can easily add this.

**Comment by mastercho** [comment]
Are you aware that CPM is not giving you realtime info? Like in me literally is rising by 1 on 1 check. So whats the point of this haha

**Comment by theycallmek** [comment]
> Why wait 60 seconds? I could add a wait inside the master worker that assigns data lines to the bots. If the CPM is above the threshold, it will just wait until it's not. I can easily add this.

That was just an example. Ideally, I would like to be able to input the wait time myself. Also, it would be awesome to be able to trigger the wait or cooldown period if the cpm goes above x amount or below y amount.

Thanks again!

**Comment by openbullet** [comment]
> 
> 
> > Why wait 60 seconds? I could add a wait inside the master worker that assigns data lines to the bots. If the CPM is above the threshold, it will just wait until it's not. I can easily add this.
> 
> That was just an example. Ideally, I would like to be able to input the wait time myself. Also, it would be awesome to be able to trigger the wait or cooldown period if the cpm goes above x amount or below y amount.
> 
> Thanks again!

But I don't understand why everything needs to be stopped when it could just wait a bit until the CPM drops a bit.

**Comment by theycallmek** [comment]
> But I don't understand why everything needs to be stopped when it could just wait a bit until the CPM drops a bit.
I am not saying wait until the CPM drops. Lets me give you an example:
I am running 20 bots against a slower website. first 5 minutes CPM sits around 500-600, then slowly drop to 1-2 over the next few minutes as the website grinds to a halt. Now if I manually pause the script for 30 seconds or so then resume it, it gives the website enough time to catch up with the requests and the CPM will jump back up to 500-600 for another couple minutes until the requests overwhelm the server and grind it to a halt again. Without manually pausing the config will get stuck at 1-2 cpm until i intervene.

So I want to be able to automate the pausing and unpausing of the script in the scenario above. Being able to set how long it pauses for and at what CPM would be awesome.

I hope that make a little more sense.

**Comment by openbullet** [comment]
@theycallmek Try now, I implemented some CPM limiting, see if it's better.

**Comment by openbullet** [comment]
Set 500 as limit and you'll see.

**Comment by ReDDOOne** [comment]
@openbullet i guess what he is looking for, and what will be a good idea also is:
sometimes, the server is very small or set to go down while a bot attack
and after this situation is enabled, using proxies or not, using the key as Retry or ban, it does not change nothing

all what is possible here is:
1. from the user: to stop/ pause testing for x mins + re-lunch with low bots
2. from the app, it would be very helpful if the app can do that. if you can add a way so a key can trigger the runner to stop/pause and re-lunch after x mins

what do you think @theycallmek

**Comment by openbullet** [comment]
@ReDDOOne I just implemented something like that here https://github.com/openbullet/openbullet/commit/631f9b3cb9d8461eb9b53b4665932bb0ab94ef20
Basically if it's very fast it will reach the CPM limit quickly and then wait for a bit until more than 1 minute is passed from the first test, then again it will start until it reaches the limit. Please test it out.

**Comment by ReDDOOne** [comment]
@openbullet i already did, and i can confirm that it is working, it meet exactly what request was about i guess

btw my idea was a bit different, some sites throw a ban key or server is down for 5 mins to 10 mins
so even with proxies, the app will have to re-lunch proxies so many times before the 10 mins end, so it is all about retries in this time.

so a key to trigger a stop/pause for x mins would be also good

**Comment by openbullet** [comment]
@ReDDOOne okay but that would be a different issue, open a new one. Closing this.

**Comment by ReDDOOne** [comment]
alright

**Comment by mastercho** [comment]
> @openbullet i already did, and i can confirm that it is working, it meet exactly what request was about i guess
> 
> btw my idea was a bit different, some sites throw a ban key or server is down for 5 mins to 10 mins
> so even with proxies, the app will have to re-lunch proxies so many times before the 10 mins end, so it is all about retries in this time.
> 
> so a key to trigger a stop/pause for x mins would be also good

Use some logic, none of these was in BB and we was still able to implement with what we have in hand
