### ISSUE TITLE
[REQUEST] Maximum number of consecutive Redirects

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#177]
Lately, i am testing a web site with 8 redirects after login requests.
but the app is throwing this
<img width="629" alt="Screen Shot 2019-05-07 at 11 24 49 PM" src="https://user-images.githubusercontent.com/23710158/57339045-5ece1600-711f-11e9-9a3c-33eea504227d.png">

**Describe the solution you'd like**
Can you increase the maximum number to 10

**Describe alternatives you've considered**
Maybe a setting Box which control this

Thanks

**Comment by openbullet** [comment]
Done
