### ISSUE TITLE
Hide if not Capture found [REQUEST]

### ISSUE THREAD

**Issue by beer15** [openbullet/openbullet#180]
**Is your feature request related to a problem? Please describe.**

I have an idea to make the captures cleaner, sometimes we have to capture several things on one page, but also sometimes we manage to capture one thing on several things
at the end we have a not very clean result, example subscription= premium - accountType= UHD - ChannelAddon1= - ChannelAddon2= - ChannelAddon3= true

Here you can see ChannelAddon1= - ChannelAddon2= not capture found

https://i.gyazo.com/09dc663e04a60cbd1d3bd3d857b84e7d.png

**Describe the solution you'd like**

add an option in parse block, which allows you to hide if the capture has not been found

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/74d5aa34363c08fbc12523cd5ebfd1dffe49b1b4

**Comment by beer15** [comment]
thanks alot ruri @
