### ISSUE TITLE
[BUG] Utility Variable Split

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#183]
**Describe the bug**
the split seems to work only when the separator is "," as it is the default one
and it does not overwrite the default one with others like  "-", "_", "|" ...

**To Reproduce**
<img width="1504" alt="Screen Shot 2019-05-09 at 12 47 03 PM" src="https://user-images.githubusercontent.com/23710158/57454634-d3f13680-7258-11e9-896c-0e434350d45a.png">

**Version**
 - Version [e.g. 1.1.2]

**Comment by openbullet** [comment]
Fixed
