### ISSUE TITLE
[BUG] Sorting in config list

### ISSUE THREAD

**Issue by shdf2** [openbullet/openbullet#184]
> https://github.com/openbullet/openbullet/commit/c227ffed2b78b50d542af414d9b528300e19c05f

Looks like we can't sort by creation date, you can only sort by ascending order. when you click the column again it doesn't sort in descending order. Some other columns have the same behavior... maybe it's something expected ??

EDIT:
probably the same bug as described here ?
https://github.com/openbullet/openbullet/issues/149

**Comment by openbullet** [comment]
Duplicate https://github.com/openbullet/openbullet/issues/149
