### ISSUE TITLE
About Proxies and wordlist

### ISSUE THREAD

**Issue by r00tee** [openbullet/openbullet#185]
Hi
I hope you add you can choose the (load proxies / api Proxies) of you want to use on config
Instead of using proxies on all the config
Some paid proxies require 100 threads to be used
When you use more, your account is ban

It will be a unique addition to Openbullet

Also when you want to delete all wordlist
When pressed (no) is also delete all

Thank you

**Comment by mastercho** [comment]
100 threads = 100 bots

**Comment by openbullet** [comment]
Duplicate https://github.com/openbullet/openbullet/issues/153
And for the second part, done.
