### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by deletelist** [openbullet/openbullet#186]
ciao
i siti hanno un solo specifico nik per utente e per agevolare chi lo usa si puo inserire un auto pulitura hits/free/custom che elimina dalle combolist tutti i doppioni delle hits/free/custom gia trovate  all'interno della combolist cosi da non ripetere inutili test con i nikname delle  hits/free/custom gia trovate , grazie per l'attenzione

nessun programma fa quello che chiedo !

**Comment by openbullet** [comment]
Use external software to achieve this, OpenBullet was not meant to do what you intend to do.
