### ISSUE TITLE
[BUG] 2captcha/RuCaptcha URI lenght

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#187]
**Describe the bug**
If try to pass BASE64 IMG to 2captcha/RuCaptcha url throws URI too long error

**To Reproduce**
1. Parse BASE64 image or just use this example
```iVBORw0KGgoAAAANSUhEUgAAAUIAAAAyCAIAAACmmkW+AAAABnRSTlMAAAAAAABupgeRAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAYV0lEQVR4nO1dyW4c2bGNnOeqyho4qMpqqRuQYMOAAKMbXnjZm/5df4S9NQwvDC1It1ripCJrznl6i/MycFlFUjRTbLLfy1gIpWLOeU/EiRNxb0nHx8fUWmu/rimKIkkSEVVVJX6PL0Xb2oD/m+d5nueSJKmqqqqqJEm7+27tiH15s7u3F3eRZVn85os73nj8rRvZtTzP73PYG01+8J6ttdbExGEt1fbFvXgzWZYVReHjSJL0RZyw48CWVW13Xx6OLP73tqvauoUvXs8DtrzN1Ib7t9bag+22yLYVNndNkiTE87IsJUmSZZk/331GRvuWE7nxArb+JF7t3bvf/0a+eIR7Wgvj1p6R3TMuSTt2n1B89zY3knxYWZb4AH+xu9fddk+a0MRaGLf2xHY3rb1tiPNfGZ9fzI13j7m7i4h2hN+yLBnGd59il1GLp7ubXNxx2PtYC+PWnsxuBPCNxPXufYG3+8B46yx3RGAxfxZhjIT8jsu+7VB3w7hhetxKXK219pu3Nhq39mR2Y0iEUnWfmMyaE2+PsHljpUfcmHY0KoRckWzLspxlmSzLuq7jsHEcZ1nGAXlXBrtNPLst5t+Td9zHWhi39mQGaImU+J5VWTEx3ioj3WZc+71DG8cHgBZqVlVVRVGI1eMbte6tg9x4m1tfPqw0dZs1gvFf//pXTdO4+J7neVEUcGBUl7PLsqyqCo+AywN86UVREJEsy3hq+BdlfVmWi6KA85NluSzLPM9Zb0DZkA+L68Fl4Jhc7vvpp5+a3GNrj2RbQRJ2B0i29t0NuTzMbmspEc/IEZiEXpStHFXchmpg7+axN57ujtj7GNYIxgAwPx1+iIzDLd2PPyuKItIY3hLfYEtFUXRdZ41BPI6qqqw0cBEfjxho5234HbT2rGxLoKKbmPD9JasvSsG0M074v/ynu1VrEqj7M7RGMOa0AUhDUM3zPEkSXdcty2JOwgV6MTIzVwGq+XVqmoa9gMMsy3Bwzkk0TcOJGLrYtyzLoiiyLBPfVvNn1Nqvafd5ayIOOWDcc0fxMzNtEnDOQxrjWQw/YswXD3j3eX8F8DeCsehHQXdV9X8PKEmSqqpVVWVZxpjEQyGiLMvyPOenLx6NapIDABdFAWrNhwWY8Se8OeBZ0zSO7UVR4MvbygOtPSvjVy++6Du2R5J1WxS90USc814AJI7G8hiTuOp6HWv3dFunvlGy2rqjGwHfHOeNYAwpj6ECQivLMqJlWZacviJP5phcFAX+in05i8afiqLQdV1RlCRJcAp4B+TGkBDzPE/TNEkSbGPbtu/7lmUhMw/DMM9z5O0NH1Brv47tIvkOQyDljGkLnHfvKMorTAx5aLFMQ7XmIvLErUNtXfnuf7fY/m1BuzlnbDTKRUJLNdVh1CVJApQiPLLih8etqioeGcdb7A4KzbIWjoyQy7vjr3meL5fLi4uLMAyHw6FpmrZtw61AY0Pq3uQGW3tU4wC1G+XuM7LFUMli1W0b8wERKsRvEBWKolBVFfGDd6l2JC7GNl3H59NmcI1gDBDGcYwYiBQXEC2KIooi5LFALO4faOQ4THVejelmVEd4ZtRSLfpTnUXDE8uybBiGLMtxHG82G9u2syxLkiSOY9M0HcdxXTeKojiOGz+i1r6+IfQRkSzLaZqKWjER5XmOMUNEWZbhM2q22B2Qo7rSwXthvCmKkmUZ1R6f3QRgBuVluVwWRWEYBhElSWIYRlEUSZJgaCGQYEfkhiTUWRRFQUUG32Mkc5TCxeAaQNFxkDRNDcNI0xS3AOyw1tsw+2sKY1wiZC3TNHEzCJ54rHjihmEoihIEAZ4Csxq8TgRPDrN4tXmeA6hFUeC/7CmqqtJ1XVXVKIps216tVlmWYRu4A+TGzZ9Oa49n7KDFIQF5EuMqTVNd1yVJQn6EvzLaefCADwK9iCg8cZeVMIxPWZYdx0mSBCz6w4cPnU6HiDqdDpCZpmlRFL1ezzAMDOyyLOM4hrPQNA0DFXjmKI14w8MY3xAR8A/LsoydC+McwKEaR00eZlNSbZqmqqpBEOR5HkVRmqaSJAFFlmVZllWW5Waz2Ww2iqJEUeQ4Dm4PWTTuBAbn1Ol08M6ICCk0kJkkyWazCcMwyzLTNPv9vmEYjuPgFPxGEZDhqjVNM02zyQ229kgGiGIkAD+IvRg5GNa6riN2MdrFPCtNU7xoy7JAxHRdh9MHqqkeP5qmMZCA5zRNN5vNbDZbLpdEdHh46DiOYRgYh6ZpGobBjD3Pc8APYwxBQmwFYXmVOSPVQjcuBqMRZF7XdRwNF8xsomH21xTGiqKktcVxHIYhpKmyLEejkW3bkiRtNpvVagXPmiSJbdue52HHoigWi8Vms+HsKE1TiFVEtNlsEMzLskzTNAgCRF3LsiRJ8n1fTKdlWQ6C4OPHj1mWDYfDwWAAyt3kBlt7JAM+MdAXi0UQBOC3HEsx4ouisG0byiWINw+SLMs2m02apt1uF2QVyRSAygdBTpemKQ8hTdOWy+V0OiWiX375hYhms9n+/v7e3h76FObzeVEUjuOwHAvgrVYry7J832egYoM0TfEZJ5UkCQ4F9BADuKoqRPgkScIwxLW5rgsXwynGg62pUl0URRAEcGxRFMH54SUZhqFpWhiG8/kc1x3HcZIkmqaNx+PBYIA3cXV1hXegqmoYhkD1aDQCo06SZDqdxnEMvg3ErlYrTdMcx4GfBrbX63VVVYvFAmepqmo4HDZ8Oq219puwRjCGHwKlmU6naZq6rovGDwTeT58+rddrx3GGw2Ecx+DeWZat12vbtpMkubi4YD+qqupqtTo5OamqynEcEJLZbHZyciLL8ng8dl13tVrN5/MwDA3DAIcHYvM8h6Pt9XpBEFxdXeV57jiO53lf60m19hWNu26JCIMHMQoZJjjqarUqy9IwjP39/fF4jPwZOeRmswmCQJKk8/Pz//znP6PRCMLq4eFhr9criuLs7AwnQvZLREVRXF5eLhaLwWCw2WxQ4Dg/P6e6p1DX9V6vJ0nSfD6/urqaTCbcgBAEARF9/vzZNE2MMY4oaZoicjDh1zSt3++bponAG4YheLXrurIsh2G4Wq2IKM9z3/f39/fFSvWD7SuUVZHkAJ+6rvu+b5ombh6oMwzDMAxQHdCMMAyDIAAJN03T8zzTNIHJIAiYUM1ms/Pz8yiKRqMRHg0KwoqiIFZXdZcYHrfjON1uFy/p4uJiMpn0er3mN9jaVzeWi8A2i6I4OjoiotVqhZyr2+3meR7H8dnZme/7f/nLX7755hsWlsqyXC6X/X7ftu0PHz6cnp4Skaqqp6enf/7znzVNu7q6IqLLy0vLsvb29sbjMYjhdDoFZ7y8vISvp7rdCIkhEZ2enoZhGEXRYDAgojRNkUJ/+vSJiBzHMU0T9DvLssVisVgsoJDhpKvVajKZfPfdd6Zprtfrz58/z2YzyDSj0QiknYhmsxmI/XA4xBNo8jybdnEhXdE0TdO0IAgURen1erZtB0HAhQQgHHeyXC6lerYDHgpE7DiO1+v1ZrOhWkuoqgru03Gcfr+Pxk/DMFzXxbvnOh4atlzX9X3fMIyyLE3T3Gw2y+XyxYsXTW6wtUcySFAYG4qiIF8louPj46qqPM978+bNZDIhoul0enR0BE/96tUrRGMk0mEYOo4zGAyOjo6Y1um6/sc//hEVipOTkyiKJpOJpmmHh4ee53met9lsoihaLpfz+Rxkrd/vdzodyFpIX8/OzpIk+f3vf9/pdDg33mw28Aue5w2HwzRNwzC8uLjAEJVleb1eE9H79++Pjo6SJHn37l2n05Ek6ejoCOd68+bNeDzGLQRBsFgsbNtGhvyUEhfXeImIOQ8cbRzH4NWmaUKigLwMguH7PiQE8GGIAUmSQA+IoigIAgjgWZYZhoHwTkSWZfX7fRQPuCEEl9HpdDqdDm8GYTxJkiY32NojGd4ynLUkSShqEFFZlovFIkmS7777TlXVbrfb6XR+/vnnv//977ZtHxwcQPVVFMV13cvLS9u2Dw8PV6vV6ekpIxnaKhFlWTabzRzHmU6n/X7f930MtqurK5A+xED8qdvtsnT6+fPnIAjQVoRLxUmvrq5++eWXb775ptfrzefz9Xo9n8/BBQaDAZzLaDT6xz/+oWnawcHBy5cv+/1+WZZnZ2e42sFgABriOA5OgcHf9Hk22Rk+EvUeCHSQo3HP6LLqdDrD4dB13TRN+/0+fA84iaZpqMsRkaZplmW5rhvHMSANkRBztbl8j5CO9iz4SA7sKEgA21yv52p7a8/KUDUElsDFEBhBzXjKjeM44/F4Pp8jB55Op4eHh1S3DKFtAyT8xYsXAFWWZUdHR3t7e0TU7/dPT08x1y1NU8/zxuMxlFEUQap6co7neb1ezzRNWZZ/97vfXV1dgd4jKYOLQeIGzhgEQVmWnz59mk6n6/Ua3uHdu3dE5HnefD6P4/jTp0+DwcBxnNevXx8fH6MEmySJ7/tE9Pbt2/V6res6bhms/sHPsxGMkfECNuiJQQcIFGzETMDbNE2A0PM8CNRoz5hOp1ypcxwnDEPUorn8EIYh6gpZlmVZZlmWaZpZlkHfIiK8dRSlEOoBfjDztuD0PI07q/Cm4KmpLq6qquo4ThRFw+FwOBz6vn95eRnH8cnJCdAOkcWyLLh1TdOiKFJV1TRNEDfISGicsiwL6gxYoWEYSLiQwRERSsrIxSDQYJQiW0ROh80Wi4WqqlmWAahZlv38889Jkrx69arb7SJTGI1Gb968mc1mSZIghQQPRwrted5oNCKiTqcDVQ+ND09ZcEJ5CekxPAqiMQdn6MnT6RQ5ANAeRdFqtUKjJUrHeNBioyVoBtqk0zSdz+eAKzdsg43otVE9vwIXg83kneVIW3smxjBGlRHBgOpeZYwBTdOyLEN37f7+/mAwQLylOhp7noeIimGG/krIzqDB0J8xGDBQ0ZWBnAttnlRrMVI9qQ5tW6ZpKooCmo2rwmi0bRsxZrlczmYz1Ef39/cnk4njODjpixcvoNrKwkwsVLBd14V4zg0n4o0/2Joq1ajL89RCniYCkmzb9mw2+/z5s+M4o9EI/gkt0MhYoIohXMdxHEURwjheHsCPnhuoCMiW4YwxEQKXUdZGRDyxCa6k4Q229hgGbGDYIEflKQfcbz8YDKqqQtPFy5cvDw8Pq6o6OTkhIgBYURQwNRSBeGY7d2hTPe0BZJCECcMYroifwKqu66DHVVVdXV31ej1WcJFC8+I2iqIMh8PZbAZNuyzL8/NzwzDAliFcIbpwKxSfUZzzJ9VT66XrM58fYE1X/xCbqEFIIEqjSw4dIFmWnZ2dLRYLJKuSJPX7fc/zzs/PgyBg7R69lhAAV6uVaZq9Xi8Mw9lsFgTBdDoFRYnjuKoq3/dR5UPtmoiAf27M5pHR2jM0iFsY3Gi25ZeIOhNau5BDQa8aDodExCXc+Xyu6zoAg9oyJsPwHFgiQlEXBJi7I5GgiZtJkhQEAQIGOB2aEREM+NrQxUlE4MaTycR1XWixl5eX//73vw8ODohI13Ve/QYtFUjjofjgfkmYaCHV1uR5foW6MSvyeExJkiBLQSzFnaAfE20eoDSY+eC6blmWYERokYXjRHFvMBigJjGbzcIwRNCWJAlJOCqBoEZQxaFLY4IEKk8gV609T6uqCkoH/Di+lCQpDMPLy8uPHz++fPnS8zzEQ+jJgPG//vWvy8tLwzBQOk7T1Lbt/f39jx8/gqKjlx7B8PT09P379+jZhIYCogtmR0Ro40c/P1dbTk9P3759S0RhGKIYBvwjllRVtb+//+OPP85msw8fPuR5/s9//hO62uvXr6uqguPAXADuIwYDR2znpWyqrzHJsRGMEYrhwDqdjuu6cJxwdbqu7+3tybKMdhx0dyEHhtrc6XTG4zFCaJZljuPYtt3pdPBWUIv2PM/3fW4rB5H2PK/f70PBwn+hJVKtkFuWBWW/Vaqfp3FDMlIwBGEiQjpmmibPkAF/xmjp9XrdbpeIMGaQeUG4Go1Gf/rTnxC9sTsRvXjxYjaboUX37OxM13XAfjQaTSaT4+NjOAW0Ks1mM4DfsqyDg4MoioA6RAgiMgyj0+lcXFwg5ruu++7duyiK/va3vy0WC6r7Q0ajEQYeAhURua47Ho/RUzybzVBe7na7CMvy9XWCHmaNYMzkAQhEJQlcBTxB1/XhcNjr9XhmItRFsGtN00ajEWRnRVG63a6u60EQRFGE1ALH57Yw8JyyLF3XReMLjoBZEI7jwMMhdel2u5z8tNba/21rqlQDWp7ngbFAfALjhwgBvY57UFEcQqqAPMGyLJTycAQI9Dg4+Lnv+wjRVb3eJf+kreM4kAdxLswX8TwPWncURa1S/TytqhemQ33Rtm1epwkl5cPDQ9/3MX4kSYI+DJ5FRK9evVJVFeUfzBauqmo8Hh8cHCwWC6gqRISJdBhp6/V6vV4jF3Nd99tvv4XmQkTI0cqyDMPQtm00KUHWWSwWw+EQVa7lcjkajVAxRpSK4/iHH35wHOf9+/eoWhHRer3GLFqecaWq6tu3b3E73MsAmJT1WpFP2YwJuEJa5NfAXB9JLC/igYlaZb3uES9SC00biiIeEJ4ptAGqGzxAPLhvHudFVQnJOct9yL2RnDS5u9Yez7gqiRfNqztAy0DPn+/7mBXITI1zSMMwJpPJcDjkIYER0uv1NpsNRFYiqqoK6gzyL7QMgTb6vv/999+jfIUhSkSQVJD69ft99IRR3Tpq23ZZlkiYocPBp7x+/dr3/fV6jSYFJI9IMKMoiqLIMIw//OEPk8kE3cQ4VymsOgRIN3mejWAM8syN01W9cBHyHOANHghxmIhYDIRADUWBVQe5Xo6P4znV86ioXi0Ebo+lTtb6xLW+uBWkjcbP07g8mWUZyhP4nmnUYrFAWzX8Pjw7V5IwSDCiuDsAkEZkA/DAAcHUMOqYx5mmube3h6DNLUyAMZI+XsEDcYJq4sDBg9tCHcfBjCCuS2FNL75I0NXJZIIuCbGfHLHniXNjpV4xr6pXiufFVnCh6K1BcQwXDYDxc+eaOwpFEMB4AQeQZO61BnfiOW4I8tiM1zTCFGW5Xk6pXcTn2RrGwHK5BE1F3Ov1eoDZ+fn5YrEAicN7LOv1sahezYfF3lJY9Q7FTq4kcds2KhfYDNGPG4fA2/mqsIs4qHA00AFZWHEdUi5PruRGND4U4g00IyQIIlw5AnETyIOt6eofjGEurHMriEgemA7JwsoJ8GdVvcqJVP9wBPsnDrlUr10kCT+9xS0foksrr6+V3Ubj52mS8Gshuq67rosWxbdv33KKFIbher1mYMvCD/1IwpKU3KTB0jdd/1lT8YMsLI0ufinXv1vCB+RWQj419kKzCjoouWmiEJbahMcRb1Cu1waEP6qEtq1SWFi2iTWNxiIfEGOsfH2das6W5Xppb47JirAqYnl9uVwSlq3np8x78VJGmBFJNS/AAZmrN7nB1h7JeJRjfnie55jca1kWVquKosiyrNVqBcoq8mQSRhoJP8jGqqokLEMrC4tOM+Dlm35lgo/Gx1TqlV7FK8e+4uJ4oh8hAZnS9d8/UutfSmI1iz1Oc87YFMZoT2OUin/CFW/dKgkxnARHyN8z9kS/KNfTIcv6R55Ap5V6Qa9K+FUK0SU3FABbezzDS7csCxMY0KQFzoWIBxBiPACfJMBMdPeV8CtfW/+KgbcUfnsIVl6fYytCkXbYnDgaeQ1A3lhM0ct6gUcSgvNWAizXv9Ow61AeYF9n2QCR1fBVUs1AttDFG2zRFRxN7G4RiRC7RrluN2d1cctHkOAR29z4ORveJqRjLltwwgltCWVIIiqE3wASxUuRqYkhgYRxxeGRmZoIUf4sCwvKI7ZL17udeViybC6GHGzDw7WoF8pEjEGmIAk/SMSp6BNH4y0HI3656xrFDyRQDrr+oOkmj8tulf+Ft5YkibmK6J7FSlWTG2ztkYyxx9NUOaZV9ewIYJgZKRdmSYC06OtZH6mu52UwJoBVLceyAgrHIQm5MZ9097LxgTHJJ+K9AE4Rq0X9oyh8zfyvXP8OYcPnKR0fHzc8RGut/bfGANgtt7D7vmeM2sXAVjbLEeK2Lbe2/29t67Aitm+8vF2T6+X1H3wN7S+VtfaMbJeI3WhbsL/x+/9X1sK4tSew3QC4FcToTkxWOwIy3fsH3G482j0vsrndFrobWps6ttbab97aaNzaE9hWFNoKxV+MUTdu8CSM+pnQ+BbGrT0vu096/IB8+EYeLtZHdvPtZwLR+1gL49aewG6sCbX2YGth3NpztBuDp/hX/vzbUqofyW21EldrT2YipxW/fP5ofG72P5SDCzfGFfOlAAAAAElFTkSuQmCC```
2. Pass this to solve to 2captcha/RuCaptcha
3. Will Throw exception right there https://gyazo.com/2731fab5acd3aeb065d0b6cc073d77ee for Long URI error

**Expected behavior**
Convert BASE64 to img then use POST as FILE to solve it.

**Version**
 - Version [e.g. 1.1.2]

**Comment by openbullet** [comment]
No need to post as file, fixed in another way.
