### ISSUE TITLE
[REQUEST]Reading key in DOM

### ISSUE THREAD

**Issue by Ei-Dotter** [openbullet/openbullet#188]
Hi,

is there a way to search keys in the DOM?
It seems that this tool is looking for a keyword in the source which there is still variables, like 
"Valid until: %Date%"
So there is no possibility to parse this text which is behind %Date%.
Moreover any possible output are in the source, so you can't get clearly keys.
Like:
"Your Account is 
var 1: "expired"
var 2: "free"
var 3: "Valid until: %Date%"

Only in DOM you see the text "Your Account is free", but by looking for keys in the source you'll find all of them.

**Comment by openbullet** [comment]
BROWSERACTION -> SourceToDom
