### ISSUE TITLE
[BUG] CF Bypass block

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#191]
**Describe the bug**
Cloudflare is tricky and won't trigger always, in the last Library which OP was using to bypass CF was okay but in the current one, if CF doesn't trigger their check its says 

> ERROR: CF Bypass Failed: Unknown protection detected

 and sets status as ERROR. 
https://gyazo.com/9db261e8b006e6f5970fad153d30f56a

**To Reproduce**
Just try a site like in screenshot where CF won't trigger always

**Expected behavior**
IF no CF triggers in CF Bypass block instead of setting status ERROR must continue like was before to next block.

**Version**
 - Version 1.1.2

**Comment by openbullet** [comment]
Give me an example site where this happens please

**Comment by openbullet** [comment]
Ah ok nevermind daofile.com got it

**Comment by openbullet** [comment]
Done

**Comment by 1tarko** [comment]
it is possible to implement pass-delay 
challenge solver as in Mr.Viper's storm,
to bypass cloud flare? Regards

**Comment by openbullet** [comment]
@1tarko what?

**Comment by mastercho** [comment]
If skips CF now doesn't follow redirect

**Comment by openbullet** [comment]
I'm pretty sure this behaviour is the exact same when you bypass CF. If it redirects, it will not follow it.

**Comment by mastercho** [comment]
> I'm pretty sure this behaviour is the exact same when you bypass CF. If it redirects, it will not follow it.

because is a different library?

**Comment by openbullet** [comment]
I mean, it's based on HttpClient and the default value for AllowAutoRedirect is true, sooo.. I don't know what's going on.
