### ISSUE TITLE
[REQUEST]HTML entity encoder/decoder

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#192]
I notice some security challenges like math questions numbers will be in HTML Entitiy in the source code, but currently, we dont have decode function in OB and cant continue with config. Would be nice to add them under functions

**Comment by openbullet** [comment]
Please provide an example

**Comment by mastercho** [comment]
Example code is below to parse CAPTCHA numbers  which they are like HTML Entity:

```
BYPASSCF "https://daofile.com/?op=login" 

#CAP PARSE "<SOURCE>" REGEX "Enter code below:<\\/b><\\/td><\\/tr>\\s*<tr>\\s*<td align=right><div style='.*'><span style='.*'>([^<]*)<\\/span><span style='.*'>([^<]*)<\\/span><span style='.*'>([^<]*)" "[1][2][3]" CreateEmpty=FALSE -> VAR "CAP" 
```

**Comment by openbullet** [comment]
Done
