### ISSUE TITLE
[REQUEST]Antoher problem with key in DOM

### ISSUE THREAD

**Issue by Ei-Dotter** [openbullet/openbullet#194]
Please excuse my further annoying question, you gave me the hint to use BrowserAction to send DOM to source.
This works fine, but when I'm looking for keywords in a member-area FireFox starts and OpenBullet Navigate to the site in the member-area. 
FireFox is not able to open this site because a login is necessary. I didn't find a way to transfer the Post-Data from Open-Bullet to FireFox, so FireFox can directly access the DOM from the member-area.
So how can I grab the DOM from a member-area  in OpenBullet source?

**Comment by openbullet** [comment]
You need to log back in using firefox, or you can try to use BROWSERACTION SetCookies (or GetCookies, I don't remember which one it is) to transfer cookies from the HTTP requests to the browser. That way, the site will recognize it's logged in thanks to the cookies.

**Comment by openbullet** [comment]
I also think you need to specify the domain when you use that browser action (e.g. example.com)
