### ISSUE TITLE
[BUG] Base64Decode

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#195]
**To Reproduce**
FUNCTION Base64Decode "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YjQ2ZmQ2YmZjNGUwNzFjNzE2ZWE4YWEiLCJhdWQiOiJjbGllbnQiLCJ0eXBlIjoiYWNjZXNzVG9rZW4iLCJpc3MiOiJmYiIsImNJZCI6IjViNDZmZDZiZmM0ZTA3MWM3MTZlYThhYSIsImp0aSI6InFnZmJuc3p0MGlxbnIiLCJpYXQiOjE1NTc2NjMwNzMsImV4cCI6MTU1ODI2Nzg3M30.xRRgfGgHkp005YatrvuRWLDCj5tqtVl22Vc7S1MiwHY" -> VAR "decoded" 

**Screenshots**
<img width="606" alt="Screen Shot 2019-05-12 at 12 15 28 PM" src="https://user-images.githubusercontent.com/23710158/57582050-a81bbe00-74af-11e9-8705-8443817b47d4.png">

**Version**
 - Version [e.g. 1.1.2]

**Comment by openbullet** [comment]
What happens if you do a `FUNCTION Replace "." "" "<decoded>" -> VAR "decoded"` beforehand?

**Comment by ReDDOOne** [comment]
ERROR: Invalid length for a Base-64 char array or string.

**Comment by ewwink** [comment]
it list of base64 encoded string but I don't know what is the third item.
You have to `Split` it using dot `.` then for the second item (before dev fix) append character `=` because base64 encoded string should can be multiplied by 4 or you will get an error.

> ERROR: Invalid length for a Base-64 char array or string.

loliscript test

```
#String FUNCTION Constant "Your base64 encoded string here" -> VAR "EncodedInput" 

#Split UTILITY Variable "EncodedInput" Split "." -> VAR "ENCODEDLIST" 

#Fix_2nd_item FUNCTION Constant "<ENCODEDLIST[1]>=" -> VAR "SecondBase64Encoded" 

#Count_List FUNCTION Length "<ENCODEDLIST[*]>" -> VAR "EncodedCount" 

#base64decode_1 FUNCTION Base64Decode "<ENCODEDLIST[0]>" -> VAR "DECODED1" 

#base64decode_2 FUNCTION Base64Decode "<SecondBase64Encoded>" -> VAR "DECODED2" 
```

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/011aa0cd9088ea069982045d33ba82dedf2c803d
