### ISSUE TITLE
[BUG] Having problem getting one source from a url

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#196]
**Describe the bug**
i am requesting a url, which return a javascript code
i need to parse that code and execute it.
but the app is not helping
the app return the content-length but no source

**Screenshots**
<img width="610" alt="Screen Shot 2019-05-12 at 12 56 59 PM" src="https://user-images.githubusercontent.com/23710158/57582653-07310100-74b7-11e9-9510-cac4d2b859ce.png">

**Version**
 - Version [e.g. 1.1.2]

you will find the url at Demi
thanks

**Comment by ReDDOOne** [comment]
update:

i have tried the POST req instead of the GET from before
and i was able to get the source without any error
PS the source from both GET and POST are the same

so it is weird why the app can not get the source in a get request

again, you will find the config at demi
you decide about this issue (close or leave open)

**Comment by openbullet** [comment]
Okay thanks
