### ISSUE TITLE
Doesnt change <USER> and <PASS> into their variables

### ISSUE THREAD

**Issue by SharkD3v** [openbullet/openbullet#2]
per example we have a login of username1: password1
the post data is username=<USER>&password=<PASS>&login=1
the username and password entries will be <USER> and <PASS> and not the login ones

**Comment by openbullet** [comment]
If you want to have those variables, you need to define a new Wordlist Type inside the Environment.ini file. This is not an issue, this is how it's supposed to be. Please get a correct Environment.ini file.

**Comment by SharkD3v** [comment]
Alright, appreciated.
