### ISSUE TITLE
[REQUEST]COMBOTYPE IDENTIFIER

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#201]
**Is your feature request related to a problem? Please describe.**
I have a website which allows only certain email domains, and usernames. So i want make 
`IF COMBOTYPE EqualsTo "EmailPass" then convert them into UserPass by removing email domain part. 

`**Describe the solution you'd like**
I dont know what best would be to do that, add function Email to User or COMBOTYPE IDENTIFIER

**Describe alternatives you've considered**
Write regex to get rid of domain part but cant control if is combotype is correct or not.

**Comment by openbullet** [comment]
```
IF "<USERNAME>" Contains "@"
FUNCTION Replace "@.*$" "" UseRegex=True "<USERNAME>" -> VAR "CLEAN-USERNAME"
ENDIF
```

**Comment by mastercho** [comment]
> ```
> IF "<USERNAME>" Contains "@"
> FUNCTION Replace "@.*$" "" UseRegex=True "<USERNAME>" -> VAR "CLEAN-USERNAME"
> ENDIF
> ```

Tried but would screw User combos which include @

**Comment by openbullet** [comment]
You can improve the regex by adding something like `@.*\..*$` which will make sure there is a dot after the at symbol. There is a VERY THIN chance that a username has both of them in that sequence.

**Comment by openbullet** [comment]
For the whitelisted email domains you could make something like
```
KEYCHECK BanOnToCheck=False
  KEYCHAIN FAILURE AND
    KEY "<USERNAME>" DoesNotContain "@gmail.com"
    KEY "<USERNAME>" DoesNotContain "@yahoo.com"
    etc...
```

**Comment by mastercho** [comment]
ok thanks i got your idea, i'm waiting for answer in forum :D
