### ISSUE TITLE
New Line 

### ISSUE THREAD

**Issue by blurar** [openbullet/openbullet#202]
Newline on the UTILITY Block.

When we save vars on the .txt files , no matter how many vars are in there   it will just put all vars together in the same line.

Example :
Hello:Hello  VAR1 VAR2

And we want it

To

Hello:Hello
VAR1
VAR2

**Comment by ReDDOOne** [comment]
i guess it depends on the editor, where you are pasting

**Comment by openbullet** [comment]
He wants OB to print a new line when he types `\n` in the box.

**Comment by ewwink** [comment]
before saving combine your variable like below
```
FUNCTION Constant "Hello\\r\\n<VAR1>\\r\\n<VAR2>" -> VAR "VarsWithNewLine"
```

there is also ```UTILITY > List > Join``` to combine List with defined separator

**Comment by openbullet** [comment]
@ewwink Yeah but did you test if it actually works? Because I think it will just print `\r\n` to the file as ascii characters instead of making a new line. I don't remember if I implemented a replace function for that escape sequence.

**Comment by ewwink** [comment]
It work, I already test it before posting :grin:

**Comment by openbullet** [comment]
You're not the first one who knows my software better than I do :D thanks for the awesome help man, I'm gonna close the issue at this point since it's solved.

**Comment by blurar** [comment]
The Syntax for a new line on the Utility Block.
`\r\n`  

 And For Loli Script it should be like this,
`\\r\\n`

EX : `UTILITY File "" Append "<VAR1>\\r\\n<VAR2>"`

**Comment by dirbaal11** [comment]
i need help
