### ISSUE TITLE
[BUG]DeCaptcher RIP

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#204]
**Describe the bug**
Decaptcher doesn't check balance or solve captcha

**To Reproduce**
1. Add DeCaptcher acc and click Check Ballance in settings will do nothing, its not doing POST request to check balance at all
2. Lets consider only balance check i s broken and try to solve captcha with it. So go to stacker and run some config
And we will get

```
<--- Executing Block CAPTCHA --->
Checking balance...
ERROR: Specified argument was out of the range of valid values.
Parameter name: value
```

**Expected behavior**
To check balance and solve IMG captcha
**Screenshots**
https://gyazo.com/3c02725dfbcd51fd13206709e32bbdcf
**Version**
 - Version 1.1.2

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/42938b45debb2d8b5954f7c974ad390e79aaabe3
