### ISSUE TITLE
[BUG] <USER> & <PASS> var

### ISSUE THREAD

**Issue by Felwey** [openbullet/openbullet#208]
OB no longer replace USER and PASS variables with input data

At first I thought there was a problem with my configuration files but I realized by simulating a test with the debugger that OB was no longer replacing these 2 variables and I don't know why. I also don't know if this problem concerns everyone but a few people told me they were facing the same problem.

I would like to point out that a few days ago, everything was working properly.
I tried to uninstall and then reinstall OpenBullet but nothing has changed...

Version: 1.1.2
Screenshot: https://pasteboard.co/IeO9UFX.jpg

**Comment by Felwey** [comment]
I finally found the solution and the problem came from the "Environment.ini" file.
 
The same problem as with the old version...

**Comment by openbullet** [comment]
Stop posting this stuff, OpenBullet should **not** be used for malicious purposes and we all know USER and PASS are used on cracking forums. I will not facilitate that kind of behaviour, so the Environment.ini file will stay as it is now.
