### ISSUE TITLE
[BUG] Make header `Accept-Encoding` Optional

### ISSUE THREAD

**Issue by ewwink** [openbullet/openbullet#209]
Some website block request if there are additional HTTP header including `Accept-Encoding: gzip,deflate`, this header appended automatically by

https://github.com/openbullet/openbullet/blob/d31c8768925057b3434804c7138a4ca7d8bf066e/RuriLib/Blocks/BlockRequest.cs#L349

I think it should be optional, maybe you can create another checkbox to turn this on/off.

**Version**
 - Version 1.1.2

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/59a421876d86bd6812e07af00fea8858764a6d87
