### ISSUE TITLE
Capture Data isn't getting saved

### ISSUE THREAD

**Issue by ForlaxPy** [openbullet/openbullet#21]
Well basically after getting some hits and going to the hit logs you will find everything well saved but as you restart open bullet you will still find your accounts hit but all their capture will be just gone/empty .

**Comment by openbullet** [comment]
Could you please check through liteDB explorer if the captured data is saved inside the database (and hence if it's only a loading issue) or if it's not saved at all? Thanks.

**Comment by ForlaxPy** [comment]
I just checked and I found that the capture does exist in the db file but for some reasons it doesn't load 
![preview](https://i.imgur.com/QmRERnA.png)
![preview2](https://i.imgur.com/q3lzOOR.png)

**Comment by styles977** [comment]
Yeh same thing Happening for me.  It saves the captured data but when I restart the app the captured-data do disappear.

**Comment by styles977** [comment]
@openbullet this is the only main issue , give me your email or sth I will mail you the captured database if needed.

**Comment by openbullet** [comment]
@styles977 No need I can just make some random data to check it. I will address this asap.

**Comment by shdf2** [comment]
i confirm that bug. whe nyou restart OB, the columns **Wordlist** and **Captured data** are both empty, while the data  are in the database.

**Comment by openbullet** [comment]
I fixed the wordlist column but I cannot manage to reproduce your issue with the Captured Data. At this point I think I need one of you to send me your database file if you can, thanks. Please send it to my mail (ruridev at protonmail com).

**Comment by styles977** [comment]
@openbullet  sent :D

**Comment by styles977** [comment]
@openbullet I couldn't open my hits database through LiteDB it shows empty but BB can open it 🥉

**Comment by openbullet** [comment]
Yeah perfect it looks very tricky to debug but I'll do my best

**Comment by ForlaxPy** [comment]
Any updates on this?

**Comment by ForlaxPy** [comment]
@openbullet Ok I tried debugging it and I found that the issue is coming from RuriLib.Models.CVar.cs  Line 122, it fails converting the capture data from type 'object[]' to 'System.Collections.Generic.List<string>'' and that's what make it not display it.
![pic](https://i.imgur.com/MGB9kfR.png)

**Comment by openbullet** [comment]
Thanks @ForlaxPy you really helped out a lot, fixed https://github.com/openbullet/openbullet/commit/a6a4d1fe89fe9ea0325580e08930fad89aab6b8c
