### ISSUE TITLE
[REQUEST] salvare hit e free

### ISSUE THREAD

**Issue by deletelist** [openbullet/openbullet#212]
ciao vorrei fare una richiesta di salvataggio hit e free tramite txt cosi da non aprire ogni volta openbullet , tutto quello fatto in blackbullet e andato perso perche non salvava su txt le hit e i free se siete cosi gentili da fare qualcosa 

hello I would like to make a request to save hit and free via txt so as not to open openbullet every time, everything done in blackbullet has been lost because it didn't save the hits and free on txt if you are so kind to do something maybe you start to improve the program making it as flexible as possible for all uses.

**Comment by openbullet** [comment]
HitsDB -> Select anything you want to export -> Right click -> Save

**Comment by deletelist** [comment]
se capita che si corrompe e non posso aprire piu il programma perdo tutto ! e se e cosi lo puoi usare solo tu il programma , gia mi e capitato con blacbullet che ho perso tutto !
se devi fare una cosa o la fai bene o altrimenti non la fare proprio !
a me piace essere diretto Ruri 

if it happens to be corrupted and I can't open the program anymore I lose everything! and if and so you can only use the program, already it happened to me with blacbullet that I lost everything!
if you have to do something or do it well or otherwise don't do it right!
I like to be directed by Ruri

**Comment by openbullet** [comment]
Allora innanzitutto se non sei capace di fare le cose non dare la colpa a me.

Secondo, BlackBullet utilizza un database di tipo SQLite. Se ti scarichi il programma chiamato SQLite Browser puoi aprire il database anche se BB non lo legge e tirare fuori i tuoi dati.

Terzo, OpenBullet utilizza un database diverso, chiamato LiteDB. Se ti scarichi il programma chiamato LiteDB Explorer puoi aprire il database anche se OB non lo legge e tirare fuori i tuoi dati.

E' tutto scritto in ogni caso sulla documentazione, quindi prima di aprire la bocca collega il cervello per favore, grazie.

**Comment by openbullet** [comment]
E comunque caro "ultimo" ti si riconosce dalla grammatica da prima elementare, dopo aver parlato male di me vieni anche a rompere le palle su github?

**Comment by deletelist** [comment]
Caro Ruri 1 non sono il tuo amico ultimo 
2 devo installare 100 cose per utilizzare il programm per vedere qiello e per vedere quell'altro
tu se ragioni da programmatore cosa che dubbito tu sei devi agevolare gli utenti non rincoglionirli
3 riferiro a ultimo e vedrai che ora vi cracka e vi rompe le palle anche qui !

**Comment by openbullet** [comment]
1 - Ma tu hai vinto il premio simpatia per 10 anni di seguito?
2 - Altro da fare non ce l'hai? Sul serio, sono curioso, un lavoro... la scuola... pornhub... ci sono tanti hobby.
3 - Cosa c'è da craccare qui? Il mio account? In bocca al lupo ^_^

**Comment by CheNoia** [comment]
1 - Vai a casa dai su che e' tardi! 
2 - Ecco bravo,...diglielo a ultimo 
3 - Ma ultimo chi? Ahhh ho capito chi e' ultimo
4 - Ma e' ultimo ultimo? Oppure solo ultimo e basta?

**Comment by deletelist** [comment]
proprio vero che se parli con i cretini vincono sempre loro alla fine chi ci rimette sono io che vi do retta , ciao e bun pasticcio per il programma.

**Comment by openbullet** [comment]
Ciao e buon ban!

**Comment by CheNoia** [comment]
Arrivederci e buon pomeriggio !
