### ISSUE TITLE
[REQUEST] ability to use specified proxies and auto stop after x number of to check

### ISSUE THREAD

**Issue by winuser** [openbullet/openbullet#215]
**Is your feature request related to a problem? Please describe.**
1. Allow the use of specific proxies for specific configs, perhaps an option to load a specified list of proxies for a specific config. (This is needed as some services only available for that particular country)
2. auto stop the process after to check tab combos reaches a certain threshold. This is to prevent further combos to be sent to the to check and it won't require ob to waste resources and eventually crashing the program. So if consecutive combo keep going to the to check tab, stop the cracking process.

**Comment by openbullet** [comment]
1. Refer to this https://github.com/openbullet/openbullet/issues/468
2. This will be done in the scheduler update which is already planned.
Closing the issue as both requests will be tracked elsewhere
