### ISSUE TITLE
[Issue] Arrow keys for selenium

### ISSUE THREAD

**Issue by krombopulosM** [openbullet/openbullet#217]
trying to open a form using selenium. I've managed to select it using <ENTER>.. but to get to the option I require I'd need to use the down arrow.
I've tried to use <ARROWN_DOWN>
<DOWN_ARROW>
<DOWN>
Keys.ARROW_DOWN

None of which worked, so can someone please tell me the correct input for arrow keys?

**Comment by openbullet** [comment]
Only <ESC> <ENTER> and <TAB> are implemented. The others are not. Did you try selecting it using <TAB> already? Because that works in 99% of cases.

**Comment by ewwink** [comment]
@openbullet for selecting Option drop down you need to add function `.SelectByValue()`

@Ron-Swansonl use `EXECUTE JS`

if your option like this
```
<select id="myID" name="testname">
  <option value="1">CAT</option>
  <option value="2">DOG</option>
  <option value="3">BAT</option>
</select>
```

to select `BAT` the JS is

```
document.querySelector('#myID').value= "3";
```

**Comment by openbullet** [comment]
@ewwink Thanks for reminding me, I was meaning to add that but I forgot which one it was. You're the MVP mate.
