### ISSUE TITLE
[BUG]Jtoken doesn't work as supposed to be

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#218]
**Describe the bug**
To go inner in json you must enter JToken (Regex for Json). In OB this rule doesn't work.

**To Reproduce**
Enter Jtoken to reach the second index of occurrence.
And you will get this error:
https://gyazo.com/a3e65403bfe60d6ab2ce50f97f65b984

**Expected behavior**
To respect Jtoken and get the second index of message
https://gyazo.com/0e5db2fde26d6e23c7c87dbbb182032d

**Version**
 - Version [Last commit]

**Comment by openbullet** [comment]
Of course it doesn't work, it's not meant to be like javascript where you build an object from the json string and then access children via `.` it's just meant to be a basic json parser! Doing what you ask would require a radical change to how I'm parsing json, I'd need to actually deserialize it hence increasing the RAM consumption by a lot when used on big json responses and with many bots.
I'm not sure I want to do this. Let's see if anyone else wants this.

**Comment by ewwink** [comment]
maybe we can implement this

```C#
using Newtonsoft.Json.Linq;

string key = "d.message"; // user input
JObject json = JObject.Parse("{'d': {'message': 'hello'}}");
string result = json.SelectToken(key).ToString();
Console.WriteLine(result); // hello
```

about RAM consumption that user risk :grin:

**Comment by openbullet** [comment]
It needs to be also integrated with the recursive capture (an array of objects containing the same key name). That's the thing that makes all this a bit harder ^_^

**Comment by ewwink** [comment]
I forgot about "recursive capture" :D but we can use `SelectTokens` and `[*]` to select multiple item.

```C#
// single
string key = "d.message";
JObject json = JObject.Parse("{'d': {'message': 'world'}}");
var result = json.SelectTokens(key, false); // [hello]
Console.Write(string.Join("\r\n", result)); 

Console.Write("\r\n\r\n");

// array
key = "d[*].message"; 
json = JObject.Parse("{'d': [{'message': 'hello'}, {'message': 'world'}]}");
result = json.SelectTokens(key, false); // [hello, world]
Console.Write(string.Join("\r\n", result));
```

**Comment by ewwink** [comment]
real code, no call to  `parseJSON`

```C#
case ParseType.JSON:
    JObject json = JObject.Parse(original);
    var jsonlist = json.SelectTokens(jsonField, false);
    foreach (var j in jsonlist)
            list.Add(j.ToString());

    break;
```

**Comment by openbullet** [comment]
Aite man ^_^ thanks, I'll give it a look as soon as I have some time to code. Life's keeping me very busy at the moment.

**Comment by ewwink** [comment]
you're welcome, no problem.

**Comment by openbullet** [comment]
Thanks again @ewwink https://github.com/openbullet/openbullet/commit/4e2554ad1890a4bf9e9abe4ac9e68f14be61ecca
