### ISSUE TITLE
[BUG] Selenium drivers

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#219]
**Describe the bug**
1.Chromium on navigate if is timeout then all next blocks don't work.
https://gyazo.com/a94b6a262c31a8b74e30513ee04d2cc2 even with unticked **Ban if timeout**. 
In this scenario, the page is loaded but apparently waiting for some JS/CSS finish up loading and throws timeout which is fine but then i cant execute next block which is DomToSource or GetCookies whatever is next... 
2. Firefox doesn't work with proxies, https://ruri.is-a-virg.in/tYgZeY screenshot you can see set proxy different.

**Version**
 - Last Commit 202

**Comment by Gareebo** [comment]
Same error as Mastercho mentioned, please fix it as I need something done fast Ruri/Roori :kappa: 
I will give you a gud loli pic

**Comment by openbullet** [comment]
If you want it done fast, make a pull request :D

**Comment by Morgann88** [comment]
I have the exactly the exactly same problem , if someone can fix it I will be grateful forever.
I tried a lot to solve this but it is impossible for me , ruri please help :(

**Comment by Ac3n34d-X** [comment]
Another Bug with Socks5
Selenium Doesn't Connect SOCKS5
Just Spits 
[ERR CONNECTION_FAILED]

**Comment by ewwink** [comment]
for firefox proxy, missing underscore `_`

https://github.com/openbullet/openbullet/blob/4e2554ad1890a4bf9e9abe4ac9e68f14be61ecca/RuriLib/Blocks/SBlockBrowserAction.cs#L358-L369

it should be
```
network.proxy.http_port
network.proxy.ssl_port
network.proxy.socks_version
```

To force get page source on Timeout, replace

https://github.com/openbullet/openbullet/blob/4e2554ad1890a4bf9e9abe4ac9e68f14be61ecca/RuriLib/Blocks/SBlockNavigate.cs#L88-L91

with

```C#
catch (OpenQA.Selenium.WebDriverTimeoutException)
{
    data.ResponseSource = data.Driver.PageSource; // add this line
    data.Log(new LogEntry("Timeout on Page Load", Colors.Tomato));
    ....
```

**Comment by openbullet** [comment]
Thank you. The missing underscores everywhere in the program are the consequence of a very sad mistake during the early stage of the alpha build (replace all _ with nothing, before adding source control... yeah I know ^_^).

I'll fix it immediately

**Comment by openbullet** [comment]
@ewwink I'll be glad to approve your pull requests by the way if you want, so you can appear as a contributor to this project! For this one, I'll do it myself following your directions.

**Comment by openbullet** [comment]
About the 2nd thing you said, that is not the problem, as once the execution exits the catch statement, the UpdateSeleniumData function is called (look a couple lines below the catch), which includes in its body that line that you added. So that will not work.

**Comment by ewwink** [comment]
@openbullet maybe next time I will create pull request but thanks. 

for the 2nd, from what I understand he can't go to next block for example `DomToSource` because `data.ResponseSource` is empty so we need to fill it and that what above code for, but maybe I misunderstand :D

this just alternative because code above not return `<body>` if timeout

```C#
var js = (OpenQA.Selenium.IJavaScriptExecutor)data.Driver;
string html = (string)js.ExecuteScript("return document.documentElement.outerHTML");
data.ResponseSource = html;
```

**Comment by openbullet** [comment]
I don't think we understood each other.
Basically what I'm saying is: this is the block of code you mentioned:
```try
{
	[...]
}
catch (OpenQA.Selenium.WebDriverTimeoutException)
{
	data.ResponseSource = data.Driver.PageSource;
	data.Log(new LogEntry("Timeout on Page Load", Colors.Tomato));

	if (BanOnTimeout)
	{
		data.Status = BotStatus.BAN;
	}
}

// The execution continues right here, even if there was an exception, because it was caught previously

data.Driver.Manage().Timeouts().PageLoad = TimeSpan.FromSeconds(data.GlobalSettings.Selenium.PageLoadTimeout);
UpdateSeleniumData(data); // This function gets called!
```

The function `UpdateSeleniumData` is defined like this:
```
public static void UpdateSeleniumData(BotData data)
{
	data.Address = data.Driver.Url;
	data.ResponseSource = data.Driver.PageSource; // This is the same line you added!
}
```

As you can see your line gets executed anyways, so you just added a repeated line. I don't see how this can solve the problem. If it works, it means it would have worked exactly the same even without it.

**Comment by openbullet** [comment]
Are you saying that the data.Driver.PageSource is empty while the DOM is not? Because in that case yeah, I will implement the automatic Dom to Source upon timeout and it will work ^_^ Just let me know because I didn't understand very well.

**Comment by mastercho** [comment]
i think @ewwink is right because website loads, just take some extra time for js/css which are trying to load from external links in <head> so when hits
` catch (OpenQA.Selenium.WebDriverTimeoutException) 
 { 
     data.Log(new LogEntry("Timeout on Page Load", Colors.Tomato)); 
`
Timeout all next blocks of browser action will return with timeout exception and won't trigger. Also PageSource is empty and DOM is also, here another try 

https://gyazo.com/8cd8ecc67975a6cb6436e9be30a3933d

**Comment by ewwink** [comment]
@openbullet  I miss to look `UpdateSeleniumData()` :grin: but sometimes `data.Driver.PageSource` is missing `<body>` if timeout and it return like `<html><head><link rel="stylesheet" href="file.css" /></head></html>` so we can't do `DomToSource`, but I think it better to use better proxy instead.

**Comment by Zurzar** [comment]
Guys, Which browser version are you using?

**Comment by mastercho** [comment]
> Guys, Which browser version are you using?

Latest because of webdriwer won't run with an older one

**Comment by mastercho** [comment]
Anyone comes up with idea here? lol Being annoying issue

**Comment by mastercho** [comment]
@ewwink  do you have discord or telegram so we can sort this out together?

**Comment by mastercho** [comment]
I was doing some debug and notice something is not ok, that in @ewwink screenshot says `Timeout on Page Load`, and in my stacker says  Remote Driver timeout (see the screenshots), the thing is on me is not entering in the catch of timeout and that's probably Ban on timeout was not working either. Will update you guys if found anything else. Also please test if is same for anyone of you?

**Comment by openbullet** [comment]
Maybe the issue refers to this problem? https://github.com/openbullet/openbullet/issues/497
I will close this issue as it's pretty old and probably fixed. Please reopen if not fixed and provide a way to consistently replicate it.
