### ISSUE TITLE
[REQUEST] Make portable(mono  linux/mac)

### ISSUE THREAD

**Issue by newsages** [openbullet/openbullet#220]
**Before you begin**
This is NOT Forlax's mod or any other mod. If you implemented features or fixes related to those versions DO NOT post them here as they will be closed and disregarded immediately.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by openbullet** [comment]
There are no plans to port this over to other platforms right now.
