### ISSUE TITLE
openbullet/blackbullet DB

### ISSUE THREAD

**Issue by xcyclonix** [openbullet/openbullet#221]
anyway to import all my hits from BB 2.5.1 to openbullet
or the best way to edit DB were hits are at ?
by the best program ever thanks for making it for us.
... x

**Comment by openbullet** [comment]
BB -> SQLite database -> [SQLite Browser](https://sqlitebrowser.org/dl/)
OB -> LiteDB database (NoSQL) -> [LiteDB Explorer](https://github.com/julianpaulozzi/LiteDbExplorer/releases)

You're welcome :]
