### ISSUE TITLE
OpenBullet slower than Sentry?

### ISSUE THREAD

**Issue by Crackingforum** [openbullet/openbullet#222]
Please see the screenshot, i am trying the same site on both programs, same number of bots and without any proxies. Sentry is cracking it much faster than OB,i have covered the site's name because of security reasons.

Any idea?

https://imgur.com/a/vxFoecE

**Comment by openbullet** [comment]
Sentry was made just for the purpose of credential stuffing, and was built with Delphi which compiles to very fast code.
OpenBullet can be used for a lot of things and has a level of abstraction that reduces complexity when making configs but adds to the processing time of a single check (it needs to parse the LS line from the script, build an entire Block from it, process that block, dispose of the block). You win some, you lose some.
