### ISSUE TITLE
[REQUEST] Need  Cap3 captcha solving

### ISSUE THREAD

**Issue by scooby420** [openbullet/openbullet#223]
**Before you begin**
This is NOT Forlax's mod or any other mod. If you implemented features or fixes related to those versions DO NOT post them here as they will be closed and disregarded immediately.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by openbullet** [comment]
What kind of request is this? You explained NOTHING about what you want implemented.

**Comment by mastercho** [comment]
i don't know for him but for me if is recapv3 invisible then 2captcha,dbc and rucap is fails to solve it

**Comment by openbullet** [comment]
Provide a test site

**Comment by mastercho** [comment]
match.com , usa version with usa proxy. Tricky site cuz is switching randomly between v2 and v3

**Comment by scooby420** [comment]
Anyone up to the challenge ?

**Comment by openbullet** [comment]
Discussion will continue here https://github.com/openbullet/openbullet/issues/300
