### ISSUE TITLE
Response code 500 on every request

### ISSUE THREAD

**Issue by ronnie32** [openbullet/openbullet#224]
I'm getting response code 500 on every request with fresh compiled OB, while I created exactly the same config on an old version (didn't compile it myself), and its working, is it me did I miss something in the compiling?

**Comment by beer15** [comment]
It's a server error, are you sure you didn't make too many requests?

**Comment by openbullet** [comment]
Did you get the correct Environment.ini file? Because I'm almost sure that's your problem ^_^ Get the environment.ini file from the old version and put it in the new one, it will work.

**Comment by ronnie32** [comment]
Tried to erase Environment.ini file with the ini file from the ForlaxPy last compiled OB (which works with the exact same config), and still error 500...I'm comparing both requests and they are exactly the same, any clue ?

**Comment by ronnie32** [comment]
> Did you get the correct Environment.ini file? Because I'm almost sure that's your problem ^_^ Get the environment.ini file from the old version and put it in the new one, it will work.

Tried to erase Environment.ini file with the ini file from the ForlaxPy last compiled OB (which works with the exact same config), and still error 500...I'm comparing both requests and they are exactly the same, any clue ?

**Comment by openbullet** [comment]
I have no clue mate, sorry :(
