### ISSUE TITLE
[REQUEST] Utility.List.removeDuplicated

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#226]
**Describe the solution you'd like**
 sometimes, i want to parse a couple of ids (variable number)
 and do a loop and a request using each id at a time in url or postdata ...
 so i need to clean the list of parsed ids from duplicated ones.

so if you add a remove duplicated function would help a lot 
i am tired of joining the list sending to js, split into a list again then clean, join again and send to loli

**Describe alternatives you've considered**
Add Utility > List > remove/clean Duplicated

**Comment by mastercho** [comment]
Good idea

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/838eea84ab641285e3effcb08198eaed75efc4cb

**Comment by ReDDOOne** [comment]
thank you again
