### ISSUE TITLE
[BUG] Conditional Statement

### ISSUE THREAD

**Issue by ghost** [openbullet/openbullet#227]
**Describe the bug**
Lately, working with conditional statement in OB, i have noticed that the app does not support 3+ layers of conditions.
The minified example is like this:
we have an IF contains an IF/WHILE contains an IF

**To Reproduce**
When the contition = True in the first IF
Everything is running will
<img width="1951" alt="Screen Shot 2019-05-21 at 1 53 32 PM" src="https://user-images.githubusercontent.com/23710158/58103216-1e1bd580-7bd2-11e9-9114-65e4e14c06b1.png">

When the contition = False in the first IF
we have an error
<img width="1962" alt="Screen Shot 2019-05-21 at 1 54 05 PM" src="https://user-images.githubusercontent.com/23710158/58103266-3986e080-7bd2-11e9-9964-41d745841f8d.png">

i was thinking maybe the while is causing the problem
so i have changed it, to IF
but still  same problem
<img width="1965" alt="Screen Shot 2019-05-21 at 1 55 48 PM" src="https://user-images.githubusercontent.com/23710158/58103410-70f58d00-7bd2-11e9-97c9-06a9a6f6321d.png">

**Version**
 - Version [e.g. 1.1.2]

**Comment by openbullet** [comment]
LoliScript does not support nested statements. It's a very simple single-instruction language (assembler-like).
If you read the LS documentation you will see that when IF is false it will jump to THE FIRST ELSE OR ENDIF statement, which might not be its own!
I guess I could implement a counter that checks if it finds any other IF statement inside it and skips over the first ELSE and ENDIF it finds and goes to the next one. This is a good suggestion.

Right now though, the only way to achieve what you want is through jumping to different parts of the code using the JUMP statement

**Comment by ReDDOOne** [comment]
when ever you will be improve this
can you add "AND" "OR" to **IF**, so we can use at least 2 conditions

thanks

**Comment by openbullet** [comment]
There are currently no plans to implement nested loops in loliscript.
Please refer to this thread https://forum.openbullet.dev/topic/87/nested-ifs-and-operators to understand how to AND or OR conditions.
