### ISSUE TITLE
[REQUEST] Hello, bro can you please release BlackBullet To OpenBullet Config Converter For Free

### ISSUE THREAD

**Issue by SpearRipper** [openbullet/openbullet#229]
Hello, bro we so grateful that you finally released BlackBullet for free to us and we really appreciate it. 

But can you please be more kind and release a config converter for free for us 

I mean for the people that have no money to buy your BlackBullet 2.5.2 which i am one of them even tho you closed sales for it.

I will be really more than grateful if you release this thank you in advance anyway.

**Comment by openbullet** [comment]
No I'm sorry.
