### ISSUE TITLE
Please revert last commit

### ISSUE THREAD

**Issue by meinname** [openbullet/openbullet#23]
I don't like the fix from https://github.com/openbullet/openbullet/commit/bc6382362c6857cca311161032e7e9f5ad7a6f9d

Before the slider was for the rough placement and clicking for finetuning.
Now it jumps by 10 and so at least for me it's now difficult to set a number of for example 13 bots with a trackpad via RDP.

**Comment by openbullet** [comment]
Done. See the comments under commit bc6382362c6857cca311161032e7e9f5ad7a6f9d for the reason behind this.
