### ISSUE TITLE
[BUG]Multipart Postdata not shown in debugger

### ISSUE THREAD

**Issue by meinname** [openbullet/openbullet#230]
**Describe the bug**
Multipart Postdata not shown in debugger

**To Reproduce**
Send Multipart Postdata and look at the debugger.

**Expected behavior**
See in debugger what is sent ;)
(i checked - it was really sent, just not shown in debugger)

**Screenshots**
![](https://media.discordapp.net/attachments/536312226445787137/581178431060967436/unknown.png)

**Version**
1.1.2 commit 206

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/9e4f7af84c06af55bdab4d136803c95f125fcfe7
