### ISSUE TITLE
[BUG] Small known bugs

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#231]
**Describe the bug**
There are small bugs which are not fixed yet, they are.

**To Reproduce**
1. Go in Log and try to copy some log... OB will crash https://gyazo.com/05b4733adbe192306cdda5384c8cdb8f
2. On delay function, we got Parse output https://gyazo.com/427d26e59d6465c92e94299dbb5d2593
3. In settings, Draw mouse won't work, and i think is better to move in other options https://gyazo.com/2f5d3cbc3d91714894f1eddf0a1c0be7
4. Please bring back insert in DB when hit or smh like before because if OB crash all gone and nothing saved

**Version**
 - Commit 206

**Comment by openbullet** [comment]
1. Your clipboard is probably hogged by another program, it works fine here
2. If I skip the variable declaration when the variable name is empty, it will be for every block. Are you okay with that?
3. Draw mouse works with the intended functions e.g. draw line human. Also no way I'm moving that to other options, as it's just a visual cue.
4. OB already saves hits in the DB as soon as they are obtained. It does not wait until you stop checking, please look at the code and you will see.
