### ISSUE TITLE
[REQUEST] A working (True/False) column in the configs manager

### ISSUE THREAD

**Issue by M3T4LL1C4** [openbullet/openbullet#232]
I have some configs (written by me or other people) that doesn't work. Because they are wrongly made, because the site changed,.. Anyway I that to fix them.

When you have a large list of configs, it's hard to remember which ones are not working.

It would helps if there was a way to toggle (working/not working) the status of a config and show that in the configs manager, next to the category, author,... columns.

**Comment by openbullet** [comment]
No please it's already bloated like this. You can just edit its name (add like [NOT_WORKING] at the start of the name) or maybe make a subfolder for not working configs and move it there so the Category will change. Sorry.
