### ISSUE TITLE
[REQUEST] Duplicate a config in the manager

### ISSUE THREAD

**Issue by M3T4LL1C4** [openbullet/openbullet#233]
Some sites are very similar, so the configs are. Or sometimes I want to write a better config that the one I have.

Instead of writing such configs from the scratch, I use an existing config as a template. To do that I duplicate it in my file manager, open the loli file with notepad, change the name string and click Rescan in the config manager.

I'd like to have a duplicate button in the config manager, where OB will ask the name of the new one.

**Comment by openbullet** [comment]
Can't you just click on the first config, switch to the loliscript view and copy the whole code from there, then click the "New" config button and paste the code there? ^_^

**Comment by M3T4LL1C4** [comment]
Well I also do that sometimes ^_^

It's just that a duplicate button would be even easier.

But I understand if you don't want to spend your time on that, it's was a suggestion, that's all :-)

**Comment by openbullet** [comment]
Alright made, glad you're not taking it too hashly ^_^ There's more pressing issues and whenever I happen to have some free time to code I try to focus on those.
