### ISSUE TITLE
[BUG] Send POST req with empty Content

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#234]
**Describe the bug**
i am trying to send a post request, with empty postdata
the app is able to send the request, but without **Content-Type**

<img width="1494" alt="Screen Shot 2019-05-25 at 1 57 38 PM" src="https://user-images.githubusercontent.com/23710158/58370390-854cc900-7ef5-11e9-99fb-23a3b000694c.png">

when i add postdata, then the CT is sent with  the headers
<img width="1490" alt="Screen Shot 2019-05-25 at 1 59 32 PM" src="https://user-images.githubusercontent.com/23710158/58370398-9564a880-7ef5-11e9-948a-883f13a16bea.png">

""the bug is in this peace of code"" i guess
<img width="1448" alt="Screen Shot 2019-05-25 at 2 09 07 PM" src="https://user-images.githubusercontent.com/23710158/58370485-b4b00580-7ef6-11e9-8cd8-1b937c1c55ff.png">

and for writing CT in LS, this part is making the bug
try to write each one separately 
<img width="497" alt="Screen Shot 2019-05-25 at 2 10 42 PM" src="https://user-images.githubusercontent.com/23710158/58370505-e7f29480-7ef6-11e9-94df-7f68ba53eb76.png">

**Version**
 - Version [e.g. 1.1.2]

**Comment by openbullet** [comment]
It was never meant to work because Extreme.NET does not allow for empty POST data. I will have to fix it inside the library before even fixing it in RuriLib.

**Comment by ReDDOOne** [comment]
ok thank you

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/be1bbc76c87abc6a377e19d166887df6437e2362
