### ISSUE TITLE
capture cookie data?

### ISSUE THREAD

**Issue by Ron-Swansonl** [openbullet/openbullet#237]
I'm trying to capture the data from a cookie so that I can use it in the POST Data..
I tried doing COOKIE(svSession) in the Var section while parsing through <SOURCE> and <COOKIES>. But both showed zero results.. I can assume it's cause it doesn't know what to look for, but if someone could help me out I'd really appreciate it.

![image](https://user-images.githubusercontent.com/49811113/58383183-72a4c380-7fcb-11e9-922e-1d782eb20866.png)

![image](https://user-images.githubusercontent.com/49811113/58383185-7d5f5880-7fcb-11e9-9806-5e8b865992dc.png)

**Comment by JuninoBoy** [comment]
![image](https://user-images.githubusercontent.com/51048618/58383387-64a87000-7fd6-11e9-80a2-745004d438dd.png)
Here = <COOKIES(svSession)>

**Comment by openbullet** [comment]
Please read the online documentation to understand how dictionary variables work.
https://openbullet.github.io/stacker.html
