### ISSUE TITLE
[BUG]OpenBullet Not Responding/Freezing After The Latest Update

### ISSUE THREAD

**Issue by Crackingforum** [openbullet/openbullet#238]
**Describe the bug**
I have just complied the latest version and tried it,everytime, i change or switch from one tab to another tab in OB, it is freezing and not responding.Please check the screenshot.

**To Reproduce**
1. Go to OB
2. Load any config,then change or make some modifications to it ,save it,try to jump from config section to to other sections,like proxy settings ecc ecc.

**Expected behavior**
The version i used till yesterday was working smooth, no ram consuming,no freezing.

**Screenshots**
https://imgur.com/a/I4XH5R3
https://imgur.com/a/OPTmIix

**Version**
 - Version 1.1.3

**Additional context**
I am using it on a dedicated windows server 2012 with 4 GB RAM and 2.40Ghz*2 processor

**Comment by meinname** [comment]
Sorry, couldn't reproduce.
Maybe check out the source again and recompile.

**Comment by openbullet** [comment]
I asked people and no one can reproduce this error :/

**Comment by Crackingforum** [comment]
Ok,i will re-compile it and update you.

Thankyou

**Comment by openbullet** [comment]
Don't just recompile, maybe clone the repo again from scratch. You might have changed something that conflicts with the proxy changes.

**Comment by Crackingforum** [comment]
Yeah,i meant to say that.Sorry.

**Comment by Crackingforum** [comment]
Cloned and compiled again,working fine.

Thankyou.
