### ISSUE TITLE
[BUG] Cyrilic websites

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#239]
**Describe the bug**
Having an issue with a couple of Cyrillic websites

**To Reproduce**
 Go Stacker and run request
```
#GETTING_TOKEN REQUEST GET "https://secretdiscounter.ru/" AutoRedirect=TRUE 
  CONTENT "" 
  CONTENTTYPE "application/x-www-form-urlencoded" 
  HEADER "Accept: */*" 
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" 
  HEADER "Pragma: no-cache" 
#TOKEN PARSE "<SOURCE>" LR "name=\"csrf-token\" content=\"" "\"" Recursive=FALSE -> VAR "TOKEN" "" "" 
#CHECKING REQUEST POST "https://secretdiscounter.ru/login?rc=0.3108367193982289" AutoRedirect=TRUE 
  CONTENT "_csrf-frontend=<TOKEN>&LoginForm%5Bemail%5D=<USER>&LoginForm%5Bpassword%5D=<PASS>" 
  CONTENTTYPE "application/x-www-form-urlencoded; charset=UTF-8" 
  HEADER "Accept: application/json, text/javascript, */*; q=0.01" 
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" 
  HEADER "Pragma: no-cache" 
  HEADER "referer: https://secretdiscounter.ru/" 
  HEADER "x-csrf-token: <TOKEN>" 
  HEADER "x-requested-with: XMLHttpRequest" 
```
And that will return `Object reference not set to an instance of an object`

https://gyazo.com/be793028e3c22a2ee11c0793e9603186

Met in couple more websites

**Expected behavior**
To pass as usual without thrown error

**Version**
 - Commit 211

**Comment by meinname** [comment]
Redirect Problem.
Disable the Auto Redirect (maybe also Resp. Source to make it faster)
And Request the Location Header manually. like
REQUEST GET "<HEADERS(Location)>"

**Comment by mastercho** [comment]
It is Redirect but must say it is redirect error instead Object reference not set to an instance of an object

**Comment by openbullet** [comment]
It's an Extreme.NET error, you should investigate the cause with debug symbols on there directly. I don't have time to look into this, sorry.
