### ISSUE TITLE
chromedriver file does not exist.

### ISSUE THREAD

**Issue by rlku** [openbullet/openbullet#24]
Opening browser...
OpenQA.Selenium.DriverServiceNotFoundException: The chromedriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html.
   at OpenQA.Selenium.DriverService.FindDriverServiceExecutable(String executableName, Uri downloadUrl)
   at OpenQA.Selenium.Chrome.ChromeDriverService.CreateDefaultService()
   at RuriLib.SBlockBrowserAction.OpenBrowser(BotData data)

Chromedriver is installed and works fine in BB but not in OB.

**Comment by openbullet** [comment]
Can you please tell me more information (e.g. where are you running it from, the permissions of the program, whether you compiled from source or if you're using some pre-compiled version) because I literally cannot reproduce this :(

**Comment by styles977** [comment]
@openbullet  I compiled the app this morning and getting the same error. Though chromedriver.exe  and gechodrier.exe is already on the same folder where "openbullet.exe" is located.
but still says "The chromedriver.exe file does not exist in the current directory or in a directory on the PATH environment variable"

**Comment by btri92** [comment]
Copy file chromedriver.exe move folder /bin

**Comment by openbullet** [comment]
Guys I'm sorry but I can't fix it if I can't reproduce it.

**Comment by openbullet** [comment]
Maybe someone with the same problem can debug it and make a pull request!

**Comment by styles977** [comment]
@openbullet problem is fixed when I move chromedriver.exe to folder "openbullet\bin" thanks @btri92 
so I think " Switch to Release " mode is problem while compiling not creating chromedriver in bin folder  :3

**Comment by openbullet** [comment]
Thank you @btri92 and @styles977 for your input! I fixed the post-compilation events so now it should move the files correctly. The commit is this one https://github.com/openbullet/openbullet/commit/b30bf9af1411aa9c4fe395d047e3b440fb22e878
