### ISSUE TITLE
[BUG] Hash Base64 Encode different result in ob than in other tools

### ISSUE THREAD

**Issue by vyrusthemofo** [openbullet/openbullet#240]
**To Reproduce**
1. Go to 'stacker'
2. Click on 'function block'
3. Create 2 Functions, 1 hashing a test string to sha1, second one base64 encoding the result of the first block

**Expected behavior**
I put in test and got https://i.imgur.com/lW0fRyR.png (encoding of the sring)
Expected: https://i.imgur.com/kWHeod3.png (encoding of the byte array)

**Version**
 - Version 1.1.2

**Additional context**
https://i.imgur.com/dbW7RQG.png
works in python

**Comment by openbullet** [comment]
If you expect oranges from an apple tree you have something wrong friend ^_^
That function is supposed to encode a STRING to base64.
What you are supposed to do in your case is use the UTILITY block like this
```
FUNCTION Hash SHA1 "test" -> VAR "TEST123" 
UTILITY Conversion HEX BASE64 "<TEST123>" -> VAR "TEST1234"
```
