### ISSUE TITLE
[REQUEST] Add C# Wrapper with Javascript Library support

### ISSUE THREAD

**Issue by poiuedws** [openbullet/openbullet#241]
The ability to run javascript code without the selenium browser, with the option to run it from a variable with loli script (a string that contains javascript code for example) and save the output to a new variable.

I think there are pre-existing libraries that do this, but im not sure.
from a quick google search i found
https://github.com/deltakosh/JsBridge this libary adds support for Microsoft's Chakra JavaScript engine, which could be a great fit for this project.
thank you for taking the time to read this.

**Comment by openbullet** [comment]
Jint is already implemented exactly as you said.
Go to LoliScript -> Documentation -> Flow Control -> BEGIN SCRIPT to learn how to use it.

**Comment by openbullet** [comment]
IronPython is also supported (python syntax for C# assemblies)
