### ISSUE TITLE
[BUG]Wordlist Count 

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#242]
**Describe the bug**
Once you insert wordlist in OB, if you edit it after like first time when i instert list is 70 but after i edit and add 20k lines on it in OB will still show 70 even after close and reopen and once get 70 runner will stop will not continue with rest of list

**Comment by openbullet** [comment]
You have to import it again.

**Comment by mastercho** [comment]
Everybody knows that's is a workaround, but not meant to be like that. Have to refresh index when the dialog opens up. Beside remove import on every 2 minutes takes to much time...

**Comment by openbullet** [comment]
It takes time to refresh a wordlist length. Imagine if OB did that for maybe 50 or 100 wordlists every time you press "Select Wordlist" or every time it boots up. Imagine waiting 30 seconds... Also why are you editing your wordlist anyways? I don't see the point. Make a new one instead.
