### ISSUE TITLE
[REQUEST] Add support for "Privacy Pass"

### ISSUE THREAD

**Issue by poiuedws** [openbullet/openbullet#243]
Add the ability to use tokens from 
https://github.com/privacypass/challenge-bypass-extension
as a recaptcha service.

**Comment by ewwink** [comment]
have you tried the extension? it is make recaptcha checked automatically?
From what I understand, privacypass is require website to install the challenge-bypass-server and this is not commonly used, so this is useless.

**Comment by openbullet** [comment]
I thought it's quite useless too but didn't want to be mean ^_^

**Comment by poiuedws** [comment]
it works for recaptcha with cloudflare (ANY recaptcha with cloudflare)
i thought it could be useful instead of paying for recaptcha service.
