### ISSUE TITLE
Maybe finally started release every new version ?

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#245]
without need release from visual studio ?

**Comment by openbullet** [comment]
What's the point of this issue? Why state the obvious?

**Comment by Teals53** [comment]
i cant find any other place for ask this u ?

**Comment by openbullet** [comment]
We added CI and auto deployment so every build gets upped here https://github.com/openbullet/openbullet/releases after each commit.

**Comment by Teals53** [comment]
Nice <3
