### ISSUE TITLE
[Help Wanted] Way to check SetCookies

### ISSUE THREAD

**Issue by ozunaltun** [openbullet/openbullet#246]
Hi,
When i try to set cookies from the get request to the selenium, i get no cookies. (no login)
Is there any way to if the cookies are set, because i am not sure about if the cookies are set correctly or there are something wrong with my method. My code is something like this; 
```
REQUEST GET "https://google.com" 
  
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko" 

BROWSERACTION Open 

BROWSERACTION SetCookies "google.com" 
```
Version [1.0.1]

**Comment by ewwink** [comment]
selenium limitation, it can only set cookies to the current page. You have to navigate to the page and get final domain which is `www.google.com` after redirecting, set cookies and reload the page.

```LUA
REQUEST GET "https://google.com" 
  
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko" 

BROWSERACTION Open 

NAVIGATE "https://google.com" 

BROWSERACTION SetCookies "www.google.com" 

NAVIGATE "https://www.google.com" 
```

but the problem now OB replace `www.google.com` to `google.com` so the cookies will not set, @openbullet maybe you should keep it unchanged?

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/4887d5a51b9c6742430999f94028f1eb352f4897

**Comment by ozunaltun** [comment]
@ewwink thanks, it worked!
