### ISSUE TITLE
[REQUEST] More Known things

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#249]
**Is your feature request related to a problem? Please describe.**
This is just reminder ticked not request.
1. Add Socks support to CF.
2. Add Use "HTTP Only" amongst other options https://gyazo.com/aa793678f15ca2de118bda9382de93a9 ( I might do PR if find time to do it)

**Comment by openbullet** [comment]
1. I know
2. SSL only is basically already HTTP only, I don't really check for SSL support, it's just very poorly written

**Comment by mastercho** [comment]
i did open ticked as a reminder not for being request and being closed because you know lol

**Comment by openbullet** [comment]
There's mein and demi reminding me everyday, I will do it eventually

**Comment by openbullet** [comment]
Also next time if you want your issues to be left open, do not make 1 big issue with a lot of stuff inside, make 1 for each problem with a good title so I can see what needs to be done at a glance when looking at the issues page.
