### ISSUE TITLE
CountOccurrences Function dont work

### ISSUE THREAD

**Issue by G4rf1eldz** [openbullet/openbullet#25]
Hello Ruri, is me. I'm having problem with CountOccurrences, it dont work for any tries
1. Put <SOURCE> In Input
https://i.imgur.com/QtMkIHV.png
2. Parse it to a list but not return sum of them
https://i.imgur.com/nA4xNPx.png
And there any change to turn off auto execute "\" regex in script?  
Like I have a Loliscript like this
PARSE SOURCE LR "Test\\\\\" "\\\\" -> VAR "HELLO"
This will break the config, same happen if put this in any order block type
Sorry for bothering, I'm noob at coding and still starting with Python, Thanks you Ruri.

**Comment by openbullet** [comment]
Please make sure to check the commit history before opening issues that are already fixed, thank you.
Fixed here: https://github.com/openbullet/openbullet/commit/043c4ad635746e014781d05fb93cf892f1f0eb3b
