### ISSUE TITLE
[REQUEST] Temporary WordList/WordList On-The-Fly

### ISSUE THREAD

**Issue by noammiz007** [openbullet/openbullet#250]
**Describe the solution you'd like**
I would like to see a feature of adding a "Temp WordList" on-the-fly. Which means i don't need to add a list to WordList manager. So i add it to a specific runner.
This can be used if the wordlist is very small and not worth to add it so it can be faster.

**Comment by ForlaxPy** [comment]
Will work on this.

**Comment by openbullet** [comment]
@ForlaxPy make a button in the wordlist selection window that will load it from file. Use the same white folder icon I use for importing files in the proxy manager and wordlist manager please. Also either add automatic wordlist type detection like I did for the drag and drop or make a small dropdown selector for that.

**Comment by ForlaxPy** [comment]
@noammiz007 feature added you can close this now.

**Comment by noammiz007** [comment]
ok thanks for adding this feature. :D
