### ISSUE TITLE
[BUG] Data Rules

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#252]
**Describe the bug**
I found in Data rules MustContain rule doesn't work, here an example
Set the following rule:

https://gyazo.com/4a82a93c82a8fa679607053bf1c7a714
and that's skips the whole wordlist https://i.imgur.com/n74HoJO.png
and wordlist looks like this https://i.imgur.com/nWQqodp.png

Thought maybe symbols are not right like `! ?` is not count for symbols so i take out this rule but was still same, then what i did was take out all rules and run the same wordlist and got hit https://i.imgur.com/kV0dRn7.png and when i got hit i realize that Data rules are broken...

Data Rule min or max length is working correctly but not and MustContain

**Comment by openbullet** [comment]
I just checked and `Hello12$` passes using your rules. Did you set up the Wordlist type and allowe Wordlist types correctly?

**Comment by mastercho** [comment]
Yes and works in Stacker but not in Runner

**Comment by ReDDOOne** [comment]
it is working in here, OBv1.1.3-232

**Example:**
WordList:
name1:Hello12$
name2:Hello12
name3:Hello$
name4:ello12$

Config:
1 httpbin.org request
every call is set as success

DataRules:
  "AllowedWordlist1": "UserPass",
  "AllowedWordlist2": "",
  "DataRules": [
    {
      "SliceName": "PASS",
      "RuleType": 0,
      "RuleString": "Uppercase",
      "Id": 1600623707
    },
    {
      "SliceName": "PASS",
      "RuleType": 0,
      "RuleString": "Digit",
      "Id": 1398638365
    },
    {
      "SliceName": "PASS",
      "RuleType": 0,
      "RuleString": "Symbol",
      "Id": 1561375762
    }
  ]

[WLTYPE]
Name=UserPass
Regex=^.*:.*$
Verify=True
Separator=:
Slices=USER,PASS

**Result:**
![Screen Shot 2019-06-02 at 3 52 34 AM](https://user-images.githubusercontent.com/23710158/58756539-ef630080-84e9-11e9-955c-75fb7be48ec1.png)

**what may cause this:**
check if the lines does not end with a space/TAB > in this case it does not for me

**Comment by mastercho** [comment]
That's weird, i ask 1 of my customers to check and he said is not working for him too :(  thats weird, so tried with another config UserPass type. And in UserPass works can you try MailPass @ReDDOOne

**Comment by ReDDOOne** [comment]
@mastercho still work
![Screen Shot 2019-06-02 at 4 30 48 AM](https://user-images.githubusercontent.com/23710158/58756821-3e5f6480-84ef-11e9-9395-7f7171ca9da7.png)

**Comment by mastercho** [comment]
Thanks, i will debug then in VS to see what's going wrong :)

**Comment by mastercho** [comment]
Found the issue, ! was not count as Symbol so if you remove MustContain Symbols will not skip combo which comtains !

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/c20f02be012c521ba8a2900e653c202f5411cc31
