### ISSUE TITLE
Solverecaptcha Doesn't work

### ISSUE THREAD

**Issue by thekillerrkil** [openbullet/openbullet#253]
I got proof this time that it doesnt work. Can someone give me the link to the fixed one. I deleted my solverecaptcha key so yall dont know it thats not the problem. I look in the solve recaptha console first off it says 8 fucking hours ago and its solving test wtf barely 1 task i wanted it to do.
Proof
https://ibb.co/zhRV9pt
https://ibb.co/S5x6g9N
https://ibb.co/2jC78Nj

**Comment by openbullet** [comment]
I just checked, it's the service's fault. They don't provide a good service at all. It's not OpenBullet's fault. You are invited to check using postman and calling their API with it.
