### ISSUE TITLE
[BUG] Weird Retries on RDP

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#254]
**Describe the bug**
I don't know for you all but in my and my customers RDP's there is a strange error which causes retry mostly on RECAPTCHA block.
The error refers to:

`ERROR in block RECAPTCHA | Exception: The underlying connection was closed: The connection was closed unexpectedly.`

For test being, we run in 3 RDP's and here screenshot from 1 of RDP's from running 12h

https://i.imgur.com/eOlRy7L.png

And this is just couple minutes run in a non-RDP machine on the same config with same settings + same proxies  

https://i.imgur.com/D96QOdK.png

when the environment is non-RDP never get

`ERROR in block RECAPTCHA | Exception: The underlying connection was closed: The connection was closed unexpectedly.`
that error. Short research in google i found is a bug in .NET and can be fix with some adjustments

**Comment by jurczakos** [comment]
ME TOO
reeeeeeeeeeeeeeeeeeeeeeeee

**Comment by openbullet** [comment]
> Says .NET is bugged
> Doesn't link to the source of this claim
Welp

**Comment by mastercho** [comment]
https://stackoverflow.com/questions/1459475/system-net-webexception-the-underlying-connection-was-closed-the-connection-wa

**Comment by openbullet** [comment]
I'm just being curious here, what's the captcha timeout you have put in the settings? Can you try to increase that? Because the error you're getting sounds like a normal timeout error when the captcha isn't solved before the timeout value you set.

**Comment by openbullet** [comment]
Oh and I'm quite sure the .NET framework is perfectly fine, not bugged.

**Comment by mastercho** [comment]
default 120s on both in personal PC and in test RDP's

**Comment by openbullet** [comment]
Increase it to 180 and let me know if it's better. Also RDP is a protocol, not a server. A VPS is a server ^_^

**Comment by jurczakos** [comment]
same, 120s on own laptop and 2 dedi servers. shit doesnt gib ban on invalid hits, ree

**Comment by mastercho** [comment]
> same, 120s on own laptop and 2 dedi servers. shit doesnt gib ban on invalid hits, ree

if you mean ur are using selenium that another issue here https://github.com/openbullet/openbullet/issues/219 and ok let me check in RDP

**Comment by mastercho** [comment]
For me still same even if i increase the timeout to 250. Let's see others if have that issue

**Comment by jurczakos** [comment]
i tried 250, tried literally everything, anti-captcha, imagetyperz, all kinds of proxies. STILL SAME ISSUE. pleaseeee help with this :(

**Comment by ewwink** [comment]
Try to turn off firewall in your RDP.
Does it happen in debugger? are using online captcha provider or software? 
make sure .net framework 4.6.1 is installed.

**Comment by mastercho** [comment]
Will try in 2 different pc's and 2 more rdp's

**Comment by Crackingforum** [comment]
I can also confirm this problem of lot of retries, i am using it on a VPS with netframework 4.6.1 and with firewall off for the recaptcha software and for OpenBullet.

**Comment by jurczakos** [comment]
same shit all along :/

**Comment by Crackingforum** [comment]
Any progress?

**Comment by openbullet** [comment]
Closing old issue
