### ISSUE TITLE
[REQUEST]Remove Banned/Bad proxies from the proxylist

### ISSUE THREAD

**Issue by atiufi** [openbullet/openbullet#255]
**Is your feature request related to a problem? Please describe.**
when you use all proxies in the runner then they all get refreshed again even if  some of them are bad or banned proxies

**Describe the solution you'd like**
if the proxies are saved in a dynamic array you can make a for loop that checks if the proxy has banned/bad status if yes then remove that from the list  if not keep it in the refresh list.
and you could trigger that for loop maybe by putting the loop in a if statement that triggers the for loop only when "total proxies"==0 or if its possible you remove them instantly when they get the bad/banned status

**Describe alternatives you've considered**
i heard that the proxies are saved on a databases or something from pure. i dont know how databases work but maybe you can sent a request to remove proxies that had the bad/banned status in the runner.

**Comment by openbullet** [comment]
The proxies are used until all of them are banned, so doing what you suggest would mean deleting all the proxies. You should rather set up a reload API instead.
