### ISSUE TITLE
[BUG] Cloudflare bypass not working

### ISSUE THREAD

**Issue by I3lakHat** [openbullet/openbullet#257]
**Describe the bug**
Cloudflare bypass option not working.
Getting error like:
"ERROR: The parameter '{0}' cannot be an empty string. Parameter name: cookie.Domain"

**Comment by openbullet** [comment]
Please provide a website where I can test this on

**Comment by Zigoleiro** [comment]
https://sso.teachable.com/secure/teachable_accounts/sign_in
Method POST, BypassCF not working

**Comment by mastercho** [comment]
> https://sso.teachable.com/secure/teachable_accounts/sign_in
> Method POST, BypassCF not working

Current CF bypass supports only GET

**Comment by beer15** [comment]
me i have "<--- Executing Block BYPASS CF --->
ERROR: CF Bypass Failed: Cloudflare [JavaScript]: invalid submit response
WARNING: The test input data did not respect the validity regex for the selected wordlist type!"

**Comment by I3lakHat** [comment]
Many sites not working..
https://vogov.com/authentication/

**Comment by openbullet** [comment]
Fixed on 1.1.4
