### ISSUE TITLE
lsass.exe Local Security Authority Process High procces [BUG]

### ISSUE THREAD

**Issue by beer15** [openbullet/openbullet#258]
**Describe the bug**

when I run an config the proccesus lsass.exe goes up a lot, but when I stop the runner the proccesus goes down, I have the bug on a lot of configs, but not all configs

**To Reproduce**

Download this config: [REMOVED]

**Expected behavior**

fixing

**Screenshots**
GIF: https://gyazo.com/de99d4491fa61d31348d7c2117059a45

**Version**
 - Version [e.g. 232]
- Windows server 2012

**Comment by openbullet** [comment]
This bug is not related to OpenBullet, it could happen with any other software with the same behaviour.
https://www.thewindowsclub.com/lsass-exe-terminated-error-and-high-cpu-usage
