### ISSUE TITLE
[REQUEST]  To check Feature

### ISSUE THREAD

**Issue by swallowko** [openbullet/openbullet#259]
If only the failure key is entered and the account is correct.
To check.
success.

https://imgur.com/a/qsZ4pmq
https://imgur.com/a/4R7Kg0z

**Comment by openbullet** [comment]
Untick "ban if no key found"

**Comment by swallowko** [comment]
I'm really sorry.
Thank you for making a good tool.

2019년 6월 7일 (금) 오후 6:15, openbullet <notifications@github.com>님이 작성:
