### ISSUE TITLE
Some Issue

### ISSUE THREAD

**Issue by styles977** [openbullet/openbullet#26]
I just reCompiled on VB 2019 .... and found this Issue
1. Variable Issue
http://prntscr.com/n7qn6o
Bot just Printing <USER> instead of giving actual one.

2. Selenium Issue
Opening browser...
OpenQA.Selenium.DriverServiceNotFoundException: The chromedriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html.
   at OpenQA.Selenium.DriverService.FindDriverServiceExecutable(String executableName, Uri downloadUrl)
   at OpenQA.Selenium.Chrome.ChromeDriverService.CreateDefaultService()
   at RuriLib.SBlockBrowserAction.OpenBrowser(BotData data)

**Comment by G4rf1eldz** [comment]
1. Update Enviroment file, link areally posted on forum
2. Replace default chromedriver with newer version of chrome driver.

**Comment by styles977** [comment]
@G4rf1eldz 
 Update Enviroment file, link areally posted on forum ... but where, please provide me link?

**Comment by mathew12hi2** [comment]
@styles977  https://openbullet.github.io/usage.html#environment

**Comment by styles977** [comment]
Thankyou I see new change .. understood

**Comment by openbullet** [comment]
Closed since it was an Environment issue.
