### ISSUE TITLE
[REQUEST] UTILITY block to create a folder

### ISSUE THREAD

**Issue by Zigoleiro** [openbullet/openbullet#260]
**It would be great if OpenBullet could generate folders in the block utility.
The writing to text files function only works if the folder already exists, it would be good if this were done automatically.**

**Comment by ForlaxPy** [comment]
Not sure if this is really required, however here is a piece of code would do the job
`                       //  RuriLib.Blocks.BlockUtility
                      //    public override void Process(BotData data)
                     // Line 542
                            case FileAction.Write:
                                {
                                    if (!Directory.Exists(Path.GetDirectoryName(file)))
                                        Directory.CreateDirectory(Path.GetDirectoryName(file));

                                    File.WriteAllText(file, input);
                                    break;
                                }

                            case FileAction.WriteLines:
                                {
                                    if (!Directory.Exists(Path.GetDirectoryName(file)))
                                        Directory.CreateDirectory(Path.GetDirectoryName(file));

                                    File.WriteAllLines(file, inputs);
                                    break;
                                }

                            case FileAction.Append:
                                {
                                    if (!Directory.Exists(Path.GetDirectoryName(file)))
                                        Directory.CreateDirectory(Path.GetDirectoryName(file));

                                    File.AppendAllText(file, input);
                                    break;
                                }

                            case FileAction.AppendLines:
                                {
                                    if (!Directory.Exists(Path.GetDirectoryName(file)))
                                        Directory.CreateDirectory(Path.GetDirectoryName(file));

                                    File.AppendAllLines(file, inputs);
                                    break;
                                }
`

**Comment by openbullet** [comment]
I was going to 
- add a new Utility Group called Folder and related methods
- extend the File one with Copy, Move, Delete.
Although this could be used to mess with a user's important files so it should be taken very lightly.
We should limit the scope of these actions to the OpenBullet folder to avoid being able to make configs that:
- steal data from a user (e.g. chrome passwords)
- delete important windows files in case OpenBullet runs as administrator

**Comment by openbullet** [comment]
Anyways I'll take care of this request, don't worry. I'm just having a hard time coding now due to all the exams I have to take, so it's going to take a while to find some free time to sit down and clear some issues.

**Comment by ForlaxPy** [comment]
I could work on these features you stated @openbullet ofc if you're fine with that, tomorrow or even tonight I will get them ready.

**Comment by Zigoleiro** [comment]
Thanks,
Don't worry, I appreciate the attention.
We focus on studies, and good evidence.
