### ISSUE TITLE
[BUG] LineBreak - disable temporary

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#261]
**Describe the bug**
after the last updates where you did add support for '\n' line break in the app
now, i am having problem sending a STANDARD post content with \n on it
without the app breaking that line

**Expected behavior**
it is good that the app support the line break, this feature is necessary
but it should also come up with a way to disable this feature when we want

i have a json post like this
{"ob":"Ruri\nRed\nOne"}

**Version**
 - Version [e.g. 1.1.3]

**Comment by openbullet** [comment]
This was present since 1.0.0
I only added \n for files recently. Anyways okay I will add it.

**Comment by openbullet** [comment]
You can now type `\\n` to get `\n` instead of a new line. https://github.com/openbullet/openbullet/commit/62801c80188b6c65efc062fae3228b2b6e656e79
