### ISSUE TITLE
Scrape proxies

### ISSUE THREAD

**Issue by r00tee** [openbullet/openbullet#262]
Hi
Some times an error message appears when scrape proxies and after this all work stops
When you close the message, everyone starts working

When you make the work in rdp
after a day I find it all word stopped
Because of error message

I hope to fix this
Thanks for the great work Which you offer.

**Comment by openbullet** [comment]
I didn't understand, please tell me the exact error message you get.

**Comment by r00tee** [comment]
Sorry I forgot to Add the picture

![1](https://user-images.githubusercontent.com/32619657/59145712-6c154380-89f0-11e9-9322-f0fe17b097d1.png)

**Comment by beer15** [comment]
Proxyscrap ?I had the same mistake, but it's normal, the api was down, normally it's fixed

**Comment by twister77** [comment]
@openbullet 

I'm still experiencing this issue. Could you take a look at it again?

**Comment by openbullet** [comment]
Hey guys, this is a known issue and will be addressed when I come back in October. For the time being, do not use that feature.

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/2dd41fa1c7622385889f576beb0905dd27412b6a
