### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by kingfly55** [openbullet/openbullet#263]
Could you guys add a browser action wait block? Kinda like element action waitforelement but more thorough so you can specify specifically what to wait for. For example I want to wait until my elements text attribute isn't empty before continuing the config execution.

Selenium has a built in function for this, I was going to try and edit the source myself but I don't know c# ;(

If you guys decide to add this, my suggestion is to have an option "Find Element By: (Id, class, etc)", an option for timeout, an option for what part of the element you are waiting for / what attribute (in my case I'm waiting for innerHTML to be non-empty), and an option for what you are waiting for similar to the available options for keycheck (contains, less than, greater than, etc), either that or regex. Also maybe have it automatically wait for the element to exist first, before waiting for more specific things

So like this:
Find Element By: dropdown box (Id, class, etc)
Wait for: dropdown box (attribute, innerHTML / text)
To match: regex / keycheck options (contains, less than, greater than, etc)

**Comment by openbullet** [comment]
There's no "you guys", there's just me :3

**Comment by mastercho** [comment]
> wait until my elements text attribute isn't empty

Can be done with waitforelement and correct Xpath

**Comment by openbullet** [comment]
As mastercho said, this can be done with xpath or selector, for example the selector can be `[myattribute=value]`. If the element exists but its `myattribute` attribute has a value different than `value`, it will not match the selector and OB will keep waiting for it.
