### ISSUE TITLE
[BUG]Function Lenght broken

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#264]
**Describe the bug**
Don't know what cause it but in my case SOURCE is not empty but Lenght says it is empty then stucks and wont continue to next step.

https://i.imgur.com/kF1EnCN.gif

In Runner ups CPU 100% so can't make gif unfortunately and yeah it happens randomly on different configs but only in Selenium. Might be refer again to a bug where won't get DOM if timeout but here we don't have a timeout error 

**Version**
 - Commit 236

**Comment by mastercho** [comment]
Nevermind issue is if you do 2 times Domtosource to the same source then happens something like infinity loop in something which i have to debug and find

**Comment by openbullet** [comment]
I don't understand what you mean, so I guess the bug was another one? Reopen if not fixed.
