### ISSUE TITLE
[BUG]Encode Content problem with ==

### ISSUE THREAD

**Issue by shdf2** [openbullet/openbullet#265]
**Describe the bug**
Looks like the = (equal) char is not urlencoded

**To Reproduce**
![image](https://user-images.githubusercontent.com/37487684/59146598-96ff9780-89f0-11e9-831d-818fb51c21ab.png)

**Expected behavior**
== must be encoded to %3D%3D

**Screenshots**
In google Chrome :
![image](https://user-images.githubusercontent.com/37487684/59146642-0d9c9500-89f1-11e9-88d5-c4fab945353b.png)

**Version**
latest 1.1.3

**Comment by openbullet** [comment]
It's not a bug. It's not encoded because otherwise it would encode stuff like `param1=10&param2=20` completely breaking the data coming from forms.
In case your string has other `=` characters that you want to encode you NEED to use the Function -> URLEncode block.
