### ISSUE TITLE
CF Bypass error [BUG]

### ISSUE THREAD

**Issue by beer15** [openbullet/openbullet#267]
**Describe the bug**
I have a mistake with the CF Bypass block "ERROR: CF Bypass Failed: Cloudflare [JavaScript]: invalid submit response"
On my VPS Windows server 2012 

But on my real computer the block works without any problem "[Success] Protection bypassed: JavaScript
Got Cloudflare clearance!"

**Expected behavior**

The problem is my VPS or other ?

 - Version [e.g. 1.0.1]
1.1.3

**Comment by mastercho** [comment]
There is a weird issue on RDPs where you will get tons of retries but will be ok in your pc, its discussed here https://github.com/openbullet/openbullet/issues/254

**Comment by beer15** [comment]
> There is a weird issue on RDPs where you will get tons of retries but will be ok in your pc, its discussed here #254

True, my friend have the same problem, work in pc but not in rdp

**Comment by mastercho** [comment]
2 weeks ago CF update their JS again so might be plugin outdated now

**Comment by openbullet** [comment]
Fixed on 1.1.4
