### ISSUE TITLE
[BUG] Proxy reload status code 504

### ISSUE THREAD

**Issue by twister77** [openbullet/openbullet#269]
Sometimes i get **_Could not contact the reload API - The error on the server side. Status code: 504_** error message when the proxy reload is set to fetch proxies from remote sources and OB just stops.

I believe this is due to too many requests to some of the reload urls. Either the proxies are getting banned really fast and reload happens too often or something else.

I know you could just disable those sources, but it would be nice if the error could just be ignored and OB continued with the work instead of waiting for you to click OK to the error message popup.

https://i.imgur.com/Llzavky.png

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/issues/262
