### ISSUE TITLE
Proxy reload Issue

### ISSUE THREAD

**Issue by styles977** [openbullet/openbullet#27]
When All proxies are banned it could not reLoad it http://prntscr.com/n7rn1f
I have this option selected also 
http://prntscr.com/n7rofx

but still got  http://prntscr.com/n7rn1f  the same issue

**Comment by styles977** [comment]
I notice this problem only arise when "Max uses per proxy" is selected http://prntscr.com/n7t0qt ...
which never have arised on BlackBullet ver.....

**Comment by openbullet** [comment]
Thank you I will look into it

**Comment by openbullet** [comment]
Fixed here https://github.com/openbullet/openbullet/commit/6ae7c461820739a241c8febd7279130842c16962
