### ISSUE TITLE
[REQUEST]Add selector to the keycheck tab

### ISSUE THREAD

**Issue by ruz0ne** [openbullet/openbullet#271]
Hey can you please add to the keycheck tab  selector and or xpath ?

**Comment by openbullet** [comment]
No, use 2 blocks.

**Comment by ruz0ne** [comment]
ohh its already possible to "key check" an selector ? what do you mean with 2 blocks can you please give me a example

for example: i want that if the selector ".avatar" is found  the combo goes to "BAD"

thank you

**Comment by openbullet** [comment]
I mean use 1 element action block and use the EXISTS action which will output True / False and then inside the keycheck make a success key like "<OUTCOME>" EqualTo "True"
