### ISSUE TITLE
[REQUEST] Ability to drag proxies.

### ISSUE THREAD

**Issue by noammiz007** [openbullet/openbullet#273]
**Describe the solution you'd like**
I would like to see the ability to drag and drop proxies into the proxies manager just like adding a wordlist.

i know it sounds unstable (like, how will it know the proxy-type??)

so i thought if it could know the proxy type if it is in the file name.

for example:

blablablaSOcKs4ffewfew.txt = socks4 cuz its in the name
etc

**Comment by openbullet** [comment]
If I do this, I'll only do it for the default proxy type (HTTP)

**Comment by noammiz007** [comment]
> 
> 
> If I do this, I'll only do it for the default proxy type (HTTP)

ok but if the proxy type is in the file name can you make it set it to the type which in name?

**Comment by ForlaxPy** [comment]
> 
> 
> > If I do this, I'll only do it for the default proxy type (HTTP)
> 
> ok but if the proxy type is in the file name can you make it set it to the type which in name?

yep could be possible. if file name.contains socks4 or socks5 or http then do the process of adding the proxies to the manager if not then just don't add em by saying failed to parse proxy type from the file name.

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/pull/283
