### ISSUE TITLE
[REQUEST] API periodic rescan

### ISSUE THREAD

**Issue by Zigoleiro** [openbullet/openbullet#276]
API that pulls settings from an external server has a fault.
If the client runs on a VPS and doesn't close the program or rescan, it uses the settings for life.
Could you implement a periodic rescan?
Or when it clicks to start the checker or stop it, OpenBullet automatically checks the configs API.

**Comment by shdf2** [comment]
hi, i already asked to fix this...unfortunately openbullet doesn't want to do it... There is a hope with the **Paradox fork**, but since today they didn't add the feature, still waiting...

**Comment by openbullet** [comment]
@Zigoleiro feel free to post a thread here and I'll tell you how to edit the source code to implement what you want ^_^ https://forum.openbullet.dev/category/21/mods

**Comment by openbullet** [comment]
Also mind that the API is not supposed to be secure, a user can make 1 request to download all .loli configs, so do not use this to protect your intellectual property! A secure version of the API was proposed here https://forum.openbullet.dev/topic/12/poll-openbullet-secure-api but it had mixed reactions

**Comment by Zigoleiro** [comment]
> oi, eu já pedi para consertar isso no fórum oficial ... infelizmente o openbullet não quer fazer isso ... Há uma esperança com o **fork** do **Paradox** , mas desde hoje eles não adicionaram o recurso, ainda estão esperando. ..

Anything new?
