### ISSUE TITLE
[REQUEST] Add Update/Replace HTTP,Socks4 Proxies from URL with the given time mins or hours

### ISSUE THREAD

**Issue by SpearRipper** [openbullet/openbullet#277]
I don't like to use modded OpenBullet, as i don't trust any but yours so.

i do request if possible to added and support proxyscrape.com

like put URLs from the site and OpenBullet grab or fresh the proxy in the table after the given time

in mins or hours for example

https://proxyscrape.com/free-proxy-list/http goes to HTTP and replace the existing proxy there
https://proxyscrape.com/free-proxy-list/socks4 goes to socks4 and replace the existing proxy there

this is gonna be so great and make the testing/checking process at fine level since proxies getting refreshed after some times so.

**Comment by openbullet** [comment]
You can already do this. Go to Settings -> RuriLib -> Proxies and add the proxy sources! (You need to be on the latest build). Just type the URLs from proxyscrape in there and they will automatically be pulled when you start your config and refreshed from the API when they are all banned ^_^

**Comment by SpearRipper** [comment]
> You can already do this. Go to Settings -> RuriLib -> Proxies and add the proxy sources! (You need to be on the latest build). Just type the URLs from proxyscrape in there and they will automatically be pulled when you start your config and refreshed from the API when they are all banned ^_^

oh i see that now thank you a lot Ruri <3
