### ISSUE TITLE
[REQUEST] WordList Auto-Grabber From Selected Directory

### ISSUE THREAD

**Issue by noammiz007** [openbullet/openbullet#278]
**Describe the solution you'd like**
An option to select a folder that will automatically grab wordlists from there would be nice,
Instead of adding it by yourself every time you add a txt file.

**Comment by ForlaxPy** [comment]
You mean such as the one we got for configs right. I think I can make something using the same logic, basically making it auto grab them when the checker starts and also uh adding a rescan button as the config in case if someone added items to the folder while OB is running.

**Comment by noammiz007** [comment]
> 
> 
> You mean such as the one we got for configs right. I think I can make something using the same logic, basically making it auto grab them when the checker starts and also uh adding a rescan button as the config in case if someone added items to the folder while OB is running.

yes, something like the configs manager.

**Comment by openbullet** [comment]
@ForlaxPy Configs take a very small disk space, while wordlists can be huge, it's better to keep them in separate folders and just store their location in the database. Sorry but I won't do this.

**Comment by openbullet** [comment]
Also, in case you were thinking to keep both the DB selection and the folder selection, I don't think it's a good idea to have 2 separate locations for things it will only create more confusion in the code in the long run ^_^

**Comment by openbullet** [comment]
Plus, if people want to import wordlists all at once, they can simply drag and drop them, it takes 2 seconds and it automatically detects the wordlist type, I don't see what's the problem here really!
