### ISSUE TITLE
[BUG] Infinity loop error on Condition

### ISSUE THREAD

**Issue by mastercho** [openbullet/openbullet#279]
**Describe the bug**
Some configs converted from the old project i was getting infinity loops which were causing OB to freeze and was no error in the stacker. Enabled logs and saw it there. Error is the following:

`Processing of line IF "<SOURCE> Contain [...] failed, exception: Parsing Exception on line 111: Invalid 'CONDITION'
`
It's not a big bug, just have to throw an error when happens and show it also in stacker

**Comment by openbullet** [comment]
At the first glance it seems that `IF "<SOURCE>" Contains` was missing a `"`.

**Comment by mastercho** [comment]
Actually issue was Invalid 'CONDITION' which leads to Infinity loop in converted configs, need to implement function if Invalid 'CONDITION' then stop debugger instead going into loop

**Comment by openbullet** [comment]
But the log clearly shows that there is no " after `<SOURCE>`. Anyways yeah I will implement better script parsing to avoid loops, there are a few bugs of this kind, I will address them sooner or later.
