### ISSUE TITLE
Compiling Solution

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#28]
while i was compiling the openbullet solution
i got this error : 

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Warning |   | Found conflicts between different versions of "System.Net.Http" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. | OpenBullet |   |   |

**Comment by kernelzeroday** [comment]
Pull my tree instead. Devs refuse to fix

**Comment by kernelzeroday** [comment]
Or just use my compiled bins

**Comment by Choempie** [comment]
Its just a warning fuck it :kappa:

**Comment by openbullet** [comment]
It's just a warning, leave it.
