### ISSUE TITLE
[BUG] content-type: application/json issue with empty POST

### ISSUE THREAD

**Issue by shdf2** [openbullet/openbullet#289]
**Describe the bug**
When selecting **content-type: application/json** OB is sending **Content-Type: application/x-www-form-urlencoded** when the POST DATA is empty.
in some configurations using Oauth2 it is sometimes necessary to send an empty POST with **content-type: application/json**

if i keep it empty i receive this error mesage in my config:
> {"code":400,"reason":"Bad Request","message":"The request could not be processed because it specified the content-type 'application/x-www-form-urlencoded' when only the content-type 'application/json' and 'multipart/form-data' are supported"}

if i add a space or any character in the POST:
> {"code":404,"reason":"Not Found","message":"Resource '' not found"}

so in this situation it is mandatory to send an empty POST with **content-type: application/json**

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/a1247ea74a62b2acff520529ceb1e71b0c8792e4
If it doesn't work, reopen

**Comment by shdf2** [comment]
Sorry i don't know how to reopen ?

Actually it sends the  **Content-Type: application/json** but for some reason i keep receiving that error message from the server:
{"code":404,"reason":"Not Found","message":"Resource '' not found"}

in the logs i can see this :
`Post Data: `
i'm wondering if it has to be sent, or if it is sending a space ??

**Comment by shdf2** [comment]
Here is the Raw data from HTTPdebugger pro that i'm trying to reproduce in my config : 
`POST /iam/json/sessions?_action=getMaxIdle&tokenId=AQIC5wM2LY4SfcyHCWo2PgC-dx26ZraheW1YiKfk160fzqQ.*AAJTSQACMDIAAlNLABM0NjI4MTUyNDk2NjI4ODE0MzgzAAJTMQACMDQ.* HTTP/1.1
Host: moncompte.carrefour.fr
Connection: keep-alive
Accept-API-Version: protocol=1.0,resource=1.1
Origin: https://moncompte.carrefour.fr
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Content-Type: application/json
Accept: application/json, text/javascript, */*; q=0.01
Cache-Control: no-cache
X-Requested-With: XMLHttpRequest
Referer: https://moncompte.carrefour.fr/iam/XUI/
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,mt;q=0.6
Cookie: JSESSIONID=26F372833A03CAB986878439FB711680; visid_incap_441619=zlpCjnTDQfKDQQbUKWgsAGg3B10AAAAAQUIPAAAAAACqfMK1zrS78huAn6B+50zJ; nlbi_441619=hKN2ddVmuzti/dyxNgXC3QAAAADyZh5Vcwx43NOt7QMkoNok; incap_ses_188_441619=T8zrF9Ijd2Sj87cKwOqbAmg3B10AAAAArf2hb3iEQpuzxlo1HxsUUA==; TCPID=1196184761850524926; FRONTONE_USER=1563346026; _ga=GA1.2.786249721.1560754027; _gid=GA1.2.456306359.1560754027; cookieIDCrfOne=V1201961784760.33444186629122563; TCSESSION=20196184786024360849; _cs_c=0; X-Mapping-bjehncgj=EA5B9EFC763D8803F6AC99F24C3607CE; visid_incap_1267558=wxDd1er+S1SOtJfqZqAP4G83B10AAAAAQUIPAAAAAAAlMGU72/eirhQzKYi836JL; incap_ses_188_1267558=4b9QZnkTwBh/97cKwOqbAm83B10AAAAAAfca1au0oP7Au1MgCfZ3Zg==; i18next=fr-FR; amlbcookie=04; TC_OPTOUT=0@@@@@@ALL; login=undefined; FRONTAL_STORE=179; visid_incap_1722501=qF27wte3QmCR26fh9mfZfno3B10AAAAAQUIPAAAAAABpvlvR0kqG2DvwyLhzbei4; already_visitedOne=1; _gcl_au=1.1.858132468.1560754043; sto__session=1560754044798; cto_lwid=fbf1810d-8f18-46f0-8262-ed3ff2033265; OAX=wftax10HN4cAASCK; TCAUDIENCE=; sto__vuid=d735951b811a442e9c152cce1fb18779; _fbp=fb.1.1560754054540.898963303; incap_ses_188_1722501=P7TpW+jgpwDdTrgKwOqbAiY4B10AAAAAx2h6bE8twv23j3ApFUGOvg==; ADRUM=s=1560754226231&r=https%3A%2F%2Fwww.carrefour.fr%2F%3F0; sto__count=3; ABTasty=uid%3D19061708470957869%26fst%3D1560754029486%26pst%3Dnull%26cst%3D1560754029486%26ns%3D1%26pvt%3D5%26pvis%3D5%26th%3D368744.-1.0.0.0.0.1560754048077.1560754048077.1_395327.507423.4.4.1.1.1560754029522.1560754389056.1_424199.0.5.5.1.1.1560754029529.1560754389063.1_424838.542016.4.4.1.1.1560754029534.1560754389068.1_430468.548327.1.1.1.0.1560754029508.1560754029508.1_430948.0.1.1.1.0.1560754029517.1560754029517.1_436335.554973.3.3.1.1.1560754042765.1560754389074.1; _gat_gtag_UA_3928615_46=1; _cs_cvars=%7B%2220%22%3A%5B%22ABTasty%22%2C%22%5B395327%3D507423%5D%5B424199%3D0%5D%5B424838%3D542016%5D%5B436335%3D554973%5D%22%5D%7D; ABTastySession=sen%3D31__referrer%3D__landingPage%3Dhttps%3A//www.carrefour.fr/__referrerSent%3Dtrue; datadome=1rqhRrAi0UYieGOKp~1aJGNCWGqIe15BXWkEbumk7rk; tc_cj_v2=%5Ecl_%5Dny%5B%5D%5D_mmZZZZZZKOPJQONMSNRNOZZZ%5D; pageCounterCrfOne=7; _cs_id=7f07cf0c-0b01-a06f-b620-c2ba3a860d18.1560754029.1.1560754395.1560754029.1.1594918029800; _cs_s=7.0; session-jwt=eyAidHlwIjogIkpXVCIsICJlbmMiOiAiQTEyOENCQ19IUzI1NiIsICJhbGciOiAiUlNBRVNfUEtDUzFfVjFfNSIgfQ.PKmaZ0E52pcchnOnykLXwIRqfReKjetjkOizSqVj99DZzHetItssOLJhzwHIHOZ1HekfPmR5cTVBx0-u-O8luqFvFHsMswFaPCE-gUEaPz0LvT_fLG_h3QfiUpPnC12xR3ywPG6-5zueAwT0wPeuZAKbX0fp6wqPIQZQH5tVGEPB68TmcAQMu1sdw5cfhQlrdm_V0hPqKFFHprwcMTWgSnuMH3F2Y8obG6gsIzhBaaPDzsF_G4Y9euXRsE2v7gL-WCTKbUt68H8DiT3AoR0sQwhSTkCoywiRXtGRJ0g-aI5i9tMhsSoJ57qLJ685VSvQeOV7dI1kkdV4lWTms45b5g.Djtf2YHJLQMVrU2Qyw8hBA.Lqj55HYUD8IKKnDyvIDRQg7cqieqlo7b0b1sxt-jwbp6fPhFyt_6IaM5iYiv8Rupe0-ad3DCu3IBjZRhEJVz_3V1umQfihnUoInvA7i6QAuCjpvEAPgkGLECrb785FCGSojy7ACShodw7V7D1Q6s7QzBPi-8V2iOY0pU4h8CVnT9NA0vWoOg-s0MXMdLnBPvPTk8cA7UWEqczFI-29C-950XsstmB-1hzBFrATfIzogQrSZ3cMptRRpnTzAj2w_NQKQw1Z5N8WDq4H8Eg8edp_e13SIg-7upBOS33OtdPx0m-GpJQzilpcl0DjJAzIotG8HyZtrs5gueB3tbxuIjnu3eu3weZUT_RFjRCeZVQaNATgI_hbd7kPxJB4hA0xiTWTI4IlsKSPZXmSgCfMe5OXbKGkf7OQZpkEY1vMQFz8Q6jWzJo8_Cfme3lUfMPiOXiXBafkyD74FD2RPkqIPRBJGHjWXCqUI1OcRFCEKwtuOZ-nCL-DR2UnccBHuJ0ebR7d9nrhph9GGZpzd9Icc0xK4Gww-BJb1m-4WhJTrAXTm1sF6rwMR6Gb8Uuj6q0qE8K3g1zJU-lr-OazKYtEwV0TIN6Jnx1_weDWbTWIGZeR5gsQNqL1IzeAJq0oEuH3EMgtucMQGKxlsuOGmsdPCvtYz0_xp51k1HJFc2MyzRGPsiCnDlaAjPBNort-wQEUiefOk88sJAoRySz1W6hs4loAihI7-UxX8Cx8I0zkO-CQbmKHSNJmAK9e7Ger4Rh49AFeE2bZ5F9tvwtSanWA_yJQ7wmg7C4ujM0HJHt8KhphoCVBiJjzRZENlqsx6Zbue4.VkKBOnIxl55nMToxj2SsGQ; c4iamsecuretk=AQIC5wM2LY4SfcyHCWo2PgC-dx26ZraheW1YiKfk160fzqQ.*AAJTSQACMDIAAlNLABM0NjI4MTUyNDk2NjI4ODE0MzgzAAJTMQACMDQ.*
Accept-Encoding: gzip, deflate
Content-Length: 0

`

**Comment by viper645** [comment]
still doesn't work after reopen any other solutions?
