### ISSUE TITLE
IronPython integer variable assign problem

### ISSUE THREAD

**Issue by styles977** [openbullet/openbullet#29]
When I write this script
http://prntscr.com/n7tyxj
It doen't assin the variable i.e number to openbullet var.

When I Set unknown random var then it works  >_< :/
http://prntscr.com/n7tvco

but it works perfectly on Javascript i.e assign javascript var to OpenBuller var ....

also this error only happens when variable is integer on python ...

**Comment by styles977** [comment]
it works perfectly with string http://prntscr.com/n7u17b

**Comment by openbullet** [comment]
Thanks, I'll see what I can do to automatically convert non-string outputs

**Comment by openbullet** [comment]
Fixed buddy https://github.com/openbullet/openbullet/commit/6508fb63d7a088c2db80ff4193937a127c6533d9
