### ISSUE TITLE
[BUG] Custom AES KEY is never getting used

### ISSUE THREAD

**Issue by ForlaxPy** [openbullet/openbullet#290]
**Describe the bug**
Well I was working on implementing AES custom IV keys on OB but I was shocked that the encryption is always the same even after changing keys, I tought I fucked up something so I came back to the original current build and I retested to find out that the aesKey that we actually provided never gets used, it's always null as you can see in the screenshots.
I tried debugging it but I kinda got lost, but my vision is that the actual aeskey isn't getting saved to the config settings somehow or fails to get fetched, so it always as a null string.

**To Reproduce**
1. MAke a config
2. Add a AES Encryption function and provide a custom key

**Expected behavior**
It was expected that the algorithms uses our key to encrypt the input data

**Screenshots**
![preview](https://i.imgur.com/PR5INKH.png)
![preview1](https://i.imgur.com/wg9q9GO.png)
![preview2](https://i.imgur.com/DpzwU9k.png)

**Version**
 - 1.1.3#254

**Comment by ForlaxPy** [comment]
yep the argments of that specific function arent getting saved. Simply by setting the aes key and switching to loliscript you find that the key is already gone, [p](https://i.imgur.com/IaAmi3a.png)
[p2](https://i.imgur.com/UK8v7GB.png)

**Comment by openbullet** [comment]
Fixed here https://github.com/openbullet/openbullet/commit/cfcbd76ff3c4e8bb3c74e3141f60e6fe1dde2224
Also mind that the IV and the Key are two different things. The IV is the initialization vector, it's just a random value it's not your secret key! You can look below for reference
![Diagram](https://i.stack.imgur.com/qCpdv.png)

**Comment by openbullet** [comment]
The algorithm inside OB uses the IV equal to the key just because I decided to do so for simplicity, but usually they are different ^_^

**Comment by openbullet** [comment]
There is also an issue https://github.com/openbullet/openbullet/issues/31 that requested the ability to customize the IV, but it's very low priority as OB does not have a comprehensive list of encryption functions, so I would need to add a lot of stuff to really make it usable and complete not just the IV on that specific block cipher mode.
