### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MeowBullet** [openbullet/openbullet#292]
**Before you begin**
1. This is **NOT** Forlax's mod or any other mod. If you have issues related to those versions **DO NOT** post them here as they will be closed and disregarded immediately.
2. Do **NOT** post any form of illegal content (e.g. screenshots of you cracking a website with stolen credentials) and do **NOT** ask for Configs for websites. Doing that will result in a report to the GitHub security team and a permanent ban from posting to this repository.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**
 - Version [e.g. 1.0.1]

**Additional context**

idk what category to put this under, but I don't see an option to parse a cookie as a var anymore.... 

very confusing

**Comment by MeowBullet** [comment]
SORRY IDIOT ALERT KEK

**Comment by openbullet** [comment]
Please don't make issues for this dumb stuff, use the forum. Thanks...
https://forum.openbullet.dev/topic/4/how-to-parse-cookies-headers
