### ISSUE TITLE
[REQUEST] Check For Update Button [AutoUpdate]

### ISSUE THREAD

**Issue by xXxStarxXx** [openbullet/openbullet#294]
**Before you begin**
This is NOT Forlax's mod or any other mod. If you implemented features or fixes related to those versions DO NOT post them here as they will be closed and disregarded immediately.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Just i suggest to add check for update button

**Comment by openbullet** [comment]
Why aren't people deleting the stuff above if they don't want to fill it out?
Also I cannot understand anything about what you want.

**Comment by openbullet** [comment]
Ah okay you want an auto updater inside OB. No sorry it's not planned right now.
