### ISSUE TITLE
[REQUEST] Variable from list

### ISSUE THREAD

**Issue by icloud2017uk** [openbullet/openbullet#295]
Is it possible for OB to read from example a text file list of data and insert a random line from this list as a variable?

**Comment by openbullet** [comment]
Utility block -> read all the lines from a file into a LIST variable
Utility block -> get the length of that list
Function block -> generate a random number between 0 and the maximum length
Then simply do something like `<LIST[<RAND>]>` to get the random line and use it wherever you want.

**Comment by openbullet** [comment]
Next time please use the forum for something like this so it can help other people too.
https://forum.openbullet.dev
