### ISSUE TITLE
[REQUEST] reCAPTCHA v3 Solving

### ISSUE THREAD

**Issue by sondreavik** [openbullet/openbullet#300]
**Is your feature request related to a problem? Please describe.**
A block for solving reCAPTCHA v3.
[reCAPTCHA v3 example site](https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php)

**Describe the solution you'd like**
Solving by 2Captcha or other captcha solving services. [2Captcha example request](https://2captcha.com/blog/solving_recaptcha_v3)
`http://2captcha.com/in.php?key={ApiKey}&method=userrecaptcha&googlekey={siteKey}&pageurl={siteUrl}&version=v3&action=verify&min_score={minScore}`

**Describe alternatives you've considered**
Implementing it into the configs themselves.
```
FUNCTION Constant "{ApiKey}" -> VAR "key" 

FUNCTION Constant "{siteKey}" -> VAR "googlekey" 

FUNCTION Constant "{siteUrl}" -> VAR "pageurl" 

REQUEST GET "http://2captcha.com/in.php?key=<key>&method=userrecaptcha&googlekey=<googlekey>&pageurl=<pageurl>&version=v3&action=verify&min_score=0.3" 
  
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko" 
  HEADER "Pragma: no-cache" 
  HEADER "Accept: */*" 

PARSE "<SOURCE>" LR "OK|" "" -> VAR "TaskId" 

REQUEST GET "http://2captcha.com/res.php?key=<key>&action=get&id=<TaskId>" 
  
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko" 
  HEADER "Pragma: no-cache" 
  HEADER "Accept: */*" 

WHILE "<SOURCE>" Contains "CAPCHA_NOT_READY"

FUNCTION Delay "5000" 

REQUEST GET "http://2captcha.com/res.php?key=<key>&action=get&id=<TaskId>" 
  
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko" 
  HEADER "Pragma: no-cache" 
  HEADER "Accept: */*" 

ENDWHILE

PARSE "<SOURCE>" LR "OK|" "" -> VAR "token" 
```

**Comment by openbullet** [comment]
There were already plans to do this, as this issue https://github.com/openbullet/openbullet/issues/223 was previously open. Anyways, since this issue is formatted way better I'll close the other one.

**Comment by erbhosting** [comment]
when using recaptcha in runner only get retries why it's happend?!

**Comment by openbullet** [comment]
@erbhosting that is not relevant to this issue. You probably have misconfigured your captcha solving service / software.

**Comment by erbhosting** [comment]
> 
> 
> @erbhosting that is not relevant to this issue. You probably have misconfigured your captcha solving service / software.

why i don't have problem with same config in blackbullet?!

**Comment by openbullet** [comment]
I honestly have no clue. Are you using xevil / capmonster? Also please open a new separate issue do not spam under this issue, it is related to recaptcha v3 while you have problems with recaptcha v2
