### ISSUE TITLE
[REQUEST] Wordlist Type For Generated Wordlists To Be Automatically Added

### ISSUE THREAD

**Issue by sondreavik** [openbullet/openbullet#301]
**Is your feature request related to a problem? Please describe.**
When generated wordlists are automatically added to the wordlists manager you're not able to select the type. It's a minor annoyance having to manually add the generated wordlists to select a type other than _Default_.

**Describe the solution you'd like**
Add a dropdown box to the immediate right of the _Automatically Add to Wordlist Manager_ button (found under _Tools > List Generator_) where you can select the appropriate type for the soon-to-be generated wordlist.

Additionally, it'd be nice if we'd be able to change the wordlist type for any wordlist on the fly in the wordlists manager.

**Describe alternatives you've considered**
_Settings > Environment.ini_
```
[WLTYPE]
Name=Default
Regex=^.*$
Verify=False
Separator=:
Slices=NUMERIC,DATA
```

**Comment by openbullet** [comment]
Just wanted to quickly point out, your Slices field should say `NUMERIC,DATA` with a comma or it won't work ^_^
Anyways okay that sounds like a good suggestion I will do that

**Comment by sondreavik** [comment]
> 
> 
> Just wanted to quickly point out, your Slices field should say `NUMERIC,DATA` with a comma or it won't work ^_^
> Anyways okay that sounds like a good suggestion I will do that

You've got a keen eye my friend! Nice catch, I edited the comment to reflect upon your discovery.

**Comment by openbullet** [comment]
This is not needed anymore due to the changes to how lists are generated.
