### ISSUE TITLE
[BUG]Can't solve reCAPTCHA using imagetyperz

### ISSUE THREAD

**Issue by oppaje** [openbullet/openbullet#304]
When I try to solve reCAPTCHA using imagetyperz I get this error 
![Screen Shot 2019-06-23 at 2 41 39 PM](https://user-images.githubusercontent.com/52138057/59981169-d374eb00-95cd-11e9-8dcf-d958306f8c78.png)

**Comment by openbullet** [comment]
It's not an OB error, it was working until a few days ago they might have problems on their side
