### ISSUE TITLE
[BUG] CF Bypass Failed

### ISSUE THREAD

**Issue by Zurzar** [openbullet/openbullet#305]
Hello, new versions of the cloudflare does not handle. At the same time, old versions cloudflare work normally through this CF block. The need either fix or new solution, Thanks

<a href='https://postimg.cc/646DKpQt' target='_blank'><img src='https://i.postimg.cc/646DKpQt/2019-06-24-122943.png' border='0' alt='2019-06-24-122943'/></a>

ERROR: CF Bypass Failed: Cloudflare [JavaScript]: invalid submit response

**Version**
 - Version [e.g. 1.1.3]

**Comment by ModeratorCN** [comment]
Change the user agent.

**Comment by beer15** [comment]
same for me, you use an VPS/RDP ?

**Comment by Zurzar** [comment]
Thank you guys, the error was in the network settings, there was some kind of failure, I reinstall windows and everything began to work fine
