### ISSUE TITLE
[BUG]Corrupted Hits DB

### ISSUE THREAD

**Issue by XVNX** [openbullet/openbullet#306]
Software stopped working suddenly after massive hits happened two times and ended with corrupted DB 2 times i don't know the reason but while trying to launch Open Bullet it gives Open Bullet has stopped responding immediately or just doesn't start at all tried from different computers. 

Decided to open it with Lite DB Explorer 

Proxies,Wordlists and Records are shown except for Hits
When Pressed Refresh on Lite DB Explorer this error appeared 

Unhandled exception occured.

Additional information written into: 'C:\Users\****\AppData\Roaming\LiteDbExplorer\explorer.log'.

Application will shutdown.

Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'.

Here is the log file

Hope you fix it or just tell me how to retrieve the data and stop this issue from happening.
Thanks in advance.

[explorer.log](https://github.com/openbullet/openbullet/files/3327126/explorer.log)

**Comment by openbullet** [comment]
This error started appearing since this PR
https://github.com/openbullet/openbullet/pull/286
I will investigate it when I have time

**Comment by openbullet** [comment]
Did you happen to import any wordlist on-the-fly?

**Comment by XVNX** [comment]
Nope i guess i had like 5 runner going on didn't interrupt them but i guess maybe a config had alot of high ratio of going "to check" as the Database file increased to 70 mb and the server did a reboot.

**Comment by XVNX** [comment]
i don't mind sharing the database in case you want to analyze things
in Lite DB explorer all tabs are working except the Hits doesn't show data and it gives a error when trying to refresh it

**Comment by openbullet** [comment]
Ah damn. When the server reboots while it's writing to the DB, it gets corrupted.
I'm yet to find a tool that can fix a corrupt liteDB, I'll keep you updated if I find a way to recover it.

**Comment by XVNX** [comment]
and oh yea for word lists i guess a day before this happened i rearranged the hits (in the hits db according to capture data) and then sent them to recheck so it created some word lists

**Comment by openbullet** [comment]
Sorting has no actual effect on the DB, just on the view. As for the other thing, it's interesting thanks for providing that info.

**Comment by XVNX** [comment]
managed to retrive some hits using find command in litedb but couldn't fix the corruption of the file D:

**Comment by openbullet** [comment]
I did this https://github.com/openbullet/openbullet/commit/6e9513ad4c17f49323b22fd15ae3cbdde81f3d82

**Comment by donesmarcos** [comment]
Hello!

did you find any tool for fix corrupted DB ?
