### ISSUE TITLE
Add possibility to type a specific IV for AES encryption

### ISSUE THREAD

**Issue by wz48bapt** [openbullet/openbullet#31]
All is said in the title, could be nice for some configs. Thanks

**Comment by styles977** [comment]
you can  do this in python script I guess
just install python module  Pycrypto ... and add this module in OB
that way it can be done

**Comment by vxco** [comment]
@styles977 The AES block is managed by this [code](https://github.com/openbullet/openbullet/blob/master/RuriLib/Blocks/BlockFunction.cs#L1075), actually the IV is deducted from the secret key, i don't think a python module is needed.

**Comment by openbullet** [comment]
Yes currently the key is being used as IV, I guess if you really need this I can make it customizable.

**Comment by openbullet** [comment]
Done in last refactor.
