### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MeowBullet** [openbullet/openbullet#312]
**Describe the bug**
For some reason, when I do selenium with an Open action, and a Navigate block, if the site has invisible recaptcha, and normal recaptcha, it for some reason has been crashing. I restarted, and went to a normal site for example, the forum, was fine.

**To Reproduce**
1. add an open action.
2. add a navigate aciton.
3. navigate to https://www.google.com/recaptcha/api2/demo?invisible=true

**Expected behavior**
It should crash for you, I did try on several recaptcha demos, and tried multiple times... Normal sites seem to work fine? I even decided to rebuild a new copy. Same error? I also decided to test with chrome, and firefox. same problem? I will post the exception shortly.

**Version**
 - Version 1.0.3

![image](https://user-images.githubusercontent.com/49174722/60597835-fc2b8a80-9dee-11e9-9ba7-0364aee35b6d.png)

**Comment by openbullet** [comment]
It happens to one of my official testers as well, I've never been able to reproduce it honestly.

**Comment by openbullet** [comment]
Could you please try and run OB from VS and see where exactly it crashes and which exception causes it?

**Comment by MeowBullet** [comment]
Sorry, I never got around to screenshotting that, I will do that later today.

**Comment by openbullet** [comment]
Please refer to https://github.com/openbullet/openbullet/issues/376 for a solution
