### ISSUE TITLE
Go to CurrentRunnerPage from CreateRunner() 

### ISSUE THREAD

**Issue by iSlyte** [openbullet/openbullet#316]
"addRunnerButton_Click" appends to Runners but how can i append+click that list item? The reason i ask is because i've implemented a wordlist that when you get a hit, i need it to create another runner with a certain wordlist(ive already done this). send to RECHECK basically, but sending to recheck creates new runner, clicks that runner, then SetWordlist happens.

does this make sense?

**Comment by openbullet** [comment]
Just look at the function that gets executed when you click on a runner, and basically call it on the last item of the Runner Manager's list. If you can't manage to make it work I can provide a piece of code I guess.

**Comment by iSlyte** [comment]
If you don't mind providing a piece of code :)
I tried 8 hours before posting here yesterday lol.

**Comment by openbullet** [comment]
Okay please write what you want to do step by step, what you tried and where you struggled so I can have a clear picture thanks!

**Comment by iSlyte** [comment]
Send to RECHECK = Send to CurrentRunnerPage(already clicked a runner, ShowRunner executed)
         runner2.vm.SetWordlist(Globals.mainWindow.WordlistManagerPage.GetList(listName)); (sets wordlist in that runner)
var runner2 = (Globals.mainWindow.CurrentRunnerPage)
if runner2 == null {return;}
listName = "myhits.txt";
        
before it goes to CurrentRunnerPage(a runner you already clicked/chosen), i want it to :
                addRunnerButton_Click(this, null) 
and also trigger click on that new runner(as you said, last runner in list)

**Comment by openbullet** [comment]
Hey, the methods you need to create a runner and switch to it are inside the RunnerManagerPage's viewmodel (vm). So you need to access that, you cannot access the private methods that click the buttons because they are private ^_^

```csharp
var manager = Globals.mainWindow.RunnerManagerPage.vm;
manager.CreateRunner();
var runner = manager.Runners.Last().Page;
Globals.mainWindow.ShowRunner(runner);
```

Anyways this sounds like a good addition to the program so I'm going to commit it myself, feel free to pull the new changes ;)

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/19cac1e1549d8b9d41cd77bc19d69f13ee879456
