### ISSUE TITLE
[REQUEST] Add GPU support to openbullet (Nvidia) 

### ISSUE THREAD

**Issue by patelj04** [openbullet/openbullet#317]
Hey, I noticed that openbullet does not utilize gpu, but adding this would help the program so much, since gpus are good repetition. It would not only mean a huge upgrade to the version but also provide another possibility for other user!

**Comment by iGaMePro** [comment]
That will help in achieving higher cpm
i don't know if thats possible tho

**Comment by openbullet** [comment]
Uhm no sorry I won't do this, too much effort and I don't even think it's worth it.
