### ISSUE TITLE
[REQUEST] Function to decode unicode char

### ISSUE THREAD

**Issue by shdf2** [openbullet/openbullet#318]
Many sites are using these unicode char in their json or source code : \u0026 \u0030 etc...
it will be nice to have a function to automaticaly replace this with the associated ascii char.

Thanks

**Comment by openbullet** [comment]
Hey, nice suggestion. Will do this. In the meantime you can use jint to do that real quick.

**Comment by meinname** [comment]
Added unescape for this https://github.com/openbullet/openbullet/commit/4a89360a4eacd8275191fd1e328ec3cc511252e4
