### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by GTRGHOST** [openbullet/openbullet#321]
I dont want ob to reorganize headers
there are many sites which doesn't accept the reorganized ob headers

**Comment by openbullet** [comment]
In which way does it reorganize headers? Can you show screenshots?

**Comment by GTRGHOST** [comment]
This is what i want it to look like:
![image](https://user-images.githubusercontent.com/52917048/61212321-373c9080-a702-11e9-9a90-544d9c85cd7a.png)


This is how is send it:
![image](https://user-images.githubusercontent.com/52917048/61212401-75d24b00-a702-11e9-800b-b864f8213783.png)
so i get a error from the api

**Comment by openbullet** [comment]
Ah yes it's definitely Extreme.NET's fault. You should open an issue on my Extreme.NET fork not here.
