### ISSUE TITLE
[REQUEST]Function to decode HS256 algorithm

### ISSUE THREAD

**Issue by jaygit23** [openbullet/openbullet#324]
Sir,
Kindly include to decode HS256 algorithm in new update of Openbullet, please.

Regards.

jaygit

**Comment by meinname** [comment]
Do you really need to decode it?
I bet you only need it for JWT - in that case just parse the part between the 2 dots and do a FUNCTION Base64Decode on it

**Comment by openbullet** [comment]
Decoding HMAC SHA-512? Right, cause one can do that ^_^
