### ISSUE TITLE
[REQUEST] Separator in UTILITY Block for List>Zip

### ISSUE THREAD

**Issue by shdf2** [openbullet/openbullet#326]
Would it be possible to add a separator in the Block Utility for the List > Zip ?

Actually when you combine 2 arrays, for example a product name and its expiration date, they are both glued together :
![image](https://user-images.githubusercontent.com/37487684/61613531-dbbe5580-ac61-11e9-8fab-6740dc0781d8.png)

**Comment by weres123** [comment]
u need add space at suffix for variable

**Comment by shdf2** [comment]
thank you for the trick :)

**Comment by openbullet** [comment]
@shdf2  I just wanted to add, you can also do
`FUNCTION Constant "<LIST[*]> " -> VAR "LIST"`
It will take all the elements of LIST, add a space, and project them into a new list (saved in the same var LIST).

**Comment by shdf2** [comment]
even better ! thank you
