### ISSUE TITLE
[BUG] Upgrade Connection to Websocket

### ISSUE THREAD

**Issue by g2asell2019** [openbullet/openbullet#327]
**Describe the bug**
I couldn’t upgrade connection to websocket 

**To Reproduce(Example from OpenBullet Discord)**
1. Go to Stacker
2. Create 2 TCP blocks
3. Add Host, port and messages

**Expected behavior**
https://imgur.com/a/IuboHgi

**Screenshots**

**Version**
 - Version [e.g. 1.3.5]

**Additional context**

**Comment by meinname** [comment]
Can you please remove the screenshot? 
Or can you prove you are allowed to test the security of the site shown in the screenshot?

**Comment by g2asell2019** [comment]
My bad, Maybe I’m using the modded version by LethalLuck and Pure
But I want response header like this https://imgur.com/a/IuboHgi

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/294e6f93caa6e0e13d4a4b808fd022145fd4d75e

**Comment by openbullet** [comment]
You can upgrade directly from the REQUEST block now without using the TCP block.
