### ISSUE TITLE
Type: FREE is missing in the HITS DB

### ISSUE THREAD

**Issue by flyal** [openbullet/openbullet#33]
Hello
In the version 1.2.1 the Type: FREE is missing in the HITS DB
Pleas repair this problem

**Comment by ForlaxPy** [comment]
Well you got a custom one too which replaced FREE: ![preview](https://i.imgur.com/lBY5vcr.png)

**Comment by flyal** [comment]
Yes but some config have both, and when i click costume it don't give the info of free.

**Comment by flyal** [comment]
You Can Free in LiteDB tell that Zalando have free info, but when i click custom don't give nothing

![image](https://user-images.githubusercontent.com/7648746/55653658-7dbf4c80-57ef-11e9-90b8-6c02f6bbc182.png)

**Comment by openbullet** [comment]
First of all that version you have is not the master branch, and it's not supported by me, so you shouldn't post here. So basically your issue is that user-defined custom keychains do not display the related hits correctly in the hits DB. I will look into it.

**Comment by openbullet** [comment]
By the way @ForlaxPy could you add like (Forlax Mod) on the title of your releases? Because people are starting to contact me with issues related to that build thinking I made that update. Thank you so much.

**Comment by ForlaxPy** [comment]
Oh yes sure, sorry for the inconvenient

**Comment by ForlaxPy** [comment]
@flyal could you please to try to add this `
[CUSTOMKC]
Name=FREE
Color=OrangeRed`
To the Environment.ini in Settings. I think that's why it's missing

**Comment by flyal** [comment]
Ok i will try it now. Thnx

**Comment by openbullet** [comment]
Yeah most definitely @ForlaxPy solution will work, let us know

**Comment by flyal** [comment]
Now it display the free but remove the custom. Or to add both?

**Comment by ForlaxPy** [comment]
@flyal totally up to you, you can keep the custom one or remove it but Id suggest you to keep it as it's built in the main OB and most of config makers are using it.

**Comment by flyal** [comment]
Ok thnx

**Comment by openbullet** [comment]
Perfect, I'll close this then ^_^

**Comment by flyal** [comment]
I try, the solution is to have both
it work display free and custom

[CUSTOMKC]
Name=CUSTOM
Color=OrangeRed

[CUSTOMKC]
Name=FREE
Color=OrangeRed

[Environment.zip](https://github.com/openbullet/openbullet/files/3050559/Environment.zip)
