### ISSUE TITLE
Content-Type application/json problem

### ISSUE THREAD

**Issue by viper645** [openbullet/openbullet#331]
When i choose content-type application/json it still sends application/x-www-form-urlencoded and i tried to reopen it nothing pls fix this

**Comment by openbullet** [comment]
With "reopen" I meant reopen the other issue, not reopen the program...
Anyways, please show what you are doing (I hope you're selecting the content-type from the dropdown menu), and delete any other header you might have in the custom headers.

**Comment by openbullet** [comment]
My beta tester just tried and said this works, please provide more information or we cannot help you, closing this for now.

**Comment by Sussyamogus021** [comment]
Skill issue 🤡
