### ISSUE TITLE
[BUG] To use this feature, you need to turn on JavaScript in your browser settings.

### ISSUE THREAD

**Issue by Jolge2** [openbullet/openbullet#333]
i want get data from website but get this error in HTML View
![image](https://user-images.githubusercontent.com/54249118/63230011-5ad08a80-c21c-11e9-83e3-b2aa0150385f.png)

after enable javascript in browser debugger show blank page
how can fix this ?
thanks

**Comment by openbullet** [comment]
You cannot execute the page's javascript code using requests. Try using selenium instead.
