### ISSUE TITLE
[REQUEST]Shrink database button

### ISSUE THREAD

**Issue by shdf2** [openbullet/openbullet#334]
Hi,
even after deleting a lot of rows in the database, the size remain the same and this could be an issue sometimes (OB doesn't start anymore or crash). i suggest to add a database shrink button. i saw it is supported since litedb 2.0 here : https://github.com/mbdavid/LiteDB/issues/50

**Comment by openbullet** [comment]
Hey, thank you, it will be done.

**Comment by shdf2** [comment]
Don't forget me :-)

**Comment by Teals53** [comment]
Xd

**Comment by openbullet** [comment]
I said I would do it, bumping the request just makes me want to delay it :)

**Comment by meinname** [comment]
https://github.com/openbullet/openbullet/commit/a97eb3afedb6b1a6a15519bcb1846815ef3e8a74
Please don't forget to backup ;)
