### ISSUE TITLE
[REQUEST] <COOKIES(RegEx)>

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#337]
**Describe the solution you'd like**
i 'd like to see a solution for getting the cookie value from a generated cookie name
for example:
mein_born_\d\d\d_\d\d\d\d\d: cookieValueX
mein_born_987_5463: cookieValueY
mein_born_209_6495: cookieValueZ

thx

**Comment by openbullet** [comment]
You could use the variable `<COOKIES>` as is and then parse from that one with regex. I don't think I will implement that sorry.
