### ISSUE TITLE
[REQUEST] UTILITY Object

### ISSUE THREAD

**Issue by ghost** [openbullet/openbullet#338]
**Is your feature request related to a problem? Please describe.**
Sometimes, there is an additional cookie inside the cookies object, that i want to remove.
to do that i have to pass the <COOKIES> to javascript code, then i can process the object.
Then ClearCookies, and assign the new object to Cookie: in the next header.

**Describe the solution you'd like**
so i was thinking if you could have an UTILITY Object, like the Utility List, with some functions inside
this Utility would have the possibility to access <COOKIES>
POP/REMOVE one element
...

thx

**Comment by openbullet** [comment]
Yes there are basically no functions to work with dictionary variables atm, I will implement more soon.

**Comment by ReDDOOne** [comment]
@openbullet a small reminder :)
a dictionary.pop(<by-given-name>)

**Comment by openbullet** [comment]
@ReDDOOne I won't be able to implement anything for at least another 2 weeks, life's being pretty busy.
