### ISSUE TITLE
[REQUEST] Ability to read and control Statistics Variables

### ISSUE THREAD

**Issue by Micro-Crackedto** [openbullet/openbullet#339]
Hello,

It would be nice if we are able to read for example the current amount of hits and reset them after following some execution steps.
The reason for this would be so that we can auto post every X amount of hits on a site.
++
IF "<HIT<HITS>S>" EqualTo "10"
JUMP #10 HITS
ELSE
JUMP #NOT 10 OR NOT WORKING
ENDIF
++
When jumping to #10 HITS
It will post all the 10 hits and reset the hit counter, so it will continue to post 10x new accounts at a time.

Also, adding all the hits to a LIST does not work, as it seems the LIST gets reset upon each new "ADD".

So to make a long story short, I want to be able to get all current hits when they reach a total that I provide or random, post them onto a site and simply reset the hits counter and loop this process.
[I can already post the accounts on a site, I just need the other stuff.]

**Comment by openbullet** [comment]
The issue with this is that the bots don't (and shouldn't) know anything about the total statistics, and I prefer to keep it this way. You will be able to interact with statistics in the scheduler though, so you can set conditions for example
WHEN HITS > 10 --> STOP RUNNER --> WAIT 5 MINUTES --> START RUNNER
