### ISSUE TITLE
[REQUEST] parse

### ISSUE THREAD

**Issue by aliabusaad** [openbullet/openbullet#340]
Hi. I have stupid problem.

 

I Need to parse a token as url in

 

<--- Executing Block REQUEST --->
Calling URL: https://sss/ss
Post Data: ssssss
Sent Headers:
Origin: https://sssss
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Referer: https://sss
Accept-Language: en-US,en;q=0.9,es;q=0.8
Content-Type: application/x-www-form-urlencoded
Sent Cookies:
NSC_ESNS : fd67ffaf-e5f7-1d61-9678-00e0ed2173b0_0550533224_3809951812_00000000008545847365
NSC_WT_DD_IUUQ_80 : ffffffff0903760a45525d5f4f58455e445a4a423660

 

Address: https://ssss/?ant=30...h=587534191&t=1

 

i need parse this Address: how is this possible its not working by using <HEADERS(Address)> or <COOKIES(Address)>

 

i hope some one can help me with this

**Comment by winuser** [comment]
<HEADERS(Address)>

cookies is only for value of a cookie

**Comment by openbullet** [comment]
If you want to parse a header, the answer above is correct. If you want to parse the response URL you need to type `<ADDRESS>`
