### ISSUE TITLE
[REQUEST] option to set the "Hits DB" in colors

### ISSUE THREAD

**Issue by Spangonagornomb** [openbullet/openbullet#341]
a cool and neet option that I think might be very useful and neet 
what I am referring to is related to the "Hits DB".

What I am suggesting you guys is to add a small and neet option. which is the ability to set up colors like you **select whatever** you want and then **right click** and then "Set up color" and then you choose the whatever you want

![image](https://user-images.githubusercontent.com/48364104/63654204-3d278780-c72c-11e9-8fad-ba69f2fcec49.png)

I believe that is is a super neet option because for example your home electrics crashed and you want to set up start right from the start but then you need to go to the "Hits DB" and look up for the last hit but then after you get newer alts you become confused
setting up colors to hits would be amazing and super helpful!
with colors you just set up a color and take in mind that all the stuff in green you already sticking onto text files on other location on your pc or whatever..

Small option could be useless for most but could be helpful for **some users.**

Have a wonderful day!

**Comment by openbullet** [comment]
You can just order by date. I won't do this. Also you're doing illegal stuff, next time you'll be banned from accessing the repo.
