### ISSUE TITLE
[REQUEST] search box in the area of configs

### ISSUE THREAD

**Issue by Zigoleiro** [openbullet/openbullet#343]
**A search box in the area of configs, I have + 240 configs, it is very difficult to find something, if it were possible a search box there, would make it very easy !
I believe that many have the same problem as mine!**

**Comment by openbullet** [comment]
Mate i literally implemented less than 24 hours ago...
https://github.com/openbullet/openbullet/commit/3bcfb7cae9c3da45741325ebe15aea45975295b8
