### ISSUE TITLE
[REQUEST] get mail with IMAP/POP3

### ISSUE THREAD

**Issue by thanhlouis** [openbullet/openbullet#345]
Can use this to login email with imap ?

**Comment by openbullet** [comment]
Yes, use the TCP block and issue IMAP commands through it

**Comment by thanhlouis** [comment]
I don't know how to get the right message to send, can you help me ?
And, have any way use many imap in one config ?

**Comment by openbullet** [comment]
Any guide like this works http://blog.andrewc.com/2013/01/connect-to-imap-server-with-telnet/
for example for logging in it's `anything LOGIN <USERNAME> <PASSWORD>`
To use multiple IMAPs you have to identify the domain that is going to be logged in and translate it into a host + port using the Translate function block. Also 1xx ports do not use SSL while 9xx ports do, so make an IF check for those. I will not help you any more than this.

**Comment by thanhlouis** [comment]
thank you
