### ISSUE TITLE
TLS issue in build 1.1.4

### ISSUE THREAD

**Issue by Myztical1** [openbullet/openbullet#349]
ERROR: Unable to establish SSL-connection with HTTP-server.
Working on older builds 1.1.3

**Comment by openbullet** [comment]
Might be due to the System.Net.Http assembly change. Have you tried redownloading from scratch?

**Comment by Myztical1** [comment]
Yes but it didn't work

**Comment by meinname** [comment]
Are you the same one as here?  Or is it a friend of yours?
https://forum.openbullet.dev/topic/129/error-unable-to-establish-ssl-connection-with-http-server

Just asking as I heard about this error 3-4 times now - but it was always about the same URL

**Comment by Myztical1** [comment]
@meinname It's not me & no affiliation with that person however it's not url because I tried on different sites as well. I using this build & all good http://prntscr.com/p6yd0z

**Comment by openbullet** [comment]
Can you try to use the System.Net.Http assembly and the OpenBullet.config file from the 1.1.3 build and put them in the 1.1.4 build replacing the existing ones and tell me how it goes?

**Comment by Myztical1** [comment]
It doesn't has System.Net.Http in 1.1.4  http://prntscr.com/p77cdk  however I try putting it in bin folder & still no luck. http://prntscr.com/p77drd

**Comment by openbullet** [comment]
I need to know the domain in order to try it myself

**Comment by openbullet** [comment]
Or does it happen on every domain?

**Comment by meinname** [comment]
are you In Windows 7 or Windows 2008r2?
Then it's because Openbullet now supports TLS 1.1 and 1.2 but you System has disabled it per default.
To enable it use https://www.smartftp.com/static/Products/Client/Addons/TLS%201.x%20on%20Windows%207.zip
from https://support.cybersource.com/s/article/How-do-I-enable-TLS-1-2-on-Windows-7

**Comment by Myztical1** [comment]
TLS 1.2 was enabled on windows 7 & working on 1.1.4  
https://gyazo.com/66f2a76f42b6a11f780165184bccee8d
http://prntscr.com/p8v77s

Thank you guys...

**Comment by openbullet** [comment]
@Myztical1 if it worked please close the issue thanks!
