### ISSUE TITLE
Bypass CF issue

### ISSUE THREAD

**Issue by James94665** [openbullet/openbullet#35]
Hi there, anyone know how i can fix this error?
[12] ERROR in block BYPASS CF | Exception: Object reference not set to an instance of an object.

**Comment by James94665** [comment]
Works fine in debugger but in bruteforcer it gives the error above

**Comment by styles977** [comment]
@openbullet  CF is perfecty bypassed for some sites
but the bot couldn't bypass for some special site like this please see it ---> http://puu.sh/DaN4T/5baaa5d8c2.txt
CF always change their technique lol :3

**Comment by openbullet** [comment]
There is another issue with the same problem https://github.com/openbullet/openbullet/issues/12 I will close this one. Anyways be aware that since I rely on Leaf.xNet for the bypass, unless the dev pushes a fix for those sites my hands are a bit tied.

**Comment by Mike129812** [comment]
Just tested this and openbullet perfectly bypassed the cf of 99rdp. However for some reason it only works via the debugger, il see if i can find a fix for it working in the openbullet program itself.

**Comment by James94665** [comment]
Could you not ask the dev to fix the sites?

**Comment by mastercho** [comment]
> Just tested this and openbullet perfectly bypassed the cf of 99rdp. However for some reason it only works via the debugger, il see if i can find a fix for it working in the openbullet program itself.

bypass only homepage but if you go to login page will fail to bypass

**Comment by ruz0ne** [comment]
any update? have the same problem working fine in debugger but not in runner tab )= ???
