### ISSUE TITLE
[REQUEST] make request pass through localhost

### ISSUE THREAD

**Issue by MostafaCoolaa** [openbullet/openbullet#350]
some sites that have akamai like nike, gamestop and hilton needs the request to be sent on 127.0.0.1
i have burp suite listening to 127.0.0.1
here without 127.0.0.1 as proxy
![image](https://user-images.githubusercontent.com/46325804/65266658-c8215500-db13-11e9-8a64-66d3a7ec55df.png)
here is after using 127.0.0.1 as proxy
![image](https://user-images.githubusercontent.com/46325804/65266774-00c12e80-db14-11e9-8652-417bcf86715d.png)

**Comment by openbullet** [comment]
So what exactly is your problem? Also you MUST specify a port for the proxy like `127.0.0.1:3000` or whatever port it is, otherwise I think it will not be parsed at all!

**Comment by MostafaCoolaa** [comment]
the problem is that the connection gets refused if it doesn't pass on localhost
as shown in screenshots
i think the server knows that i am using a bot

**Comment by openbullet** [comment]
Did you try with the correct burp port first?

**Comment by MostafaCoolaa** [comment]
when i correct burp port it get rejected like in first image

**Comment by MostafaCoolaa** [comment]
![image](https://user-images.githubusercontent.com/46325804/65269322-3a486880-db19-11e9-8c24-8168e00e54e3.png)

**Comment by MostafaCoolaa** [comment]
![image](https://user-images.githubusercontent.com/46325804/65274945-ce6bfd00-db24-11e9-888a-a5ac8c38e1c3.png)
