### ISSUE TITLE
[REQUEST] Selenium need to quit browser to change proxy

### ISSUE THREAD

**Issue by GGttyyy** [openbullet/openbullet#354]
Please add the feature . On the status of ban or retry , quit the browser at the same time.
![1](https://user-images.githubusercontent.com/42407379/65507536-bc150900-df00-11e9-8010-d7e9c0a1e012.png)
Ban on time out also.

**Comment by openbullet** [comment]
You mean Other options -> Selenium -> Quit browser at the end? Or you only want to close it for those 2 specific statuses?
