### ISSUE TITLE
[BUG] JToken parsing JSON Arrays

### ISSUE THREAD

**Issue by dNitro** [openbullet/openbullet#355]
**Describe the bug**
JToken parsing is unable to parse sources which are valid json arrays

**To Reproduce**
1. Go to Configs
2. Click on new to make a new config
3. add a GET request block to http://www.mocky.io/v2/5d8a16ab3000008cc2b9a6e5
4. add a parse block, make a variable TITLE and tick JToken parsing.
5. now click start and debugger will give the following error:
```
Response Source:
[{"id":1,"title":"hello"},{"id":2,"title":"world"}]
<--- Executing Block PARSE --->
ERROR: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.
```

**Expected behavior**
Of course the aforementioned source is valid json and someone should be able to reach a specific value with for example `[0].title` ( or `[0]["title"]` )

**Version**
 - Version 1.1.4

**Additional context**
I think we could try..catch JObject.Parse(json) and in catch block parse it with JArray.Parse(json); cuz valid json is just in one of these two forms.

**Comment by dNitro** [comment]
By the way, found this guide of you which seems promising:
https://forum.openbullet.dev/topic/37/parsing-complex-json-using-jtokens
but it's very nice to have this feature built-in. these issue could be closed till there. Anyway, Very Nice Tool, Keep up the good job man ;)

**Comment by openbullet** [comment]
As you answered yourself, the guide explains why it's happening. I will leave this open in case I decide to implement something automatic.

**Comment by openbullet** [comment]
Thanks again for the nice suggestion, done https://github.com/openbullet/openbullet/commit/62344f715543222b278e9c3a713722b7cc89fc00
