### ISSUE TITLE
[BUG] LoliScript does not respect Number equality

### ISSUE THREAD

**Issue by dNitro** [openbullet/openbullet#356]
**Describe the bug**
It seems key check EqualTo does not respect Numbers equality and coerce numbers to String which leads to the wrong check.

**To Reproduce**
1. Go to Configs
2. Click on +New to make a new config
3. Add a GET request block to http://www.mocky.io/v2/5d8a49b63000007f08b9a897
4. Add a parse block and collect status in a variable called STATUS (using json with key: status or leftRight. it does not matter which one to use )
5. Add a key check block with two situations one success with:
```
STATUS EqualsTo 1
```
and another with failure:
```
STATUS NotEqualsTo 1
```
6. Click start; The final status of Bot is FAIL

**Expected behavior**
The final status of the bot should be Success as STATUS is 1

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/13446672/65533688-013e3880-df0b-11e9-9666-86c9b3bd6a45.jpg)

**Version**
 - Version 1.1.4

**Additional context**
Removing double-quotes in LoliScript syntax: `KEY "STATUS" EqualTo "1" ` is not allowed. Also parsing with JToken parsing does not help. I think for boolean ( i.e: true, false) and Null values in json sources there is a similar problem.

**Comment by openbullet** [comment]
Mate, if you want to use a variable you have to use `<STATUS>` not `STATUS` in the keycheck textbox. Also, note that STATUS is a reserved variable for the bot status (FAIL, SUCCESS etc.) so you cannot use it, use another name when you parse it and then type like `<HELLO>` EqualTo `1`
