### ISSUE TITLE
[REQUEST] add UserAgent header in CAPTCHA Block

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#357]
can you, please, add a a userAgent header to the request sent in CAPTCHA Block when trying to download an image

reason:
so it can match the requests going on
and fix a problem with site with both CF and Captcha in the same time

thanks

**Comment by ShadixAced** [comment]
CF already has got the UserAgent added in the solving bypass code.

**Comment by ReDDOOne** [comment]
thank you
