### ISSUE TITLE
[REQUEST] UTILITY Function Create Folder

### ISSUE THREAD

**Issue by beer15** [openbullet/openbullet#358]
Hey 

I would like to see an option to automatically create a folder, like STORM, 
Example, put a destination and propose to create a folder, or make sure that it is saved in a hits folder with a variable of your choice or a date.

https://i.gyazo.com/b12fec3ec962570b85edc3485b8c7c56.png

I think it could improve the configs and make them better

Thanks alot

**Comment by openbullet** [comment]
Duplicate https://github.com/openbullet/openbullet/issues/260
