### ISSUE TITLE
[BUG] Multiline post data input for text/plain content-type

### ISSUE THREAD

**Issue by dNitro** [openbullet/openbullet#365]
**Describe the bug**
Lately, we were unable to make a request because its payload was multiline. Trying to make it multiline by using \n is not an option cuz backend service is not unable to parse it.

**To Reproduce**
1. Go to Configs
2. make a post request
3. select text/plain as Content-Type
4. It's not possible to send the following payload (the first line of the payload is empty; just contains a newline character ):
```

SOME-DATA-HERE
```

**Expected behavior**
Someone should be able to copy the above payload and paste it into POST DATA input, so it should be Multiline like Cookies and Headers Inputs.

**Version**
 - 1.1.4#329

**Additional context**
By the way a multiline input for other types like x-www-form-urlencoded and json types also would be beneficial ( it's much more readable because of wrapping ), but for plain/text payloads is essential.

**Comment by openbullet** [comment]
If you type `\n` it makes a new line. I'm guessing the backend is windows-based and expects `\r\n` at this point?

**Comment by dNitro** [comment]
No, I've also tested `\r\n`. When I paste the aforementioned payload in *postman* I receive the response but it's not possible to paste in POST Data input of OB, and if I use \n ( or \r\n ) then the payload is not parseable at all. Even if I use \n ( or \r\n ) in *postman*, server responds with error: unable to parse. The problem is newline character is not typable and if we use \n ( or \r\n ) it is not parsable but if copy-pasted then it works; which current OB POST Data input does not allow to paste multiple lines.

**Comment by openbullet** [comment]
Yes you can type a `\n` using `\\n` try it. It was just added in a recent update!

**Comment by openbullet** [comment]
If you want to send the actual `\n` character, that is. `\r\n` is not implemented but I can implement it if you want! It's the same used in other multiline textboxes so it should work!

**Comment by dNitro** [comment]
Wow, `\\n` does the trick. And it should be nice to also have literal `\r\n`. Many Tanx man! Big up to you. Cheers.

**Comment by tanveer-hash** [comment]
just do one thing,open notepad++ paste whatever you want to post(postdata)
Then encode it using base64
copy and paste it to function input,and use function as base64 decode and get it to variable 
or contact me @perrcocet telegram

**Comment by tanveer-hash** [comment]
just do one thing,open notepad++ paste whatever you want to post(postdata)
Then encode it using base64
copy and paste it to function input,and use function as base64 decode and get it to variable
