### ISSUE TITLE
FUNCTION HEX [REQUEST]

### ISSUE THREAD

**Issue by Zigoleiro** [openbullet/openbullet#367]
**FUNCTION HEX DECODE/ENCODE**

As there is now a possibility to use sockets, it would be interesting to put a function like this.

**Comment by openbullet** [comment]
There is already one in the UTILITY block under the Conversion group I believe

**Comment by Zigoleiro** [comment]
There's no function for that yet.

**Comment by syzer7** [comment]
como criar funçoes
