### ISSUE TITLE
[BUG] "automatic TOCHECK after x BANs" does not show in Hits DB

### ISSUE THREAD

**Issue by GGttyyy** [openbullet/openbullet#368]
"automatic TOCHECK after x BANs" does not show in Hits DB. It's BAN Type, not NONE.

![image](https://user-images.githubusercontent.com/42407379/66186211-448b6a80-e6b4-11e9-8f9b-5dd3f5454414.png)

**Comment by openbullet** [comment]
Thank you for the report! I will fix it asap

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/29b05fb252b3fe15997b35ada4f21d46dc2a8a99 if it's still bugged please reopen the issue thanks!
