### ISSUE TITLE
Error Compiling the solution

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#37]
while compiling
. VS 2017
. GIT for windows is installed

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error |   | The command "chmod +x """ exited with code 9009. | OpenBullet |   |   |

**Comment by ReDDOOne** [comment]
<img width="2179" alt="Screen Shot 2019-04-06 at 11 58 47 AM" src="https://user-images.githubusercontent.com/23710158/55668533-7fc2f300-5863-11e9-9a23-589c00a8fb5b.png">

**Comment by ReDDOOne** [comment]
after i close and re-open the VS, and try to build again
it is successful but it has the warning from last time

**1>------ Build started: Project: OpenBullet, Configuration: Debug Any CPU ------
2>------ Build started: Project: OpenBulletCLI, Configuration: Debug Any CPU ------
2>  OpenBulletCLI -> C:\Users\<USER>\source\repos\openbullet\OpenBulletCLI\bin\Debug\OpenBulletCLI.exe
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "System.Net.Http" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>  OpenBullet -> C:\Users\<USER>\source\repos\openbullet\OpenBullet\bin\Debug\OpenBullet.exe
========== Build: 2 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
**

**Comment by ReDDOOne** [comment]
when i try to run the .exe, i am having this
<img width="448" alt="Screen Shot 2019-04-06 at 12 08 24 PM" src="https://user-images.githubusercontent.com/23710158/55668658-bbaa8800-5864-11e9-852e-ddbc66102af3.png">

i dont know weather to add that .ini from the compiled version or i should find somewhere

**Comment by ForlaxPy** [comment]
Well first of all Clone the official [Extreme.Net repository](https://github.com/nickolasKrayn/Extreme.Net) then compile it and you will get Extreme.Net.dll
After that clone OpenBullet repo and Right click in each of the three projects ![preview](https://i.imgur.com/wjQ6LeJ.png) then ==> Add ==> Reference ==> Browse for the Extreme.Net.dll if you get that done correctly it should work fine

**Comment by openbullet** [comment]
Sometimes you get that error when compiling, just switch the build mode from Debug to Release or vice versa and compile, and then switch back to Release, it will work. Also it should automatically generate a default Environment.ini file the moment you compile the solution.

**Comment by ReDDOOne** [comment]
but it is not generating the Environment.ini file
