### ISSUE TITLE
[BUG]When using remote proxy api ,all bots will stuck at initializing.

### ISSUE THREAD

**Issue by GGttyyy** [openbullet/openbullet#374]
when all banned and reload the proxy  ,all bots will stuck at initializing.

**Comment by openbullet** [comment]
You need to post more info (your settings) or a video of the problem happening. Please no illegal things or you will be banished from this repo.

**Comment by GGttyyy** [comment]
This problem starts from 1.1.4#323 version . All defaut settings . I add only 2 api links https://api.proxyscrape.com/?request=getproxies&proxytype=socks4&timeout=10000&country=all
https://api.proxyscrape.com/?request=getproxies&proxytype=socks5&timeout=10000&country=all
![2019-10-06 16-11-53](https://user-images.githubusercontent.com/42407379/66266494-7c331780-e858-11e9-8f66-5a12efa0273f.gif)

**Comment by openbullet** [comment]
I reverted it https://github.com/openbullet/openbullet/commit/253c9c7aa3b61281519ee09b8a0ba9dbb24fc6e0
