### ISSUE TITLE
Xevil not being detected by Two Captcha 

### ISSUE THREAD

**Issue by theman480** [openbullet/openbullet#375]
The lastest version of openbullet is not detecting the lastest version of xevil, anyone can help me?

**Comment by openbullet** [comment]
How am I supposed to debug this without buying xevil? :D

**Comment by theman480** [comment]
It`s working perfectly, was an settings problem.
Sorry for the dumb question.

**Comment by openbullet** [comment]
Then please close the issue yourself next time, thanks!
