### ISSUE TITLE
[BUG] problem with recaptcha block and selenium

### ISSUE THREAD

**Issue by viper645** [openbullet/openbullet#376]
Get crash from OB if i use recaptcha block and selenium
When i try this out i get crash : https://forum.openbullet.dev/topic/18/how-to-insert-a-recaptcha-v2-solution

screenshot : https://prntscr.com/pfcypv

Can u guys pls fix it or find a easy way to use recaptcha that works with capmonster or any other service in selenium.
Most of the extension on chrome or firefox don't work at all with selenium.

**Comment by openbullet** [comment]
This is the everlasting problem that beta tester demiurgo experienced since the beginning. I will update you if we find any fix for it.

**Comment by openbullet** [comment]
The issue is due to the HTMLViewer. Please disable HTMLViewer in settings and it won't crash anymore.
