### ISSUE TITLE
Prasing Json Error

### ISSUE THREAD

**Issue by styles977** [openbullet/openbullet#38]
There is a minor error in Parsing json i guess when the parsing, "keyword" isn't there then the Bot set it's status to error. 
http://prntscr.com/n8c2vq

giving 
ERROR: Sequence contains no elements

**Comment by openbullet** [comment]
Fixed https://github.com/openbullet/openbullet/commit/b81262f9c3760297a6821adb4ecb9d2df6543738 thanks!
