### ISSUE TITLE
[REQUEST] A variable to hold CLIPBOARD content

### ISSUE THREAD

**Issue by dNitro** [openbullet/openbullet#386]
**Is your feature request related to a problem? Please describe.**
Currently, OB does not have access to clipboard content. It would be beneficial to have a variable that holds it so we can use clipboard content.

**Describe the solution you'd like**
A variable named for example CLIPBOARD which holds clipboard content and is accessible via `<CLIPBOARD>`

**Additional context**
Sometimes in selenium pipelines, we copy some data by clicking buttons but there is no way to access its value as is copied to clipboard.

**Comment by openbullet** [comment]
No it would not be beneficial. Maybe a user copied some sensitive banking information and through automation a malicious third party can retrieve those and send a request to his server to collect the info. I will not do this, if you have a secure way to do this then feel free to explain further.

**Comment by dNitro** [comment]
Oooow, I didn't see that from the security point of view but it seems, implementing it would make OB vulnerable! Thank you for mention it. Of course, implementing it in a secure way remains a question! Right now I'm also answerless. Maybe others could help with this. watching out whether others need this feature and could come up with a secure solution ...
