### ISSUE TITLE
[BUG] selenium open new tab

### ISSUE THREAD

**Issue by dNitro** [openbullet/openbullet#387]
**Describe the bug**
It seems there is no way to open a new tab. I've examined all BROWSER ACTIONS block actions including `open` and `switchToTab` but none opens a new browser tab.

**Expected behavior**
It's expected there to be a way to open a new tab and then navigate to a URL. Or OB could have a `new tab` Checkbox in NAVIGATE block so by checking it, the browser should open a new tab and navigate to defined URL.

**Version**
 - Version 1.1.4#334

**Additional context**
Other possible ways include equip `switchToTab` to open a new tab if it does not exists Or add function keys like CTRL to `sendKeys` browser action so sending CTRL+T will open a new tab.

**Comment by ReDDOOne** [comment]
did you try Execute JS block 

window.open('about:blank','_blank');

**Comment by openbullet** [comment]
Please let us know if ReDDOOne's solution works, but it would be nice to have this implemented as a Browser Action.

**Comment by dNitro** [comment]
@openbullet , yes, @ReDDOOne 's solution works perfectly. but as you said it would be nice to have `NewTab` and `CloseTab(index)` Browser Actions. I think these two actions are At least more frequent than `Maximize` and `Minimize` in day to day work with browsers ^-^
