### ISSUE TITLE
[BUG] Can't Launch Program 

### ISSUE THREAD

**Issue by RV7007** [openbullet/openbullet#389]
all i have problem my openbullet can't launch before not problem after restart vps my openbullat can't launch or stoped program on my other vps 
Im already installed newer version 
.net 4.8 
c ++ 2015-2019

this screenshoot
http://prntscr.com/pjzwhp

**Comment by openbullet** [comment]
If there is a problem with the .NET framework the program will tell you about it. Crashing does not mean it's a problem with the framework, it's probably of another nature. Did you try to download it again? Care to post a crash dump from the OS?

**Comment by RV7007** [comment]
how to step post a crash dump from the OS?

**Comment by openbullet** [comment]
I had a problem once on a shared VPS where I was not able to launch ANY executable. Have you tried if other programs crash on start?
