### ISSUE TITLE
Report incorrect recaptcha DBC

### ISSUE THREAD

**Issue by ConsciousState** [openbullet/openbullet#390]
Would be very awesome if you added the ability to report incorrect recaptchas so we don't pay $ for incorrectly solved recaptchas!
Hope you can add this in the near future.

**Comment by Bilaboz** [comment]
Yes it would be very nice !

**Comment by ConsciousState** [comment]
Is this gonna be added or?

**Comment by openbullet** [comment]
Maybe when I can finally find some time to code features..

**Comment by ConsciousState** [comment]
> Maybe when I can finally find some time to code features..

would be nice.
cos its really not worth using a captcha solving service the way it works now.
