### ISSUE TITLE
[BUG] checking "Create Empty" still creates the variable.

### ISSUE THREAD

**Issue by shdf2** [openbullet/openbullet#391]
**Describe the bug**
When i uncheck "Create Empty" it still creates the variable.

Here is an aexample with this JSON, i try to capture **Code** value, and i don't want the variable to be created if it is empty:

`{"ServiceResponse":{"Status":"1","NowUTC":"20191005131341","OutData":{"Code":""}}}`

Here is the Result:
![image](https://user-images.githubusercontent.com/37487684/67158399-e0b1a480-f337-11e9-84a2-60f308278f3d.png)

I noticed the same behavior if it's a L/R Parse.

**Comment by openbullet** [comment]
Create Empty simply means:
if you don't find the L and R or the json field or the regex pattern inside the input, still create the variable with an empty value.
It has nothing to do with values that ARE present but are empty / null. If I change the behaviour I will break existing configs, sorry.

**Comment by shdf2** [comment]
And making a new checkbox "Don't create if null/empty" ?
This is in order to have clean captures without useless variables...

**Comment by openbullet** [comment]
The max I can do, and that I also told demi, is to make a checkbox inside the config options so that it would clean all the empty capture before saving to the database.

**Comment by shdf2** [comment]
sounds good for me :)
