### ISSUE TITLE
[BUG] BYPASS CF not working

### ISSUE THREAD

**Issue by ndt258** [openbullet/openbullet#392]
Can't bypass CF anymore.
Eror message:
ERROR: Specified argument was out of the range of valid values.
Parameter name: Unknown operator: 
![image](https://user-images.githubusercontent.com/43379889/67256815-28a90680-f4b3-11e9-9139-45983d3a383e.png)

**Comment by openbullet** [comment]
Yes Leaf is having trouble on some sites. If you want you can go back to the build that was using CloudflareSolverRe as a library, that should still work. I will try to find a better system when I have time.

**Comment by ndt258** [comment]
Got it. Thanks you!
