### ISSUE TITLE
[REQUEST]Wait time and start againg

### ISSUE THREAD

**Issue by percebal** [openbullet/openbullet#396]
I was wondering if you can implement the function when all the proxies have been banned, wait a certain number of minutes and start automatically after that time, thanks.

**Comment by Micro-Crackedto** [comment]
I think you are looking for the reload interval..

https://i.imgur.com/yhLTPpj.png

**Comment by openbullet** [comment]
This will be included in the scheduler which is planned to be released at some point this year
