### ISSUE TITLE
[BUG] CF Bypass ERROR

### ISSUE THREAD

**Issue by karimbenammar** [openbullet/openbullet#397]
**Describe the bug**
Bypassing cloudflare just throws an error:

<--- Executing Block BYPASS CF --->
ERROR: Specified argument was out of the range of valid values.
Parameter name: Unknown operator: 

**To Reproduce**
1. Add BYPASS CF Block
2. Use this URL: http://host-engine.com/xc/index.php
3. Run the block

**Expected behavior**
CF Bypassed with related cookies showing up.

**Screenshots**
![image](https://user-images.githubusercontent.com/29929026/67578222-e9d8b200-f739-11e9-9758-9f6e783e3c04.png)

**Version**
 - Version 1.1.4 # 344

**Comment by openbullet** [comment]
I will close this issue, please keep track of https://github.com/openbullet/openbullet/issues/435 instead
