### ISSUE TITLE
Parse Get Parameters missing in OpenBullet

### ISSUE THREAD

**Issue by Zero-HL** [openbullet/openbullet#4]
Hello,

Do you think this option should be back on OpenBullet?
For me, I need it.

![Get](https://user-images.githubusercontent.com/49173169/55365352-84df1580-54e4-11e9-9ea7-423c8c3e1ea0.png)

**Comment by MeowBullet** [comment]
If you need it so badly you can commit to the project and add it yourself.

**Comment by openbullet** [comment]
Please let me know if anyone else would like this feature implemented.

**Comment by botboyz67** [comment]
I would like this feature too.

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/157dc84194d020061619c5523281f8d3b972c6b5

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/f88d80f27f92d5a83a0f12829caf305190e006eb
