### ISSUE TITLE
[QUESTİON] Helping for making config

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#402]
hello im try to making my first config today but i cant find user/mail:pass data for test account like asd123:12345 i select every type in here but its not write my writed user pass in website what can i do ?
![image](https://user-images.githubusercontent.com/13446881/68390178-c835ec80-0175-11ea-817b-7c2977acfc64.png)

**Comment by openbullet** [comment]
Credentials

**Comment by openbullet** [comment]
And use your brain

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/68409368-02b08100-0198-11ea-88d2-c55899759d33.png)

**Comment by Teals53** [comment]
no its not write my want data

**Comment by Teals53** [comment]
@openbullet

**Comment by Teals53** [comment]
no reply ? @openbullet

**Comment by openbullet** [comment]
The variables for "Credentials" wordlist type are USERNAME and PASSWORD, not what you wrote. USER and PASS are used by crackers and I do not support them on the official Environment.ini so either mod it yourself or go somewhere else. Also, I am not obliged to reply to you immediately so please do not be rude and do not ping me. I reply when I have time. This is the last warning, next time you will be banned from posting to my repositories.

**Comment by Teals53** [comment]
i am sorry for ping and rude etc but if its not support this option why people need to use this ?

**Comment by openbullet** [comment]
Because they are illegal actors.

**Comment by Teals53** [comment]
yes and i ask for "legal" one for what people need use ob ?

**Comment by openbullet** [comment]
What?
