### ISSUE TITLE
[BUG] ImageTyperz Not working with Recaptcha

### ISSUE THREAD

**Issue by theman480** [openbullet/openbullet#403]
I cant get imagetyperz o decode recaptcha: 

https://prnt.sc/ptt1n7

**Comment by openbullet** [comment]
Have you tried multiple times in different days or just once?

**Comment by theman480** [comment]
> Have you tried multiple times in different days or just once?

About one week trying, with 3 configs.

**Comment by theman480** [comment]
If you need I can lend you my account to try.

**Comment by openbullet** [comment]
PM me on the forum and send it to me there, so I can debug the issue. Thanks. Posting it here will just result in your balance getting drained.

**Comment by theman480** [comment]
I just send you the API key on the forums, thank you Ruri!

**Comment by openbullet** [comment]
Problem confirmed, now I'm trying to figure out if the problem is on their end or in OB.

**Comment by theman480** [comment]
> Problem confirmed, now I'm trying to figure out if the problem is on their end or in OB.

Thank you Ruri, any news about the problem?

**Comment by theman480** [comment]
Hello Ruri, is the problem too bad?

**Comment by openbullet** [comment]
Hey sorry for not responding, I was busy with other stuff. I will try to fix this asap.
