### ISSUE TITLE
[BUG] DOMtoSOURCE not work

### ISSUE THREAD

**Issue by lengocan1231** [openbullet/openbullet#408]
Hi!
**Describe the bug**

I use Selenium to perform some manipulations. I use the DOMtoSOURCE block but I can't get the source of the website. Error as shown below.

https://upanh.vn/image/anh2-2.AIhJV
Thank you.

**Version**
1.1.4

**Comment by openbullet** [comment]
Have you tried setting a bit of a delay before using DOMtoSOURCE? Maybe the page didn't fully load yet. Otherwise, I will investigate. Does it do this on every page or just on a specific one?

**Comment by lengocan1231** [comment]
I add Funtion Delay. Input 5000.
When I navigated page, I can see SOURCE (https://upanh.vn/image/anh1-2.AyzeJ)
But when I click Sign In, I have error.

**Comment by openbullet** [comment]
What do you mean error?

**Comment by lengocan1231** [comment]
Error is I can't get Source after click Sign In. I tried with a longer delay but still couldn't get the source.

**Comment by openbullet** [comment]
Click Sign In
Then put a delay 5000
And then finally put a Dom to Source block.
Did you do them in that order?

**Comment by lengocan1231** [comment]
Yes, I do it.
I tried with delay 10000 or 15000 but still couldn't get the source.

**Comment by Enzo2911** [comment]
Need to add function constante and call <SOURCE>
