### ISSUE TITLE
Spy TheSpy.txt file

### ISSUE THREAD

**Issue by jeanpierre19** [openbullet/openbullet#41]
Hi,
I have an error when I run a runner. I have a SpyTheSpy.txt file that opens with a message "A Debugger has been detected! Please close System.Diagnostics.Process []".
Can you tell me where the problem comes from and how to fix it.

Thank you in advance.

**Comment by ForlaxPy** [comment]
You can't report it here you have to report it here https://github.com/ForlaxPy/openbullet-1.2
And yes ,I fixed it and the update will be launched today so feel free to close this.

**Comment by openbullet** [comment]
This happens on another version (1.2.1) which is NOT made by me, closing
