### ISSUE TITLE
[BUG] Bot Log can't be disabled

### ISSUE THREAD

**Issue by meinname** [openbullet/openbullet#412]
**Describe the bug**
Though Bot Log is disabled in Settings there is a log available on Hits/Custom/ToCheck which includes "The Bot Logging is disabled in General Settings" followed by the Bot Log

**Expected behavior**
No log when disabled.

**Version**
 - Version 1.1.5#370

**Comment by PurityWasHere** [comment]
It seems to only be the Request

**Comment by Paerot** [comment]
I have the same issue, I get the whole source from every request, which can be a lot. If you disable Bot Logging it shouldn't print the whole source.
