### ISSUE TITLE
[BUG] Base64 Decode padding error

### ISSUE THREAD

**Issue by Yommy** [openbullet/openbullet#415]
Functions/Encoding/Encode.cs -> FromBase64()

Currently it is adding too many padding bytes.
If you try to decode `T0I` it should add 1 padding char to make it a block of 4 chars, instead its adding 3. which causes decode error.

to fix.
`if (remainder != 0) toDecode = toDecode.PadRight(toDecode.Length + (4 - remainder), '=');`

Version, latest commit

**Comment by openbullet** [comment]
Hey, that's awesome. Why don't you make a pull request instead so you can both show up as a contributor? Let me know ^_^
