### ISSUE TITLE
CurrentUnixTime[BUG]

### ISSUE THREAD

**Issue by beer15** [openbullet/openbullet#418]
**Describe the bug**
CurrentUnixTime bug

**To Reproduce**
create function CurrentUnixTime

**Expected behavior**
normaly is 1574519805
Now 1574519805,49477

,xxxx ?

**Screenshots**
https://i.gyazo.com/20c11b2b69b42593b7fef3c3d953fbfd.png

**Version**
 - Version [e.g. 1.1.5 last]

**Comment by openbullet** [comment]
Thanks for reporting, fixed https://github.com/openbullet/openbullet/commit/84f39fffdb1c8add90361aba34904e22324c7d62
