### ISSUE TITLE
[REQUEST] SSL Error Ssl Pls upgrade

### ISSUE THREAD

**Issue by OrJiNaL33** [openbullet/openbullet#420]
SSL Error Ssl Pls upgrade
SSL Hata veriyor Bazı Sitelerde

![Adsız](https://user-images.githubusercontent.com/49400023/69564880-db91e600-0fc4-11ea-88db-bba1724159bd.jpg)

**Comment by openbullet** [comment]
Did you just censor the website and then leave it in the white and red text of the log? 🤦‍♂

**Comment by meinname** [comment]
I bet you are on Windows 7 or Server 2008R2 (or older)
Please read here https://forum.openbullet.dev/topic/129/error-unable-to-establish-ssl-connection-with-http-server/15

**Comment by openbullet** [comment]
Closing as the OP is dead or something
