### ISSUE TITLE
[BUG] + [REQUEST] Functions: Variables not possible on integer Values in Function Block

### ISSUE THREAD

**Issue by meinname** [openbullet/openbullet#422]
**Expected behavior**
We should be able to use Variables containing only Digits as Inter Values on Functions

**Screenshots**
https://media.discordapp.net/attachments/536312226445787137/639425657184714752/unknown.png
https://media.discordapp.net/attachments/536312226445787137/648736642802384907/unknown.png
Tried with and without ""

**Version**
 - Version up to current 1.1.5#377

**Comment by openbullet** [comment]
I don't think I can do this without actually converting the Integer to a Literal and hence breaking all previous configs that used it. I can make methods to automatically convert old configs when they get loaded but I fear that will add a lot of confusion and mismatches between different mods, so I'd prefer not to. Anyways this is needed so I will leave this open until I figure out a decent way to approach this.
