### ISSUE TITLE
[REQUEST] proxy switch function

### ISSUE THREAD

**Issue by whynot3k** [openbullet/openbullet#424]
it would be nice to have a function block that just changes the proxy as you only have option for one it picks and one you set manually but sometimes i need it to just get a new proxy randomly for some things that may silent ban and what not

**Comment by Micro-Crackedto** [comment]
You can easily fix this by using a valid account and check for failure keys.
If failure key= silent ban

**Comment by openbullet** [comment]
Can't you just ban so that the data will be retried with a different random proxy?
