### ISSUE TITLE
Add option to choose lower + digit on function randomString

### ISSUE THREAD

**Issue by mayuvuong** [openbullet/openbullet#425]
sometime I need use function guid but it's only on OB Anomaly mod, I can use function randomString instead that one on Anomaly, but I need option that allow me choose lower + digit to do that. Please add this to OB

**Comment by meinname** [comment]
Why do you want lower + digits for guid? A guid consists of hex.
So a valid guid v4 is made like
FUNCTION RandomString "?h?h?h?h?h?h?h?h-?h?h?h?h-4?h?h?h?h-?h?h?h?h-?h?h?h?h?h?h?h?h?h?h?h?h" -> VAR "guid"
