### ISSUE TITLE
[BUG] Process ends up in the middle with an error showing

### ISSUE THREAD

**Issue by bofizim** [openbullet/openbullet#428]
This error never happened while using the initial version, but I'm facing this since version 1.1.4 and it still continues on 1.1.5

while process goes on, it suddenly stops with an error showing that says "The Master Worker has encountered an error: Object reference not set to an instance of an object."

I've tried different configs made by different makers. But it happens for all configs. So I made sure it's not config issue; rather the engine issue.

Usually what I've seen the percentage marker forwards more than the actual percentage. Say for example while the engine completed checking 40% of the list, the marker showing 60% or more. But if the process being stopped and then resumed, it starts from 40% which is actual percentage. There's no certain percetage of when the error will occur. It might happen any time at any percentage; usually when the marker shows more percentage than the actual.

So the problem might be causing for that mismatching between the actual process and marker's process. Expecting a permanent fix on this issue. The error snap has been attached with.

![Untitled](https://user-images.githubusercontent.com/58468884/70046234-d13ca100-15ef-11ea-88ce-6c7e0d59e254.png)

Thanks in advance..

**Comment by openbullet** [comment]
Hello, in this line https://github.com/openbullet/openbullet/blob/master/RuriLib/Runner/RunnerViewModel.cs#L623 can you replace `Error.Message` with `Error.ToString()` so I can see exactly on which line the problem happened? Otherwise I don't have enough information, thanks.

**Comment by openbullet** [comment]
Closing as the OP is dead or something
