### ISSUE TITLE
[REQUEST]Custom Headers In Block Captcha.

### ISSUE THREAD

**Issue by percebal** [openbullet/openbullet#429]
there would be some way to add to the captcha block the possibility of adding custom headers,some sites if you do not send all the headers u get banned and you will not receive the captcha, thanks.

**Comment by Cheetah55** [comment]
yeah, that's happened to me a couple of times.

**Comment by openbullet** [comment]
Use a normal request block (set up the headers and everything you need), choose the option to save the response to file and tick the "save as screenshot" checkbox. Then inside the captcha block simply tick "use saved screenshot".
