### ISSUE TITLE
just sug

### ISSUE THREAD

**Issue by laithalshabi** [openbullet/openbullet#43]
we need some screen for a key code using php mysqli that will be awesome to keep it private for any one that build his own ddos program and thanks u did a rly good job

**Comment by ForlaxPy** [comment]
You can code a login system for that in your own build. The project is already open src ^^.

**Comment by laithalshabi** [comment]
> You can code a login system for that in your own build. The project is already open src ^^.

i not that much in cs XD

**Comment by openbullet** [comment]
Sorry I am not going to do that as it's not in the scope of this project, you can implement it yourself or find someone who will.
