### ISSUE TITLE
[BUG] Hits DB Not Showing Type Custom Record

### ISSUE THREAD

**Issue by ajaysinghrawat777** [openbullet/openbullet#431]
**Describe the bug**
Hits DB Not Showing Type Custom Record

**Expected behavior**
In Old Version of OpenBullet Hits DB showing Type CUSTOM Records But In New Version it's Not Showing

**Version**
 - Version [1.1.5#379]

**Comment by Micro-Crackedto** [comment]
Make sure you are actually using the latest version, since its working on my end.

**Comment by openbullet** [comment]
I think he means you cannot see any custom status that is configured in the Environment.ini file, and you just see CUSTOM for all of them instead of their actual status.

**Comment by Unkn9wn1** [comment]
i had the same issue:
i was using an old version, and it has a customized "Environment.ini"
my key was set on "custom (Expired)" and another key on "custom", and the version that i was using was newer
i stated the bot on new app and selected my config that made on an old ver on ob
i got hits on "custom (Expired)" and on "custom" and "success"
hit's was invisible in Hits DB! except "success" ones

**Comment by ajaysinghrawat777** [comment]
KEYCHECK 
  KEYCHAIN Success OR 
    KEY "<SOURCE>" DoesNotContain "Awaiting 1st payment" 
  KEYCHAIN Custom "FREE" OR 
    KEY "Awaiting 1st payment" 

KEYCHECK 
  KEYCHAIN Custom "EXPIRED" OR 
    KEY "Suspended" 
  KEYCHAIN Success OR 
    KEY "<SOURCE>" DoesNotContain "Suspended"


this is the loli script KEYCHECK Code

Sorry guys due to exam i am not able to read replies.
