### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Abdourealcf** [openbullet/openbullet#432]
in debugger the "USER" and "PASS" dont get parsed and i end up with :
user=%3CUSER%3E&password=%3CPASS%3E
instead of : user=email@email.com&password=pass
image of the problem:
<img src="https://live.staticflickr.com/65535/49175435211_8e5b4a814e_w.jpg" width="400" height="230">
openbullet version: 1.1.5

**Comment by ajaysinghrawat777** [comment]
Just Replace This File In Settings Folder of OpenBullet

[https://anonfile.com/bbzdCcD7n6/Environment_ini](url)

**Comment by Itamai** [comment]
The official version of openbullet doesnt have USER and PASS as Slices. You should check your Environment.ini can be found in your Openbullet->Settings folder.

**Comment by Micro-Crackedto** [comment]
As @Itamai mentioned above, add MAIL:PASS to your Environment.ini
Simply edit and add the following:

`[WLTYPE]
Name=MailPass
Regex=^*.@.*:.*$
Verify=True
Separator=:
Slices=USER,PASS`

Then make sure to add your Email:Pass lists as MailPass and select this as the "Allowed Wordlist Types" under Configs> Other Options> Data

**Comment by Abdourealcf** [comment]
thanks that solved my problem
i didn't know about that as i am new to openbullet
BTW i used as a work around "Credentials" and USERNAME-PASSWORD instead of USER-PASS in post data.
but your suggestion did solve the problem thank you
