### ISSUE TITLE
[BUG]  Cloudflare bypass does not work correctly.

### ISSUE THREAD

**Issue by Spink0704** [openbullet/openbullet#435]
1) Enter the address of the site where there is CloudFlare in "BF BYPASS"

2) Create the same GET request to the same address

3) We get such an answer.

![1](https://user-images.githubusercontent.com/35750488/70388753-a3c07080-19be-11ea-84c4-6c15a90e71a0.PNG)
![2](https://user-images.githubusercontent.com/35750488/70388754-a3c07080-19be-11ea-8253-55c52d968beb.PNG)
![3](https://user-images.githubusercontent.com/35750488/70388755-a3c07080-19be-11ea-8cd1-1181570b9e81.PNG)

or 

![4](https://user-images.githubusercontent.com/35750488/70388780-ea15cf80-19be-11ea-81ae-23db53ed0203.PNG)

user-agent is the same everywhere.

I tried simple GET requests to check the performance on many sites where there is CloudFlare .. everywhere the same ..

**Comment by openbullet** [comment]
The CF bypass needs to be rewritten manually, the libraries always have issues apparently. I don't have time to do that so I don't know when this will happen.

**Comment by GunnGrave** [comment]
cf already sent an update to web sites
now it is performing a POST request to redirect to main page after solving the js

so the actual lib is down 100%

**Comment by willywilly12345** [comment]
Went here to ask the same question...

**Comment by mastercho** [comment]
lib author said wont update it anymore

**Comment by openbullet** [comment]
I reimplemented the old cloudflare on this branch https://github.com/openbullet/openbullet/tree/cloudflare but it doesn't work on multithreading so posted an issue here https://github.com/RyuzakiH/CloudflareSolverRe/issues/15 let's wait for his reply.

**Comment by mastercho** [comment]
> @openbullet will be still http only proxy after the issue been solved?  

I did chat with leaf.xnet dev he wants 40$ for CF update and said will do it after 6th Jan so RIP

**Comment by Paerot** [comment]
any update/news on the issue

**Comment by openbullet** [comment]
@Paerot are you on 1.2.0? The cloudflare bypass should work in most cases, if it doesn't please post the website that's giving you trouble and i'll take a look at it.

**Comment by mastercho** [comment]
> any update/news on the issue

If you try using xevil for 2cap in CF bypass on 1.2.0 won't work. You need a real account until this issue is fixed

**Comment by openbullet** [comment]
Actually XEvil and CapMonster are working correctly if you use CustomTwoCap and specify the ip and port correctly
