### ISSUE TITLE
Hi Dear Ruri

### ISSUE THREAD

**Issue by navidevangel** [openbullet/openbullet#436]
if possible please add <select> options for element on selenium in ob

**Comment by openbullet** [comment]
What do you mean? You want to be able to select a certain option from a `<select>` element? If that's the case, yes I can do it.

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/83408a9f72b5e2abbfa8e496e22c07d2be17a1af
Will merge into master soon
