### ISSUE TITLE
What is the sqlite db default password?

### ISSUE THREAD

**Issue by DevonStout** [openbullet/openbullet#438]
The database file has grown too big and it keeps crashing Openbullet. 
I've removed it from the folder and it created a new one. 
I need the password to recover the hits from it.
Does it use the same password or is it randomly generated?
Thank you in advance.

**Comment by meinname** [comment]
There is no password - and it's not sqlite. (maybe that's why your sqlite tool is asking for a password)
It's LiteDB - read more about it here https://openbullet.github.io/usage.html#database

**Comment by DevonStout** [comment]
@meinname I see. Thank you
