### ISSUE TITLE
[REQUEST]content lenght in keycheck

### ISSUE THREAD

**Issue by simonrule** [openbullet/openbullet#439]
Hi Ruri
could you please add conent-lenght to keycheck its really usefull sometimes we need to use it on complex configs

**Comment by openbullet** [comment]
It's just a normal header so `<HEADERS(Content-Length)>` will give you what you need.

**Comment by unmonstre2018** [comment]
Hello, how to get (in the "Parse" section) : 

--> the content length of POST DATA send by openbullet in request

please thanks you
