### ISSUE TITLE
TCP SendKeys Not Working

### ISSUE THREAD

**Issue by styles977** [openbullet/openbullet#44]
When I send TCP Keys Bot's Just keeps on waiting ... am I doing right ?
http://prntscr.com/n8mac0
I tried on many sites ... same issue ..

**Comment by openbullet** [comment]
You have to write \r\n at the end of your message or it will not understand the message text is over! Tell me if it works

**Comment by openbullet** [comment]
I tried that with the IMAP protocol and it worked like a charm ^_^

**Comment by styles977** [comment]
@openbullet  Thanks it works. http://prntscr.com/n8mcv1
Now Just waiting for you to fix List[] type database capture error and goona compile again 
thankyou man :D

**Comment by openbullet** [comment]
Alright sure, I'm going to close this issue, I will solve the other one now ^_^
