### ISSUE TITLE
[REQUEST] Save Capture to File, without Writing Data to DB

### ISSUE THREAD

**Issue by GunnGrave** [openbullet/openbullet#441]
Hello,

sometimes when am running some checker (check Mail / User if it exists)

i noticed that OB is writing many lines to DB

so i was thinking to save everything in a .txt file
but the thing is:
* when i put success key so i can keep track of the number good checks, still OB will write the Data part to DB
* when i remove the success key, everything will go toCheck. still writing to DB

so i did write a loliscript

KEYCHECK BanOnToCheck=FALSE 
  KEYCHAIN Failure OR 
    KEY "failure key x" 
  // removed the sk from here

IF "SOURCE" Contains "success key x"
UTILITY File "store.txt" AppendLines "USER:PASS" -> VAR "Save" 
SET STATUS FAIL
ENDIF

so with this, OB is not writing to DB anymore
BUT (the request part) i cant keep track of the number of the success checks

so if there is already a better way, please let me know
if not i would be so happy to see a new function in KEY CHECK that only saves in a file

thanks for reading
best regards

**Comment by openbullet** [comment]
Hello. Can't you just rename your main database and just let OB create a new one when you want to perform this kind of jobs? Then you can just delete the database when you're done and rename back your main DB.

**Comment by GunnGrave** [comment]
it would be easy to delete if am using OB for 1 site.
but i am running 2 or 3 + 1 as an EMAIL checker

anyway, this very low prio when it comes to CF or COOKIES Dict ...

**Comment by openbullet** [comment]
Yeah exactly it's low priority

**Comment by insanebeeftw** [comment]
I am doing it in this way, it worked! Please check the following code:

KEYCHECK BanOnToCheck=FALSE 
  KEYCHAIN Success OR 
    KEY "<DATA>" Exists 
IF "<STATUS>" EqualTo "SUCCESS"
#Write_to_File UTILITY File "Hits\\MyHits.txt" AppendLines "<DATA>" -> VAR "Output" 
SET STATUS FAIL
ENDIF

**Comment by Unkn9wn1** [comment]
@openbullet 
I think it's not low prio
a good solutions for this problem is adding a new parameter for CustomKC in Environment.ini to save the Custom Hit to DB
example :
![image](https://user-images.githubusercontent.com/41063376/76613797-16983500-6534-11ea-8f2f-33257e28f80a.png)
Default = True
Type = Boolean
If parameter was not exist, then Option is = True (it's good if user copied old Environment.ini in new ver of OB)

**Comment by GunnGrave** [comment]
@openbullet hello
i was wondering if you can re consider adding a thing for this in 1.2.2 after you are done with captchas APIs
"write hits to a file and keeping track on the numbers of hits
and without writing to DB

**Comment by GunnGrave** [comment]
I will close this one, as it is already solved
thank you
