### ISSUE TITLE
[BUG] Auth proxies does not work in proxy checker.

### ISSUE THREAD

**Issue by dNitro** [openbullet/openbullet#442]
**Describe the bug**
When using proxies with Auth ( i.e. `1.1.1.1:80:username:password` ) in the proxy checker, all go to **Not Working** while the same proxies work in Runner.

**Expected behavior**
Expect Auth proxies to also work in proxy checker so they could be checked before using.

**Version**
 - Version 1.1.5#379

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/107fbb1ce54f827c290159353c7e74fc61395e02
Please reopen if it doesn't work

**Comment by dNitro** [comment]
Thanx, it works.
