### ISSUE TITLE
[BUG] UTILITY List Concat - Missing input box

### ISSUE THREAD

**Issue by GunnGrave** [openbullet/openbullet#444]
Hello,

The function UTILITY List Concat loliscript is fine
UTILITY List "names1" Concat "names2" -> VAR "new"

but if you are setting it up in the UI, you notice that the input box is missing
<img width="1011" alt="Screen Shot 2019-12-16 at 3 10 51 AM" src="https://user-images.githubusercontent.com/58314941/70874260-ae2bcd00-1fb1-11ea-81c4-74a7230e11ff.png">

* missing tab for the name of the concated list

**Comment by openbullet** [comment]
Fixed on dev
