### ISSUE TITLE
Del Dupes Button in Hits DB

### ISSUE THREAD

**Issue by shdf2** [openbullet/openbullet#45]
The "Del Dupes" Button in Hits DB doesn't seem to work.

**Comment by openbullet** [comment]
Could you please provide an example to backup your claim? Thank you.

**Comment by meinname** [comment]
Tried it.
Dupe gets removed from Database - but GUI is not updated.

**Comment by openbullet** [comment]
Alright thanks mein, I will get around to fixing it soon.

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/1aff26e3c850368e0d880ccc95f6d9041ec6bbee
