### ISSUE TITLE
[REQUEST] JavaScript variable to Capture

### ISSUE THREAD

**Issue by NCBPFluffyBear** [openbullet/openbullet#450]
It would be extremely useful if I could convert a JS variable to Capture. I am writing this variable by getting an element's text using Selenium.

I have tried using LoliScript without success.

**Comment by openbullet** [comment]
This was implemented here https://github.com/openbullet/openbullet/commit/098df27c4f7a424f8ecbbbe7254f5ee9b7a6e54a
