### ISSUE TITLE
[REQUEST] Improve Element Action

### ISSUE THREAD

**Issue by NCBPFluffyBear** [openbullet/openbullet#451]
Currently, the Class and GetText options under Element Action function find their targets in unconventional ways. Therefore, I propose these changes:

1) Improve (or add a new option) to the "Find Element by `Class`" to reflect JavaScript's `document.getElementsByClassName():`

2) Add an action to return the `value` field of an element, rather than the innerHTML

I hope these two features will be implemented soon!

**Comment by openbullet** [comment]
I am using the selenium api exactly how it is, so for number 1 I cannot help you. For number 2 you can use GetAttribute instead of get text, and in the input field you can type the name of the attribute, `value` in this case. Reopen if it doesn't work.
