### ISSUE TITLE
[BUG] SolveRecaptcha

### ISSUE THREAD

**Issue by johnsmith1232541** [openbullet/openbullet#455]
**Before you begin**
I'm trying to test SolveRecaptcha with my config. 
It works perfectly if I use TwoCaptcha by just plugging in my api key.
However, I switched to SolveRecaptcha due to the unlimited requests for a monthly fee but it doesn't work. Check balance gives me 999 (as expected) after putting the correct userid and key.
However, the config stopped working. On the SolveRecaptcha console I see requests coming in and I see many of them marked as "Solved" so it is solving them but Openbullet doesn't come back with "success". 
I tried checking for logs but I'm not being able to get the failure logs. What I know is that if I switch back to TwoCaptcha it works perfectly but not in SolveRecaptcha despite both services receiving the captcha and solving them. Maybe it's not reading the data back from solverecaptcha correctly?

**Version**
 - Version 1.1.5

**Comment by openbullet** [comment]
I will try to check as soon as possible as long as I still have a working key.

**Comment by r00tee** [comment]
Even I have the same problem
I hope to solve it in the next release
If you need user id and api key just contact me

**Comment by openbullet** [comment]
@r00tee send it to me on the forum via pm thanks

**Comment by r00tee** [comment]
> @r00tee send it to me on the forum via pm thanks

Done check your messages  🙂

**Comment by openbullet** [comment]
SolveReCaptcha support will be removed from OpenBullet starting from v1.2.1 as the site barely ever works and it looks like a big scam.
