### ISSUE TITLE
[REQUEST] Prioritise proxies

### ISSUE THREAD

**Issue by kost123** [openbullet/openbullet#457]
Is it possible to implement a feature where it prioritises the fastest proxies? 

It should check over all proxies 1-3 times, get the average speed of each one, then use the fastest proxies until they die out/get banned and continue to use the others in order. A bonus would be if it took into account how many retries it was generating and going for the least retried, not sure how that would work.

Close if already implemented.

**Comment by openbullet** [comment]
Sorry this is not something OpenBullet should do, seek a good proxy checker instead.
