### ISSUE TITLE
[REQUEST] add new bypass captcha site 1captchas

### ISSUE THREAD

**Issue by amrmostafa800** [openbullet/openbullet#459]
please add new bypass captcha site
name : 1captchas
url : http://1captchas.com/
api : http://1captchas.com/apiintegration.html
and thanks

**Comment by openbullet** [comment]
Hi, I want to work on this feature but I need an account with positive balance to see if it's working. Are you able to provide that to me via PM on the OB forum?

**Comment by amrmostafa800** [comment]
> Hi, I want to work on this feature but I need an account with positive balance to see if it's working. Are you able to provide that to me via PM on the OB forum?

ok when i get account i will send it to you

**Comment by amrmostafa800** [comment]
> Hi, I want to work on this feature but I need an account with positive balance to see if it's working. Are you able to provide that to me via PM on the OB forum?

ok i get one i will send it in openbullet forum

**Comment by openbullet** [comment]
This can be implemented through CustomTwoCaptcha in latest OB
