### ISSUE TITLE
Proxy Overiding

### ISSUE THREAD

**Issue by styles977** [openbullet/openbullet#46]
Is it Possible to Dominate current proxy with new one?  .. I tried  but it fails.
Please take a look 
http://prntscr.com/n8p2pa

When I comment it out
http://prntscr.com/n8p5sz 

I want' to override other HTTP proxy with my own local proxy i.e "127.0.0.1:8888" when necessary
but it always get's an error. Is this possible? :3 

Sorry for posting too much stupid issues .. lol forgive me.

**Comment by openbullet** [comment]
Are you sure that local port is open on your machine? Can you try to do the same with like a free proxy from the internet to see if those commands work? Thanks.

**Comment by styles977** [comment]
The command works for the free proxy. But I couldn't connect to my own machine ...
I did this also https://www.windowscentral.com/how-open-port-windows-firewall 

but It do works when I open fiddler and configure it to listen on port 8888.
I guess I couldn't configure my windows machine ... :3

also I try to delete proxy by adding following command ..
DELETE VAR "<PROXY>"
and this happens 
http://prntscr.com/n8uqtj

I just want the OB script to connect the site without proxy > when sucesskey found >then connect the proxy through OB proxy database.

Enable Proxy on config but not using it..
when Success key found then using it ... That way.

**Comment by openbullet** [comment]
Yes I understood your issue, I was just trying to make you debug it a bit for me but I'll do it no worries ^_^

**Comment by styles977** [comment]
thank you so so much ... respect /\

**Comment by meinname** [comment]
I was asked to test.
Works for me:
![image](https://user-images.githubusercontent.com/16181408/56963821-2a27f080-6b5a-11e9-8053-63d330614782.png)

(the local proxy is GSA Proxy Scraper which forwards to some random proxy :)
<img width="429" alt="image" src="https://user-images.githubusercontent.com/16181408/56963887-4f1c6380-6b5a-11e9-9328-0c2d5318aacb.png">

**Comment by openbullet** [comment]
Also I implemented what you asked https://github.com/openbullet/openbullet/commit/13767e4b6ba999cca887bbd76abb65333ae1bbed
