### ISSUE TITLE
[REQUEST] ignore Sourceless response checkbox

### ISSUE THREAD

**Issue by Abdourealcf** [openbullet/openbullet#460]
i am trying a config for an IPTV website as follow:
i request m3u file then i parse 1st link in the m3u file for a channel i am 99.99% sure its a working link
then to check if account is working i have to request the channel link but since the response is a video file it have no source so the debugger ends up with an error regardless if account is working or not and don't execute the "KEY CHECK" block
since i am not interested in the source i need only the response code if account is working i have 200 if not its a 302
i am requesting a checkbox inside REQUEST bloc "ignore sourceless response" or something like that
**_Working Account image:_**
<img src="https://live.staticflickr.com/65535/49353321217_d2ddf18639_o.png" />
**_Not working account image:_**
<img src="https://live.staticflickr.com/65535/49353322167_d327e7bcc2_o.png" />
thank you

**Comment by openbullet** [comment]
I'm pretty sure this exception is coming from Extreme.NET, not OB itself. Anyways, copy paste the issue on my Extreme.NET fork, and you could try to go to Config Other Settings -> Requests and tick the ignore all errors while you wait for me to fix the issue.

**Comment by Abdourealcf** [comment]
thanks for your response
1- sorry i don't know how to"copy paste the issue on my Extreme.NET fork"
2- " you could try to go to Config Other Settings -> Requests and tick the ignore all errors" i already ticked it and the problem is not solved
BTW i tried all option in settings without any luck always the same error that's why i requested a new option to ignore this error
<img src="https://live.staticflickr.com/65535/49357841372_f350b63253_o.png" />

**Comment by openbullet** [comment]
1 - You're perfectly right, issues are disabled by default on forked repos. I activated them now https://github.com/openbullet/Extreme.Net/issues
Go open it there

**Comment by Abdourealcf** [comment]
thank you the issues tab is now activated
i copied it in there, hope you get some time to solve it soon
keep up the good work
love you and love OB best user friendly  cracking software ever

**Comment by Wanted135** [comment]
this is not a cracking softaware, it is for testing purposes

**Comment by Abdourealcf** [comment]
> this is not a cracking softaware, it is for testing purposes
> […](#)
i know may bad
