### ISSUE TITLE
[REQUEST] Random Pool

### ISSUE THREAD

**Issue by Unkn9wn1** [openbullet/openbullet#462]
Hi,
please add ability to make a list in functions, and the bot/thread when started, selects a random line of list as the variable
thanks for this great project ❤

**Comment by openbullet** [comment]
Could you elaborate please?

**Comment by Unkn9wn1** [comment]
for example, i have a list of specified User-Agents
i add a funtion block and set variable as "RaniPhoneUA"
i add my list of specified User-Agents in function's input Like this:

Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A403 Safari/602.1
Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_1 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.86 Mobile/14A403 Safari/601.1.46
Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1
Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/13G36 Safari/601.1.46
Mozilla/5.0 (iPhone; CPU iPhone OS 10_1_1 like Mac OS X) AppleWebKit/602.2.14 (KHTML, like Gecko) Mobile/14B100

now i add the variable in Request block
User-Agent: <RaniPhoneUA>

and i wanna OB chose one of my 5 line random for every bot each time

it was just an example, it's also useful for many other situations, can make config proxyless in case that target has many IPs/Hosts with same api! can use to send random specified answers to fill CVs

**Comment by openbullet** [comment]
Okay I will add a UTILITY List functionality that will take a random element from a list.

**Comment by openbullet** [comment]
Hey, I just checked and the functionality is already there man! Utility Block -> List -> Random ^_^ so just make a list variable with those values and then add the block that I just mentioned, done.
