### ISSUE TITLE
[BUG] Character Encoding Detection

### ISSUE THREAD

**Issue by Unkn9wn1** [openbullet/openbullet#463]
i have a strange target
language of target website is "Arabic/Persian"
encoding is OK when i use GET method
but when i use POST method, the target response is unreadable because of wrong encoding, and also when i added my keys in "Key Check" as correct and also as non-correct encoding chars, OpenBullet was not able to match my keys.
the website is OK in Firefox and Chrome browsers, but the problem is only in OpenBullet
i think it's because OpenBullet don't have feature like "Compact Encoding Detection" that is available in chrome...
https://github.com/google/compact_enc_det
Please add ability to change default encoding in settings or config
thank you

**Comment by openbullet** [comment]
OpenBullet encodes as UTF-8 not Unicode, that's the problem. Please consider using the UTILITY Conversion functions.

**Comment by openbullet** [comment]
Can I close this issue? Does it work when you use the utility block?

**Comment by Unkn9wn1** [comment]
Yeah, it's ok
Thank You 👍

**Comment by Unkn9wn1** [comment]
Yes, thank you 👍

**Comment by Unkn9wn1** [comment]
Actually, problem was not solved and i did not worked on that target anymore
i was needed function to encode `<SOURCE>` to `Windows-1256 Arabic (1256)`
J Like this:
https://gchq.github.io/CyberChef/#recipe=Encode_text('Windows-1256%20Arabic%20(1256)')&input=2LfCs9i44oCe2LfCp9i44oCmINi3wq/YuMuG2LfCs9i32r4g2LfCudi3wrLYuNm52LfCsg

my target updated and problem solved but i said this all, maybe you add this function
sorry for close and reopening this issue

**Comment by openbullet** [comment]
Can you post a site that sends some arabic things that OB is failing to parse?

**Comment by Unkn9wn1** [comment]
no, my target updated.

**Comment by openbullet** [comment]
Then I'm closing the issue until the problem appears again, since I have no way to replicate and fix this currently.
