### ISSUE TITLE
[REQUEST] Number of Hits in Types List

### ISSUE THREAD

**Issue by Unkn9wn1** [openbullet/openbullet#465]
Hello,
it's good to see number of hits after type name in types list
specially when we add our custom types...
like this 😁👇
![image](https://user-images.githubusercontent.com/41063376/72517304-6629ef80-3868-11ea-8189-c6110427f0b9.png)

and it's also good if you add all hit's number of a config after it's name in config list of "Hits DB" section

**Comment by openbullet** [comment]
The number is already shown on the top right after you click on it. Sorry I will not do this.
