### ISSUE TITLE
[BUG] "Parse" via "Automatic Mode" Makes config corrupt!

### ISSUE THREAD

**Issue by Unkn9wn1** [openbullet/openbullet#466]
![image](https://user-images.githubusercontent.com/41063376/72555059-1d4a5900-38b1-11ea-8557-2b3e5d8a8634.png)
Hi bro,
when i use "Automatic Mode" in "PARSE" block
it does not change line breaks to \n or \r\n or everything it should be :\
and make config break!!

**Comment by openbullet** [comment]
Thanks for reporting.

**Comment by openbullet** [comment]
I will address this issue together with https://github.com/openbullet/openbullet/issues/480 so I'm closing this one.
