### ISSUE TITLE
[REQUEST] More Advanced Proxies "Del. Duplicates"

### ISSUE THREAD

**Issue by Unkn9wn1** [openbullet/openbullet#469]
![image](https://user-images.githubusercontent.com/41063376/72615596-5b478b80-394a-11ea-8084-ff6eff0d3e89.png)

Some premium proxy services have an IP with multiple PORTS
They are OK and should not removed when deduplicating
But when using public proxy lists, we have to remove this proxies [one ip and many ports!]
it would be good if OB ask it when deduplicating

**Comment by openbullet** [comment]
But how should it know which port to keep and which to remove?

**Comment by Unkn9wn1** [comment]
if they are tested before, just keep one of them and remove another ones!
not matter when all of the ports is open and also working

but if they are not tested proxies, check for priority
Set Default ports on top
3128 for HTTP/S Proxies
1080 for Socks Lists

also i sorted my tested public proxy list's ports by most occurrence
and here is results 👇

My Working Public HTTP Proxy List Results :

Occurrence Count | PORT
-----------------------------------------------------
3909 | 9999
2973 | 8080
850 | 80
737 | 3128 [Default PORT]
304 | 53281
181 | 8118
147 | 8888
122 | 1080
117 | 9000
100 | 83
78 | 8081
77 | 8060
75 | 8000
74 | 23500
73 | 999
69 | 8213
65 | 84
60 | 82
57 | 3000
54 | 61234
54 | 808
47 | 6666
43 | 3129
41 | 8090
36 | 41258
34 | 443
30 | 9090
28 | 20183
27 | 81
25 | 33729
25 | 9991
22 | 8811
19 | 3130
19 | 8082
16 | 48678
14 | 51618
14 | 8085
13 | 35116
13 | 8083
13 | 9797
12 | 35101
12 | 37647
12 | 40049
12 | 44581
12 | 63141
12 | 8123
12 | 87
11 | 4433
10 | 55443
9 | 41288
9 | 8181
8 | 39484
8 | 58732
7 | 10000
7 | 25
7 | 8088
6 | 21231
6 | 31281
6 | 43399
6 | 47424
6 | 56975
6 | 65301
6 | 7070
5 | 16538
5 | 40768
5 | 41353
5 | 45612
5 | 49833
5 | 54419
5 | 65309
5 | 666
5 | 8010
5 | 8111
4 | 3131
4 | 32192
4 | 36127
4 | 39850
4 | 44331
4 | 44759
4 | 4624
4 | 47150
4 | 49509
4 | 52581
4 | 52821
4 | 53100
4 | 60446
4 | 8001
4 | 8091
4 | 8113
3 | 10080
3 | 31094
3 | 31280
3 | 32231
3 | 3282
3 | 33446
3 | 35258
3 | 35432
3 | 35704
3 | 36555
3 | 37188
3 | 40052
3 | 41049
3 | 41310
3 | 41454
3 | 41787
3 | 43037
3 | 4550
3 | 46696
3 | 51062
3 | 51393
3 | 51811
3 | 53557
3 | 53905
3 | 54754
3 | 55184
3 | 55207
3 | 57804
3 | 58080
3 | 58302
3 | 58461
3 | 63000
3 | 8086
3 | 8089
3 | 8116
3 | 8380
3 | 88
3 | 9001
3 | 9006

My Working Public SOCKS4 Proxy List Results :

Occurrence Count | PORT
-----------------------------------------------------
4546 | 4145
646 | 1080
162 | 4153
100 | 44550
83 | 3629
81 | 10801
75 | 8291
66 | 54321
63 | 11337
60 | 51327
60 | 64312
58 | 1085
55 | 39593
50 | 42647
45 | 50489
44 | 31337
44 | 6667
42 | 59341
39 | 1081
39 | 9050
38 | 9999
29 | 51372
28 | 59311
27 | 32525
27 | 44178
22 | 63253
19 | 31094
19 | 44252
19 | 52106
19 | 58338
18 | 39867
17 | 51080
16 | 57669
15 | 14888
14 | 32100
14 | 57386
14 | 58294
13 | 1827
13 | 31110
13 | 37498
13 | 41610
13 | 42063
13 | 45357
13 | 50916
12 | 13629
12 | 38051
12 | 41180
11 | 31596
11 | 38392
11 | 443
11 | 55243
10 | 31618
10 | 32789
10 | 55492
10 | 58526
10 | 61221
9 | 21675
9 | 38120
9 | 45823
9 | 55170
9 | 60030
9 | 8080
8 | 13818
8 | 14153
8 | 30622
8 | 33555
8 | 34292
8 | 36331
8 | 37118
8 | 38293
8 | 44642
8 | 48800
8 | 52658
8 | 52871
7 | 26441
7 | 39072
7 | 39825
7 | 4328
7 | 58351
7 | 61283
6 | 3129
6 | 32851
6 | 33633
6 | 34305
6 | 37630
6 | 37640
6 | 37723
6 | 39457
6 | 39856
6 | 39921
6 | 42144
6 | 42584
6 | 45827
6 | 50612
6 | 51521
6 | 52036
6 | 53709
6 | 53900
6 | 55774
6 | 58865
6 | 60909
6 | 8888
5 | 30110
5 | 30211
5 | 31008
5 | 32571
5 | 33840
5 | 35603
5 | 36342
5 | 3887
5 | 39163
5 | 39651
5 | 40543
5 | 41228
5 | 41448
5 | 41539
5 | 43110
5 | 43870
5 | 44053
5 | 48324
5 | 50283
5 | 51314
5 | 51693
5 | 52264
5 | 55156
5 | 56731
5 | 57408
5 | 59598
5 | 60861
5 | 61601
4 | 30225
4 | 31164
4 | 31248
4 | 31576
4 | 33296
4 | 34432
4 | 35053
4 | 35488
4 | 35683
4 | 35856
4 | 36073
4 | 38717
4 | 38973
4 | 39172
4 | 39477
4 | 40241
4 | 40274
4 | 41903
4 | 42204
4 | 42891
4 | 42909
4 | 44328
4 | 45764
4 | 46067
4 | 46440
4 | 47205
4 | 49232
4 | 49420
4 | 52015
4 | 53529
4 | 53718
4 | 54194
4 | 54631
4 | 55394
4 | 56636
4 | 57596
4 | 58395
4 | 58431
4 | 58555
4 | 59624
4 | 60419
4 | 61117
4 | 61231
4 | 61287
4 | 61885
3 | 1337
3 | 30669
3 | 31246
3 | 31433
3 | 31523
3 | 31680
3 | 31886
3 | 32251
3 | 32279
3 | 33032
3 | 33283
3 | 33620
3 | 33913
3 | 34047
3 | 34079
3 | 34763
3 | 35329
3 | 35350
3 | 35729
3 | 35805
3 | 35944
3 | 3636
3 | 36926
3 | 36934
3 | 38211
3 | 38240
3 | 38313
3 | 38316
3 | 39037
3 | 39618
3 | 39787
3 | 41346
3 | 41815
3 | 42608
3 | 43020
3 | 43393
3 | 43928
3 | 44193
3 | 45120
3 | 45587
3 | 46056
3 | 46280
3 | 46987
3 | 47930
3 | 48079
3 | 48258
3 | 48458
3 | 49218
3 | 50860
3 | 51178
3 | 52109
3 | 52522
3 | 52753
3 | 52829
3 | 52851
3 | 54913
3 | 55226
3 | 55749
3 | 56184
3 | 56921
3 | 58401
3 | 58888
3 | 59157
3 | 59533
3 | 60789
3 | 60837
3 | 61437
3 | 7663
2 | 10000
2 | 10368
2 | 1099
2 | 11100
2 | 13108
2 | 13222
2 | 22432
2 | 30022
2 | 30048
2 | 30161
2 | 30248
2 | 30448
2 | 30643
2 | 30740
2 | 30913
2 | 31063
2 | 31127
2 | 31210
2 | 31220
2 | 3128
2 | 31429
2 | 31622
2 | 31699
2 | 31841
2 | 31976
2 | 32075
2 | 32226
2 | 32241
2 | 32688
2 | 32720
2 | 32865
2 | 32918
2 | 33012
2 | 33020
2 | 33145
2 | 33150
2 | 33201
2 | 33367
2 | 33413
2 | 33638
2 | 33662
2 | 33882
2 | 34040
2 | 34126
2 | 34146
2 | 34244
2 | 34285
2 | 34413
2 | 34686
2 | 34715
2 | 34746
2 | 35270
2 | 35294
2 | 35313
2 | 35502
2 | 35618
2 | 35914
2 | 35933
2 | 36177
2 | 36185
2 | 36228
2 | 36390
2 | 36496
2 | 36732
2 | 36932
2 | 37266
2 | 37983
2 | 38077
2 | 38123
2 | 38124
2 | 38145
2 | 38174
2 | 38247
2 | 38369
2 | 38375
2 | 38433
2 | 38590
2 | 38603
2 | 38629
2 | 38902
2 | 39222
2 | 39446
2 | 39475
2 | 39509
2 | 39688
2 | 39835
2 | 40021
2 | 40037
2 | 40040
2 | 40050
2 | 40094
2 | 40128
2 | 40156
2 | 40157
2 | 40167
2 | 40243
2 | 40247
2 | 40367
2 | 40411
2 | 40540
2 | 40559
2 | 40627
2 | 40679
2 | 4078
2 | 40795
2 | 40901
2 | 41123
2 | 41151
2 | 41156
2 | 41283
2 | 41517
2 | 41541
2 | 41542
2 | 41599
2 | 41600
2 | 41705
2 | 41773
2 | 41970
2 | 42055
2 | 42097
2 | 42187
2 | 42310
2 | 42369
2 | 42649
2 | 42728
2 | 42801
2 | 42810
2 | 42886
2 | 42981
2 | 43494
2 | 43573
2 | 43907
2 | 43908
2 | 44023
2 | 44032
2 | 44087
2 | 44293
2 | 44347
2 | 44436
2 | 44452
2 | 44611
2 | 44675
2 | 44953
2 | 45058
2 | 45128
2 | 45233
2 | 45256
2 | 45307
2 | 45444
2 | 45506
2 | 45529
2 | 46038
2 | 46240
2 | 46659
2 | 46846
2 | 47512
2 | 47747
2 | 48039
2 | 48164
2 | 48282
2 | 48309
2 | 48644
2 | 48680
2 | 48759
2 | 49082
2 | 49139
2 | 49163
2 | 49255
2 | 49271
2 | 49379
2 | 49393
2 | 49429
2 | 49765
2 | 49882
2 | 49919
2 | 49997
2 | 50152
2 | 50387
2 | 50523
2 | 50843
2 | 50892
2 | 51101
2 | 51122
2 | 51229
2 | 51436
2 | 51525
2 | 51565
2 | 51688
2 | 51692
2 | 51754
2 | 51776
2 | 51870
2 | 52425
2 | 52435
2 | 52825
2 | 52941
2 | 53118
2 | 53243
2 | 53285
2 | 53562
2 | 53826
2 | 53832
2 | 53858
2 | 53956
2 | 54012
2 | 54066
2 | 54163
2 | 5430
2 | 54344
2 | 54744
2 | 54845
2 | 54931
2 | 55113
2 | 55290
2 | 55317
2 | 55359
2 | 55395
2 | 55710
2 | 55731
2 | 55796
2 | 55873
2 | 55919
2 | 55967
2 | 55975
2 | 56093
2 | 56142
2 | 56212
2 | 56264
2 | 56457
2 | 56536
2 | 56594
2 | 56600
2 | 56646
2 | 57010
2 | 57031
2 | 57124
2 | 57230
2 | 57335
2 | 57553
2 | 58063
2 | 58275
2 | 58350
2 | 58405
2 | 58563
2 | 58918
2 | 59235
2 | 59247
2 | 59272
2 | 59284
2 | 59365
2 | 59418
2 | 59534
2 | 60113
2 | 60120
2 | 60489
2 | 60616
2 | 60988
2 | 61352
2 | 61401
2 | 61436
2 | 61910
2 | 80
2 | 8082
2 | 8083
2 | 8841
2 | 9060

My Working Public SOCKS5 Proxy List Results :

Occurrence Count | PORT
-----------------------------------------------------
84 | 1080
55 | 8080
55 | 9999
42 | 9050
33 | 6667
18 | 1081
9 | 21675
8 | 13818
8 | 34292
8 | 4145
7 | 55317
7 | 7302
6 | 8888
4 | 11100
4 | 3887
4 | 4328
4 | 9060
3 | 10000
3 | 3129
3 | 45128
3 | 47512
3 | 53281
3 | 61078
3 | 61117
3 | 64699
2 | 10368
2 | 13108
2 | 13156
2 | 13222
2 | 1337
2 | 26441
2 | 28363
2 | 33032
2 | 34724
2 | 36177
2 | 4078
2 | 41970
2 | 49373
2 | 49401
2 | 49443
2 | 49545
2 | 49567
2 | 49595
2 | 49821
2 | 50005
2 | 50009
2 | 50017
2 | 50079
2 | 50112
2 | 50117
2 | 50181
2 | 50223
2 | 50225
2 | 50475
2 | 50483
2 | 50527
2 | 50531
2 | 50536
2 | 50745
2 | 50841
2 | 50880
2 | 50932
2 | 51050
2 | 51071
2 | 51138
2 | 51193
2 | 51200
2 | 51347
2 | 51479
2 | 51497
2 | 51532
2 | 51716
2 | 52048
2 | 52106
2 | 52357
2 | 52373
2 | 52391
2 | 52393
2 | 52517
2 | 52533
2 | 52559
2 | 52571
2 | 52599
2 | 52613
2 | 52619
2 | 52675
2 | 52803
2 | 52855
2 | 52873
2 | 52919
2 | 52935
2 | 52941
2 | 52947
2 | 52949
2 | 52985
2 | 53007
2 | 53015
2 | 53057
2 | 53065
2 | 53103
2 | 53175
2 | 53177
2 | 53265
2 | 53421
2 | 53525
2 | 53551
2 | 53696
2 | 53700
2 | 53791
2 | 53815
2 | 53953
2 | 54009
2 | 54039
2 | 54122
2 | 54180
2 | 54237
2 | 54620
2 | 54724
2 | 54796
2 | 54810
2 | 54886
2 | 54932
2 | 55112
2 | 55295
2 | 55363
2 | 55365
2 | 55387
2 | 55399
2 | 55409
2 | 55446
2 | 55491
2 | 55625
2 | 55645
2 | 55733
2 | 55761
2 | 55789
2 | 55796
2 | 55799
2 | 55924
2 | 55958
2 | 56022
2 | 56028
2 | 56077
2 | 56102
2 | 56128
2 | 56272
2 | 56423
2 | 56442
2 | 56486
2 | 56489
2 | 56493
2 | 56796
2 | 56800
2 | 56880
2 | 56899
2 | 56915
2 | 56945
2 | 56985
2 | 56990
2 | 57003
2 | 57031
2 | 57042
2 | 57049
2 | 57091
2 | 57138
2 | 57263
2 | 57350
2 | 57372
2 | 57446
2 | 57636
2 | 57641
2 | 57687
2 | 57794
2 | 57806
2 | 57912
2 | 57981
2 | 58208
2 | 58223
2 | 58382
2 | 58408
2 | 58475
2 | 58491
2 | 58515
2 | 58645
2 | 58690
2 | 58698
2 | 58771
2 | 58886
2 | 58934
2 | 58953
2 | 59006
2 | 59108
2 | 59196
2 | 59232
2 | 59248
2 | 59374
2 | 59396
2 | 59512
2 | 59572
2 | 59708
2 | 59735
2 | 59792
2 | 59827
2 | 59849
2 | 59972
2 | 60120
2 | 60134
2 | 60182
2 | 60318
2 | 60367
2 | 60380
2 | 60394
2 | 60534
2 | 60536
2 | 60548
2 | 60556
2 | 60588
2 | 60606
2 | 60644
2 | 60656
2 | 60658
2 | 60678
2 | 60694
2 | 60724
2 | 60782
2 | 60794
2 | 60873
2 | 60916
2 | 60922
2 | 60923
2 | 60928
2 | 60936
2 | 60940
2 | 60958
2 | 60960
2 | 60966
2 | 60968
2 | 60976
2 | 60996
2 | 61048
2 | 61076
2 | 61134
2 | 61223
2 | 61250
2 | 61258
2 | 61275
2 | 61294
2 | 61364
2 | 61392
2 | 61432
2 | 61468
2 | 61496
2 | 61518
2 | 61579
2 | 61594
2 | 61650
2 | 61700
2 | 61760
2 | 61766
2 | 61808
2 | 61842
2 | 61845
2 | 61864
2 | 61904
2 | 61923
2 | 61934
2 | 61949
2 | 61952
2 | 61992
2 | 62072
2 | 62077
2 | 62128
2 | 62154
2 | 62248
2 | 62252
2 | 62274
2 | 62322
2 | 62332
2 | 62687
2 | 62691
2 | 62717
2 | 62747
2 | 62814
2 | 62869
2 | 62882
2 | 62999
2 | 63017
2 | 63021
2 | 63033
2 | 63047
2 | 63063
2 | 63067
2 | 63075
2 | 63089
2 | 63105
2 | 63145
2 | 63159
2 | 63171
2 | 63249
2 | 63261
2 | 63341
2 | 63351
2 | 63355
2 | 63363
2 | 63367
2 | 63391
2 | 63413
2 | 63417
2 | 63425
2 | 63441
2 | 63457
2 | 63459
2 | 63463
2 | 63481
2 | 63499
2 | 63507
2 | 63515
2 | 63543
2 | 63630
2 | 63855
2 | 63893
2 | 63905
2 | 63957
2 | 64035
2 | 64081
2 | 64107
2 | 64115
2 | 64123
2 | 64143
2 | 64336
2 | 64387
2 | 64469
2 | 64539
2 | 64565
2 | 64590
2 | 64657
2 | 64667
2 | 64677
2 | 64703
2 | 64765
2 | 64797
2 | 64811
2 | 64928
2 | 64993
2 | 808
2 | 8081
2 | 8975
2 | 9090

List of [gatherproxy(dot)com] Proxies, sorted by most occurrence
![image](https://user-images.githubusercontent.com/41063376/72672949-030ea780-3a78-11ea-8e97-85b666c2ffaa.png)

8080 (920)
9999 (667)
3128 (257)
80 (219)
53281 (90)
8118 (45)
83 (30)
8888 (27)
23500 (22)
8811 (17)
41258 (15)
8000 (13)
9000 (13)
999 (12)
3000 (12)
8081 (11)
8060 (11)
84 (11)
82 (11)
443 (10)
9991 (10)
808 (10)
9090 (10)
48678 (9)
20183 (8)
63141 (7)
61234 (7)
81 (5)
1182 (5)
44151 (5)
8086 (4)
1080 (4)
8001 (4)
87 (4)
3129 (3)
8181 (3)
8085 (3)
44331 (3)
8197 (3)
58461 (3)
55555 (3)
35101 (3)
65309 (3)
54419 (3)
8088 (3)
35116 (3)
55443 (3)
4550 (2)
52018 (2)
8090 (2)
31288 (2)
57243 (2)
10000 (2)
8008 (2)
58080 (2)
53438 (2)
43716 (2)
58198 (2)
3389 (2)
59760 (2)
43399 (2)
8087 (2)
44610 (2)
52636 (2)
6000 (2)
46558 (2)
21776 (2)
60626 (2)
55184 (2)
56035 (2)
21213 (2)
47150 (2)
38170 (2)
30004 (2)
35522 (2)
45557 (2)
36733 (2)
41454 (2)
43929 (2)
36630 (2)
9797 (2)
39617 (2)
50626 (2)
41049 (2)
666 (2)

**Comment by openbullet** [comment]
Just... holy...

**Comment by Unkn9wn1** [comment]
or you can also check them before removing!
maybe each port had different IP!

you can test them using proxy judge APIs like
http://azenv.net/index.html
or
http://httpbin.org/get?show_env
https://httpbin.org/get?show_env
smtp://smtp.gmail.com
smtp://aspmx.l.google.com
https://www.proxy-listen.de/azenv.php
http://www.proxyfire.net/fastenv
http://proxyjudge.us/azenv.php
http://ip.spys.ru/
http://www.proxy-listen.de/azenv.php

or even ip checker APIs like
https://ifconfig.co/ip
https://api.ipify.org/?format=text
https://ifconfig.io/ip
https://myexternalip.com/raw
https://wtfismyip.com/text
https://icanhazip.com/
https://ipv4bot.whatismyipaddress.com/
https://ip4.seeip.org
https://whatleaks.com/

if all ports shows one unique ip, remove them!
if results was different, keep the different ones

this trick is really good, and also will be no problems even for premium proxies

**Comment by openbullet** [comment]
After thinking for quite a bit, I decided to not implement this feature, as the time it would take is far more than the actual added value to the program.
