### ISSUE TITLE
i cant change the name of my program 

### ISSUE THREAD

**Issue by laithalshabi** [openbullet/openbullet#47]
when i change every thing it return to openbullet in the program and tasks

**Comment by openbullet** [comment]
There are plenty of places where the name needs to be changed, for starters in the code behind of MainWindow. Also this is not an issue, this is just your not being able to see how the name is set. Closing.

**Comment by MeowBullet** [comment]
It's easy to change the name, lmfao, if you want to change the name there's firstly the mainwindow for the title, then there's the confirmation boxes, etc, Which is also found in the mainwindow, the about found in main, the settings found in main, the runner manager found in main, however you still need to change the name in settings, or you will have openbullet as your process in the task manager regardless of wether you change the title name or not. 

I would note if your going to sell this version after changing the name and taking credit for it, you may want to add more features or someone will be very pissed off with you when they discover what you did and will probably out you as a scammer, so I highly suggest you start learning some c# before thinking of doing this.  

sidenote if you want to change the version that can be found in obVersion

**Comment by MeowBullet** [comment]
Also located in globals is the default names for the settings files, database, license, config folder etc.
