### ISSUE TITLE
[BUG] Screenshot, Show Last Response In Browser

### ISSUE THREAD

**Issue by Unkn9wn1** [openbullet/openbullet#470]
Hi,
![image](https://user-images.githubusercontent.com/41063376/72675676-344d9e80-3a9d-11ea-967f-3c449682c617.png)

i clicked Screenshot button, screenshot saved in my clipboard, but i saw nothing in Screenshots folder, instead there is file named 'screenshot.jpg' in root folder of OB and if i take new screenshot by OB, older one will replaced by new one

it has not too much usage but if you wanna fix it,
it's good to save it in 'Screenshots' folder, name it as it's taken time instead of replacing
and if it's possible, make screenshot's quality better

![image](https://user-images.githubusercontent.com/41063376/72675872-0453ca80-3aa0-11ea-9e9c-f5b23541275a.png)

when 'Save Last Response Source' is disabled, should not it just show an error instead of making empty file and openning it?
another question is why when 'Last Response Source' of hit logged, why OB don't save last \<SOURCE\> in html and open it?

**Comment by openbullet** [comment]
The Screenshots folder is exclusively meant for Selenium (e.g. taking a screenshot of a webpage or a web element) it has nothing to do with screenshots of the program itself.

The other things you said should be put in a separate issue.
