### ISSUE TITLE
[REQUEST] Keep Runners Upon Restart of OpenBullet

### ISSUE THREAD

**Issue by caspertheghost1337** [openbullet/openbullet#471]
I think an option or default to keep OpenBullet runners upon restart is essential, since people can easily remove runners, but when I am needing in multiple runners/wordlists, and I have to restart because of an issue, it is a hassle to keep remaking them.

**Comment by openbullet** [comment]
This is already planned

**Comment by caspertheghost1337** [comment]
Is there an estimated release date? Because of this bug, I really want either this request to be added, or this bug fixed (https://github.com/openbullet/openbullet/issues/472) since each time this happens, I have to restart my OpenBullet and lose all my runners.

**Comment by openbullet** [comment]
Nope, no date.

**Comment by openbullet** [comment]
I didn't see this issue and we opened a duplicate one https://github.com/openbullet/openbullet/issues/519 it's ready for delivery in 1.2.1 (I'm going to close this one)
