### ISSUE TITLE
[REQUEST] Break line in Custom Export Format

### ISSUE THREAD

**Issue by Unkn9wn1** [openbullet/openbullet#478]
i add something like :

[EXPFORMAT]
Format=----------------------\nDATA: <DATA>\nProxy: <PROXY>\nCaptures:\n<CAPTURE>

in Environment.ini but \n don't break line
\r\n don't work too

add break line functionality in EXPFORMAT please
add \t (tab) too

thank you

**Comment by openbullet** [comment]
Hey, I don't know which version you're using but on 1.1.5 both `\n` and `\r\n` are working

**Comment by openbullet** [comment]
I also added `\t` support on dev branch
