### ISSUE TITLE
[REQUEST] Selenium Wait(Sleep) Action

### ISSUE THREAD

**Issue by Unkn9wn1** [openbullet/openbullet#479]
Hi,

Please add Wait (Timeout/Sleep) Action to "Selenium Element" Actions
not waiting for specially element, just wait/sleep for seconds

ty

**Comment by openbullet** [comment]
`FUNCTION Delay "2000"`

**Comment by zeyrox007** [comment]
Can we use custom waitforelement time is yes them how?
