### ISSUE TITLE
Bot stuck on ban?

### ISSUE THREAD

**Issue by winuser** [openbullet/openbullet#48]
https://gyazo.com/db3e5454a9973cca24b8f59e67eb9b0c
non of the bots are checking, I think they are stuck on ban or something. Have to stop and start again in order to run again. Then it checks around 1-2k then same issue

**Comment by styles977** [comment]
Because it's not getting the failure and success key . untik "Ban if No key found" option and debug it

**Comment by openbullet** [comment]
It probably means all the proxies got banned, this is not an issue with the software itself. In case you find a problem with the software please provide a detailed explanation on how to reproduce it and open a new issue.
