### ISSUE TITLE
[REQUEST]Pasrse [Header]

### ISSUE THREAD

**Issue by batonboy** [openbullet/openbullet#481]
Hi nice coder,

Could you please add a feature for PARSE block to parse variables in Address or Location in the <Header> except <Source>? It seems not this kind of function in ob when checking the DOC.

Further, please add a Redirect Block if possible, too.

Thanks much

**Comment by openbullet** [comment]
Please read the online documentation, especially this part https://openbullet.github.io/stacker.html#request
