### ISSUE TITLE
[BUG] Cookies and headers dictionaries keys and values are reversed

### ISSUE THREAD

**Issue by Laiteux** [openbullet/openbullet#485]
**Describe the bug**
`<COOKIES(*)>` actually contains all the cookies **values**, and `<COOKIES{*}>` all the cookies **keys**/names). Same behavior for `HEADERS`.

**Expected behavior**
By looking at the LoliScript documentation, `()` is supposed to represent **keys** and `{}` **values**, which is the opposite here.

**Version**
1.1.5 (Latest when submitting this issue)

**Comment by openbullet** [comment]
The `*` means it can have ANYTHING written inside it, so if you type `<COOKIES(NAME)>` and it prints a `VALUE`, then `<COOKIES(*)>` is interpreted as "it can have any name" and so it returns all the values. It is consistent and it was intended to work this way by design.
