### ISSUE TITLE
why not add download link here ?

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#49]

**Comment by Teals53** [comment]
and make a milestone for updates

**Comment by openbullet** [comment]
I bump the version number when I have enough bugfixes. Also I do not want to provide the download here for a different number of reasons, you can compile it yourself or easily find a compiled version by just googling OpenBullet and the version number.

**Comment by Teals53** [comment]
why ? people want to find this quickly (like me) why i need download this from other ?

**Comment by openbullet** [comment]
Alright I'll consider it in the future, first I have to check how to go about the license for redistributing the libraries that I'm using, because that's a huge part of the reason.

**Comment by Teals53** [comment]
kk :)
