### ISSUE TITLE
[BUG] IF statement can't handle nested variables

### ISSUE THREAD

**Issue by Paerot** [openbullet/openbullet#495]
The IF statement checks the single variable instead of checking both variables combined when using `<LIST[<VAR>]>`
Maybe this is intended like this in LoliScript, but you still can use `<LIST[<VAR>]>` on some Functions.

Have a list, set a single variable with a number and execute a IF statement with them.
The IF statement should check if the condition is true based on both variables combined, not the second one.

**Version**
1.1.5

**Comment by openbullet** [comment]
Did you already read this thread? Can you make an actual example of an input and desired output?
https://forum.openbullet.dev/topic/87/nested-ifs-and-operators

**Comment by Paerot** [comment]
Code (Single) = 4
Library (List) = [RU, FR, DE, PT, ES]
------------------------------------------
IF "<Library[<Code>]>" Contains "ES"
SET STATUS FAIL
ELSE
SET STATUS SUCCESS
ENDIF
-----------
Result: Success
Expected: Fail

The thread you linked is not related to this.
Anyway I managed to workaround the issue using extra functions.

**Comment by openbullet** [comment]
Okay sorry I did not understand the first time. Anyways I don't see why that code would not work, so thank you for opening the issue.

**Comment by Itamai** [comment]
I tried to replicate the problem but its giving me the expected output.

![image](https://user-images.githubusercontent.com/53093696/75122362-f562c800-569c-11ea-8ed4-90288a482b55.png)

**Comment by openbullet** [comment]
Closing as i cannot replicate either
