### ISSUE TITLE
[BUG] Importing Proxies

### ISSUE THREAD

**Issue by Boosted1000** [openbullet/openbullet#496]
When trying to import new proxies i hit import new proxies and the program freezes and closes, I've tried it multiple times.

**Comment by openbullet** [comment]
@Boosted1000 can you please tell me the exact version of OpenBullet that you're using?

**Comment by TRAlruwaily** [comment]
1.3.5.3

**Comment by openbullet** [comment]
That's not an official build, I'm going to close this issue
