### ISSUE TITLE
[REQUEST] Add IMAP and SMTP blocks in OB

### ISSUE THREAD

**Issue by iwitilfcuzlk** [openbullet/openbullet#499]
Receive and parse mail by many parameters is a very often used function when working with such programs. In the imap block, you need to add the server / port / username / password / ssl, nonssl / folder name in the mail. When parsing data, take into account such parameters as the sender of the letter / recipient of the letter / text of the letter / subject of the letter / all links from the letter to the variables. Also the ability to delete letters. Receive the number of letters by the parameters above. Proxy on / off.

Sending letters via smtp is not so frequent, but it is sometimes used .. The parameters can be said to be the same, only they need to be sent, not accepted and parsed =)

Thanks.

**Comment by jelly88893333** [comment]
Really good idea

**Comment by openbullet** [comment]
Duplicate https://github.com/openbullet/openbullet/issues/494
