### ISSUE TITLE
<USER>:<PASS> Not working

### ISSUE THREAD

**Issue by MeowBullet** [openbullet/openbullet#5]
![image](https://user-images.githubusercontent.com/49174722/55368142-1af25a80-553c-11e9-95b0-c36919c47115.png)

As far as I can tell user:pass isn't working, same with the runner.

**Comment by MeowBullet** [comment]
WOW so it's username and password. lol I will change the enviroment can close this issue.

**Comment by MeowBullet** [comment]
<USERNAME>:<PASSWORD> 

For others having this issue -> change environment slice to USER:PASS

**Comment by sieunhando** [comment]
I think this should be note because many people think this like Black Bullet xD
