### ISSUE TITLE
Bugs in Utility Block.

### ISSUE THREAD

**Issue by styles977** [openbullet/openbullet#50]
I am working on a Project To bypass CF by reloading chrome browser get it's cF cookies write it on cookies.txt files and reload this
cookies on every bot as long as the cookies last but I got some problem in Utility block.
Whenever I try to split the string  variable "COOK"  it always automatically changes to variable "SPLITTED" and this thing always happens whenever I switch from
LoliScript Tab To Stack View tab ...
Before ---> http://prntscr.com/n96jtu
If I switch back to Stack View and again to LoliScript then VAR "COOK" Automatically changes to VAR "SPLITTED" ...
After  ---> http://prntscr.com/n96k77
and I am stucked :(

**Comment by openbullet** [comment]
Thank you so much for the VERY detailed explanation, I wish more people were like you! It should be fixed like this https://github.com/openbullet/openbullet/commit/6b3d1aeb8e66f540bf2a7436584030a761b4b9c7
