### ISSUE TITLE
[BUG] ERROR: Have exceeded the maximum number of consecutive redirects.

### ISSUE THREAD

**Issue by shlok8749831769** [openbullet/openbullet#501]
ERROR: Have exceeded the maximum number of consecutive redirects.
I get this error while trying to load the website https://generator.email/
It works without proxies and loads successfully but the second I turn on proxies I get the redirect error
I also have tested my proxies and they work
I have tried to increase maximum redirects to 10000 but still same problem
I have already contacted Ruri in Forums and Ruri told me to come here.

Thanks in Advance!

**Comment by meinname** [comment]
Seems they have a very good http proxy detection or list.

Tried several socks4 proxies - all worked 
Also tired several http proxies (from public lists) got following

`
HTTP/1.1 302 Found
Date: Tue, 03 Mar 2020 07:42:34 GMT
Server: Apache
X-Powered-By: PHP/7.2.22
Set-Cookie: surl=ttps%3A%2Fgenerator.email%2F; expires=Wed, 04-Mar-2020 07:42:34 GMT; Max-Age=86400; path=/; domain=.generator.email
Strict-Transport-Security: max-age=31536000; includeSubDomains
Location: https://generator.email
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Content-Length: 0
`
(from http debugger - but same on OB when Autoredirect is disabled)

**Comment by openbullet** [comment]
So basically it's not a thing that we can fix right? If it does the same in other software using proxies.

**Comment by openbullet** [comment]
Okay, please use socks4 proxies in this case. Closing.
