### ISSUE TITLE
[REQUEST] Continue capturing for FREE and CUSTOM status

### ISSUE THREAD

**Issue by Derp0** [openbullet/openbullet#507]
I'd like to request the feature of having an option to continue processing the rest of the blocks in case the status is anything other than `SUCCESS` or `NONE`.

**Comment by Itamai** [comment]
@openbullet 
` if (data.Status != BotStatus.NONE && data.Status != BotStatus.SUCCESS && data.Status != BotStatus.CUSTOM)
            {
                i = lines.Count(); // Go to the end
                return;
            }`

that is what i did just added the custom bot status to the if statement ^^
is it okay to leave it like that or should we make an extra button in other options which forces custom status to go to the end?

**Comment by openbullet** [comment]
Everything in OpenBullet that changes the previous behaviour should be an optional choice (in this case in the config's other options), disabled by default as to not disrupt previous configs made with the assumption that it worked in a certain way. Also we're working on a separate repo right now to code and test 1.2.0 so if you make a PR now it's going to be a bit of a problem, I will take care of this myself, thanks anyways.

**Comment by Itamai** [comment]
sorry i didnt saw your message when i created the pull request will close it :)
