### ISSUE TITLE
[BUG] RSA funtion not working.

### ISSUE THREAD

**Issue by percebal** [openbullet/openbullet#514]
RSA Encryption still does not work in the new version 1.2.0.
i try in debuguer whit a site want that encryption and i saw still does not work,thanks.

**Comment by openbullet** [comment]
Hey, can you please PM me on the forum and give me the website? Thanks!

**Comment by meinname** [comment]
Though i also said it via PM here if someone else has problems with it:
1. All inputs for RSA Encryption need to be in Base64.
2. Also beware that the source of the Key and Modulus are very often HEX
So don't use `FUNCTION Base64Encode` but `UTILITY Conversion HEX BASE64` 
3. the output is also Base64 - so maybe you need to decode/convert this again before further using it.

**Comment by openbullet** [comment]
Tested and it works, please follow the instructions kindly provided by @meinname

**Comment by meinname** [comment]
Have to say. 
Not fixed yet.
Was able to test myself now and have to say i'm was not able to get the right result

**Comment by openbullet** [comment]
Reopening this since with further testing we realized this is not fixed. I will copy the working code from 1.1.4

**Comment by meinname** [comment]
Yes, my suggestion: 
keep RSAEncrypt as it is.
re add the one from 1.1.4 with it's old name RSA.
add to description that this is for pkcs1pad2 Implementations (like steamRSA)
