### ISSUE TITLE
[BUG] CF Bypass not working

### ISSUE THREAD

**Issue by alexparkin** [openbullet/openbullet#516]
![image](https://user-images.githubusercontent.com/59986106/76660244-a38fbe00-6535-11ea-8618-32c6c1ed8657.png)

URL tried:
https://hidemy.name/ ("ERROR: One or more errors occurred.")
https://codepen.io/ ("ERROR: One or more errors occurred.")
https://speed.cd/ ("Unknown protection, skipping the bypass!")
https://www.japscan.co/ ("[Success] Protection bypassed: JavaScript Got Cloudflare clearance!")

User-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

Version 1.2.0

**Comment by meinname** [comment]
1.  not protected by Cloudflare (at least not when i tested)
2. Protected with recaptcha -  it seems https://github.com/RyuzakiH/CloudflareSolverRe has now problems with solving recaptcha challenge (though i have 2captcha a captchasolver it doesn't request the recaptcha solving.)
3. they do a 302 redirect to https://speed.cd/login.php - the CloudflareSolverRE doesn't follow these redirects. So if you want to use the CF Block in Openbullet you need to use the Address where you are landing after all redirects. 
so use https://speed.cd/login.php 
4. you had a success - so it worked?

Yes. We are also not very happy with the Cloudflare situation. 
We depend on external libraries.
Leaf.xnet, we used before, removed support for CF from public version and wants 60 dollar per User for nonpublic with Cloudflare solving. 
Cloudflaresolver stopped their work and even deleted their Github repo.
Their successor CloudflaresolverRE. Has several other problems as you see.
Ruri fixed the main Problem with running multiple threads (Bots), so it's at least a bit useable.
But if it wont get much better or something else comes up, it seems we need a own CF Solution.
(but this is much work to do and it needs constant work, as cloudflare is regularly updating their protection)

**Comment by alexparkin** [comment]
I tried those websites because according to the library they tested them successfully, and because some of them were not working I thought it might have to do with some bug on the implementation. 

![image](https://user-images.githubusercontent.com/59986106/76684485-a1773f00-65c9-11ea-82fa-dbf3b6258b8b.png)

I guess we will just have to wait for someone to come up with a fully working CF Solution.

Thanks @meinname for the feedback!

**Comment by openbullet** [comment]
I did some testing
1) No protection (why even put a CF Bypass block?)
2) CloudflareSolverRe had a problem with recaptcha, I just fixed it, will be live on 1.2.1
3) CloudflareSolverRe does not handle redirects so you need to provide the exact URL as @meinname already told you
4) Success

I will close this, if you find more problematic sites please let me know.
