### ISSUE TITLE
[BUG] String vs. Variable Name

### ISSUE THREAD

**Issue by nonrect** [openbullet/openbullet#517]
**Describe the bug**
Some parts just don't accept variable names and consider it as a string
e.g:

    • I generate a random user agent via a function with the name <RUA> then when I type <RUA> in a "BYPASS CF" block's input string, it give the error "The format of value '<RUA>' is invalid."
    • Also setting <USER> or <PASS> as input string of Sendkey in selenium just sends the actual string instead of current username or password

Thanks

**Version**
 - v1.2.0

**Comment by meinname** [comment]
Both work for me
