### ISSUE TITLE
[BUG] CF Block do not support SOCKS?

### ISSUE THREAD

**Issue by Zurzar** [openbullet/openbullet#518]
- Version [1.2.0]
I don’t know, but for some reason the new version 1.2.0, CF block is un supported SOCKS 4 and 5. Only HTTP proxies. I don’t know whether this bug is or not, but the previous version fully supported any proxies
https://prnt.sc/rg6qrw

**Comment by openbullet** [comment]
Previous version was Leaf.xNet. Current version is CloudflareSolverRe which is based on the HttpClient and hence has no native socks support.
