### ISSUE TITLE
OpenBullet not same behavior as BB

### ISSUE THREAD

**Issue by botboyz67** [openbullet/openbullet#52]
Same config, same wordlist, same proxies.

OpenBullet say i have 2 hits and take 9 hours to finish.
BB got 122 hits and took 10 mins.

I have a rule in my config to check PASS, so it only try if it have 8 to 12, 1 number, 1 capital and 1 non capital.

It seem as OpenBullet is not checking for these rules.
Tried removing them and putting them again.
Tried redoing the config completly.

Here is what Environment.ini look like ; 

https://pastebin.com/eGtn3RKD

**Comment by openbullet** [comment]
The Environment.ini file does not contain any slice for PASS so it's only obvious it won't work. You need to get a correct Environment.ini file that's all you need to solve your issue, closing this.

**Comment by openbullet** [comment]
Can you please show the data rules section of the config? Thank you.

**Comment by openbullet** [comment]
Sorry I keep clicking on close by mistake ^_^

**Comment by botboyz67** [comment]
Haha it's cool. Here ; 

![Capture](https://user-images.githubusercontent.com/43886593/55800218-2ba55200-5aa1-11e9-94a3-a2d8a4e5b873.PNG)

**Comment by botboyz67** [comment]
Im i dumb and i should put PASS instead of <PASS> ?

**Comment by openbullet** [comment]
Yep you should put PASS not <PASS>

**Comment by openbullet** [comment]
Whenever it asks for a Name (Slice Name, Variable Name) you're supposed to skip the angle brackets, those are just needed when you want to replace their values inside some textbox that is gonna be used for something else.
