### ISSUE TITLE
[BUG] bug in wordlists

### ISSUE THREAD

**Issue by lamjed001** [openbullet/openbullet#529]
**Describe the bug**
when i delete wordlist from my computer and then click on delete not found in tab wordlist the software crashed

**To Reproduce**
Steps to reproduce the behavior
1. Go to 'Wordlists'
2. Click on 'Delete Not Found'
When wordlist not found you will see the error
3. See error

**Screenshots**

![](https://forum.openbullet.dev/assets/uploads/files/1584365318176-11a660a0-5b40-40b7-b7b1-d04ff249f49a-image.png)

![](https://forum.openbullet.dev/assets/uploads/files/1584365190906-d9e34334-e15a-4e17-9715-ef93f1d6f0c8-image.png)

**Version**
 - Version  1.2.0

**Comment by openbullet** [comment]
Fixed
