### ISSUE TITLE
Drag and Drop wordlist not attributing Type

### ISSUE THREAD

**Issue by botboyz67** [openbullet/openbullet#53]
When you drag and drop a wordlist in BB. It automatically detect it and set it's Type.

Per example ; MailPass

While in openbullet, the Type is always Default.

Is that a normal behavior ?

**Comment by openbullet** [comment]
If you looked carefully you would've seen this https://github.com/openbullet/openbullet/commit/32f623a3b804ef6150474842f87f9ef7af2d243e commit fixes the issue, so either recompile or get the 1.0.1 version which already has the fix inside it.
