### ISSUE TITLE
[REQUEST] IF/ELSE Condition as a block.

### ISSUE THREAD

**Issue by Muayyad1999** [openbullet/openbullet#531]
I've been wandering around in the blocks and checking if there's an IF/ELSE condition, I found in the documentation that the only way is to edit a KEY Block and put IF/ELSE statements in the loli view,

I wished that there were a block for IF statements even if it weren't nested just a simple IF block that checks the output of the variable/function.. etc.

**Comment by openbullet** [comment]
No, use LoliScript. Read the documentation, I will not make blocks for those instructions.

**Comment by openbullet** [comment]
You can read more here https://forum.openbullet.dev/topic/87/nested-ifs-and-operators/2
