### ISSUE TITLE
[BUG] 404 Error on Proxy

### ISSUE THREAD

**Issue by meinname** [openbullet/openbullet#533]
Reference:
https://forum.openbullet.dev/topic/538/404-error-on-proxy

Debugged a bit - please do some Changes on extreme.net:

when http proxy, we currently do
POST https://example.com/blabla/blubb HTTP/1.1
Host: example.com

Should be just
POST /blabla/blubb HTTP/1.1
Host: example.com

And not really needed to solve the problem, but closer to the standard:
replace
Proxy-Connection:
with
Connection:

(the Proxy-Connection was just experimental - reference: https://stackoverflow.com/a/16848783 )

**Comment by openbullet** [comment]
Does Extreme send POST https... HTTP/1.1 only when there is a proxy or even normally?

**Comment by meinname** [comment]
Only on http proxy.
Neither on socks nor on direct connection

**Comment by meinname** [comment]
on the internal fix:

https is fine.

but i noticed that on http proxy when requesting http://
we need it as it was before.

it should be:
GET http://example.com/test HTTP/1.1
Host: example.com

but is:
GET /test HTTP/1.1
Host: example.com


And what we forgot on http and https with http proxy.
Connection: keep-alive
gets rewritten to
Proxy-Connection: keep-alive
but shouldn't be
