### ISSUE TITLE
[BUG] Send to recheck crash

### ISSUE THREAD

**Issue by lamjed001** [openbullet/openbullet#535]
**Describe the bug**
when go to hits and send to recheck software will be crashed

**To Reproduce**
1. Go to 'Hits'
2. Select the config and type you want
3. Select all the hits or one hit
4. Mouse right-click
5. Click 'send to recheck'
6. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/23016064/77083967-958ee100-69fe-11ea-8160-106e8c07ca27.png)

![image](https://user-images.githubusercontent.com/23016064/77084501-557c2e00-69ff-11ea-9de6-4b49fa50d755.png)

**Version**
 - Version 1.2.0

**Comment by openbullet** [comment]
This will be fixed as part of https://github.com/openbullet/openbullet/issues/522
