### ISSUE TITLE
[BUG] RSA Probleme

### ISSUE THREAD

**Issue by RALORAVLO** [openbullet/openbullet#536]
i have probleme when using Rsa algorithm i will give an example:

plane text : 5129925056508016
Site Send this values:
publicKey

MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj0oSUgN9uaVYG2BDPGq0LRbmmaSJWT5jU7W9QhT1XnS4oC64vBoiJfX19RvDk/+FIt6+5dua1VjpGZwsgVDkftZTEXf64q2b9T0LcF2UGlpDtP6hldB9MmYvyAtKBJynuKL6Tysi6MiXE8urjboWDDxp9bfqItLWUh/Yx3lmR7dm7rg5hf54ToR/6qvRYq+OyolbmKEjA5CmIh7Ju6lf/8TPwJsAjFzsauvJMMDSLWFM88oS3tULwcoDVndQThNh59SsUs9GT6n/X5PtfP6d0IKomoqkZQI/RVMpNX+fP3H7nzsp0UmXeOjog30IZT+br7otl6d5KZhOuzzFnQqlNQIDAQAB

jwk:{"RSA",
"n":"j0oSUgN9uaVYG2BDPGq0LRbmmaSJWT5jU7W9QhT1XnS4oC64vBoiJfX19RvDk_-FIt6-5dua1VjpGZwsgVDkftZTEXf64q2b9T0LcF2UGlpDtP6hldB9MmYvyAtKBJynuKL6Tysi6MiXE8urjboWDDxp9bfqItLWUh_Yx3lmR7dm7rg5hf54ToR_6qvRYq-OyolbmKEjA5CmIh7Ju6lf_8TPwJsAjFzsauvJMMDSLWFM88oS3tULwcoDVndQThNh59SsUs9GT6n_X5PtfP6d0IKomoqkZQI_RVMpNX-fP3H7nzsp0UmXeOjog30IZT-br7otl6d5KZhOuzzFnQqlNQ",
"e":"AQAB"}

after encrypt plane text with above values result should be 
Nqsm0X/EYpXB1eebpknJ1E0+jtl1lmTfpR792hkoUZb7jNXi6wMhX+K5p2piBTKLZYdSHQfbp/dHeYz0KBKcHyezfqvlK3QIr7i46GTcjQn/5xTJbmVjL8Gr1rulBeRF5jiEFqBl4cAr6MWXr1hR3qPdJWkegfA0++URoWC4ltLmrbyk/OhZczhYhZ+jh8Mzu1Em7jGCaHxp4d4ytuv5YBeVDYcxlYOs/KtaX/sTIXHsWEPzD0b77RRFrczS5MdpoEY6esHbdNU30U5FBDZxX133HXn6lNTAYIl1hM7xX9QMlg3s/RmMZz5xAWA6YtP2Dnxf8GFRIDj3AcRw2S+Omg==

but when i am using openbullet and pars (n) and (e) and put them in Modulus and Exponent with plane text as input show this probleme
ERROR: Invalid length for a Base-64 char array or string.

All Version

**Comment by openbullet** [comment]
Could you kindly provide a link to the website via PM on forum.openbullet.dev ?
Thanks
