### ISSUE TITLE
[REQUEST] Search bar in Runner Wordlist

### ISSUE THREAD

**Issue by demiOB** [openbullet/openbullet#537]
YaY!

**Comment by PurityWasHere** [comment]
I added this to Anomaly by adding this to DialogSelectWordlist.xaml
`<TextBox Grid.Column="0" x:Name="searchBox" Margin="0,0,221,0" TextChanged="SearchBox_TextChanged" />`

Then i added:

```
private void SearchBox_TextChanged(object sender, EventArgs e)
        {
            WordList = new ObservableCollection<Wordlist>(vm.WordlistList.Where(c => c.Name.ToLower().Contains(searchBox.Text.ToLower())));
            wordlistsListView.ItemsSource = WordList;
        }
```
to DialogSelectWordlist.xaml.cs

**Comment by PurityWasHere** [comment]
if you want to see how it was implemented you can see the source here, Sorry im too lazy to clone then open a PR.

https://github.com/PurityWasHere/Anomaly-Mod/blob/Expiremental/OpenBullet/Pages/Dialogs/DialogSelectWordlist.xaml

https://github.com/PurityWasHere/Anomaly-Mod/blob/Expiremental/OpenBullet/Pages/Dialogs/DialogSelectConfig.xaml.cs

**Comment by openbullet** [comment]
Alright @PurityWasHere thanks, although your approach seems to be making a new collection each time. See how I did it for the Configs https://github.com/openbullet/openbullet/blob/master/OpenBullet/ViewModels/ConfigManagerViewModel.cs
It's much more versatile if you use a filter!

**Comment by PurityWasHere** [comment]
That is a pretty nice way of doing it
