### ISSUE TITLE
[BUG] Spaces first than [SETTINGS] make OB not start

### ISSUE THREAD

**Issue by demiOB** [openbullet/openbullet#538]
Example:

    [SETTINGS]
{
  "Name": "TEST",
  "SuggestedBots": 1,
  "MaxCPM": 0,

-----------------------------

FIXED

----------------------------
[SETTINGS]
{
  "Name": "Test",
  "SuggestedBots": 1,
  "MaxCPM": 0,

**Comment by openbullet** [comment]
Pretty sure we fixed this
