### ISSUE TITLE
OB Wont Start

### ISSUE THREAD

**Issue by 83y** [openbullet/openbullet#539]
Whenever i run the latest version of OB it wont start, i have followed all the steps in the github

**Comment by openbullet** [comment]
Do you perhaps have plugins in the Plugins folder?
And can you confirm you're on version 1.2.0 and not on some mod?

**Comment by 83y** [comment]
I have the plugins

Build.cs
Check.cs
IControl.cs
Loader.cs

and i dont know how to check what version im on as it wont start :\

**Comment by openbullet** [comment]
Those are not plugins... 9 out of 10 you did not compile the program, please download the precompiled build from here https://github.com/openbullet/openbullet/releases/download/1.2.0%23531/OpenBullet.zip
