### ISSUE TITLE
Program closes down "PARSING"

### ISSUE THREAD

**Issue by Kongedam** [openbullet/openbullet#540]
**Describe the bug**
When saving the projct after I used the block "PARSE" block

**To Reproduce**
1. Insert PARSE Block
2. USE automatic mode
3. Paste tyour source
4. Highlight with shift the text you want to parse
5. Program set LR string
6. SAVE (Program closes down)
7. Nothing saved when loding your config again

**Expected behavior**
Should save

**Screenshots**
Can take a screen hot of a closed program :)

**Version**
 - Version 1.2.0

**Additional context**

**Comment by Kongedam** [comment]
![Right parse](https://user-images.githubusercontent.com/3888787/77225059-161f2000-6b6c-11ea-9cd3-43c4ea6cb7a0.jpg)

I think maybe its becurse right string is 2 lines?

**Comment by openbullet** [comment]
Duplicate https://github.com/openbullet/openbullet/issues/466
