### ISSUE TITLE
[REQUEST] Wordlist Progress Bar

### ISSUE THREAD

**Issue by vomar** [openbullet/openbullet#541]
Possible to implement simple progress bar in Wordlists tab?

![2020-03-21_14-39-11](https://user-images.githubusercontent.com/6277958/77227605-c51a2680-6b81-11ea-890c-a7d861870bc2.png)

**Comment by openbullet** [comment]
The progress of a Wordlist is bound to a certain Config. What if you have 2 different configs? Which progress bar should be shown? This makes little sense, sorry.
