### ISSUE TITLE
[REQUEST] Disable bot log for Remote configs 

### ISSUE THREAD

**Issue by bfx003** [openbullet/openbullet#542]
As title moreover whats the purpose of remote when bot log is open

**Comment by openbullet** [comment]
The remote API is just meant to be a simple way to share configs between multiple people, it's not meant to be secure and if someone wanted he could download all configs with 1 block directly from OpenBullet itself. So there's really no point in "hiding" information from the user, if you want a secure solution I suggest you read this thread where I explain how to achieve something like that https://forum.openbullet.dev/topic/12/poll-openbullet-secure-api
