### ISSUE TITLE
[BUG]Custom Hits isn't displayed in Hits DB

### ISSUE THREAD

**Issue by Ei-Dotter** [openbullet/openbullet#543]
I created a config and add a "Key Check" block through the Stack-View.
For "Type" I choose "Custom".
For "Custom Type" I can only choose "CUSTOM" this is the only entry in the pull-down menu.
![stackview](https://user-images.githubusercontent.com/28747417/77233785-0cb4a880-6baa-11ea-8ecd-4e9ceab39ee0.jpg)

So I changed to LOLISCRIPT-view and changed the line to:
_KEYCHAIN Custom "CUSTOMizedby Myself" OR_
![stackview](https://user-images.githubusercontent.com/28747417/77233941-33bfaa00-6bab-11ea-875d-624fcc606ed7.jpg)

At the Runner I can see that there are CUSTOM-Hits, the is a count at the bottom and entries in the table above.
After stopping the runner I these Hits aren't displayed at Hits DB, I can only choose between the TYPES "SUCCESS","NONE" and "CUSTOM". But my Hits are saved as Type "CUSTOMizedby Myself".
I can foun them in the "OpenBullet.db"-file

That's all.
I wrote this tu Ruris Shoutbox and he asked me to make an Issue.

**Comment by openbullet** [comment]
Hello, you can easily define your custom statuses (that will appear in the dropdown box of the keycheck block) through the Environment.ini file.
Check the guide here https://openbullet.github.io/usage.html#environment
Let me know if you solved your problem so I can close this, thanks

**Comment by Ei-Dotter** [comment]
Yes, this solved my problem, you can close this. Thanks!
