### ISSUE TITLE
Selenium - Chrome problem

### ISSUE THREAD

**Issue by nonrect** [openbullet/openbullet#544]
When I run my selenium checker on 20 threads, It works perfectly fine but after several hours the number of "chrome.exe" and "chromedriver.exe" tasks will increase significantly which freezes my PC and makes me to restart it

I had to add a windows schedule to run a bat file every half an hour to kill all "chrome.exe" & "chromedriver.exe" tasks, I also know we have this options in "Tools" but it's not auto

Yes, I also checked "Always Quit browser at the end" when I created the config

I tested the same config several times and on every test my VPS hangs the way that I have to restart it (5 Core, 5Ghz, 6GM RAM, Windows Server 216)

When sometimes I could reach to it before the full freeze, I could notice a huge number of "chrome.exe" and "chromedriver.exe" on my task manager and I was not able to run OB or some other programs because windows was giving me the error of "low RAM"

Adding Feature Request:
• I wish you could add an ability to set "Selenium Tools" on auto (run every # minutes or run after a specific number of tries, or even maybe you can develop a better workaround for this)

Thx

**Comment by Itamai** [comment]
I had the same issue.
My selenium config basically visits a site, does nothing for 10 minutes(site stays open for 10 minutes) and after that the bot closes the browser.
In the 10 minutes sometimes the site randomly navigates you to another url and then the chrome tab will stay open and the bot will ignore the instance and create another one.
Didn't use the config for 2 weeks will try it again and maybe update this post.

**Comment by nonrect** [comment]
Kind of you

Although I made a batch file to close both "chrome.exe" and "chromdriver.exe" tasks on schedule using windows scheduler every 20 minutes

Even with this, sometimes my VPS freezes again but much less

**Comment by demiOB** [comment]
> When I run my selenium checker on 20 threads, It works perfectly fine but after several hours the number of "chrome.exe" and "chromedriver.exe" tasks will increase significantly which freezes my PC and makes me to restart it
> 
> I had to add a windows schedule to run a bat file every half an hour to kill all "chrome.exe" & "chromedriver.exe" tasks, I also know we have this options in "Tools" but it's not auto
> 
> Yes, I also checked "Always Quit browser at the end" when I created the config
> 
> I tested the same config several times and on every test my VPS hangs the way that I have to restart it (5 Core, 5Ghz, 6GM RAM, Windows Server 216)
> 
> When sometimes I could reach to it before the full freeze, I could notice a huge number of "chrome.exe" and "chromedriver.exe" on my task manager and I was not able to run OB or some other programs because windows was giving me the error of "low RAM"
> 
> Adding Feature Request:
> • I wish you could add an ability to set "Selenium Tools" on auto (run every # minutes or run after a specific number of tries, or even maybe you can develop a better workaround for this)
> 
> Thx

20 bots?
Selenium is better to run at max 5, indifferently of RAM or CPU.
Try with 5 and let me know about the freeze.

**Comment by nonrect** [comment]
Regarding my hardware, I always run it on 20-30 BOTs

Although, When i reduce the BOTs, windows will still freeze but very lately

I made a small program that kills "chrome.exe", "chromedriver.exe", "conhost.exe", "cmd.exe" tasks automatically every 15 minutes as a workaround

**Comment by Itamai** [comment]
@nonrect hi sorry for the late response.
Do you use wait for element  blocks in your config?
I started since yesterday to do selenium tests again and i noticed that sometimes the bot gets stuck at tge wait for element block and i also specified a timeout from 3 seconds but it waits longer than that didnt count how much exactly either is 10 the default timeout or above that and after that i have a keycheck which changes the bot status to ban key. I need to do some testing with the keycheck because normaly it shouldnt give ban key because i can see the text which is needed for success key on my browser window.
Now the normal behavior after the ban key is that the browser quits and a browser opens but if i got that "timeout" bug the instance gets ignored and the bot starts over with a new browser window.
