### ISSUE TITLE
[BUG] Plugin Text elements on Forms do not update during Runtime

### ISSUE THREAD

**Issue by PurityWasHere** [openbullet/openbullet#548]
**Describe the bug**
Plugin Text elements on Forms do not update during Runtime.

**To Reproduce**
1) Create a Text element in a plugin that reads a Var
2) Modify that Var
3) The Text element will not change

**Expected behavior**
The text box or text to change to the new Variable content

**Version**
 - Version [1.2.0]

**Comment by openbullet** [comment]
This is not a bug, the feature is just not present, I will do this inside https://github.com/openbullet/openbullet/issues/546
