### ISSUE TITLE
[BUG] Problem with ignore Response error.

### ISSUE THREAD

**Issue by meinname** [openbullet/openbullet#553]
https://forum.openbullet.dev/topic/571/help-key-check-for-domain-not-available/5

without ignore:
![image](https://user-images.githubusercontent.com/16181408/77375095-ce1b1b80-6d6c-11ea-96d6-41c2e7b5b2a7.png)

with ignore:
![image](https://user-images.githubusercontent.com/16181408/77375107-d83d1a00-6d6c-11ea-9196-c4e7506c0b10.png)

**Comment by shdf2** [comment]
Hello, i faced this problem again today. i don't get it, what's the cause of this problem ?
when i watch in Fiddler there is nothing unusual...i send a POST request and i receive a well formated JSON in return, but in OB i have that error message : 

> ERROR: Could not recieve the message body of the response HTTP-server 'www.xxxxxxx.com'.
btw i receive only the cookies...

will it be fixed soon ?

Thanks !

**Comment by meinname** [comment]
The ready for delivery label means: we already fixed it. 
And will be included in the next release.  
When is the next release? Look in our forum.
