### ISSUE TITLE
[REQUEST]  Requests Timeout for every Request block

### ISSUE THREAD

**Issue by demiOB** [openbullet/openbullet#556]
i need to modify timeout request for some urls in some cases
Change it from https://i.vgy.me/1LOclY.png
and put the editable number in every REQUEST block

YAY!!!

**Comment by Unkn9wn1** [comment]
yeah, i said this in #477 request too
the developer is busy nowadays, thanks to Ruri

**Comment by openbullet** [comment]
He's right, this is duplicate
