### ISSUE TITLE
[REQUEST] Read status via config

### ISSUE THREAD

**Issue by Unkn9wn1** [openbullet/openbullet#559]
Hi,

please add variables to read status current bot and runner via config

something like :
\<BotsCount> = Count of bots
\<ProxyStatus> = Proxy Status [On or Off]

things that are good to known is :
Bot ID
Count of enabled Bots
Proxy Status [On/Off]
Proxy of current bot
Proxy's IP
Proxy's Port
Proxy type
Total Check Datas
CPM
Hits
Custom Hits
Retries
To Checks
Count of proxies
Banned Proxies
and etcxxxxxxxxx.

ty

**Comment by openbullet** [comment]
Due to separation of concerns, this is impossible in the current application design.
