### ISSUE TITLE
TCP Connect taking much time

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#56]
Hello,
last days i was testing the TCP Client from DBC
i was not sure if it is a bug or not, but i had to ask 
here is the params

FUNCTION RandomNum 8123 8131 -> VAR "RandPort" 
TCP Connect "api.dbcapi.me" "<RandPort>" UseSSL=FALSE 

try it

**Comment by meinname** [comment]
Can confirm - 
I checked it with nc and they just don't answer anything when you are connected. 
So there is waited till timeout
`                    
// Read the stream to make sure we are connected
                    if (UseSSL) bytes = ssl.Read(buffer, 0, buffer.Length);
                    else bytes = net.Read(buffer, 0, buffer.Length);
`

**Comment by meinname** [comment]
some "inspiration" from the DBC Socket Client
        public bool Connected
        {
            get
            {
                return null != tcpClient && tcpClient.Connected;
            }
        }


        protected bool Connect()
        {
            if (!this.Connected) {
                this.Log("CONN");
                TcpClient tcpClient = new TcpClient();
                tcpClient.ReceiveTimeout = tcpClient.SendTimeout =
                    Client.DefaultTimeout * 1000;
                tcpClient.Connect(SocketClient.ServerHost,
                                  new Random().Next(SocketClient.ServerFirstPort,
                                                    SocketClient.ServerLastPort + 1));
                if (tcpClient.Connected) {
                    this.tcpClient = tcpClient;
                }
            }
            return this.Connected;
        }
