### ISSUE TITLE
[REQUEST] for SOCKS5 auth proxies [like NørdVPN plugin] the Copy proxy need to copy also user:pass [is better to create the (socks5)host:ip:user:pass directly]

### ISSUE THREAD

**Issue by demiOB** [openbullet/openbullet#567]
https://i.vgy.me/LF1SGV.png

Also for other Auth proxies type aswell.
as soon as user and pass is not empty copy in that format

YaY!!!

**Comment by tcho-tcho** [comment]
Bonjour comment tu fais pour utiliser le proxy nordvpn sous open bullet quand j'essaye les 5000 server 5, uniquement, sont fonctionnel ?

**Comment by openbullet** [comment]
@tcho-tcho please do not ask questions about plugins here, every plugin is to be considered unofficial and you should ask the people who released it, not post on the official repo.
