### ISSUE TITLE
[REQUEST] add variable to Zip utility

### ISSUE THREAD

**Issue by beer15** [openbullet/openbullet#568]
I think it's a good idea to add a variable to Zip there's only two and sometimes two is not enough, so we have to redo a block.

https://i.gyazo.com/e469dcb41e08eeb60d3a6cd72e335954.png

**Comment by openbullet** [comment]
How can you be sure that 3 will be enough but 4 won't be needed?

**Comment by openbullet** [comment]
I don't think I will do this, sorry, please just use multiple blocks
