### ISSUE TITLE
[BUG] OpenBullet v:1.2.0#540 and Up View Loliscript / Save Config Crash

### ISSUE THREAD

**Issue by PurityWasHere** [openbullet/openbullet#570]
**Describe the bug**
On Version 1.2.0#540 and above Openbullet will crash 100% of the time if you try to view the loliscript of a config or Save a config that uses a block from a plugin.

**To Reproduce**
Create a config
Use a block from a plugin
Press view loliscript / Try to save

**Expected behavior**
For the loliscript to show like normally as it used to on version 1.2.0#529

**Version**
 - Version 1.2.0#540

**Additional context**
Seems like the bug is something to do with `Merge pull request #554 from Yommy/master`

**Comment by openbullet** [comment]
Hello, I reverted his change on a later commit https://github.com/openbullet/openbullet/commit/61f6735cbe9ead2eaa45aecb8af2f3446800c300 but forgot to make appveyor compile a release build. Can you please use that release and see if the problem is still present?

**Comment by PurityWasHere** [comment]
The latest build released a few mins ago fixed this. It seems to only exist in 2 releases. I noticed when compiling the latest source the issue wasn't present anymore as well
