### ISSUE TITLE
Selenium Bug

### ISSUE THREAD

**Issue by navidevangel** [openbullet/openbullet#573]
Hi there is a issue that i like to say
in selenium,when using the element to click on login button or submit the form of login,selenium will go fast to the next block and it wont wait to the progress of login get complete and then go to next block,
so should use delay for it and so this make problems like decrease speed,make mistakes and...

so its good if be any solution for it
tnx

**Comment by openbullet** [comment]
Do you see the page loading immediately after you click the button? Selenium should wait automatically if the page changes. If only the DOM is updated through js on the same page though (e.g. in single page applications) it won't wait and you need to use the WaitForElement action. There is no other solution.
