### ISSUE TITLE
Block or Allow Chrome Notifications

### ISSUE THREAD

**Issue by BlueberryOne** [openbullet/openbullet#576]
Hello
I'm creating a program where I need to block Chrome Notifications to continue. I looked everywhere but I couldn't find something
Is this possible to perform this or no function exists for that ?

Thank you by advance

**Comment by openbullet** [comment]
Settings -> Selenium -> CMD Line Arguments -> add `--disable-notifications`

**Comment by BlueberryOne** [comment]
Thanks but I have a problem. When I go to Settings then Selenium I don't have any case with write CMD Line Argmuent. And I can't find a block with this parameters
