### ISSUE TITLE
[REQUEST] selenium minimized mode

### ISSUE THREAD

**Issue by Unkn9wn1** [openbullet/openbullet#577]
Hi,
in BROWSER ACTION BLOCK, there is minimize action
but when i Start config, it opens browser non-minimized
then after seconds minimize it

it's good if you add ability to start browser in minimized
thanks

**Comment by openbullet** [comment]
Settings -> Selenium -> CMD Line Arguments -> add `--start-minimized`

**Comment by Unkn9wn1** [comment]
Bro it's not working, did u tested it?

**Comment by openbullet** [comment]
Apparently that command line option was never implemented, my bad. There seem to be no way to do this from chrome, maybe try this? https://www.cnet.com/how-to/how-to-automatically-start-a-program-minimized-in-windows/

**Comment by Unkn9wn1** [comment]
Chrome or FireFox, no matter
i tested the url`(cnet.com)` too
i made a shortcut with and changed it's Run setting
then i changed OB's browser path to the lnk file
but OB can't even open browser after that

**Comment by openbullet** [comment]
I have no idea, but I'm sure if you can't do it with cmd line options or windows settings you can't do it with code either.

**Comment by Unkn9wn1** [comment]
see this trick
https://stackoverflow.com/questions/6643951/how-could-i-start-a-selenium-browserlike-firefox-minimized

what you think about setting 'Windows Position' and 'Window Size' in `BROWSER ACTION` BLOCK Under `OPEN` action options?
