### ISSUE TITLE
Small Issue

### ISSUE THREAD

**Issue by styles977** [openbullet/openbullet#58]
On StackView mode When I Untick "Ban on TimeOut" .. switch to loli Mode and again to StackView mode then it's value is ticked again

http://prntscr.com/n9od47

Also is there any Way to convert Dict to List For example Cookies to list var ...?
My Captured cookie got randomly generated keys ... and I couldn't generate it to list ...:3

**Comment by openbullet** [comment]
You can use the Dict like this `<COOKIES(*)>` (a.k.a. any key) to get all the possible values and `<COOKIES{*}>` to get all possible keys. You can for example do `FUNCTION Constant "<COOKIES(*)>"` to get all the values as a list (I think it will work, report back if it doesn't). Also thanks for letting me know about the other issue, I'll fix it right away.

**Comment by openbullet** [comment]
Solved https://github.com/openbullet/openbullet/commit/7688b8bc3b43e85e45d273d66f1ff06d4ea1b6ea

**Comment by styles977** [comment]
Thank you It worked Perfect :)
