### ISSUE TITLE
[REQUEST] Variable auto urlencode

### ISSUE THREAD

**Issue by lamjed001** [openbullet/openbullet#582]
**Is your feature request related to a problem? Please describe.**
when content-type = application/x-www-form-urlencoded the post data with vars and the vars not encoded so openbullet doesn't encode it auto

**Describe the solution you'd like**
when content-type = application/x-www-form-urlencoded so openbullet will auto encode the post data when it not encoded

**Comment by openbullet** [comment]
There is a big ass checkbox called "Encode content" in the request block. Use it.
