### ISSUE TITLE
[BUG] Element parse problem

### ISSUE THREAD

**Issue by navidevangel** [openbullet/openbullet#583]
hello
in selenium,if use the element with "Get text" and make it "is capture"....it will capture and show the value in stacker good,but when use in runner,it dont show capture correctly

**Comment by openbullet** [comment]
Make everything go to tocheck in your config, then go to
Settings -> Enable Bot Log -> Start Runner -> Get a tocheck -> See what went wrong in there

If you can't figure it out, open a thread on the forum as this is probably not an OpenBullet bug and you gave zero info on how to reproduce.
