### ISSUE TITLE
[BUG] Utility AppendLines is missing some lines

### ISSUE THREAD

**Issue by GunnGrave** [openbullet/openbullet#587]
Hello,

I guess that Utility AppendLines is missing some lines !
i was running a userChecker config, i ended up having 1000 hits
the DB was showing 1000, so until here all is good
but when i checked the saved file.txt, i did not find find the same number as hits

this made me re-run the test again and again, and every time i was having a different  number of lines in the saved file.txt.

**Version**
 - Version 1.2.0

**Comment by openbullet** [comment]
It's probably because of https://github.com/openbullet/openbullet/issues/409 so please try version 1.2.1 that's going to release in a few minutes and if it doesn't work open the issue again.
