### ISSUE TITLE
[REQUEST] Notepad section

### ISSUE THREAD

**Issue by Unkn9wn1** [openbullet/openbullet#589]
**Is your feature request related to a problem?**
I always have many notes about my config (test creds, rules n etc + debug data)
i need them to improve config later or repair config in future (if target updated)
i have to make a folder for every config and save them as text files
but i like to have my notes in OB itself, whenever i load my config in stacker

**Describe the solution you'd like**
actually i have no hope and i think you will close this issue 😅
but i write:
i think a new section in Configs section is needed (After 'Other Options')
user interface is good to be look like stacker section, but every block is a note or debug data!
SearchBox and 'Word wrap' and RTL checkboxes are needed too

if user added a note block for a config, then OB have to make a file named same as the config in configs folder but with a different extension (notes should not be in config itself, this make config huge and also maybe this contains important data that users don't wanna share them with config)
if config renamed, OB should rename it
if all note blocks removed, then OB have to remove note file)

here you can make it more advanced by adding PARSE BLOCK's toggle tabs to test regex and other modes on a note block that containing debug data, (running whole config to test a PARSE BLOCK is not good)
you can also add

think about this, ty

**Comment by openbullet** [comment]
This is extremely situational and it sounds like something that would only benefit you (other than being pretty time consuming to make the way you described it). Sorry but I won't do this.

**Comment by Unkn9wn1** [comment]
extremely situational 🤔
ok, but only `'Word wrap' and RTL checkboxes` was things that would benefits only me and non english users

you also labeled #588 as low priority
if you add that(#588), i could save my things as comment and send them to notepad++ everytime that i had time to complete that config or i can save test creds in config after i completed a config
i have many folder that i made to save debug, test creds and notes of websites that i never completed

**Comment by openbullet** [comment]
Yes I will do 588 so you can use the LS itself for comments
