### ISSUE TITLE
Proxy checker not testing all proxies

### ISSUE THREAD

**Issue by M3T4LL1C4** [openbullet/openbullet#59]
Today I checked 6000 socks 4 proxies. When finished, about 40 proxies were still listed as "UNTESTED"
I think it's not the first time I see this issue.

**Comment by M3T4LL1C4** [comment]
Maybe it's just a refresh issue, because when I close OB then relauch it, nothing is listed as UNTESTED.

**Comment by openbullet** [comment]
Yes basically what happens is that when the Parallel finishes assigning proxies to the workers that check them, it stops refreshing the UI, I need to make it wait for all the workers to finish or I need to delegate the UI refresh to the workers themselves.

**Comment by Teals53** [comment]
same for me xd

**Comment by openbullet** [comment]
Fixed https://github.com/openbullet/openbullet/commit/ad44543e411272545711e6f2d31095096705fac0
