### ISSUE TITLE
[BUG] Two 'Default' Category

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/openbullet#592]
Hi,

When i make first config, and i try to make another one
there is two 'Default' category
![image](https://user-images.githubusercontent.com/41063376/78727953-4d9f1200-794b-11ea-9584-ca1e25976e74.png)
:(

**Comment by openbullet** [comment]
That's probably because Default is referring at the same time to:
- the root of the Config folder
- a subfolder in the Config folder called Default
that's why it appears twice.
Can you check if it's the case and let me know please?

**Comment by Unkn9wn1** [comment]
there is no subfolder

**Comment by openbullet** [comment]
Alright I will get this fixed, thanks for checking
