### ISSUE TITLE
i need help error  the master worker has encountered : no data to process!

### ISSUE THREAD

**Issue by KillerOtrelos1** [openbullet/openbullet#594]
when i press start i take this error: error  the master worker has encountered : no data to process!

![help](https://user-images.githubusercontent.com/63452081/78985430-754fcf00-7b31-11ea-8e3e-bc9ccec2e3bf.png)

**Comment by openbullet** [comment]
Not a bug. It means your wordlist is empty

**Comment by KillerOtrelos1** [comment]
is not empty 
![help3](https://user-images.githubusercontent.com/63452081/78995853-f4ea9780-7b4b-11ea-9412-f249d2cae4d8.png)

**Comment by openbullet** [comment]
Are you joking or what?
It says total = 0 and the file is 0KB in size

**Comment by openbullet** [comment]
You clearly didn't save the text file. In notepad to File -> Save and then import it again

**Comment by janibashamd** [comment]
One of the funniest bugs i have seen :)
