### ISSUE TITLE
[BUG]Problem whit cookies

### ISSUE THREAD

**Issue by percebal** [openbullet/openbullet#597]
i have a problem whit site, that site send cookie and OB get error and not get source is the any way to fix that.
`Received invalid cookies '; secure' from the HTTP-server 'www.site.com'.
Status code: None
Received invalid cookies '; secure' from the HTTP-server 'www.site.com'.`

**Comment by openbullet** [comment]
I need a website in order to reproduce it

**Comment by percebal** [comment]
Here is config to u can see problema and account.
https://www.mediafire.com/file/pt07sdzqysmewmh/Hegre.loli/file
account: zackc1200:Badger44

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: openbullet<mailto:notifications@github.com>
Enviado: domingo, 12 de abril de 2020 2:55
Para: openbullet/openbullet<mailto:openbullet@noreply.github.com>
CC: percebal<mailto:percebal33@hotmail.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [openbullet/openbullet] [BUG]Problem whit cookies (#597)


I need a website in order to reproduce it

**Comment by openbullet** [comment]
Are you kidding me???

**Comment by percebal** [comment]
Sorry I thought it was for private.
Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: openbullet<mailto:notifications@github.com>
Enviado: domingo, 12 de abril de 2020 3:08
Para: openbullet/openbullet<mailto:openbullet@noreply.github.com>
CC: percebal<mailto:percebal33@hotmail.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [openbullet/openbullet] [BUG]Problem whit cookies (#597)


Are you kidding me???
