### ISSUE TITLE
I just see the jump option missing when use block metod no scripting

### ISSUE THREAD

**Issue by Rastocki79** [openbullet/openbullet#60]
The title say all i think...
When i work with blocks (no use script language) in a function block missing the jump option.

**Comment by openbullet** [comment]
That function was removed, you can jump using the LoliScript IF - JUMP construct like
```
IF "a" EqualTo "b"
JUMP #Block_label
ENDIF
```

**Comment by Rastocki79** [comment]
Ok thanks
