### ISSUE TITLE
[BUG] OB freezing when checking proxies

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/openbullet#601]
![image](https://user-images.githubusercontent.com/41063376/79121522-c0284b80-7daa-11ea-8ca2-4dc96a080f52.png)
- Version = 1.2.1#637

when i start checking proxies
OpenBullet hanging or freezing (even with low bots), that makes me kill it's task
maybe it's because OB ping proxies and check what is it's country and more
that is useless in most cases
the only thing that users need in most of cases is just
checking what proxies can load their target page to use them in bots

i think it's good if make it optional to find region of proxies, ping of them n more

or, maybe it's because OB show every proxy and update it's data, it could be the reason when proxies count are too much

**Comment by openbullet** [comment]
How many proxies are you using?

**Comment by Unkn9wn1** [comment]
3000 - 4000

**Comment by Cyber-Criminal** [comment]
![image](https://user-images.githubusercontent.com/41063376/80387014-5edd9d80-88bd-11ea-9b44-28bce3f70ed3.png)
It's better now, Although the 'Country' and 'Total' is gone
and also after deDuplicating (after checking them), All of proxies goes to Untesteds
if it's not too important then just Close it
Big thanks to LeXector and Ruri

**Comment by openbullet** [comment]
Please open a separate issue regarding that matter, I will close this one
