### ISSUE TITLE
[BUG] Openbullet crashing when attempting to interact with disneyplus

### ISSUE THREAD

**Issue by PerilousTheGreat** [openbullet/openbullet#603]
**Before you begin**
1. This is **NOT** Forlax's mod or any other mod. If you have issues related to those versions **DO NOT** post them here as they will be closed and disregarded immediately.
2. Do **NOT** post any form of illegal content (e.g. screenshots of you cracking a website with stolen credentials) and do **NOT** ask for Configs for websites. Doing that will result in a report to the GitHub security team and a permanent ban from posting to this repository.

**Describe the bug**
I'm trying to create a config for Disney+ to test a few of my accounts, when I run a simple GET request from disneyplus.com the source is received, but just before it can provide me the full response, it freezes and can only stop once closing the program. I've tested other sites and they seem to be functioning perfectly. I've also built a new Openbullet release, but still no luck.

**To Reproduce**
1. Create a config and request block
2. Enter disneyplus.com
3. Run

**Expected behavior**
There should be a full source based on the GET request of disneyplus.com

**Screenshots**
![image](https://user-images.githubusercontent.com/24501189/79156692-3c328b80-7dcb-11ea-8d4d-87a9d8262034.png)

**Version**
 - Version 1.2.1

**Additional context**

**Comment by Unkn9wn1** [comment]
![image](https://user-images.githubusercontent.com/41063376/79157892-a3136d00-7dea-11ea-9c8e-ad2511f9e639.png)
Same for me on 1.2.1-635 version

**Comment by openbullet** [comment]
Settings -> General -> Disable HTML View
