### ISSUE TITLE
[REQUEST] Remove Bots number limit

### ISSUE THREAD

**Issue by Unkn9wn1** [openbullet/openbullet#607]
**Before you begin**
This is NOT Forlax's mod or any other mod. If you implemented features or fixes related to those versions DO NOT post them here as they will be closed and disregarded immediately.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by openbullet** [comment]
No, just no. People will abuse it and then complain.

**Comment by Unkn9wn1** [comment]
oh, this 'issue' posted by mistake, i wanted to explain before posting

one of issues that make people use other softwares or modded OBs is this 'bot limit'
maybe someone abuse this opportunity to share a malware to people as a modded OB!

Time/Speed matters too

@openbullet 

if you don't change default one, please add a option to bypass this limit
for people who need and know this, just set a warning when they wanted to enable this

but please think about it again

**Comment by openbullet** [comment]
200 bots are more than enough for any task you might want to perform.

**Comment by Unkn9wn1** [comment]
with this proxy system, even 500 in not enough

**Comment by openbullet** [comment]
Then just refer to your issue about the proxy system instead
