### ISSUE TITLE
Parse  variable

### ISSUE THREAD

**Issue by Rastocki79** [openbullet/openbullet#61]
When i parse a variable Mode LR example variable X=test.ts:80 
I want to parse X to be without :80 i put Right string ":" and is come test.ts and is ok but when i have X=test.ts and no :80 the variable is not save in new one with the same value how is X

**Comment by openbullet** [comment]
If you use LR with right string ':' and there's no ':' of course it won't parse it. This is not a bug.

**Comment by Rastocki79** [comment]
Ok i know this but if not have nothing to parse i want he take the value of first variable because new variable come empty be nice he take the value of first variable
