### ISSUE TITLE
[BUG] False Positives

### ISSUE THREAD

**Issue by OujiaBoard** [openbullet/openbullet#613]
**Describe the bug**
I was cracking an account on Anomaly's version (which I know isn't part of you guys) and I tested it on the account and the account worked so it wasn't a false positive. I then went to crack the account again on your recent releases download and I got all bad logins even though there were 5 correct logins

**Expected behavior**
Well with it working on the website I expected it to come up as positive.

**Version**
 - Version 1.2.1 [e.g. 1.0.1]

**Comment by openbullet** [comment]
Your environment.ini must be different
