### ISSUE TITLE
[BUG] OpenBullet crashing when attempting to view large source

### ISSUE THREAD

**Issue by PerilousTheGreat** [openbullet/openbullet#615]
When I'm trying to create a config for OpenBullet, depending on the size of the response, OpenBullet will crash. With small-sized responses, they are handled with ease, with medium-sized responses, it will hang for a second or two, and with large responses it will completely hang until I force quite the program.

1. Go to 'Create a config'
2. Add a request block
3. Enter a number of different URLs that produce responses from small to large

**Expected behavior**
For OpenBullet to provide a response without hanging/crashing

**Screenshots**
![alt-text](https://media.giphy.com/media/cjtMWJEjxgqjG8H5h7/giphy.gif)

 - Version 1.2.1

**Additional context**
I've used many different OpenBullet versions, be it original or not, and they've all produced the same issue for me. I feel its a problem with my PC but I'm not exactly sure what it could be, I've ran multiple disk scans and everything is fine. This is an issue that I've been dealing with a couple weeks now, OpenBullet used to run smooth for me, I have roughly 16GB RAM with a 2.4ghz processor. 
HTML view works perfectly fine by the way, I've also turned it off to see if it makes a difference but no luck.

**Comment by openbullet** [comment]
This is a problem related to the richtextbox component, there is already an open issue about this https://github.com/openbullet/openbullet/issues/406 take a look.
