### ISSUE TITLE
[REQUEST] Hotkey to quickly comment/uncomment lines

### ISSUE THREAD

**Issue by Derp0** [openbullet/openbullet#616]
Could you please add a hotkey to quickly comment/uncomment lines in LoliScript Editor?

I suggest `CTRL+#`, but any other combination is fine. Thanks.

**Comment by openbullet** [comment]
Duplicate https://github.com/openbullet/openbullet/issues/611

**Comment by Cyber-Criminal** [comment]
issue #611 is about a button
but this one is about a Hotkey
but this one labeled as duplicate

**Comment by openbullet** [comment]
It doesn't matter, you should instead go comment on the other issue that it would be better to also add a hotkey.
