### ISSUE TITLE
[REQUEST] Variables in Utility Path

### ISSUE THREAD

**Issue by Wafend** [openbullet/openbullet#618]
Hello,
I request to have variables in the path of the utility block
for example rn: Folder \ <VAR> .txt  would throw an error.
Instead if i wanted to sort them at the moment, i would have to do it with if cases and then manually set the filename for every statement.

**Comment by openbullet** [comment]
As you can see, i am performing variable replacement in the folder's name https://github.com/openbullet/openbullet/blob/master/RuriLib/Blocks/BlockUtility.cs#L672
