### ISSUE TITLE
Add support to .editorconfig

### ISSUE THREAD

**Issue by aidenpearce79** [openbullet/openbullet#622]
Because EditorConfig is a "standard" on a lot of text editors, should be cool to add .editorconfig as a fallback config file.

**Comment by openbullet** [comment]
I didn't think anyone would use an editor other than Visual Studio to edit a WPF app. I heard Rider supports it but I honestly don't know how reliable it is. Anyways thanks for the suggestion

**Comment by aidenpearce79** [comment]
Please generate it (Options-> Text Editor-> C # -> Code Style-> Press the button "Create .editorconfig file from settings") and share it. I don’t want to change the code style and not use features due to a mismatch in the style settings, at the moment I have ~ 600 warnings / messages from IntelliSense

**Comment by openbullet** [comment]
I generated a .NET default convention file and pushed it to master, see if it's better

**Comment by aidenpearce79** [comment]
Thanks
