### ISSUE TITLE
Socks 5 in proxy 

### ISSUE THREAD

**Issue by gomos00** [openbullet/openbullet#628]
Hello,
Please how can use my account VPN ipvanish socks 5 in proxy openbullet
Type: SOCKS5
Host: ams.socks.ipvanish.com
Port: 1080

Username: my proxy user
Password: my proxy password

Thanks

**Before you begin**
This is NOT Forlax's mod or any other mod. If you implemented features or fixes related to those versions DO NOT post them here as they will be closed and disregarded immediately.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by openbullet** [comment]
Import as `(socks5)ip:port:user:pass`
