### ISSUE TITLE
[BUG] The DB make OpenBullet crash

### ISSUE THREAD

**Issue by TrickyPatrick** [openbullet/openbullet#629]
Hi guys, the OB DB make it crash. I have to purge it every 20 mins.
Any solution for that ? Can I just make OB not write the HIT ?
Thanks

**Comment by TrickyPatrick** [comment]
![image](https://user-images.githubusercontent.com/43622896/80120396-3424d980-858b-11ea-9301-c3595d7b61db.png)

**Comment by openbullet** [comment]
On version 1.2.1+ a log gets written every time OB crashes to the file Log.txt. Please paste the crash dump in here so I can find the cause.

**Comment by TrickyPatrick** [comment]
Okay the Log.txt got overwrite because I started OB since, I will make it crash again and give you that once it's done. 
Also, I guess you're the creator. I guess you know 36 ? We are actually making a found raising for your amazing work ! I'm part of it.

**Comment by TrickyPatrick** [comment]
He sent us that 
![image](https://user-images.githubusercontent.com/43622896/80134915-bcad7500-859f-11ea-954f-3d9ff0224959.png)
I'm glad you're happy about it. This will keep increasing don't worry about it.

**Comment by openbullet** [comment]
Thank you for your support, I really appreciated your initiative!

**Comment by TrickyPatrick** [comment]
![image](https://user-images.githubusercontent.com/43622896/80135942-490c6780-85a1-11ea-91c3-a9b2e351cad6.png)

Don't worry man, also this one is reccurent but only makes runner be Idle

**Comment by TrickyPatrick** [comment]
It crashed again but the logs are empty. I guess it's because I'm using the Anomaly OB

**Comment by TrickyPatrick** [comment]
Anyway, is there any option to auto purge the DB ?

**Comment by openbullet** [comment]
You need to be on the official OB, the Anomaly one doesn't have the crash dump.

**Comment by openbullet** [comment]
Anyways that looks like a memory leak, how much ram do you have on your PC / VPS?

**Comment by TrickyPatrick** [comment]
I have 16GB ram, but still happens after 10 000 hits :/
Yeah sorry, but what an amazing work you've done so far !

**Comment by Cyber-Criminal** [comment]
10,000 Hits...
you should set ob to save them in a file instead of db
issue #441 is about this, but idk why all important issues are labeled as 'low prio'

**Comment by TrickyPatrick** [comment]
So I have to put that:
KEYCHECK BanOnToCheck=FALSE
KEYCHAIN Success OR
KEY "" Exists
IF "" EqualTo "SUCCESS"
#Write_to_File UTILITY File "Hits\MyHits.txt" AppendLines "" -> VAR "Output"
SET STATUS FAIL
ENDIF

At the end of my script to not print each hits in "Hits DB"  ? (sorry I'm new to loli script)

**Comment by TrickyPatrick** [comment]
Basically what I want is stopping OB from listing hits in "Hits OB" section so I don't have to purge it anymore

**Comment by TrickyPatrick** [comment]
@Cyber-Criminal did you achieve this ?

**Comment by openbullet** [comment]
There is currently no way to disable saving to hits to the db

**Comment by TrickyPatrick** [comment]
@openbullet We can't fake it ? Making OB thinks this is not a hit ?

**Comment by openbullet** [comment]
Yes you could use an IF like you said and then, after writing to file, you do `SET STATUS FAIL` but then you wouldn't know how many hits you got.

**Comment by TrickyPatrick** [comment]
loli script is not mine, so I should just put this code at the end of the script and it will work ? I know 90 of them will hit it's okay

**Comment by TrickyPatrick** [comment]
I found SET STATUT CUSTOM in my code, turned them into FAIL
But I can't find the SET STATUT SUCCESS, is there another way of doing ?

**Comment by openbullet** [comment]
basically you need to convert your final keycheck into a big IF. That's all there is to it

**Comment by TrickyPatrick** [comment]
I finally dit it ! Thank you guys. Sleep well and take care.

**Comment by TrickyPatrick** [comment]
Can I send you my script into discord and you change it for me ? I can't manage to get it work.
I tried hard and changed a lot of value but this is still hitting. (I managed to get the custom out but not the HIT)
My discord: ThoTho#1685

**Comment by TrickyPatrick** [comment]
I will donate more for your amazing help ahah

**Comment by openbullet** [comment]
I think it's better if I implement the option to not save hits to the DB at this point

**Comment by TrickyPatrick** [comment]
Yes please, this is causing a lot of bugs unfortunately. A lot of member of community does not want it and some people even created BATCH to delete DB file but it's not purging it.

**Comment by TrickyPatrick** [comment]
Can you just help me out for now ? I'm not familiar to loliscript and putting it to the end does not do the job. :(

**Comment by TrickyPatrick** [comment]
I DID IT !

I changed:
KEYCHECK BanOnToCheck=FALSE
KEYCHAIN Success OR
KEY "" Exists
IF "" EqualTo "SUCCESS"
#Write_to_File UTILITY File "Hits\MyHits.txt" AppendLines "" -> VAR "Output"
SET STATUS FAIL
ENDIF

To
KEYCHECK BanOnToCheck=FALSE
SET STATUS FAIL

**Comment by TrickyPatrick** [comment]
Thank you for all your help guys !!! Take care !!!

**Comment by Cyber-Criminal** [comment]
> I think it's better if I implement the option to not save hits to the DB at this point

Good, but please set this option in config options
also don't forget 'Custom Hits' too
