### ISSUE TITLE
No UserPass or Mailpass

### ISSUE THREAD

**Issue by gataarrr** [openbullet/openbullet#630]
I don't know why, but i don't have a UserPass or a MailPass. How do i get one of these?

**Comment by openbullet** [comment]
Add them youself in the environment.ini file

**Comment by otf600300** [comment]
Ik having the same problem on openbullet 2 and cannot find that folder

**Comment by otf600300** [comment]
Okay never mind I found the file can someone please send there original file
So I don’t mess up any codings

**Comment by nael-cpu** [comment]
hey, can you help me to do it plss
