### ISSUE TITLE
Provide instructions on how to build for macOS

### ISSUE THREAD

**Issue by GalacticLion7** [openbullet/openbullet#633]
Please provide instructions on how to build OpenBullet for macOS.

**Comment by openbullet** [comment]
OpenBullet is windows-only currently, there are plans to bring it to other platforms in the future though so stay tuned

**Comment by GalacticLion7** [comment]
Any updates?

**Comment by openbullet** [comment]
OpenBullet2 is going to be cross platform, it will be released in a few months.

**Comment by manicxc** [comment]
> OpenBullet2 is going to be cross platform, it will be released in a few months.

is it done?

**Comment by GalacticLion7** [comment]
> > OpenBullet2 is going to be cross platform, it will be released in a few months.
> 
> is it done?

Read the README:
> OpenBullet 1 has reached the end of its life, no more support will be provided for it. Please consider switching to OpenBullet 2 as it will be kept up to date and offers a lot more features.

**Comment by openbullet** [comment]
> is it done?

It really just takes a quick google search to find it https://github.com/openbullet/OpenBullet2
