### ISSUE TITLE
[REQUEST] Block CPM 15 max and Bots to 1 new configs - Be responsible

### ISSUE THREAD

**Issue by ianio9** [openbullet/openbullet#637]
Hello, your tool is AMAZING, but, we need to protect and be responsible with the Web.

I suggest you to avoid reCAPTCHA and Cloudflare, to block CPM to 15 max and Bots to 1 to all new configs.

This is the price for this.

**Comment by openbullet** [comment]
Hi. The tool is open source, if I do that the only thing that will happen is that someone will make a mod with those restrictions lifted and everyone will use the mod. So I don't think this is a good idea.

**Comment by ianio9** [comment]
Please, think about this idea and see if you can make this possible.
