### ISSUE TITLE
BruteForcer Not showing Exact Label ..

### ISSUE THREAD

**Issue by styles977** [openbullet/openbullet#64]
I have delay Function like this one ---> http://prntscr.com/n9un0e
When I shart Bruteforcing --> http://prntscr.com/n9unf1
http://prntscr.com/n9unny
It's very Difficult To debug like this for me :( .. Guess same as Jump function Issue :/ 

Also on using Selenium ... Sometimes There is Navigation Error .. when the error comes Bot just Set it's status to Error and retry again  instead of going to next label :3 . (I want to quit the browser and retry)

On BlackBullet ----->   http://prntscr.com/n9usj9
but on OB ------> http://prntscr.com/n9ustz

I made Specific sites config which uses Selenium Method only sometimes and it works great for some minutes say 5 but after that ... I need to stop and Re.start again or else it will ends on a Loop . I  believe this is OB error not config. Can I mail you the config?. If it is allowed ........

Thank you for reading ^.^

**Comment by openbullet** [comment]
It's fine I don't need the configuration, I understood the problem

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/d4ba3ec1871f6a1ab082a5fa0073a25a3366f8b0
