### ISSUE TITLE
[REQUEST] Include maximum value in random number

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/openbullet#648]
i added a RandomNum function (min = 0, max = 1)
i was wondering why every time the output is equal to 0
i think it's good if you add a checkbox for this, to include the max value in the result

**Comment by openbullet** [comment]
The maximum value is exclusive, this is how it is in 99% of programming languages and i'm not going to change that. Use 0-2 if you want 0 or 1 output

**Comment by Cyber-Criminal** [comment]
99% of programming languages?
OK but some of them have Both modes
like ruby
`puts rand(0..1); # includes 1`
`puts rand(0...1); # doesn't include 1`
you can add this as an option (not to change default)

also 99% of programming languages have no GUI way to code
this did not made you to make OB configs like Storm configs (script only)

**Comment by openbullet** [comment]
I am not going to change it. Period.

**Comment by openbullet** [comment]
People designed it like this in order to use the random function to get a random element from a list, which you can do easily with `list[rand(0, list.length)]`
