### ISSUE TITLE
Length List

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#65]
Hello,

i was testing the Utility > List today, but the moment i was trying to loop each element from the list and execute a function, i have noticed that there is no built in function to return length(list).

the FUNCTION Length return the length of each element, not the list length
<img width="1198" alt="Screen Shot 2019-04-10 at 2 37 47 PM" src="https://user-images.githubusercontent.com/23710158/55884247-a9e81e00-5b9f-11e9-8a38-baf0ccc6b185.png">

so can you add a length(list) function, please

**Comment by openbullet** [comment]
Yeah I'll add it to the utility block

**Comment by ReDDOOne** [comment]
@openbullet can you please add the possibility to create a non-Empty list
or add the possibility to add more than 1 element at time

thanks

**Comment by openbullet** [comment]
You can already do that, just take advantage of the SPLIT in utility block.
E.g. split `a,b,c,d` with separator comma and it will create this list [a, b, c, d]

**Comment by ReDDOOne** [comment]
> You can already do that, just take advantage of the SPLIT in utility block.
> E.g. split `a,b,c,d` with separator comma and it will create this list [a, b, c, d]

there is an issue in this part, same as the ones from before
when there is a switch from stack to loli or the opposite
the code change, which lead to failure
**Before**
![Screen Shot 2019-04-11 at 11 43 07 PM](https://user-images.githubusercontent.com/23710158/55997842-e4db7600-5cb3-11e9-9a3d-e2d57c2771a3.png)
**After the switch to stack**
![Screen Shot 2019-04-11 at 11 43 58 PM](https://user-images.githubusercontent.com/23710158/55997910-2704b780-5cb4-11e9-8835-7a2b6c7df70a.png)
![Screen Shot 2019-04-11 at 11 44 36 PM](https://user-images.githubusercontent.com/23710158/55997930-33891000-5cb4-11e9-95e9-e34cf817762b.png)

also i have noticed, another thing
when i create the code with stack, when i switch to loli
i see that the param[switch = ""], there is no comma
like this

UTILITY Variable "result" Split "" -> VAR "result" 

thank you 
regards

**Comment by openbullet** [comment]
@ReDDOOne Are you sure you're updated with the latest commit? Because I fixed the duplicate variable name here https://github.com/openbullet/openbullet/commit/6b3d1aeb8e66f540bf2a7436584030a761b4b9c7
I also fixed your other bug here https://github.com/openbullet/openbullet/commit/310eb7bc557cd95efb962a5ee8f85d0748894859 and added your feature here https://github.com/openbullet/openbullet/commit/86053cb949eeef72760a02483b1494d82dd7a974
Thanks a lot for reporting!
