### ISSUE TITLE
[REQUEST] PROTOCOL GOOGLE

### ISSUE THREAD

**Issue by Zigoleiro** [openbullet/openbullet#650]
https://developers.google.com/protocol-buffers
**Would it be possible to put the google request protocol as well?
Proto buffer**

**Comment by openbullet** [comment]
This is going to be added in OB2, probably not here

**Comment by libby421** [comment]
show me

**Comment by openbullet** [comment]
Please follow my guide https://forum.openbullet.dev/topic/830/how-to-tackle-protobuf
