### ISSUE TITLE
[BUG] SELENIUM ERROS

### ISSUE THREAD

**Issue by Zigoleiro** [openbullet/openbullet#652]
To execute the function only when you find the ( id, class, name ), if you don't find it locked.
Because it runs non-stop, and makes a mistake when it doesn't find it.
It forces the creators of config, to put excessive delay functions.
Because many times proxies take time to give the answer, and the program runs everything for good, when it doesn't find the answer it wanted it gives error.
or jump to the next block without running the old one.

If it were possible to add a global function that would prevent it from jumping to the next block without running the old one it would be perfect.
or something like that.

**Comment by openbullet** [comment]
You can use ElementAction -> WaitForElement
