### ISSUE TITLE
[BUG] Cloudflare changed their security again

### ISSUE THREAD

**Issue by Artarex** [openbullet/openbullet#654]
See here: https://github.com/RyuzakiH/CloudflareSolverRe/issues/28

OB Version: Newest
OB Error Message: 
<--- Executing Block BYPASS CF --->
ERROR: "The input data has the wrong format" (Translated from german to english)

**Comment by Artarex** [comment]
It seems they found a solution her: https://github.com/RyuzakiH/CloudflareSolverRe/issues/28
However, he is using a an other dependency (netcore) so someone needs to compile / fix it for netstandard so it runs with openbullet

**Comment by openbullet** [comment]
Yes, he added jint as dependency which relies on .NET standard 1.3+ but the library is currently based on .NET standard 1.1

**Comment by Akrelion45** [comment]
Seems like ngosang rewrote some code to make things more stable
But like you said @openbullet  it is now .Net Standart 1.3 for jint
How difficult will it be to make the dll work with openbullet again? (I would try for myself, but sadly not good at it). 
https://github.com/ngosang/CloudflareSolverRe/commit/c08efbad13e7db5a6b75f19fb5147b44a013ebfe

Thanks for your work <3

**Comment by openbullet** [comment]
I did, it compiled but it was throwing a NRE. I'll look into it next week

**Comment by Artarex** [comment]
I got it (somewhat) working
I added the Jint package with nuget to openbullet and with a single thread everything is working.
However multi threading is not working. (I followed your tutorial and did the following things: )
In cloudflaresolver.cs I removed the static keyworkd

And in CloudFlaredetector.cs I removed this:  `private static readonly SemaphoreLocker _locker = new SemaphoreLocker();`

And removed this:
`     await _locker.LockAsync(async () =>
            {
                var cloudflareHandler = new CloudflareHandler(httpClientHandler);

                result = await Detect(httpClient, cloudflareHandler, targetUri, requireHttps);

                //cloudflareHandler.Dispose();
            });`

and

`    await _locker.LockAsync(async () =>
            {
                if (!requireHttps)
                    targetUri = targetUri.ForceHttp();

                detectResult = await Detect(httpClient, targetUri);

                if (detectResult.Protection.Equals(CloudflareProtection.Unknown) && !detectResult.SupportsHttp)
                {
                    targetUri = targetUri.ForceHttps();
                    detectResult = await Detect(httpClient, targetUri);
                    detectResult.SupportsHttp = false;
                }
            });`

But now in Multithreading it is not working. No particular error message, it simply seems to not solve the JS Challenge. HTML view says: [Success] Protection bypassed: NoProtection

(And Single Threading it says [Success] Protection bypassed: JavaScript

**Comment by Artarex** [comment]
Edit: I got it working. 
Just add jint with nuget in Openbullet. And compile. Thats it.

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/690006ac46477b4692ab506f31b8e5d20f76859b
Please close if it worked
