### ISSUE TITLE
Couldn't start

### ISSUE THREAD

**Issue by livinghacker** [openbullet/openbullet#655]
Whenever I try to open Bullet, nothing happens the circle in the Cursor rotates and then nothing. I tried different version from google yet found no solution.

**Comment by openbullet** [comment]
How am I supposed to debug the issue with the little information you gave?

**Comment by openbullet** [comment]
Are you unpacking the archive before running it? Can you use version 1.2.1 and see if it creates a Log.txt file when you start? If it does, paste me the crash dump. Do you have the .NET framework 4.7 installed?

**Comment by livinghacker** [comment]
THANKS THE PROBLEM IS SOLVED
