### ISSUE TITLE
Openbullet not opening

### ISSUE THREAD

**Issue by livinghacker** [openbullet/openbullet#660]
My openbullet was working fine, but now it is not opening, Please help.

**Comment by openbullet** [comment]
You already posted on forum, why post here too?

**Comment by sudhirs63** [comment]
Mine same problem

**Comment by sudhirs63** [comment]
It's processing but not opening and not any error msg giving..what I do?
I tried it on all is 7,8,8.1 and 10 also

**Comment by noarche** [comment]
Install dependency

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by sudhirs63** [comment]
From where I get dependence

**Comment by openbullet** [comment]
It's a database problem, rename your OpenBullet.db file inside the DB folder so OB can make a new one.

**Comment by noarche** [comment]
How to build

- Make sure you have installed the .NET framework (dev) 4.7.2.

- Clone this repository and open the solution file with Visual Studio.
- Switch to Release mode for a much cleaner output.
- Build the solution (Visual Studio will fetch all the missing nuget packages).
- You can find the executables inside the folders OpenBullet/bin/Release and OpenBulletCLI/bin/Release.

SOURCE: https://github.com/openbullet/openbullet

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Armaan879** [comment]
same i got the problem too, i have the .NET framework, i cant see a file named openbullet.db and i dont have a db or ob folder, i cant seem to make it work what do i do

**Comment by openbullet** [comment]
Just shout "Open, Bullet!" and pray 🤣 
Jokes aside though, OB1 has a lot of issues that have been solved in OB2 please make the switch. OB1 is no longer supported.

**Comment by CRAZYN1NJA** [comment]
I figured out the issue and the solution:
Issue diagnosis: the tool is blocked from receiving and or sending transmissions by windows firewall defender (always blocking when it's not needed, am i right?)

Anyway, to solve this issue:
navigate through the following,
1. windows security
2. windows defender
3. firewall settings
4. advanced firewall settings
5. inbound rules

Then:
1. add rule
2. it will ask if you want to whitelist a program, port or folder 
3. in the prompt, navigate to openbullet folder and select it
4. allow all network requests.

If that doesn't fix it, do it for outbound rules too!
