### ISSUE TITLE
[REQUEST][BUG]HMAC hex/UTF-8 digest support.

### ISSUE THREAD

**Issue by Muayyad1999** [openbullet/openbullet#663]
Hello Ruri,

I've been trying to use HMAC function lately and I faced an issue, There's an Amazon AWS service that has a signature which uses HMAC-SHA256, that computes date and region and service name for the AWS 4, **Check reference**, The issue is I'm trying to calculate the signature in OpenBullet, But it doesn't give me the same results,
The algorithm of the signature is:
A secret key mixed with a "AWS4", for example, We got the key (wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY) and then we put AWS4 in the prefix to get AWS4wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY.
Using the secret key we got as a secret key for HMAC to calculate the first HMAC function, Putting the date as input in the Input field in OB, The date stamp is going to be YYYYMMDD, For example "20120215", And by calculating that as SHA256 hash, We should get "969fbb94feb542b71ede6f87fe4d5fa29c789342b0f407474670f0c2489e0a0d", Which I've successfully got the same value in OB function, But for the next step which is calculating the value we got with the region, Let's say the region of the service is "us-east-1", For this I made another block of function for HMAC to calculate it, For the secret key we're going to use the value we got from calculating date and secret as a secret, And the input is the region "us-east-1", For this I should get "69daa0209cd9c5ff5c8ced464a696fd4252e981430b10e3d3fd8e2f197d7a70c", But instead, I've got "78657665155BC911468F8410028DFA4AB7576E274FAD500B46D9981CE694BE0D" because in process it treats the value we got as a string not as HMAC-SHA256 to convert it into UTF-8 or something like that,

Sorry for taking too long, Thanks in advance.

Reference: [Signature calculating examples](https://docs.aws.amazon.com/general/latest/gr/signature-v4-examples.html)

**Comment by openbullet** [comment]
Hello, please try something like this

```
SET VAR "KEY" "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY"
SET VAR "DATE" "20120215"
SET VAR "REGION" "us-east-1"
SET VAR "SERVICE" "iam"
UTILITY Conversion UTF8 BASE64 "AWS4<KEY>" -> VAR "KSECRET_B64" 
UTILITY Conversion BASE64 HEX "<KSECRET_B64>" -> VAR "KSECRET_HEX" 
FUNCTION HMAC SHA256 "<KSECRET_B64>" HmacBase64=TRUE KeyBase64=TRUE "<DATE>" -> VAR "KDATE_B64" 
UTILITY Conversion BASE64 HEX "<KDATE_B64>" -> VAR "KDATE_HEX" 
```

**Comment by openbullet** [comment]
https://forum.openbullet.dev/topic/846/how-to-generate-an-aws4-signature
