### ISSUE TITLE
ERROR: Value is either too large or too small for Type 'Int32'.

### ISSUE THREAD

**Issue by ajay1998A** [openbullet/openbullet#665]
Maybe this ia dumb question but i cant seem to find any help so asking here :
I want to multiply unixtime by 1000, but when i do that i get this error : 
**ERROR: Value is either too large or too small for Type 'Int32'.**
I don't know where to change the datatype from it.
Any help would be appreciated
Thank you

**Comment by openbullet** [comment]
Hello, have you tried using the constant function and adding 3 zeroes to the end of the string? Like this FUNCTION Constant "<UNIXTIME>000". You can achieve the same exact result.
