### ISSUE TITLE
[BUG] CPM is awful now..

### ISSUE THREAD

**Issue by time2moveon** [openbullet/openbullet#669]
I just want to emphasize how bad this issue is to processing combos. The problem is pretty  straightforward.. no complicated steps to reproduce.. from 1000+ CPM to "barely" a 100 CPM??
At that rate it would take a week+ just to process a 100-200K combo... before a few hours.
I don't know what changed in the OB code, but it's excruciating slow to the point of unbearable.
using the latest version: 1.2.2
Is there a fix/solution on the way?

**Comment by openbullet** [comment]
You should tell me in which version it was working fine so I can pinpoint the issue and find the commit that broke it.

**Comment by time2moveon** [comment]
I'm going to close this issue. Went back and tried some older versions and ran multiple configs, Looks like the configs are at fault.
