### ISSUE TITLE
Requirement on PASS is not working

### ISSUE THREAD

**Issue by botboyz67** [openbullet/openbullet#67]
I had that problem and opened an issue for that.

I was using `<PASS>` instead of PASS.

Now, yes i feel that OB is going faster. It's still not as fast as BB.

For exemple i have a wordlist that the first 50k need to be ignored because password doesn't pass requirement. 1 number, 1 Uppercase, 1 lowercase and 8 to 12 caract.

While BB jump directly to 50k and go extremely fast because he is not trying a lot of combo. 
20k cpm

OpenBullet still is at 1k cpm max, it's faster than it was but still taking time.

Tried deleting completly config and doing it again and same problem.

The wordlist is in MailPass type in both.
![Capture4](https://user-images.githubusercontent.com/43886593/55895969-43590500-5b8b-11e9-9c54-8615648552b4.PNG)
![Capture5](https://user-images.githubusercontent.com/43886593/55895972-45bb5f00-5b8b-11e9-8507-e5d5d3dddec5.PNG)

![Capture](https://user-images.githubusercontent.com/43886593/55895808-e8bfa900-5b8a-11e9-8bd3-b44550efb1e2.PNG)
![Capture2](https://user-images.githubusercontent.com/43886593/55895811-e9f0d600-5b8a-11e9-9fbe-1a5e6279e9c3.PNG)
![Capture3](https://user-images.githubusercontent.com/43886593/55895860-08ef6800-5b8b-11e9-962c-5b0ecc2cc9a2.PNG)

BTW, THANKS FOR ALL YOUR TIME. U ARE AMAZING

**Comment by openbullet** [comment]
I don't think I can do much about this, I changed the way the program checks if an input is valid so maybe this is why it takes longer. Maybe someone else can try?

**Comment by ReDDOOne** [comment]
with regex from the env.ini you can match the requirement length
^<reEmail>:(.){8,12}$
as if you want to check for LowerUpperDigits, you can do something like
^<reEmail>:[a-zA-Z0-9]{8,12}$
BUT  in this way, regex sees this as, the string should be ([a-z] or [A-Z] or [0-9]) -> with length of 8-12

third option: you can do with FUNCTION regexmatch inside the config

or you can custom your list before

**Comment by openbullet** [comment]
Those are things anyone can do, it doesn't require me to change the code.

**Comment by botboyz67** [comment]
Yeah it look like it's checking if the input is valid after starting the bot.

In bb, it check the input and if it's correct, it launch it.

It's way faster.
With the FUNCTION regexmatch, it's still slow.
With regex, i dont understand how i can change it so it check requirements in password and not email.

**Comment by botboyz67** [comment]
openbullet - could you give me the last code before you changed it and tell me how to change it maybe ?

:s

**Comment by openbullet** [comment]
Don't worry I think I'll take a look myself, I already have a lead on where it might be

**Comment by shdf2** [comment]
i confirm, that situation is quite annoying, when you have a Faster BB 2.5.2 which is going to die at the end of the month (Even if you paid for it) and a slower OB...

**Comment by openbullet** [comment]
@botboyz67 If you look inside the code, the check is performed by the master worker not by the bots so it's not like you say. I'll try to have someone test the speed of the rules.

**Comment by openbullet** [comment]
I'm not really sure I can do anything about this, the speed is a little bit worse but nothing unbearable.

**Comment by openbullet** [comment]
Moreover, The CPM that you see is because BB counted the skipped ones inside the CPM, while OB does not! So that's why there is a massive CPM discrepancy.
