### ISSUE TITLE
[REQUEST] New view for Configs/Manager

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/openbullet#674]
Hi,
may u please add new view option in Configs/Manager
like windows explorer that there is folders, users can open folders to see it's content and return..
it's great for users with many configs
Thanks

**Comment by openbullet** [comment]
No sorry I'm not going to do this. I am reworking the config manager for OB2 so look forward to that.

**Comment by Cyber-Criminal** [comment]
good, i'm excited for OB2

i run a separated OB Process for every config
because of proxies, i can't add diff proxy lists/api for each config
and most of settings that are not same for earch config, are only in general settings
please fix this problems is OB2, ty

**Comment by openbullet** [comment]
Yes I am reworking everything also taking into considerations issues from github so most of them will be fixed out of the box in OB2
