### ISSUE TITLE
Copy-Paste in response source broken

### ISSUE THREAD

**Issue by FFaez1267** [openbullet/openbullet#677]
Whenever you try to copy paste from openbullet debugger source this gets copied to the clipboard 

**{"$type":"System.Collections.Generic.List`1[[RuriLib.BlockBase, RuriLib]], mscorlib","$values":[{"$type":"RuriLib.BlockParse, RuriLib","ParseTarget":"<SOURCE>","VariableName":"USD Balance","IsCapture":true,"Prefix":"","Suffix":"","Recursive":false,"DotMatches":false,"CaseSensitive":true,"EncodeOutput":false,"CreateEmpty":false,"Type":2,"LeftString":"","RightString":"","UseRegexLR":false,"CssSelector":"","AttributeName":"","CssElementIndex":0,"JsonField":"currentBalance","JTokenParsing":false,"RegexString":"","RegexOutput":"","Label":"PARSE","Disabled":false}]}**

Ways to recreate 

1. Open OpenBullet

2. Go to configs tab

3. Select any config

4. Send a request of any sorts

5. Copy any part of the source response 

6. Try to paste in any of the boxes of the parse function and the json from above gets pasted

**Comment by openbullet** [comment]
This only happens to some people and I'm not sure how to reproduce it because I never had this issue on my stacker. Anyways there is 1 simple way to disable that feature, just go to settings and disable Ctrl+C/V in blocks.
