### ISSUE TITLE
[BUG] Could not solve the captcha! 

### ISSUE THREAD

**Issue by shaneilahi** [openbullet/openbullet#679]
[DeathByCaptcha] Balance: $10
Could not solve the captcha! Exception of type 'CaptchaSharp.Exceptions.TaskSolutionException' was thrown.

**Comment by openbullet** [comment]
This is not an OB issue it's an issue with DBC, can you try using another service? Which kind of captcha are you trying to solve?

**Comment by shaneilahi** [comment]
funcaptcha

**Comment by openbullet** [comment]
It was working when we tested it, could you kindly write me on the forum https://forum.openbullet.dev and provide me the website so I can see if we get the same error?
