### ISSUE TITLE
[REQUEST] Improve selenium mode:  generating User agent

### ISSUE THREAD

**Issue by kazemmoridi** [openbullet/openbullet#681]
**Is your feature request related to a problem? Please describe.**
when i want to use , user agent in some website, it would said that "Provisional headers are shown" and there is no change in user agent when i ticked random user agent. and it's always same. 

**Describe the solution you'd like**
i think open bullet should change selenium tab by add some changes like what you have done in UA generator Function block and add a custom user agent where user can put their own user agent there.

**Comment by kazemmoridi** [comment]
This function is needed for some site that need special custom user agent list

**Comment by Itamai** [comment]
hello @kazemmoridi,

i tested the "Use Random User Agent" function for selenium and it worked. It is in other options > selenium.
I got three different user agents in three tests and tested/confirmed it on https://www.whatismybrowser.com/detect/what-is-my-user-agent
in the same option window there is a field where you can input custom user agent if needed.

![image](https://user-images.githubusercontent.com/53093696/82760699-9aed1b00-9df5-11ea-8a81-4342c267e019.png)
