### ISSUE TITLE
[BUG]Generating the same random string

### ISSUE THREAD

**Issue by kazemmoridi** [openbullet/openbullet#682]
**Is your feature request related to a problem? Please describe.**
when  i try to use random string function when checking for a code number, it would repeat the same random number multiple times, for instance, when i check for 8 hours there was 1400 times random string were repeated again. 

**Describe the solution you'd like**
Add a new feature so, it would not use the same repeated code in that runner (with the same config and word list)

**Comment by openbullet** [comment]
Which version of OB are you using? The problem was fixed in 1.2.0 or 1.2.2 i think

**Comment by kazemmoridi** [comment]
I just checked with the latest official version and it was fixed thnx alot
