### ISSUE TITLE
[REQUEST] Loop count as variable

### ISSUE THREAD

**Issue by Cyber-Criminal** [openbullet/openbullet#691]
Hi

please add loop count as variable
instead of banning after specified loop times because of "Ban Loop Evasion"-
i wanna set another status or doing something else, like
`IF "<LOOPCOUNT>" EqualTo "25"`
`SET STATUS FAIL`
`ENDIF`

thanks

**Comment by openbullet** [comment]
There is already a fixed variable like this it's called `<RETRIES>`

**Comment by Cyber-Criminal** [comment]
@openbullet 
Where i can find list of fixed variables?
i did not found it in documentation

can i get current unixtime without making a variable for it?
or hash a text like `MD5("<PASSWORD>")`

**Comment by openbullet** [comment]
The guide was here https://forum.openbullet.dev/topic/17/fixed-variables

In OB2 you will be able to write C# in your configs so what you say will be certainly possible, just study a bit of C# if you want to be ready ^^

**Comment by Cyber-Criminal** [comment]
@openbullet 
is ERRORs counted as RETRIES?
i made a URL Checker, some urls are not OK and status is ERROR all time
but `Ban Loop Evasion` not send them to TOCHECKs
![image](https://user-images.githubusercontent.com/41063376/82823178-646fd880-9ea7-11ea-959a-2a36b5f78bed.png)
