### ISSUE TITLE
[BUG] JSON FORM DATA VARIABLES

### ISSUE THREAD

**Issue by LilStalk** [openbullet/openbullet#695]
**Describe the bug**
```<USER> and <PASS>``` variables doesn't work in JSON POST DATA

**Expected behavior**
https://imgur.com/lAxER23
This is working. Key Succes.

https://imgur.com/0t0f6SV
This is not working. Key Fail.

**Version**
 - Version LATEST

**Comment by openbullet** [comment]
This is not a bug and it has been asked a thousand times. Please learn to search.
