### ISSUE TITLE
Error im getting

### ISSUE THREAD

**Issue by James94665** [openbullet/openbullet#7]
Hi there, i am currently getting the error below.
http://prntscr.com/n6dd2t

Would it be possible for you guys to release a precompiled version?

**Comment by Choempie** [comment]
You have to add Extreme.net DLL: https://github.com/heavilessrose/Extreme.Net
There is also a compiled version here: https://anonfile.com/s9X8u1X7m3/OpenBullet1.0.0_rar

**Comment by James94665** [comment]
Thanks
