### ISSUE TITLE
if we run the code in log for 5 times the old logs of 5 are present in log

### ISSUE THREAD

**Issue by playernoob-droid** [openbullet/openbullet#702]

**Comment by meinname** [comment]
i don't really understand what you're saying.
But maybe it has to do with having this enabled? - Try to disable it:
<img width="183" alt="image" src="https://user-images.githubusercontent.com/16181408/83335314-37a73100-a2ac-11ea-89ec-84a4e221dc57.png">

**Comment by playernoob-droid** [comment]
mm ty for help it worked
