### ISSUE TITLE
JS execution is slow

### ISSUE THREAD

**Issue by ghost** [openbullet/openbullet#71]
Hello,
today, i had to execute a hash (sha256) with a number of iteration
but i have noticed that OB is very slow executing this.
ps : i am using sjcl lib

in my nodejs, the hash is executed in a matter of 1 to 2 seconds
in OB, it is executed in a time of 21 to 25 seconds. same for BB 

![Screen Shot 2019-04-11 at 8 26 37 AM](https://user-images.githubusercontent.com/23710158/55939114-dbf78f80-5c34-11e9-9063-c50c4544b56f.png)

as for the built-in FUNCTION HASH SHA256 with a while loop
it is taking even more time, because of all the logging from the loop

**Comment by openbullet** [comment]
That's just a debugger thing, cause it gets printed so there are UI calls etc.
If you run it in the Runner with Bot Log disabled it will be fast.
Also mind that a js interpreter is created and ran from the .net code so it's waaay heavier than the real thing, if you need speed you're better off writing your own thing in node, hosting it locally and just poll the result with a http request from OB. Sorry but I can't solve this, it's intrinsic of Jint.

**Comment by ReDDOOne** [comment]
@openbullet check js execution in storm
it is built in C# and it is hosting a dll file to execute this
and it gives almost the same result as the real thing
please, review this part, i really wanted it to work
(sorry to compare with another app, i had to)

**Comment by openbullet** [comment]
Alright I'll give it a look and if needed I'll change  the library I'm using

**Comment by ReDDOOne** [comment]
how about this https://github.com/JavascriptNet/Javascript.Net 
:)

**Comment by meinname** [comment]
Sorry for bringing up this old thing:
wouldn't be https://www.nuget.org/packages/Edge.js/ more fun?

**Comment by grugruxking** [comment]
fuck you

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by meinname** [comment]
Nice comment. 
But why? - Is Edge.js not to recommend?

**Comment by GunnGrave** [comment]
close this one as you have already updated Jint in 1.2.1
