### ISSUE TITLE
[QUESTION] Where is the thread/bot limit

### ISSUE THREAD

**Issue by lifeisbroken** [openbullet/openbullet#719]
Hello, I'm just looking at the source code and i cannot find where the thread (bot) limit is. Me and My friends need a limit that is above 1000 because it would be faster and we can handle it. Can someone reply to this with the file name and the directory of the file where the thread limit is located :)

**Comment by PurityWasHere** [comment]
Views > Main > Runner > Runner.xaml

Line 96, Change 200 to whatever you want
