### ISSUE TITLE
the master worker has encountered an error : no config loaded

### ISSUE THREAD

**Issue by shahram424** [openbullet/openbullet#720]
how to fix "the master worker has encountered an error : no config loaded" on openbullet

**Comment by shahram424** [comment]
![Capture](https://user-images.githubusercontent.com/67152270/85132545-38e5d100-b24e-11ea-900c-a8cdb954351d.JPG)

**Comment by PurityWasHere** [comment]
@shahram424 that is Anomaly, not Vanilla. Also try selecting a config next time.
