### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by shlok8749831769** [openbullet/openbullet#722]
When my recaptcha key ends, I always have to get another trial from a website and its frustrating to manually put the keys over and over again in the settings

**Describe the solution you'd like**
I want a feature where the recaptcha key can be parsed and used in the config, I dont need to go to settings and  manually put it in.

Or

I put a bunch of recaptcha keys in a TXT file and it rotates them at every check.

**Comment by openbullet** [comment]
This feature was already asked so it's either already open or i decided to not do it.

**Comment by shlok8749831769** [comment]
> This feature was already asked so it's either already open or i decided to not do it.

Please add this, I will give you some API keys ;)

**Comment by openbullet** [comment]
Why do you have multiple API keys in the first place? And plenty of services allow you to transfer credit from 1 account to the other, so just do that

**Comment by shlok8749831769** [comment]
> Why do you have multiple API keys in the first place? And plenty of services allow you to transfer credit from 1 account to the other, so just do that

Its because Im using a website which gives 0.02 USD credit oer signup and i will just bot it and get lots of keys,
 "transfer credit from 1 account to the other" does AZcaptcha allow that?

**Comment by openbullet** [comment]
I'm pretty sure what you are doing is against their TOS

**Comment by shlok8749831769** [comment]
> I'm pretty sure what you are doing is against their TOS

lol idc, i want free recaptcha bypass

**Comment by shlok8749831769** [comment]
all i can request is you add a <AZCAPTCHAKEY> parse in the blocks

**Comment by openbullet** [comment]
Sorry I'm not going to do this

**Comment by shlok8749831769** [comment]
> Sorry I'm not going to do this
why not? is it because im breaking TOS or ur too lazy

**Comment by openbullet** [comment]
Because of the TOS. I don't support things that could get me in legal trouble.

**Comment by shlok8749831769** [comment]
oh ok, but in the TOS it doesnt say anything like that?
