### ISSUE TITLE
[REQUEST] in Blocks add block use proxy or this block proxyless

### ISSUE THREAD

**Issue by amrmostafa800** [openbullet/openbullet#728]
in Blocks add Choose between
1 - use default proxy (Like the current)
2 - block been proxyless (this block dont use proxy)
3 - custom proxy (this block use Fixed proxy different from the others blocks)
and thanks for good work

**Comment by openbullet** [comment]
You can do all this with loliscript, check out the documentation. In short:
```
SET USEPROXY FALSE
##PROXILESS BLOCK HERE
SET USEPROXY TRUE
##PROXIED BLOCK HERE
SET PROXY "127.0.0.1:8888"
SET PROXYTYPE SOCKS5
##USING ANOTHER PROXY
```

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
Good idea
