### ISSUE TITLE
[BUG] CAPTCHA BALANCE/ WRONG TOKEN CREDENTIALS

### ISSUE THREAD

**Issue by MorrisForest** [openbullet/openbullet#729]
I have no way of using captcha service. I get the bug error BALANCE/ WRONG TOKEN CREDENTIALS.
I have loaded credit, and have edited my host files. 
Anyone know what else to do? 

1.open ob
2. settings
3.captchas
4. insert service, api
5. get error

**Comment by openbullet** [comment]
Could you please say which captcha service is giving the error exactly?

**Comment by MorrisForest** [comment]
anticaptcha

**Comment by openbullet** [comment]
Are you on the latest official 1.2.2?
Anti-Captcha works perfectly here so it has to be a problem on your end. Do other tools that use anti-captcha work?
