### ISSUE TITLE
Only Retries

### ISSUE THREAD

**Issue by SpaceR3** [openbullet/openbullet#731]
Hey, I am only getting retries.
Those proxies work, they are bought HQ and work with other tools just fine.
The config works too, or should at least.

**Comment by openbullet** [comment]
Check if your Environment.ini is compatible with the config you're using

**Comment by SpaceR3** [comment]
Yes it is.

Turns out my proxy provider is blocking any Minecraft and Spotify request.
On other services like Hulu it works fine.

problem solved
