### ISSUE TITLE
[BUG] Proxy Checker Performance

### ISSUE THREAD

**Issue by aimeti** [openbullet/openbullet#735]
**Proxy Checker Performance**

When importing a list of Proxies (Amount of 10-20k) it checks the proxies to test on www.google.com and its title for the first 1-1.5k proxies normally after that amount being checked already it goes really slow. In older version, the proxy checker was performing better. Is there any chance of fixing this or do you know any other sites to test on?

**Comment by openbullet** [comment]
You'll have to wait for OpenBullet 2. In the meantime there are many good proxy checkers such as the one from GSA. I do not plan to improve OB1's proxy checker so i'll close this.

**Comment by torquetraction** [comment]
https://bing.com
Keyword <html
