### ISSUE TITLE
CF bypass Block Problem with Socks4/5 

### ISSUE THREAD

**Issue by mehdi199919** [openbullet/openbullet#736]
Hello Ruri i tried to use proxy Socks4/5 to checking but i just getting retries, it work well with HTTP proxy type but i think we have a problem with socks list. TnQ for listening

**Comment by openbullet** [comment]
There is already an issue about the fact that CF Bypass doesn't work anymore

**Comment by mehdi199919** [comment]
Are you sure? Weird It works well for me maybe my case use older version of cloudflare
