### ISSUE TITLE
[REQUEST] Feature to save the parse output

### ISSUE THREAD

**Issue by DarkScripting** [openbullet/openbullet#737]
Would be nice to have a feature u can save the output of the parse

**Comment by openbullet** [comment]
I have no idea about what you mean, please explain.

**Comment by DarkScripting** [comment]
like a save option for parse that saves the capture of parse the variable
the result

**Comment by DarkScripting** [comment]
that would be really nice

**Comment by openbullet** [comment]
I really don't understand. This feature is already present, just tick the "is capture" box...

**Comment by DarkScripting** [comment]
So u can save the text to a text file

**Comment by DarkScripting** [comment]
the output of the result when parsing to save that to a text file

**Comment by openbullet** [comment]
Yes, UTILITY block -> Files group -> Write
Put your variable there like <MYCAPTURE> and choose the path of the file, it will save it there

**Comment by DarkScripting** [comment]
so it will save the output from the parse block

**Comment by DarkScripting** [comment]
it doesnt save the output of the parse Parsed variable | Name: Test | Value: 4b60eadd-0775-4993-b574-6f8e73e6432e

**Comment by DarkScripting** [comment]
its hard to explain

**Comment by DarkScripting** [comment]
oh thanks it works now
solved
