### ISSUE TITLE
Missing User Pass in latest build.

### ISSUE THREAD

**Issue by Pabsb** [openbullet/openbullet#74]
Latest build is missing user pass option so doing a check for a gift card per say would not work.

**Comment by openbullet** [comment]
Read the documentation on how to add a new wordlist type to the environment.ini file. Also I'm pretty sure you're up to something illegal which does not belong here.

**Comment by Pabsb** [comment]
I bot trade on Gameflip.com so I need a program that will auto check codes that i buy and sell so i dont lose money.

**Comment by Pabsb** [comment]
> Read the documentation on how to add a new wordlist type to the environment.ini file. Also I'm pretty sure you're up to something illegal which does not belong here.
