### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by g0dev** [openbullet/openbullet#740]
Hi, the new version looks so good.
![image](https://user-images.githubusercontent.com/55219735/88292728-a0fd5c00-ccbf-11ea-9ea6-15f674a623a7.png)
in the Data Pool section, could u add a "Hitlist from Database" or something similar? 
This let us to use directly the hits (success and customs) from other configs stored on our database on ob. 

Thanks for the amazing job

**Comment by openbullet** [comment]
There will be a way to do that, and this is really not the place to discuss features of the next version, as I said on the forum post everything is subject to change. When the open beta will be released you will be able to post issues on its own repo, do not post here thanks.
