### ISSUE TITLE
[REQUEST] .anom to .loli

### ISSUE THREAD

**Issue by Aryamaan08** [openbullet/openbullet#741]
I have some .anom files but they are not being detected. Is there a way to convert them to .loli

**Comment by openbullet** [comment]
Change the extension

**Comment by dolomon007** [comment]
how to change extention

**Comment by BanditRazu** [comment]
rename from .anom to .loli

**Comment by thaisonho** [comment]
I still got an invalid data exception error when I changed the extension to .loli
