### ISSUE TITLE
ERROR: It turned out wait for a connection to the HTTP-server 

### ISSUE THREAD

**Issue by SpaceR3** [openbullet/openbullet#742]
When making any requests i just get this error: ERROR: It turned out wait for a connection to the HTTP-server 'trustallservices.ml'.

I have used it before, and everything has been working. I have no idea why did it break.

Not using any modded ones. RAW from this github

**Comment by SpaceR3** [comment]
note: it does not work with any website. Trustallservices is just my website for testing

**Comment by meinname** [comment]
works for me
![image](https://user-images.githubusercontent.com/16181408/88934079-79d6f980-d280-11ea-9d67-3d7ab36c6d31.png)
tested with and without proxy - also with http and https
