### ISSUE TITLE
[BUG] Ban proxy after Good Status not saved

### ISSUE THREAD

**Issue by M3T4LL1C4** [openbullet/openbullet#75]
**Describe the bug**
The Ban proxy after Good Status setting is not saved.

**To Reproduce**
I check the checkbox, click on save. When I exit OB and restart it, the checkbox is blank

**Expected behavior**
Remember the setting

**Screenshots**

**Version**
 - Version 1.0.0

**Additional context**

**Comment by openbullet** [comment]
Done, sorry about it https://github.com/openbullet/openbullet/commit/2a89bdb07204011fd40655a95bfb4dc3986ea638
