### ISSUE TITLE
[REQUEST] Choose which blocks to use proxies with

### ISSUE THREAD

**Issue by shlok8749831769** [openbullet/openbullet#756]
I need a feature where I can choose which blocks I want to use proxies with. It is a problem because I need to test my website and another external website (temp mail api) but my website only works with my IP and the temp mail is not available in my country.

**Describe the solution you'd like**

Being able to choose which blocks I want to use proxy with

**Describe alternatives you've considered**
No alternative

**Comment by openbullet** [comment]
This already exists through loliscript directives, please see the SET command in the loliscript documentation inside Stacker.
