### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TrillyReign** [openbullet/openbullet#758]
**Describe the bug**
When inserting post data, or trying to modify the URL in a request block, the values < USER > & < PASS > do not work. It just inserts "< USER >" or "< PASS >" into the post data. or URL. 

**To Reproduce**
1. Make a request block
2. Insert < USER > into the URL
3. Run the config
4. Look at the log data

**Expected behavior**
When inserting < USER > or < PASS > in other versions, it would replace it with the correct value, such as < SOLUTION > with Captchas. Maybe I'm confusing it with a mod...correct me if I am please

**Version**
 - Version 1.2.2

**Comment by Laiteux** [comment]
Try `<USER>` and `<PASS>`, remove the spaces

**Comment by openbullet** [comment]
https://forum.openbullet.dev/topic/8/environment-ini-a-common-problem/6
