### ISSUE TITLE
IF WE RUN  .JS LINK OF A SITE  AS REQUEST  IN OB2

### ISSUE THREAD

**Issue by pasterlevis** [openbullet/openbullet#759]
IF WE RUN  .JS LINK OF A SITE  AS REQUEST  IN OB  IT MUST AUTOMATICALLY EXECUTES AND  SHOW US A RESULT LIKE IN BUILT BROWSER AND PUT THIS OPTION IN OB2.  FOR EXAMPLE IF A COOKIES GENERATES FROM JS IN BROWSER  AUTOMATICALLY WHILE USING REAL BROWSERS AND ADD SOME FEATURES LIKE SCREENSIZE ETC

**Comment by openbullet** [comment]
Use selenium
