### ISSUE TITLE
Conditions with Lists

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#76]
**Describe the bug**
While Checking if an element is inside a **LIST** , i have noticed that there a bug
when the list has one element, the conditions are working correctly
when the list has two or more elements, the conditions does not work
by conditions, i mean (Contain, DoesNotContain)

**To Reproduce**
1. Go to REQUEST, Exec this GET "https://httpbin.org/cookies/set?cookie1=openbullet1" -H "accept: text/plain"
2. Go to KEY CHECK, Check this KEY "<COOKIES{*}>" DoesNotContain "cookie1"  
3. Switch Between DoesNotContain/or/Contain, you will see that the block return a correct result
4. Now to see the error, change the Url to "https://httpbin.org/cookies/set?cookie1=openbullet1&cookie2=openbullet2" and Repeat 2. and 3.

**Screenshots**

**when there is 1 element in the list**
<img width="1018" alt="Screen Shot 2019-04-13 at 1 16 15 AM" src="https://user-images.githubusercontent.com/23710158/56071934-e37c7d00-5d89-11e9-9c79-718bbd1e2e86.png">
<img width="1018" alt="Screen Shot 2019-04-13 at 1 16 40 AM" src="https://user-images.githubusercontent.com/23710158/56071935-e7100400-5d89-11e9-8b77-6383d85aa8f3.png">

**when there are more elements**
<img width="1043" alt="Screen Shot 2019-04-13 at 1 21 05 AM" src="https://user-images.githubusercontent.com/23710158/56072013-9d73e900-5d8a-11e9-9113-9064dc165c7c.png">
<img width="1046" alt="Screen Shot 2019-04-13 at 1 22 17 AM" src="https://user-images.githubusercontent.com/23710158/56072014-a06ed980-5d8a-11e9-8f63-a80a95a923ab.png">

**Version**
 - Version 1.0.1
- Commit 84

**Comment by openbullet** [comment]
What you are doing is not quite correct. When you use a list or dictionary in the keycheck it will simply test the condition on ALL elements of the list and if one is found to be true then the key will trigger.
What you want to use here is the condition EXISTS which will check if a certain cookie exists, so please try to do `<COOKIES(cookie1)>` (with round brackets since you are looking for a cookie Name, not Value!).
Let me know if this worked, thanks.

**Comment by ReDDOOne** [comment]
Help me understand this also:
i called this url: "https://httpbin.org/cookies/set?cookie1=openbullet1" (i will set the cookie1)
Here i tried to check if "cookie1" exist, the result is good
![Screen Shot 2019-04-13 at 11 22 41 AM](https://user-images.githubusercontent.com/23710158/56078321-92e33f00-5dde-11e9-9a43-c661180aa40e.png)
Here, i tried to check if "cookieX" exist, the "cookieX" is not there, but it did trigger the key
![Screen Shot 2019-04-13 at 11 23 18 AM](https://user-images.githubusercontent.com/23710158/56078324-98408980-5dde-11e9-9c87-3b1dea25b6c5.png)

Until here, is it a mistake i have done, or something else ?

**Request**
Can you add **DoesNotExist** condition

**Expected behavior**
sometimes, when calling a url with proxies, some proxies could redirect to some weird pages, such ("this web site X is banned in this region", "...")
So just to make sure that i am out of those, i need to ban a proxy if the response cookies does not have a particular cookie.

I hope you understand my case
Best regards

**Comment by openbullet** [comment]
Yeah that's definitely a bug, I will fix it thank you

**Comment by openbullet** [comment]
It will work now https://github.com/openbullet/openbullet/commit/3167186e4f7204230f9fba1d30f2880d907f005d thank you ^_^

**Comment by ReDDOOne** [comment]
@openbullet thanks to you
i hope to see the opposite of the condition exists soon
or
a way to check if an element is inside an list

**Comment by openbullet** [comment]
I can implement DoesNotExist ^_^

**Comment by ReDDOOne** [comment]
> I can implement DoesNotExist ^_^

@openbullet Don't forget this Please
