### ISSUE TITLE
[REQUEST] Add support for docker container as soon openbullet 2 (Web) works fine

### ISSUE THREAD

**Issue by CyberPoison** [openbullet/openbullet#760]
It will be nice to have openbullet to have support for docker container just to not have to install dependencies on the host directly. 

Kind regards

**Comment by openbullet** [comment]
I don't understand why you post OB2 ideas on the OB1 repo. Docker support is already planned.

**Comment by CyberPoison** [comment]
I'm not able to register on the forum it says
Email domain not accepted 
Also with my company mail, prontomail, and Gmail

**Comment by openbullet** [comment]
Thanks for letting me know, I think I fixed the issue. Could you try again please?

**Comment by CyberPoison** [comment]
No same issue 😢
![Screenshot_20200916_233833_com android chrome](https://user-images.githubusercontent.com/60718477/93395235-d2387980-f875-11ea-8e06-41a95d32ff3d.jpg)

**Comment by openbullet** [comment]
I fixed it for real now, had to restart the forum in order for the changes to take effect. Sorry about it!
