### ISSUE TITLE
include this feature in ob2 to run js file in it

### ISSUE THREAD

**Issue by pasterlevis** [openbullet/openbullet#763]
[SCRIPT]
SET VAR "theUserEmail" "<USER>"
SET VAR "theUserPassword" "<PASS>"
SET VAR "SilverBullet" ""
BEGIN SCRIPT JavaScript "<BASEDIR>Configs\MegaNzHash.js"
END SCRIPT -> VARS "hash"

include this feature in ob2

**Comment by openbullet** [comment]
Already done
