### ISSUE TITLE
like this make .py file to run in ob2

### ISSUE THREAD

**Issue by pasterlevis** [openbullet/openbullet#764]
[SCRIPT]
SET VAR "theUserEmail" ""
SET VAR "theUserPassword" ""
SET VAR "SilverBullet" ""
BEGIN SCRIPT JavaScript "Configs\MegaNzHash.js"
END SCRIPT -> VARS "hash"

like this make .py file to run i ob2

**Comment by openbullet** [comment]
Already implemented, why do you open useless issues? 99% of OB1 features are going to be in OB2.
