### ISSUE TITLE
[PROBLEM] proxy problem

### ISSUE THREAD

**Issue by itsArminEm** [openbullet/openbullet#768]
hello 
thanks for ur great app
i have a problem
when i  use debugger without proxy it works fine ( with vpn ! )
but when i add proxy (http,socks4,5) it doesnt work and response is empty and it shows me this :
ERROR: Unable to connect to the HTTP-server "example.com"
im sure proxy is working
i tested proxy on my most configs and it didnt work but i test another configs (not mine) and it works
is there my quality of proxies problem ?
ill be happy if u help me
tnx a lot

**Comment by rohan-patra** [comment]
I'm having the same issue, anyone find a solution?

**Comment by wuyunerge** [comment]
我也是，不知道咋弄

**Comment by wuyunerge** [comment]
I'm having the same issue, anyone find a solution?

**Comment by openbullet** [comment]
OB1 is not supported anymore, switch to OB2

**Comment by jojansel** [comment]
yo estoy teniendo problema con los proxy
