### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Myztical1** [openbullet/openbullet#77]
**Describe the bug**
When data is not found to capture, gives an error even though u have valid credential for whatever site ypu debugging. 

Error
https://imgur.com/joJnslr.png

**Screenshots**
https://imgur.com/joJnslr.png

https://imgur.com/wJNEOpq.png

**Version**
 - Version [e.g. 1.0.1]

**Example**
Data to capture   {""I love OB"} but like BB more...
LS  {""    RS "}  Capture > I love OB
If  I love OB not found error is generated.

**Comment by ReDDOOne** [comment]
the example you provided is working correctly, and there is no error 
![Screen Shot 2019-04-13 at 3 08 14 PM](https://user-images.githubusercontent.com/23710158/56080945-42300e00-5dff-11e9-888d-4e594eef15bb.png) 

that error happens only when you have a problem on your params
for example:
String = "abcdefghijklmnopqrstuvwxyz"
Case 1:  LS = "abcde"  | LR = "efghij"  >>>> on this case, you are going to get the error
Case 2: LS = "abcde"  | LR = "fghij"  >>>> return null, no error

![Screen Shot 2019-04-13 at 3 25 59 PM](https://user-images.githubusercontent.com/23710158/56081028-7b1cb280-5e00-11e9-9b6d-abe1772ae7bf.png)

so just fix your LS n LR params !

**Comment by openbullet** [comment]
Would you guys like it better if a blank value was inserted when the parse fails or are you fine with the ERROR status?

**Comment by ReDDOOne** [comment]
> Would you guys like it better if a blank value was inserted when the parse fails or are you fine with the ERROR status?

An empty string would be
thanks

**Comment by Myztical1** [comment]
> the example you provided is working correctly, and there is no error
> ![Screen Shot 2019-04-13 at 3 08 14 PM](https://user-images.githubusercontent.com/23710158/56080945-42300e00-5dff-11e9-888d-4e594eef15bb.png)
> 
> that error happens only when you have a problem on your params
> for example:
> String = "abcdefghijklmnopqrstuvwxyz"
> Case 1: LS = "abcde" | LR = "efghij" >>>> on this case, you are going to get the error
> Case 2: LS = "abcde" | LR = "fghij" >>>> return null, no error
> 
> ![Screen Shot 2019-04-13 at 3 25 59 PM](https://user-images.githubusercontent.com/23710158/56081028-7b1cb280-5e00-11e9-9b6d-abe1772ae7bf.png)
> 
> so just fix your LS n LR params !

You getting error not success when no data is present

**Comment by openbullet** [comment]
I'm pretty sure I solved this with https://github.com/openbullet/openbullet/commit/2650c65fc210a42ccb4ad7c959f89b82ee912142
