### ISSUE TITLE
proxy bug

### ISSUE THREAD

**Issue by keratinontor** [openbullet/openbullet#772]
the bug is just simple, it detects every proxy as wrong, even though it was checked with a proxy checker. u test it on google and the success key is title>google. it claims they were all wrong.

**Comment by openbullet** [comment]
I highly doubt that this is an OB issue, otherwise everyone else would be talking about it. The problem is on your end. Can you give more info about what kind of proxies you're using (type, if auth or no auth) and if you're using the proxy checker and OB from the same IP.
