### ISSUE TITLE
Install on Kal!

### ISSUE THREAD

**Issue by 750000** [openbullet/openbullet#778]
How can I Install it on Kali Linux?

**Comment by openbullet** [comment]
OpenBullet 1 is windows-only, so if you want to use it in kali linux you need a virtual machine.
OpenBullet 2 will be cross platform so it will be able to run natively on linux as well. Stay tuned for OB2 release in a few months!

**Comment by allelive** [comment]
ciao sto usando ob2 ma mi die sempre errore ricaricare la pagina, qualsiasi cosa io faccio. puoi aiutarmi grazie
