### ISSUE TITLE
Proxy Manager success key problems

### ISSUE THREAD

**Issue by ZyDoxx** [openbullet/openbullet#780]
I made a config for https://www.habbo.nl/. 
When i try to test my proxies on that specific website using the url and success key feature , none of the proxies succeed. I am sure some (about 40) of the proxies work because some can get hits when running the config.

I use the title as the success key just like the default google.com setting. ( title>Google )

The sites title is as following:
<title>Maak vrienden, doe mee en word gezien! - Habbo</title>

I figured i am supposed to enter it like:
title>Maak vrienden, doe mee en word gezien! - Habbo

Despite changing the titles and links i can get it to work on the site www.habbo.nl. Any other site works fine for testing the proxies using the default title success key.

Is this simply an issue with this site or can i use another method to get it to work?

**Comment by Wanted135** [comment]
What's a config dude ? And is it your website for you to try to pentest it ?
