### ISSUE TITLE
[BUG] unwanted header

### ISSUE THREAD

**Issue by winuser** [openbullet/openbullet#79]
**Describe the bug**
unwanted header added to the custom header

**To Reproduce**
I don't know whether this only applies to cloudflare cfg only as this issue does not occur in non cloudflare cfg. http://prntscr.com/nbi37i 
In the request block even if the custom header are blank https://prnt.sc/nbatd1 those three header are being added, you can specify a Accept header, but Accept: */* will always be added, also for pragma and user agent. This shouldn't be the case.

**Expected behavior**

**Screenshots**

**Version**
 - Version [e.g. 1.0.1]

**Additional context**

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/2df8e52f92d996b74351dd281dd84f44d45294cb

**Comment by ewwink** [comment]
it still append header `Accept-Encoding: gzip,deflate` and I can't override this. it could be problem in `Extreme.Net` ?

**Comment by openbullet** [comment]
Open a new issue @ewwink this one is closed.
