### ISSUE TITLE
Could someone help me with an error that I have?

### ISSUE THREAD

**Issue by ivanazaelm** [openbullet/openbullet#792]
I have a problem, I resolve a recaptcha and I keep getting this captcha error: c

{"appId":"PXAFlYiz9n","jsClientSrc":"/px/PXAFlYiz9n/init.js","firstPartyEnabled":true,"vid":"","uuid":"d3f04870-6a80-11eb-a7fa-a7c9dbaa6645","hostUrl":"/px/PXAFlYiz9n/xhr","blockScript":"/px/PXAFlYiz9n/captcha/captcha.js?a=c\u0026m=0\u0026u=d3f04870-6a80-11eb-a7fa-a7c9dbaa6645\u0026v="}

my open version is 1.4.4

help me please

**Comment by openbullet** [comment]
Unofficial version, use 1.2.2
