### ISSUE TITLE
Crashes upon startup

### ISSUE THREAD

**Issue by SkyFallRBLX1232** [openbullet/openbullet#798]
OpenBullet does not open in general at all. No error codes, no nothing.

**Comment by openbullet** [comment]
OB1 reached the end of support, please move to OB2.

**Comment by SkyFallRBLX1232** [comment]
> OB1 reached the end of support, please move to OB2.

OB2 does the same.

**Comment by openbullet** [comment]
> 
> 
> > OB1 reached the end of support, please move to OB2.
> 
> OB2 does the same.

Then comment on this issue https://github.com/openbullet/OpenBullet2/issues/243
