### ISSUE TITLE
Question about the proxy checker

### ISSUE THREAD

**Issue by M3T4LL1C4** [openbullet/openbullet#8]
Hi,

Does it check if the proxies are anonymous or only if they are working (ie could be transparent)?

I see nothing in the settings how to set a proxy judge or something like that.

Thanks.

**Comment by meinname** [comment]
It only checks, if Source of the the URL you define contains what is configured in Success Key when accessed via the Proxy and answers within the time from the timeout.
No judge or smth like that.

**Comment by openbullet** [comment]
I think Choempie is working on this, if he manages to implement it I will push it here.
