### ISSUE TITLE
[BUG] Jobs seems to not work fine for me

### ISSUE THREAD

**Issue by FakeException** [openbullet/openbullet#804]
When i start the job it spams an error like this in console and it seems that its not finding/testing anything, i tried both Spotify and Minecraft configs but none of them is working.

![image](https://user-images.githubusercontent.com/51448775/122083098-dc85a500-ce00-11eb-8e9a-d419be3a1f5f.png)

![image](https://user-images.githubusercontent.com/51448775/122083227-f626ec80-ce00-11eb-8df1-d460e34f8b93.png)

 - Version 0.1.16

**Comment by openbullet** [comment]
This repository is for openbullet 1 you're on the wrong one.
