### ISSUE TITLE
[BUG] OpenBullet + XEvil bug

### ISSUE THREAD

**Issue by WhiteFC** [openbullet/openbullet#806]
Hello.

I really don't know if it's a bug, but I really hope you can help me.

I'm using Openbullet and XEvil, and at the beginning everything was great, I solved captchas very fast, and I had my own proxy service. 

While testing some account combos, I noticed that OpenBullet got stuck on "bad: 72". which I found very strange. I checked XEvil, but I saw that it was still resolving the catpchas, and giving them as good, only in OpenBullet, it didn't appear as if it had been an attempt. I restarted all programs, restarted my computer, but none of this worked. Now when I try to put a combolist, XEvil says it is solving captchas, but in OpenBullet.... Not a trace

I know it's a bit confusing, that's why I'll also leave a video so you can see what I mean.

https://www.youtube.com/watch?v=P1ZyTlEikr8

I would appreciate any help. Thank you very much!

PD: I have also tried revisiting the host file, deleting the XEvil parameters and creating them again, and none of this works.

**Comment by openbullet** [comment]
I do not provide any more support for OB1, sorry. Please switch to OB2.

**Comment by openbullet** [comment]
Also I saw that you're performing illegal activity, I'm deleting this issue.
