### ISSUE TITLE
[BUG] KeyCheck for errors

### ISSUE THREAD

**Issue by emlin2019** [openbullet/openbullet#808]
So, I have a service im trying to pentest. Now the problem is that the "redirect_url" redirects to an url that can only be used on a phone. (a special url like for example "magnet:")

OpenBullet interprets that as an IP and tries to connect. Which then throws the error 

"ERROR: Specified argument was out of the range of valid values.
Parameter name: port"

Is there a way to ignore errors and do the keycheck anyways?

I tried editing the redirect_url but the service doesnt allow it (security reasons)

EDIT: Nevermind. I was using the anomaly version. "Ignore Response" option doesnt work well there.

**Comment by openbullet** [comment]
Sorry, OB1 is not supported anymore, please switch to OB2.
