### ISSUE TITLE
[REQUEST]  Unable to cast object of type "LiteDB.EmptyPage" to type "LiteDB.DatePage

### ISSUE THREAD

**Issue by Seliaxx** [openbullet/openbullet#809]
hello guys hope  you can help me with this first time happend to me here is the full error 
![Screenshot 2021-07-12 205618](https://user-images.githubusercontent.com/87335367/125342093-b34f2a80-e354-11eb-9463-d406cb9a624d.png)

**Comment by openbullet** [comment]
OB1 is not supported anymore. You could try this but I cannot guarantee that it works, otherwise I cannot provide any more help.
https://forum.openbullet.dev/topic/1977/ob-crashed-cuz-of-big-data-in-openbullet-db-any-solution/4
