### ISSUE TITLE
[BUG] Error Handle in KEY CHECK

### ISSUE THREAD

**Issue by ReDDOOne** [openbullet/openbullet#81]
**Describe the bug**
the response return an epoch expiration date
so to determine weather it is Custom or Success
i am comparing the epoch expiration date VS Current epoch date (Greater/less Than)
Until here all is good when the response has that epoch expiration date

the problem is happening when it is a Failure and there is no epoch expiration date

**To Reproduce**
1. Set an Empty var and another var with the current unix time
2. Compare both (use conditions Greaterthan and lessthan)

**Expected behavior**
the app should handle the error and not throw a "BOT STATUS: ERROR"

**Screenshots**
<img width="1445" alt="Screen Shot 2019-04-14 at 9 24 18 AM" src="https://user-images.githubusercontent.com/23710158/56090334-05b0f080-5e99-11e9-8a8d-ad2e2e082991.png">
<img width="1455" alt="Screen Shot 2019-04-14 at 9 25 14 AM" src="https://user-images.githubusercontent.com/23710158/56090336-08134a80-5e99-11e9-9d2f-433a4573b897.png">
as you can see, even if the Failure key is ON, still it return and error

**Version**
 - Version [e.g. 1.0.1]
- Commit 87

best regards
thanks

**Comment by openbullet** [comment]
Well your sub_and_epoch variable is empty what did you expect? You should first check if the epoch variable is not empty using an IF-ELSE construct in LS! I'm not going to fix this in any other way, sorry.

**Comment by ReDDOOne** [comment]
@openbullet i am not OK, just with the "BOT status : ERROR"
while making a config, you can not have an idea of all the variants problems that could happen.

so at least, the app would throw the ERROR NAME and procede with the block or stop
in this case i will get a BOT STATUS : NONE, and i will be able to check the error and fix it.

When the Bot status: ERROR occur, it keep the bot looping and looping 
and this does not help me at all

i hope you understood the case

**Comment by openbullet** [comment]
Well OB told you that it couldn't parse the input, a.k.a an empty string cannot be casted to an integer. I think the error's pretty informative. Also you should really do this
```
IF "<abc>" EqualTo ""
SET STATUS FAIL
ENDIF

KEYCHECK ...
```
Or 2 keychecks in succession like this
```
KEYCHECK
  KEYCHAIN FAILURE OR
    KEY "<ABC>" EqualTo ""

KEYCHECK
  KEYCHAIN SUCCESS ...
```

**Comment by openbullet** [comment]
Anyways maybe I'll do it, meinname is pushing to change this behaviour too.

**Comment by ReDDOOne** [comment]
thanks you ^_^ ^_^ ^_^

**Comment by meinname** [comment]
:P 
yep - all Errors in Blocks shoudn't set Error Status for the bot.

Beside the Requests and CF block - but can be set to ignore the error too by setting  the "ignore response errors" switch in config
