### ISSUE TITLE
Banned? 

### ISSUE THREAD

**Issue by TheExxotik** [openbullet/openbullet#810]
i need help why is every cfg saying banned or error? and is not hiting anything like it not even saying it bad

**Comment by openbullet** [comment]
Environment.ini problem for sure, search on the old forum. OB1 is not supported anymore, please switch to OB2.

**Comment by TheExxotik** [comment]
no its on ob2

**Comment by openbullet** [comment]
This is the repository for OB1 do you realize that?

**Comment by TheExxotik** [comment]
o mb

**Comment by openbullet** [comment]
Anyways, you have the wrong Wordlist Types in the Environment.ini file for sure, please read this guide.
https://discourse.openbullet.dev/t/comprehensive-guide-to-wordlist-types/435
Usually the Environment.ini is included by people who share configs.
