### ISSUE TITLE
[QUESTION] the content length of POST DATA send by openbullet in request

### ISSUE THREAD

**Issue by unmonstre2018** [openbullet/openbullet#812]
Hello, how to get (in the "Parse" section) : 

--> the content length of POST DATA send by openbullet in request

please thanks you

**Comment by openbullet** [comment]
You need to use the function block not parse block. The function is Length and you can type `<SOURCE>` as input to get the length of the source.

**Comment by unmonstre2018** [comment]
hello thanks for the response but : 

- the lenght of POST DATA (not the source) in Openbullet
  exemple: <USER>&<PASS>

thanks you very much

**Comment by unmonstre2018** [comment]
--> <USER>&<PASS> in POST DATA in openbullet

< USER > & < PASS > in POST DATA in openbullet (without the space)

**Comment by openbullet** [comment]
OB1 is not supported anymore, please switch to OB2
