### ISSUE TITLE
DeathBycaptcha Problem

### ISSUE THREAD

**Issue by HenryCross1** [openbullet/openbullet#813]
Hello , 

Deathbycaptcha is not working in openbullet used same info worked in another application how cani fix this?

**Comment by openbullet** [comment]
OB1 is not supported anymore, please switch to OB2 and open this issue on the OB2 repository here https://github.com/openbullet/OpenBullet2/issues

**Comment by openbullet** [comment]
Also, just tried on OB2 and it works perfectly, so just switch to OB2 and your issue should be fixed ^^
