### ISSUE TITLE
Error ssl conexión 

### ISSUE THREAD

**Issue by Alexpechin** [openbullet/openbullet#815]
This happens to someone else, help me
![100090300957_73737](https://user-images.githubusercontent.com/81532760/134989857-22b9d594-329f-4cca-bacb-e946c162ff47.jpg)

**Comment by Alexpechin** [comment]
This happens to someone else, help me

**Comment by openbullet** [comment]
There is an issue with HTTP proxies which has been fixed, please wait for the new version or build it yourself. Otherwise if you also get it without proxies it probably means there's no internet connection
