### ISSUE TITLE
[BUG] Cannot Parse token

### ISSUE THREAD

**Issue by shdf2** [openbullet/openbullet#82]
There is a problem with the PARSE block when there is a "\\" in the strings delimiters

![image](https://user-images.githubusercontent.com/37487684/56091310-9db8d500-5ead-11e9-9d09-506d95374ea1.png)

![image](https://user-images.githubusercontent.com/37487684/56091317-a7423d00-5ead-11e9-898d-1357c7c9d201.png)

**Comment by kekermen** [comment]
try to do 

ico_upload\\"><\/span>
<
just add another \ to your \

**Comment by shdf2** [comment]
thanks ! it works

**Comment by NoB1rDs** [comment]
cant help without some actual data.

**Comment by openbullet** [comment]
This is the same as issue https://github.com/openbullet/openbullet/issues/62 I'll close this
