### ISSUE TITLE
auto proxyauth whit selenium

### ISSUE THREAD

**Issue by mamamiia** [openbullet/openbullet#827]
I cant use proxy whit this format on selenium ip:port:user:pass
the browser keep asking for user:pass for the proxy 
I have some sources I hope you can fix it 
https://github.com/SeleniumHQ/selenium/issues/10042
https://coderedirect.com/questions/158523/how-to-set-proxy-with-authentication-in-selenium-chromedriver-python
https://www.py4u.net/discuss/141444
https://botproxy.net/docs/how-to/setting-chromedriver-proxy-auth-with-selenium-using-python/

**Comment by openbullet** [comment]
OB1 is not supported anymore, sorry

**Comment by mamamiia** [comment]
what about ob2 can i use it

**Comment by openbullet** [comment]
@mamamiia did you already open an issue on the OB2 repo about this? If you did, maybe link it here and then wait for it to be implemented.

**Comment by mamamiia** [comment]
I don't know if is work on ob2

**Comment by openbullet** [comment]
@mamamiia It most likely will not work since I ported selenium over from OB1 without changing much. So open an issue on the OB2 repo and wait for me to implement it in one of the next updates.

**Comment by mamamiia** [comment]
ok thanks
