### ISSUE TITLE
[REQUEST] Please Add Cookie Option In Prase 

### ISSUE THREAD

**Issue by Mus18** [openbullet/openbullet#83]
Please Add cookie option in prase i cannot make a lot of configs because there are no cookie option in prase but its available in blackbullet please add it in openbullet

**Comment by blurar** [comment]
check the Docs mate! it's already on it.
Just do : <COOKIES(the cookie name)>
and for a cookie that name changes , you can use the cookie value char,num,even symbols.
just do : <COOKIES {e8+=}> , this will bring you the cookie name as a var.
