### ISSUE TITLE
[BUG]open bullet  processing block request

### ISSUE THREAD

**Issue by ertu63** [openbullet/openbullet#830]
hello i want to use openbullet but i have this error can one help me

**Comment by openbullet** [comment]
OB1 is not supported anymore, switch to OB2

**Comment by Arman2Mali** [comment]
I'm using OB1 I have an error on HTML view.It shows You dont have permission to access on this server while make the config.Can u help meee

**Comment by openbullet** [comment]
@Arman2Mali maybe my reply wasn't clear enough? OB1 is not supported anymore, switch to OB2
