### ISSUE TITLE
AzCaptcha not working

### ISSUE THREAD

**Issue by hatehax0r** [openbullet/openbullet#851]
Dear Openbullet developer, i wanted to tell you about an issue that i had with openbullet,

recently i bought some captcha balance on azcaptcha.com because i saw its included in the openbullet captcha modules,

when i entered my api key it said wrong key so i decided to use http debugger to look what the issue is and i saw that openbullet isnt sending requests to azcaptcha.com but to 2captcha, i changed the request url from 2captcha to azcaptcha and it showed the balance just the problem is i cant check because its still sending these requests to the 2captcha api.

Please fix this problem so that it sends the requests to azcaptcha instead of 2captcha.

Greetings.

**Comment by openbullet** [comment]
Hi, openbullet 1 is not supported anymore. This is probably something I fixed in OB2 so I suggest you make the switch to OB2, I will not maintain OB1 anymore sorry.
