### ISSUE TITLE
[BUG] How to fix this ?

### ISSUE THREAD

**Issue by Kojot1312** [openbullet/openbullet#854]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to copy file "obj\Release\OpenBullet.exe" to "bin\Release\OpenBullet.exe". Could not find file 'obj\Release\OpenBullet.exe'.	OpenBullet

**Comment by openbullet** [comment]
Hello, sorry but OB1 is not supported anymore, switch to OB2
