### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Crysiz2631** [openbullet/openbullet#863]
Ive just bought rotating proxies but they are user:pass not ip:port:user:pass

how can i use this? https://imgur.com/a/BGaMyaZ

**Comment by Aholicknight** [comment]
Embedded image:
![image](https://user-images.githubusercontent.com/7843719/195638007-9dd0e520-f799-4da3-8c36-051abd69bf88.png)

**Comment by Crysiz2631** [comment]
I do not get the IP.. so I can't use it?

**Comment by Crysiz2631** [comment]
It does not have a API it looks like this:

http://gw.ntnt.io:user:pass

**Comment by Aholicknight** [comment]
> It does not have a API it looks like this:
> 
> http://gw.ntnt.io:user:pass

![image](https://user-images.githubusercontent.com/7843719/195640983-5e0a2fe0-2109-4353-b347-71813f63efa8.png)

@Crysiz2631 if you click PHP what are the other options?

**Comment by Crysiz2631** [comment]
![Screenshot_2022-10-13-17-35-26-409_com android chrome](https://user-images.githubusercontent.com/92895983/195641409-bc58190f-31f7-48bf-b918-337c96ea1b31.jpg)

**Comment by Aholicknight** [comment]
> It does not have a API it looks like this:
> 
> http://gw.ntnt.io:user:pass

@Crysiz2631 use this and see if it works

**Comment by Crysiz2631** [comment]
it wont even add the proxy 
![image](https://user-images.githubusercontent.com/92895983/195642865-c0047457-91b9-42ac-8320-c175d8c9ef88.png)

**Comment by Crysiz2631** [comment]
nvm i added it but don't work

**Comment by Crysiz2631** [comment]
:/ all the IP:user:pass proxy sites where you can buy is expensive..
