### ISSUE TITLE
[REQUEST] can be load multi combolist in runner

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#87]
for example when i click wordlist in runner and select multi combolist with press shift but just load 1 combo not my all selected one :3

**Comment by NoB1rDs** [comment]
Or just drag and drop them.

**Comment by Teals53** [comment]
İ dont talk about in wordlist section im talking about in runner

**Comment by openbullet** [comment]
No sorry, just use some program that merges wordlists (I suggest emeditor for working with huge files).

**Comment by Teals53** [comment]
why no :(
