### ISSUE TITLE
[BUG] Using operators in url

### ISSUE THREAD

**Issue by sufiyanashraf** [openbullet/openbullet#876]
My request URL has the '+' and '&' operators in the link. but when I paste and request it performs a mathematical operator and goes to the wrong URL.
For Example, My URL looks like; "scope=openid+profile+email&state=&prompt=login" but it goes to "scope=openid profile email".
How can I fix it?

**Comment by sufiyanashraf** [comment]
Bump!

**Comment by openbullet** [comment]
The + means a space. If you want to actually send a + symbol you have to URL encode it. Look into URL encoding and learn about it.
