### ISSUE TITLE
[BUG] authentication_error

### ISSUE THREAD

**Issue by sabracx** [openbullet/openbullet#879]
I have this problem when I use POST I get none and when I use GET I get token problem

Response Source:
{
	"success": false,
	"error": [ 
	{ 
		"type": "authentication_error"code": "missing_authentication_token", 
		"message": "" 
	} ], 
	"status": 403 
}
------------------------------------------------------------
Response Source:
None
------------------------------------------------------------

Version
 - Version 1.4.5

**Comment by BlueStrawBerrys** [comment]
im pretty sure this isnt a openbullet bug rather your config not working if you want u can dm me your site and ill remake it for you telegram @l03stv1
