### ISSUE TITLE
[BUG] OB wont open if I have configs in the configs folder 

### ISSUE THREAD

**Issue by ThaFrenchQuater** [openbullet/openbullet#880]
When I don't have any configs in the configs folder the program opens like normal.
If I add a config while the program is still open and i go to scan for configs in the folder the program crashes and won't open till the config(s) are removed .
stuff shows up in the logs txt so ill send that here 
[Log.txt](https://github.com/openbullet/openbullet/files/10819796/Log.txt)
Also im using version 1.2.2

**Comment by BlueStrawBerrys** [comment]
u got all the runtimes installed ? and u tried running it as admin ?

**Comment by openbullet** [comment]
Please switch to OB2, OB1 is out of support
