### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Medory13** [openbullet/openbullet#883]
How to use regex parsing?
The regex is works in regexmatch function, but it's not working in regex parsing, Idk how to use output box..

regex: anyexample
output: 1

results: [1, 1, 1, 1, ...]

![image](https://user-images.githubusercontent.com/108600718/223860746-5ce0a575-eddb-4368-a589-a6b07ae4ab32.png)

**Comment by openbullet** [comment]
You have to write `[0]` in the output field, which means print the group at index 0 (a.k.a. the full match). There are guides about this on the internet.
