### ISSUE TITLE
[BUG] how to use Keycheck for unknown Success

### ISSUE THREAD

**Issue by M3d-Edge** [openbullet/openbullet#887]
Hello, im making config Email valider to validate in reset password page of an website but the problem is that website has only one status says "Email sent" im new to openbullet i have no idea how to validing with Keycheck
screenshot of status on reset password page https://i.imgur.com/uB1gw13.png

i have done single token i just need solution for keycheck please any help will be grateful

**Comment by TugoUwU3976** [comment]
you need to know the key of fail and put success DoesNotContain in <SOURCE> for example in the image:
![image](https://user-images.githubusercontent.com/132511023/236047890-2b984cf1-eef2-4f05-9750-aa3d77464492.png)

**Comment by RifHut** [comment]
u can try this methode  :

//your condition for example 
IF "<SOURCE>" contains "status: TRUE"
//do here the keycheck condition 
ELSE
SET STATUS SUCCESS
ENDIF
