### ISSUE TITLE
Add Cookies to openbullet 2

### ISSUE THREAD

**Issue by Godfatheron** [openbullet/openbullet#888]
Hey guys I was working with openbullet 1 i make config normally but i I wanted an experience openbullet 2 but i dont understand it i dont know how to add cookies on it 
The cookies is : bsid

![Screenshot_2023-04-14_180706](https://user-images.githubusercontent.com/130494672/232111040-dc750b83-f599-4fdf-a192-186dcf01b61e.jpg)

**Comment by openbullet** [comment]
It's `data.COOKIES["bsid"]` please read the LoliCode documentation on the forum or inside the program itself by clicking on the icon in the lower left corner. Also this is the wrong repo for this :3
