### ISSUE TITLE
[BUG] How to use SET for custom status? 🫤

### ISSUE THREAD

**Issue by Samsung2023** [openbullet/openbullet#889]
using flow control, you can set status to success or fail using the "SET" command, Example: "SET status fail/success". But If you type "SET status custom" you will get ERROR... 
So is there anyone have a put status to custom using SET ?

**Comment by openbullet** [comment]
I really don't remember but I think it was SET STATUS CUSTOM CUSTOM where the 2nd custom is the name of your custom status configured in the environment file
