### ISSUE TITLE
[REQUEST] windows options like other software

### ISSUE THREAD

**Issue by Teals53** [openbullet/openbullet#89]
for example when i double click program in title its need go full screen or windowed screen but its not xd and when i click fullscreen button then click OB title and move this its go move but still fullscreen its need back windowed screen like other programs :3

**Comment by Teals53** [comment]
kk

**Comment by ForlaxPy** [comment]
@Teals53 feature added you can close this now

**Comment by Teals53** [comment]
no not all done yet ?

**Comment by openbullet** [comment]
@Teals53 in order to achieve what you want I would have to remove the custom black window top bar and put the boring ordinary white one. It will look bad, I don't want to do that. If I find another way, I'll do it.

**Comment by Teals53** [comment]
oh kk
