### ISSUE TITLE
is there a way to make the runner stop if i got the hit (one hit) ?

### ISSUE THREAD

**Issue by Starduster2018** [openbullet/openbullet#897]
i use it to brute some data with increment of 1 and i want to find out the key (password) by bruting and i want it to stop after getting the hit ?
any idea with loli code ?

**Comment by derbal5** [comment]
![لقطة الشاشة 2023-12-31 015751](https://github.com/openbullet/openbullet/assets/114672091/6c571682-6276-4005-833c-496addc29ede)
for all config

**Comment by Starduster2018** [comment]
Thanks 🙏
