### ISSUE TITLE
BasicAuth broken?

### ISSUE THREAD

**Issue by M3T4LL1C4** [openbullet/openbullet#9]
Hi,

Apparently it's broken, or I don't understand all how it works with openbullet.

I have some valid combos for some websites but I always get 401 reponses with openbullet in the debugger (same thing in the runner). With blackbullet, it's 200 as expected. By the way these websites have no special protection.

I see that the basic auth block is no more with openbullet. Apparently now, we have to use a request block and select BasicAuth in the Request Type menu. It's what I did. I tried GET, HEAD, POST methods, same 401 response.

Log:
```
<--- Executing Block REQUEST --->
Calling URL: https://xxxxxxxxxxxx.com/members/
Sent Headers:
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
Pragma: no-cache
Accept: */*
Authorization: Basic Og==
Sent Cookies:

Address: https://xxxxxxxxxxxx.com/members/
Response code: 401
Received headers:
Date: Tue, 02 Apr 2019 14:20:55 GMT
Server: Apache
WWW-Authenticate: Basic realm="Members Area"
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 290
Keep-Alive: timeout=3, max=60
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1
Received cookies:
Response Source:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Authorization Required</title>
</head><body>
<h1>Authorization Required</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>
```
While with black bullet I get:

```
<--- Executing Block BASIC AUTH --->
Calling URL: https://xxxxxxxxxx.com/members/
Address: https://xxxxxxxxxxx.com/members/
Status code: 200
Received headers:
Date: Tue, 02 Apr 2019 14:44:21 GMT
Server: Apache
X-Powered-By: PHP/7.2.16
Cache-Control: max-age=0, no-cache, no-store, must-revalidate
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Vary: Accept-Encoding,User-Agent
Content-Encoding: gzip
Content-Security-Policy: upgrade-insecure-requests;
Access-Control-Allow-Origin: *
Pragma: no-cache
Content-Length: 9486
Keep-Alive: timeout=3, max=60
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
Received cookies:
Response Source:
<!DOCTYPE html>
```
Maybe it has something to do with the custom headers that are sent by openbullet. But I can't manage to avoid them. Even if delete them and save the config, they are sent. And back when I reload the config.

I also notice:
`Authorization: Basic Og==`
It looks it sends a blank login/password or something like that, instead of the actual combo.

**Comment by Zero-HL** [comment]
Switch to loliscript 
![image](https://user-images.githubusercontent.com/49173169/55428991-a0046080-558a-11e9-933b-59222e67e1be.png)

and you'll see under you Get and set username and password
![image](https://user-images.githubusercontent.com/49173169/55428975-94189e80-558a-11e9-8b71-93fd5d068814.png)

**Comment by openbullet** [comment]
Thank you for making me realize the block info page is lacking textboxes for Username and Password. I will make a commit today to fix it.

**Comment by openbullet** [comment]
Fixed with commit https://github.com/openbullet/openbullet/commit/434ee3a4c5018d656f541516327ef658faa0749a
