### ISSUE TITLE
[REQUEST] JA3 spoofing 

### ISSUE THREAD

**Issue by cr998** [openbullet/openbullet#905]
**Before you begin**
There are some anti-bot system that are implementing validations on ssl handshake, if vou visit one site behind cloudflare your request get 403

**Is your feature request related to a problem? Please describe.**
Is an feature

**Describe the solution you'd like**
Implement something like [https://github.com/Danny-Dasilva/CycleTLS](https://github.com/Danny-Dasilva/CycleTLS)

**Describe alternatives you've considered**
i was looking for a native solution in c# along one week, but i didn't found any other solution.

**Comment by CryptoContact** [comment]
https://github.com/FlareSolverr/FlareSolverr 

Direct your post request through that

**Comment by cr998** [comment]
Okey, but it will be usefull if we could avoid use an headless browser to bypass JA·3 sign, i didn´t ask about cloudflare evasion

**Comment by openbullet** [comment]
OB1 is not supported anymore. Please continue this discussion on the OB2 repo, there are already issues that track this.
