### ISSUE TITLE
hcaptcha

### ISSUE THREAD

**Issue by topfotl** [openbullet/openbullet#915]
Gettin error when tryin to use hcaptcha solver block, others are working just fine
"[Executing block Solve H Captcha] JsonReaderException: Error reading JObject from JsonReader. Path ‘’, line 0, position 0. "

**Comment by openbullet** [comment]
OB1 is not supported anymore, switch to OB2

**Comment by rifat84** [comment]
[Executing block Solve H Captcha] TaskCreationException: ERROR_METHOD_CALL (One of the parameters is incorrect.)


what is the problem?
