### ISSUE TITLE
[BUG] Send to Recheck Start Error

### ISSUE THREAD

**Issue by caspertheghost1337** [openbullet/openbullet#95]
I select all from one config in Hits DB, then send to recheck, and this error occurs.
"The Master Worker has encountered an error: Object reference not set to an instance of an object."

**Comment by openbullet** [comment]
Is it working after this commit? https://github.com/openbullet/openbullet/commit/90ca84272f592d147883415ce6d4a926a3235d10

**Comment by openbullet** [comment]
Closing because no feedback from user.

**Comment by caspertheghost1337** [comment]
> Closing because no feedback from user.

Sorry, forgot to reply. This works on the latest release. Thanks!
