### ISSUE TITLE
[BUG]  rules for wordlists pass do not work

### ISSUE THREAD

**Issue by beer14** [openbullet/openbullet#96]
**Describe the bug**
The rules for wordlists password do not work, If I enable one option it works, example digit, but if I enable other options with it does not work.

**To Reproduce**
https://gyazo.com/252a180d76919fd135979bf290d7cc0b

**Expected behavior**
Fix

**Screenshots**
https://i.gyazo.com/c27468340c3a9340e09a79a03a359de4.png
https://i.gyazo.com/669a289a2b950b95e87c8e471fd851a5.png

**Version**
1.0.1

**Additional context**

**Comment by openbullet** [comment]
https://github.com/openbullet/openbullet/commit/f5330c97387d545f65199eded0ce3e23f9cb0ed9 Thanks for reporting, done
