### ISSUE TITLE
[BUG] New Update 1.2.2.2 Gives a Fake Hits

### ISSUE THREAD

**Issue by Mus18** [openbullet/openbullet#98]
![image](https://user-images.githubusercontent.com/49616911/56300753-33b75e80-613f-11e9-95ee-1f0198a800fb.png)
In this picture its not hit its fake hit
See : 
![image](https://user-images.githubusercontent.com/49616911/56301083-c48e3a00-613f-11e9-8149-426a9fb60f1f.png)
![image](https://user-images.githubusercontent.com/49616911/56301132-da9bfa80-613f-11e9-8157-2637660592ee.png)

**Comment by openbullet** [comment]
This is not the Forlax mod's repo, this is the official repo. Plus you're clearly doing illegal things. You are now banned from posting to this repository.
