### ISSUE TITLE
[BUG] BruteForcer Bad Speed

### ISSUE THREAD

**Issue by Mus18** [openbullet/openbullet#99]
Its proxyless config In old version it was doesn't stuck and gives a lot retries and was CPM up to 800 
![image](https://user-images.githubusercontent.com/49616911/56301768-256a4200-6141-11e9-951b-6ca0d10c2296.png)

**Comment by openbullet** [comment]
See https://github.com/openbullet/openbullet/issues/98 for the reasons of your ban
